# Klaatch Audio and Text Analysis: Predicting Loneliness from Multimodal Features

## Overview

This notebook analyzes the Klaatch dataset (2021-2023) to predict loneliness (CEL scores) using multiple feature modalities:
- **Audio Features**: Whisper embeddings, OpenSmile acoustic features, Librosa features
- **Text Features**: LIWC linguistic patterns, word categories, word embeddings
- **Demographic Features**: Age, gender, race

## Methodology

1. **Propensity Score Matching**: Create balanced demographic subgroups for fair model comparison
2. **Feature Extraction**: Extract multimodal features from audio recordings and transcripts
3. **Predictive Modeling**: Train multiple ML models (Ridge, SVR, ExtraTrees, XGBoost) using DLATK
4. **Fairness Analysis**: Test model performance across demographic subgroups
5. **Interpretation**: Analyze top predictive features and topics

## Key Research Questions

- Can audio features predict loneliness as effectively as text features?
- Do models perform fairly across gender and racial subgroups?
- What linguistic and acoustic patterns are most predictive of loneliness?

## Tools & Libraries

- **DLATK**: Differential Language Analysis ToolKit for feature extraction and prediction
- **scikit-learn**: Machine learning models and propensity score matching
- **MySQL**: Database for storing features and prediction results
- **Pandas/NumPy**: Data processing and analysis

## Demographic Subgroup Creation

Split data by gender for propensity score matching analysis. This creates balanced male and female subsets.

## Dataset Information

**Source**: Klaatch audio recordings with transcripts (2021-2023)  
**Target Variable**: CEL (Cumulative Emotion Loneliness) Total Score  
**CEL Components**:
- CELVAL1: Emotional loneliness component
- CELVAL2: Social loneliness component  
- CELVAL3: Existential loneliness component

**Features**:
- Audio recordings (.mp3 files)
- Text transcripts (cleaned and preprocessed)
- Demographics: Age, Gender, Race
- Multiple audio feature representations (Whisper, OpenSmile, Librosa)
- Text feature representations (LIWC, categories, embeddings)

## Notebook Structure

1. **Setup & Data Loading** (Cells 3-10): Import libraries, load data, clean text
2. **Preprocessing** (Cells 11-32): Propensity score matching, demographic subgroups
3. **DLATK Predictions** (Cells 33-73): Ridge regression baseline across all features
4. **SVR Models** (Cells 74-116): Support Vector Regression predictions
5. **ExtraTrees Models** (Cells 117-174): Extra Trees Regressor predictions
6. **XGBoost Models** (Cells 175-185): XGBoost gradient boosting predictions
7. **Binary Classification** (Cells 186-191): Loneliness as binary outcome
8. **Topic Analysis** (Cells 192+): Interpret top predictive features

---

## Race Classification

Define race categories for demographic analysis. Grouping White race variants together for consistent categorization.

## Feature Selection and Word Count

Select relevant columns for analysis and add word count feature for filtering short messages.

## Text Data Cleaning

Remove unwanted patterns from text data including:
- Likert scale terms (strongly agree, disagree, neutral, etc.)
- Timestamps in format [HH:MM:SS]
- Numbers and special characters
- Speaker identifiers
- Common stop words that don't add meaningful information

This cleaning ensures the text analysis focuses on substantive content.

## Data Loading

Load the Klaatch dataset from CSV and perform initial data cleaning.

## Import Libraries

Load all required Python libraries for data processing, machine learning, database connectivity, and propensity score matching.

# Klaatch DLATK Prediction Analysis

This notebook performs propensity score matching and predictive modeling analysis on the Klaatch audio dataset using DLATK (Differential Language Analysis ToolKit).

## Overview

The analysis consists of the following main components:
1. **Data Loading and Preprocessing** - Load the Klaatch dataset and clean text data
2. **Propensity Score Matching** - Create matched demographic pairs to control for confounding variables
3. **Database Setup** - Configure MySQL database for DLATK feature extraction
4. **DLATK Prediction Models** - Run multiple regression models (Ridge, SVR, ExtraTrees, XGBoost) on various audio and linguistic features
5. **Topic Analysis** - Extract and analyze top topics from the data

## Dataset
- Source: Klaatch final data CSV
- Target variables: CEL Total, CELVAL1, CELVAL2, CELVAL3
- Demographics: Gender, Race, Age

In [101]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
#from sklearn.ensemble import VotingRegressor
import re
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import NearestNeighbors
import sqlalchemy
import mysql.connector

In [85]:
df = pd.read_csv("/home/vinmayk/Klaatch_final_data.csv")
df.drop('Unnamed: 0', axis=1, inplace=True)
df.rename(columns={'New ID_x': 'New ID'}, inplace=True)
df.rename(columns={'Old ID_x': 'Old ID'}, inplace=True)
df.shape

(1465, 28)

In [86]:
import pandas as pd
import re

# Assuming merged_df is already defined as per your initial code

# Define the patterns to remove
patterns_to_remove = [
    'strongly agree',
    'strongly disagree',
    'strongly_agree',
    'strongly_disagree',
    'agree\w*',          # Matches agree, agreed, agreement, agreeable, agreeing
    'disagree\w*',       # Matches disagree, disagreed, disagreement, disagreeing
    'neutral',
    'Speaker',
    'strongly agree\w*', # Matches strongly agree variations
    'strongly disagree\w*',
    'strongly_agree\w*',
    'strongly_disagree\w*',
    'Speaker\w*',
    'speaker\w*',
    'nn\w*',
    'nnspeaker\w*',
    '!', '\$', ',', '\.', '\.\.', '\.\s*mm hmm', '\.\.',
    '0', '00 \]', '0:00', '0:00:00',
    '1', '10', '100', '11', '12', '13', '14', '15', '16', '18',
    '2', '20', '20 years', '25',
    '3', '30', '4', '40',
    '5', '5 to 10', '50', '90',
    ':', ': 00 \]', '\?', '\]', '\] hello', '\] hello \.',
    "don't\w*", 'not\w*', 'strongly\w*', 'definitely\w*', 'neither\w*', 'lisa\w*'
]



# Regex pattern to identify timestamps like [00:24:00]
timestamp_pattern = r'\[\d{2}:\d{2}:\d{2}\]'

# Note: Do NOT escape patterns that contain regex operators like \w
escaped_patterns = []
for pattern in patterns_to_remove:
    if '\\w' in pattern:
        escaped_patterns.append(pattern)  # Keep regex operators
    else:
        escaped_patterns.append(re.escape(pattern))  # Escape others

words_regex = r'\b(?:' + '|'.join(escaped_patterns) + r')\b'


# Combine word/phrase patterns with timestamp pattern
full_regex_pattern = f'(?:{words_regex})|(?:{timestamp_pattern})'

# Remove the patterns from the 'Text' column
df['Text'] =  df['Text'].str.replace(
    full_regex_pattern, 
    '', 
    regex=True, 
    flags=re.IGNORECASE
)

# Clean up any extra whitespace
df['Text'] = df['Text'].str.replace(r'\s+', ' ', regex=True).str.strip()

# Verify the changes
#print(stopwords_merged_df[['Filename', 'Text']].head())
df

,New ID,Old ID,Filename,Text,CEL Total,CELVAL1,CELVAL2,CELVAL3,Old ID_y,Age,...,Monthly Income,Cognitive Impaired,Dementia,Filepath,Cleaned Name,Old ID_y.1,Date,Original_Filename,New ID_y,Text_from_other
0,NaN,559.0,559_2021-01-22,"Hello. OK. Sure. Yesterday, I went to an appoi...",5,1,0,4,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/559_01-22-2021...,559_01-22-2021_11-40am,559.0,2021-01-22,559_01-22-2021_11-40am_wb.mp3,NaN,"Hello. OK. Sure. Yesterday, I went to an appoi..."
1,938730.0,66.0,66_2021-01-26,Hello. Please leave a message after the tone. ...,3,1,1,1,66.0,95.0,...,1841.96,NaN,YES,/sandata/karthik9/nwa/New_audio/66_01-26-2021_...,66_01-26-2021_15-20min,66.0,2021-01-26,66_01-26-2021_15-20min_wb.mp3,938730.0,Hello. Please leave a message after the tone. ...
2,938936.0,340.0,340_2021-01-26,"Yes. I'm fine, how are you? Ok. Well, what I u...",2,1,0,1,340.0,82.0,...,1630.00,NaN,NaN,/sandata/karthik9/nwa/New_audio/340_01-26-2021...,340_01-26-2021_15-05min,340.0,2021-01-26,340_01-26-2021_15-05min_wb.mp3,938936.0,"Yes. I'm fine, how are you? Ok. Well, what I u..."
3,NaN,343.0,343_2021-01-26,"Hello. All right. I'll do it now. Sure. No, no...",1,1,0,0,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/343_01-26-2021...,343_01-26-2021_08-43min,343.0,2021-01-26,343_01-26-2021_08-43min_wb.mp3,NaN,"Hello. All right. I'll do it now. Sure. No, no..."
4,938879.0,383.0,383_2021-01-27,"Hello. Hi, I'm. Ok. OK. Yes, okay. I wake up, ...",5,1,3,1,383.0,72.0,...,885.00,NaN,NaN,/sandata/karthik9/nwa/New_audio/383_01-27-2021...,383_01-27-2021_15-35min,383.0,2021-01-27,383_01-27-2021_15-35min_wb.mp3,938879.0,"Hello. Hi, I'm. Ok. OK. Yes, okay. I wake up, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,NaN,155.0,155_2021-06-02,Hello. Okay. Ready. Silence. Silence. Silence....,4,3,0,1,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/155_06-02-2021...,155_06-02-2021_21-40pm,155.0,2021-06-02,155_06-02-2021_21-40pm_wb.mp3,NaN,Hello. Okay. Ready. Silence. Silence. Silence....
1461,NaN,156.0,156_2021-06-03,"Hello? How are you? Okay! So, survey. In the w...",6,1,1,4,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/156_06-03-2021...,156_06-03-2021_17-26pm,156.0,2021-06-03,156_06-03-2021_17-26pm_wb.mp3,NaN,"Hello? How are you? Okay! So, survey. In the w..."
1462,NaN,146.0,146_2021-06-04,"Hi, baby. All right. I hate surveys. Okay. All...",8,4,1,3,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/146_06-04-2021...,146_06-04-2021_15-32pm,146.0,2021-06-04,146_06-04-2021_15-32pm_wb.mp3,NaN,"Hi, baby. All right. I hate surveys. Okay. All..."
1463,NaN,128.0,128_2021-06-09,"Hello. Long time. Uh. Here line. And, uh, ques...",6,1,4,1,NaN,NaN,...,NaN,NaN,NaN,/sandata/karthik9/nwa/New_audio/128_06-09-2021...,128_06-09-2021_13-47pm,128.0,2021-06-09,128_06-09-2021_13-47pm_wb.mp3,NaN,"Hello. Long time. Uh. Here line. And, uh, ques..."
1464,938696.0,121.0,121_2021-06-09,"Hello? Oh yeah, hi. Okay. Yeah, that's all rig...",5,1,3,1,121.0,89.0,...,1194.00,NaN,NaN,/sandata/karthik9/nwa/New_audio/121_06-09-2021...,121_06-09-2021_16-36pm,121.0,2021-06-09,121_06-09-2021_16-36pm_wb.mp3,938696.0,"Hello? Oh yeah, hi. Okay. Yeah, that's all rig..."

In [87]:
df = df[['New ID', 'Old ID', 'Filename', 'Text', 'CEL Total', 'CELVAL1', 'CELVAL2', 'CELVAL3', 'Age', 'Gender', 'Race', 'Date']].copy()

df['word_count'] = df['Text'].apply(lambda x: len(str(x).split()))

In [88]:
white_race = ['White', 'White, Jewish', 'White, Judaism', 'White,']

In [89]:
male_df = df[df['Gender']=='Male']
female_df = df[df['Gender']=='Female']
white_df = df[df['Race'].isin(white_race)]
black_df = df[df['Race']=='Black or African American']

In [75]:
gender_data = pd.concat([male_df, female_df])
race_data = pd.concat([white_df, black_df])

## Data Preprocessing: Filtering and Binary Encoding for Propensity Score Matching

### Step 1: Remove Small/Mixed Race Groups from Gender Analysis
- **Remove Asian participants**: Small sample size (9 males, 0 females) insufficient for robust comparison
- **Remove mixed-race participants**: "White, Black or African American" category creates confounding

### Step 2: Binary Encode Covariates

**For Race Comparison (`race_data`):**
- Encode Gender: Male = 0, Female = 1
- Used as covariate when comparing Black vs White participants

**For Gender Comparison (`gender_data`):**
- Encode Race: Black or African American = 0, White (all variants) = 1
- Used as covariate when comparing Male vs Female participants

### Purpose
These binary encodings prepare covariates for logistic regression models that calculate propensity scores, enabling matched pair analysis while controlling for:
- Age
- CEL Total score
- The respective demographic variable (Race or Gender)

In [76]:
gender_data = gender_data.drop(gender_data[gender_data['Race'] == 'Asian'].index)
gender_data = gender_data.drop(gender_data[gender_data['Race'] == 'White, Black or African American'].index)

race_data['Gender'] = race_data['Gender'].replace({'Male': 0}, regex=False)
race_data['Gender'] = race_data['Gender'].apply(lambda x: 1 if x != 0 else x)

gender_data['Race'] = gender_data['Race'].replace({'Black or African American': 0}, regex=False)
gender_data['Race'] = gender_data['Race'].apply(lambda x: 1 if x != 0 else x)

## Calculate Propensity Scores for Gender Comparison

### Encoding Gender as Binary
First, we encode Gender into numeric format:
- Male = 0
- Female = 1

This binary encoding is necessary for the logistic regression model.

### Building the Propensity Score Model
- **Features (X):** Race, Age, CEL Total
- **Target (y):** Gender (Male vs Female)
- **Output:** Probability of being Female given the features

### Purpose
The gender propensity score represents the likelihood of being Female (vs Male) based on:
- Race composition
- Age distribution
- CEL Total scores

We use these scores to match Male and Female participants who have similar characteristics, ensuring fair comparison by controlling for confounding variables.

In [77]:
gender_data['Gender'] = gender_data['Gender'].replace({'Male': 0, 'Female': 1}).astype(int)

gender_X = gender_data[['Race', 'Age', 'CEL Total']]
gender_y = gender_data['Gender']
gender_model = LogisticRegression(max_iter=500)
gender_data['gender_propensity_score'] = gender_model.fit(gender_X, gender_y).predict_proba(gender_X)[:, 1]

/tmp/ipykernel_2649377/3933652195.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  gender_data['Gender'] = gender_data['Gender'].replace({'Male': 0, 'Female': 1}).astype(int)

## Calculate Propensity Scores for Race Comparison

### Encoding Race as Binary
First, we encode Race into numeric format:
- Black or African American = 0
- White (all variants) = 1

This binary encoding is necessary for the logistic regression model.

### Building the Propensity Score Model
- **Features (X):** Gender, Age, CEL Total
- **Target (y):** Race (Black vs White)
- **Output:** Probability of being White given the features

### Purpose
The race propensity score represents the likelihood of being White (vs Black) based on:
- Gender composition
- Age distribution  
- CEL Total scores

We use these scores to match Black and White participants who have similar characteristics, ensuring fair comparison by controlling for confounding variables.

**Note:** This corrects the previous error where we were incorrectly predicting Gender instead of Race.

In [78]:
# Create a binary Race column
race_data['Race_binary'] = race_data['Race'].map({
    'Black or African American': 0,
    'White': 1,
    'White, Jewish': 1,
    'White, Judaism': 1,
    'White,': 1
}).astype(int)

race_X = race_data[['Gender', 'Age', 'CEL Total']]
race_y = race_data['Race_binary']  # Use the encoded Race
race_model = LogisticRegression(max_iter=500)
race_data['race_propensity_score'] = race_model.fit(race_X, race_y).predict_proba(race_X)[:, 1]

In [92]:
male = gender_data[gender_data['Gender']==0]      # ✓ Male = 0
female = gender_data[gender_data['Gender']==1]    # ✓ Female = 1

white = race_data[race_data['Race'].isin(white_race)]  # ✓ Race still has strings
black = race_data[race_data['Race']=='Black or African American']  # ✓ Race still has strings

In [80]:
print(male.shape)
print(female.shape)
print(white.shape)
print(black.shape)

(397, 14)
(931, 14)
(924, 15)
(383, 15)

## Propensity Score Matching: Creating Matched Male-Female Pairs

### What This Code Does

This implements **1:1 nearest neighbor propensity score matching** to create balanced comparison groups.

### Step-by-Step Process

1. **Find Closest Matches**
   - For each Female participant, find the Male with the most similar propensity score
   - The propensity score represents similarity in Race, Age, and CEL Total
   - Add both the Female and her matched Male to the `matched_pairs` dataset

2. **Prevent Duplicate Matching**
   - Once a Male is matched, remove him from the pool
   - This ensures each Male is matched to only one Female (1:1 matching)

3. **Separate and Balance**
   - Split matched pairs back into Female and Male groups
   - Ensure equal numbers from each group (balanced dataset)

4. **Randomize**
   - Shuffle the final dataset to remove any ordering effects
   - Use `random_state=42` for reproducibility

### Result
A balanced dataset (`final_gender`) where Males and Females are matched on confounding variables:
- Similar racial distribution
- Similar age ranges
- Similar CEL Total scores

This allows fair comparison of gender differences while controlling for these factors.

In [81]:
matched_pairs = pd.DataFrame()
for _, row in female.iterrows():
    closest_match = male.iloc[(male['gender_propensity_score'] - row['gender_propensity_score']).abs().argsort()[:1]]
    matched_pairs = pd.concat([matched_pairs, row.to_frame().T, closest_match], ignore_index=True)
    male = male.drop(closest_match.index)

matched_pairs = matched_pairs.reset_index(drop=True)

female_matched = matched_pairs[matched_pairs['Gender'] == 1]  # ✓ Use 1 for Female
male_matched = matched_pairs[matched_pairs['Gender'] == 0]    # ✓ Use 0 for Male

min_entries = min(len(female_matched), len(male_matched))

female_final = female_matched.sort_values(by='gender_propensity_score').head(min_entries)
male_final = male_matched.sort_values(by='gender_propensity_score').head(min_entries)

final_gender = pd.concat([female_final, male_final]).reset_index(drop=True)

final_gender = final_gender.sample(frac=1, random_state=42).reset_index(drop=True)

final_gender

,New ID,Old ID,Filename,Text,CEL Total,CELVAL1,CELVAL2,CELVAL3,Age,Gender,Race,Date,word_count,gender_propensity_score
0,938762.0,507.0,507_2022-12-06,Hello. Kelly Well. Sure. Fairly well. No. Hell...,4,1,1,2,72.0,0,0,2022-12-06,333,0.733261
1,938911.0,741.0,741_2022-08-11,"Hello.: Good. How are you? Well, I'm going to ...",3,1,1,1,86.0,0,0,2022-08-11,2201,0.849007
2,938913.0,661.0,661_2023-05-15,"Hello. Hi. Good. Yeah. Oh, yeah. Yeah. Yeah. U...",2,1,0,1,70.0,1,1,2023-05-15,461,0.544755
3,938652.0,522.0,522_2024-08-13,"000003] Hi, . Okay, how about you this time? I...",0,0,0,0,74.0,0,1,2024-08-13,2952,0.604046
4,938820.0,618.0,618_2023-04-06,"Hello. Oh, hi, Lorna. How are you? Good thing....",2,1,0,1,70.0,1,1,2023-04-06,926,0.544755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,938885.0,509.0,509_2023-11-17,"nd now. Ha! : Oh, yeah. Yeah, I used to be. I ...",3,0,2,1,71.0,1,1,2023-11-17,764,0.551472
790,938945.0,45.0,45_2024-09-27,"ello. I know, yeah. Hello? Hey. I'm hanging in...",5,1,2,2,74.0,1,1,2024-09-27,1175,0.576977
791,938933.0,783.0,783_2023-08-02,"Hello. Hi, . How are you? Yes, I do. Sure. Oka...",3,1,1,1,78.0,1,1,2023-08-02,411,0.634884
792,981476.0,852.0,981476_2024-11-01,"Oh, I didn't know. Very good. Oh, no, no probl...",2,0,1,1,68.0,0,1,2024-11-01,829,0.520107
793,938945.0,45.0,45_2024-07-01,"ello. Hello. Oh. Hello, sweetie. Oh. Just peac...",5,2,1,2,74.0,1,1,2024-07-01,4460,0.576977

In [82]:
matched_pairs = pd.DataFrame()
for _, row in white.iterrows():
    closest_match = black.iloc[(black['race_propensity_score'] - row['race_propensity_score']).abs().argsort()[:1]]  # ✓ Use race_propensity_score
    matched_pairs = pd.concat([matched_pairs, row.to_frame().T, closest_match], ignore_index=True)
    black = black.drop(closest_match.index)

matched_pairs = matched_pairs.reset_index(drop=True)

white_matched = matched_pairs[matched_pairs['Race'].isin(white_race)]
black_matched = matched_pairs[matched_pairs['Race'] == 'Black or African American']

min_entries = min(len(white_matched), len(black_matched))

white_final = white_matched.sort_values(by='race_propensity_score').head(min_entries)  # ✓ Sort by race score
black_final = black_matched.sort_values(by='race_propensity_score').head(min_entries)  # ✓ Sort by race score

final_race = pd.concat([white_final, black_final]).reset_index(drop=True)

final_race = final_race.sample(frac=1, random_state=42).reset_index(drop=True)

final_race

,New ID,Old ID,Filename,Text,CEL Total,CELVAL1,CELVAL2,CELVAL3,Age,Gender,Race,Date,word_count,Race_binary,race_propensity_score
0,938682.0,545.0,545_2023-04-06,"Hello. Hello. Good morning. How are you? Uh, n...",3,1,1,1,65.0,1,Black or African American,2023-04-06,790,0,0.580088
1,938695.0,687.0,687_2022-08-08,"Hello. Yet. Oh, okay. Yeah. Yeah. How you doin...",0,0,0,0,74.0,0,Black or African American,2022-08-08,1436,0,0.738187
2,938698.0,170.0,938698_2024-10-30,Hello. I'm doing pretty well. Yeah. What am I ...,2,1,1,0,87.0,1,White,2024-10-30,1206,1,0.69502
3,938917.0,173.0,173_2022-11-10,"Hello.: Oh, hi. How are you?: Good, good, good...",0,0,0,0,90.0,1,Black or African American,2022-11-10,3206,0,0.670894
4,938673.0,144.0,144_2024-07-17,"ello? Oh, okay. Um, are you recording now? Alr...",3,1,1,1,83.0,1,White,2024-07-17,3554,1,0.692447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,938667.0,419.0,419_2021-05-17,"Hello. You. OK, I can hear. Sure. Yes. I take ...",1,1,0,0,73.0,1,White,2021-05-17,541,1,0.585976
762,938868.0,523.0,523_2022-03-29,"Hello. Good. Yeah, he's good. Sure. Oh. Well. ...",2,0,1,1,72.0,1,White,2022-03-29,797,1,0.602682
763,938702.0,600.0,600_2024-07-17,ello? Yes. Who? Put you? Behave yourself. All ...,0,0,0,0,89.0,1,White,2024-07-17,1604,1,0.664875
764,938703.0,158.0,158_2023-09-21,"000000] Hello. Hello. So saying. Yes, I do. Oh...",0,0,0,0,77.0,1,Black or African American,2023-09-21,545,0,0.588911
765,938728.0,553.0,553_2023-05-10,"Hello. Yes, I'm okay. Deborah Raw, honey. No, ...",3,1,1,1,68.0,1,White,2023-05-10,631,1,0.599779

In [95]:
print("Black propensity scores:")
print(f"  Min: {black['race_propensity_score'].min():.3f}")
print(f"  Max: {black['race_propensity_score'].max():.3f}")
print(f"  Mean: {black['race_propensity_score'].mean():.3f}")
print(f"  Count: {len(black)}")

print("\nWhite propensity scores:")
print(f"  Min: {white['race_propensity_score'].min():.3f}")
print(f"  Max: {white['race_propensity_score'].max():.3f}")
print(f"  Mean: {white['race_propensity_score'].mean():.3f}")
print(f"  Count: {len(white)}")

Black propensity scores:
  Min: 0.533
  Max: 0.918
  Mean: 0.680
  Count: 383

White propensity scores:
  Min: 0.451
  Max: 0.900
  Mean: 0.718
  Count: 924

## Subgroup Prediction Analysis: Testing Model Fairness Across Demographics

### What Are We Doing?

We're building **separate prediction models** for each demographic subgroup (Males, Females, Whites, Blacks) to test if our text-based prediction of CEL Total scores works equally well across different groups.

### Why Is This Important?

**Goal:** Ensure fairness and check for algorithmic bias
- If the model predicts well for Whites but poorly for Blacks → potential bias
- If the model predicts well for Males but poorly for Females → gender bias
- Equal performance across groups → fair and robust model

### The Process

1. **Separate Matched Data by Subgroups**
   - Males (397 participants)
   - Females (397 participants)
   - Whites (383 participants)
   - Blacks (383 participants)

2. **For Each Subgroup:**
   - Convert text transcripts to TF-IDF features
   - Split by participant ID (80% train, 20% test)
   - Train Random Forest model to predict CEL Total from text
   - Evaluate using Mean Absolute Error (MAE)

3. **Compare Performance**
   - Lower MAE = better predictions
   - Similar MAE across groups = fair model
   - Large differences = potential bias or data quality issues

### What We're Testing

**Research Question:** Can we predict emotional loneliness (CEL Total) from speech patterns equally well across:
- Gender groups?
- Racial groups?

### Expected Outcome

If MAE is similar across all groups (~1.3-1.6), it suggests:
- ✓ The model works fairly across demographics
- ✓ Text features capture loneliness patterns consistently
- ✓ No systematic bias in prediction capability

In [98]:
stratified_male_df = final_gender[final_gender['Gender']==0]    # ✓ Male = 0
stratified_female_df = final_gender[final_gender['Gender']==1]  # ✓ Female = 1
stratified_white_df = final_race[final_race['Race'].isin(white_race)]  # ✓ Race is still string
stratified_black_df = final_race[final_race['Race']=='Black or African American']  # ✓ Race is still string

# List of DataFrames
dataframes = {"Females":stratified_female_df, "Males":stratified_male_df, "Whites":stratified_white_df, "Blacks":stratified_black_df}

# Initialize a list to store results
mae_results = []

# Loop through each dataframe
for name, dataframe in dataframes.items():
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(dataframe['Text'])
    y = dataframe['CEL Total']
    
    # Get unique IDs and split them
    unique_ids = dataframe['New ID'].unique()

    random_state = np.random.RandomState(42)
    random_state.shuffle(unique_ids)

    train_size = int(len(unique_ids) * 0.8)
    train_ids = unique_ids[:train_size]
    test_ids = unique_ids[train_size:]

    train_mask = dataframe['New ID'].isin(train_ids)
    test_mask = dataframe['New ID'].isin(test_ids)

    train_mask = train_mask.to_numpy()
    test_mask = test_mask.to_numpy()

    X_train = X[train_mask]
    X_test = X[test_mask]

    training_dataset = dataframe[train_mask]
    testing_dataset = dataframe[test_mask]

    y_train = training_dataset['CEL Total']
    y_test = testing_dataset['CEL Total']

    print(f"Training set shape for {name}: {X_train.shape}")
    print(f"Test set shape for {name}: {X_test.shape}")

    # Model training
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Prediction and evaluation
    predicted_scores = model.predict(X_test)
    model_score = model.score(X_test,y_test)
    mae = ((y_test - predicted_scores).abs()).mean()

    print(f"{name} model score: {model_score}")
    print(f"{name} predictions Mean Absolute Error (MAE): {mae}")
    print("----------------------------x------------------------------------")
    mae_results.append(mae)

# You can now access the mae_results list, which contains the MAE for each dataframe
print("MAE results for all datasets:", mae_results)

Training set shape for Females: (317, 11935)
Test set shape for Females: (80, 11935)
Females model score: 0.05740081774253514
Females predictions Mean Absolute Error (MAE): 1.6806249999999998
----------------------------x------------------------------------
Training set shape for Males: (317, 12692)
Test set shape for Males: (80, 12692)
Males model score: 0.06991909246575356
Males predictions Mean Absolute Error (MAE): 1.7127500000000002
----------------------------x------------------------------------
Training set shape for Whites: (296, 12103)
Test set shape for Whites: (87, 12103)
Whites model score: 0.07093888524590153
Whites predictions Mean Absolute Error (MAE): 1.211954022988506
----------------------------x------------------------------------
Training set shape for Blacks: (311, 9163)
Test set shape for Blacks: (72, 9163)
Blacks model score: -0.022513573515092533
Blacks predictions Mean Absolute Error (MAE): 1.5711111111111107
----------------------------x------------------------------------
MAE results for all datasets: [1.6806249999999998, 1.7127500000000002, 1.211954022988506, 1.5711111111111107]

In [100]:
print(stratified_male_df.shape)
print(stratified_female_df.shape)
print(stratified_white_df.shape)
print(stratified_black_df.shape)

(397, 14)
(397, 14)
(383, 15)
(383, 15)

In [ ]:
#stratified_male_df = stratified_male_df[['Filename', 'Text', 'KlaatchID', 'Date', 'CEL Total', 'CELVAL1', 'CELVAL2', 'CELVAL3', 'Age', 'status']]
#stratified_female_df = stratified_female_df[['Filename', 'Text', 'KlaatchID', 'Date', 'CEL Total', 'CELVAL1', 'CELVAL2', 'CELVAL3', 'Age', 'status']]
#stratified_white_df = stratified_white_df[['Filename', 'Text', 'KlaatchID', 'Date', 'CEL Total', 'CELVAL1', 'CELVAL2', 'CELVAL3', 'Age', 'status']]
#stratified_black_df = stratified_black_df[['Filename', 'Text', 'KlaatchID', 'Date', 'CEL Total', 'CELVAL1', 'CELVAL2', 'CELVAL3', 'Age', 'status']]

,New ID,Old ID,Filename,Text,CEL Total,CELVAL1,CELVAL2,CELVAL3,Age,Gender,Race,Date,word_count,gender_propensity_score
0,938906.0,643.0,643_2021-12-17,"Yes. From where? Okay, Diana. Oh, yeah, yeah...",4,1,1,2,79.0,0,Black or African American,2021-12-17,2208,0.021498
1,938727.0,490.0,490_2022-03-29,"Hello, Lisa. Has been. I've probably been. Rig...",3,1,1,1,84.0,1,Black or African American,2022-03-29,821,0.991453
3,938663.0,48.0,48_2022-05-27,"No. Hello, Lisa. Okay. I checked. Mine, too. O...",2,1,1,0,75.0,1,Black or African American,2022-05-27,677,0.989632
5,938733.0,606.0,606_2022-07-18,"Oh, please leave a message. Oh, lousy today. V...",1,0,1,0,94.0,1,Black or African American,2022-07-18,1660,0.993513
6,938731.0,766.0,766_2024-09-27,ot sauce? Yes. Okay. How are you? No. Yeah. Ye...,3,1,1,1,66.0,1,Black or African American,2024-09-27,634,0.98693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,938705.0,24.0,24_2021-02-09,"Yeah. Good. Okay. Yeah, I'll do it. Okay. I...",5,1,1,3,93.0,0,Black or African American,2021-02-09,282,0.029204
756,938682.0,545.0,545_2024-07-24,"ello? Yes. Speaker2: I'm fine. Lorna, how are...",4,2,1,1,65.0,1,Black or African American,2024-07-24,333,0.986356
758,938751.0,386.0,386_2024-08-07,"ello. Hi. What happened? Oh, okay. No. Okay. W...",3,1,1,1,80.0,1,Black or African American,2024-08-07,507,0.990605
760,938672.0,79.0,79_2022-02-01,"Fine, thank you. How are you? Yes, sure. It wa...",3,1,1,1,90.0,1,Black or African American,2022-02-01,297,0.992584
764,938906.0,643.0,643_2021-05-13,"Hello. Yes. OK, well, we're coordinating where...",2,1,1,0,79.0,0,Black or African American,2021-05-13,1073,0.022343

In [ ]:
def connect_to_db():
    return mysql.connector.connect(
        host='127.0.0.1',
        database='Audio_features',
        username="vinmayk", password="yA2Siru4l4yfEf1a"
    )
    
def create_table_if_not_exists(table_name):
    """
    Creates the table if it does not exist.
    """
    create_table_query = f"""
    CREATE TABLE IF NOT EXISTS {table_name} (
        message_id VARCHAR(191) NOT NULL,
        message TEXT,
        Date DATE,
        CEL_Total INT,
        CELVAL1 INT,
        CELVAL2 INT,
        CELVAL3 INT,
        klaatch_id INT,
        PRIMARY KEY (message_id)
    );
    """
    connection = connect_to_db()
    cursor = connection.cursor()
    try:
        cursor.execute(create_table_query)
        connection.commit()
        print(f"Table {table_name} is ready.")
    except mysql.connector.Error as err:
        print(f"Error creating table {table_name}: {err}")
    finally:
        cursor.close()
        connection.close()


def insert_data(df, table_name):
    """
    Inserts data into the specified table.
    Args:
    df (pd.DataFrame): The DataFrame containing the data to insert.
    table_name (str): The name of the database table to insert data into.
    """
    
    create_table_if_not_exists(table_name)
    
    # Establish a connection to the database
    connection = connect_to_db()
    cursor = connection.cursor()

    # Construct the INSERT query dynamically based on the table name
    insert_query = f"""
    INSERT IGNORE INTO {table_name} (
        message_id, message, Date, CEL_Total, CELVAL1, CELVAL2, CELVAL3, klaatch_id
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """
    
    # Convert DataFrame to a list of tuples, including all required columns
    data = df[['Filename', 'Text', 'Date', 'CEL Total',
               'CELVAL1', 'CELVAL2', 'CELVAL3', 'Old ID']].values.tolist()
    
    # Insert data
    try:
        cursor.executemany(insert_query, data)
        connection.commit()
        print(f"Inserted {cursor.rowcount} rows successfully into table {table_name}.")
    except mysql.connector.Error as err:
        print(f"Error: {err}")
    finally:
        cursor.close()
        connection.close()

# Example usage
insert_data(stratified_male_df, "stratified_male")
insert_data(stratified_female_df, "stratified_female")
insert_data(stratified_black_df, "stratified_black")
insert_data(stratified_white_df, "stratified_white")

Table stratified_male is ready.
Inserted 397 rows successfully into table stratified_male.
Table stratified_female is ready.
Inserted 397 rows successfully into table stratified_female.
Table stratified_black is ready.
Inserted 383 rows successfully into table stratified_black.
Table stratified_white is ready.
Inserted 383 rows successfully into table stratified_white.

In [19]:
print(len(stratified_male_df))
print(len(stratified_female_df))
print(len(stratified_white_df))
print(len(stratified_black_df))

397
397
383
383

## DLATK

### DLATK Feature Extraction with Librosa Features

Running DLATK predictions using Librosa acoustic features (MFCCs, Chroma, Spectral Contrast, Tonnetz)

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:46:06
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5248689291572339), ('intercept_', 0.8006644518272414), ('n_features_in_', 38)]
  *FOLD R^2: -1.1689 (MSE: 0.6203; MAE: 0.5141; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.44090123261404107), ('intercept_', 0.7748344370860918), ('n_features_in_', 38)]
  *FOLD R^2: -0.0102 (MSE: 0.6824; MAE: 0.6173; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.53693826148832), ('intercept_', 0.8239202657807307), ('n_features_in_', 38)]
  *FOLD R^2: 0.0727 (MSE: 0.3023; MAE: 0.4525; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.45018063549596427), ('intercept_', 0.764900662251655), ('n_features_in_', 38)]
  *FOLD R^2: -0.0185 (MSE: 0.6294; MAE: 0.5529; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.460288217033178), ('intercept_', 0.801324503311258), ('n_features_in_', 38)]
  *FOLD R^2: 0.0458 (MSE: 0.6066; MAE: 0.5495; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1039
*Overall FOLDS R^2:    -0.2158 (+- 0.2137)
*R (sqrt R^2):         nan
*Pearson r:            0.1059 (p = 0.03994)
*Folds Pearson r:      0.1806 (p = 0.22066)
*Spearman rho:         0.2073 (p = 0.00005)
*Mean Squared Error:   0.5676
*Mean Absolute Error:  0.5370
*Train_Mean MAE:       0.1594

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7239943905499026), ('intercept_', 0.7508305647840531), ('n_features_in_', 38)]
  *FOLD R^2: 0.0537 (MSE: 0.5557; MAE: 0.5381; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6962782418632073), ('intercept_', 0.7715231788079456), ('n_features_in_', 38)]
  *FOLD R^2: -0.0399 (MSE: 0.6315; MAE: 0.6317; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6938069715203532), ('intercept_', 0.784053156146179), ('n_features_in_', 38)]
  *FOLD R^2: -0.0485 (MSE: 0.6775; MAE: 0.6206; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6522964270885608), ('intercept_', 0.7350993377483441), ('n_features_in_', 38)]
  *FOLD R^2: -0.0271 (MSE: 0.8406; MAE: 0.6534; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6703949626574852), ('intercept_', 0.7516556291390725), ('n_features_in_', 38)]
  *FOLD R^2: 0.0302 (MSE: 0.7835; MAE: 0.6367; mean train mae: 0.6564)
*Overall R^2:          0.0005
*Overall FOLDS R^2:    -0.0063 (+- 0.0182)
*R (sqrt R^2):         0.0233
*Pearson r:            0.0920 (p = 0.07446)
*Folds Pearson r:      0.1091 (p = 0.43750)
*Spearman rho:         0.1076 (p = 0.03685)
*Mean Squared Error:   0.6973
*Mean Absolute Error:  0.6159
*Train_Mean MAE:       0.1123

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1.0), ('best_score_', -0.8161573751952729), ('intercept_', 1.0099667774086376), ('n_features_in_', 38)]
  *FOLD R^2: -0.9428 (MSE: 1.3239; MAE: 0.8254; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1.0), ('best_score_', -0.7323874990799896), ('intercept_', 0.9867549668874183), ('n_features_in_', 38)]
  *FOLD R^2: -0.1765 (MSE: 1.0805; MAE: 0.8286; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8453909355898868), ('intercept_', 1.0332225913621267), ('n_features_in_', 38)]
  *FOLD R^2: 0.0733 (MSE: 0.5293; MAE: 0.5377; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6984014680059724), ('intercept_', 0.956953642384106), ('n_features_in_', 38)]
  *FOLD R^2: -0.0867 (MSE: 1.1024; MAE: 0.7524; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7560197808020086), ('intercept_', 1.0000000000000004), ('n_features_in_', 38)]
  *FOLD R^2: 0.0744 (MSE: 0.9008; MAE: 0.6818; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1739
*Overall FOLDS R^2:    -0.2117 (+- 0.1691)
*R (sqrt R^2):         nan
*Pearson r:            0.1160 (p = 0.02434)
*Folds Pearson r:      0.1471 (p = 0.43017)
*Spearman rho:         0.2190 (p = 0.00002)
*Mean Squared Error:   0.9870
*Mean Absolute Error:  0.7250
*Train_Mean MAE:       0.3315

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1.0), ('best_score_', -3.874035112250055), ('intercept_', 2.5614617940199182), ('n_features_in_', 38)]
  *FOLD R^2: -1.5154 (MSE: 7.1161; MAE: 1.6989; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.4935474968273073), ('intercept_', 2.533112582781454), ('n_features_in_', 38)]
  *FOLD R^2: -0.0183 (MSE: 4.2061; MAE: 1.6027; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.814700823309217), ('intercept_', 2.641196013289036), ('n_features_in_', 38)]
  *FOLD R^2: 0.0598 (MSE: 2.9125; MAE: 1.3643; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:46:43
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.408993315730126), ('intercept_', 0.6843853820598008), ('n_features_in_', 38)]
  *FOLD R^2: -0.2008 (MSE: 0.3310; MAE: 0.5029; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4139947081584578), ('intercept_', 0.6821192052980132), ('n_features_in_', 38)]
  *FOLD R^2: -0.0960 (MSE: 0.2728; MAE: 0.4699; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3441652284218695), ('intercept_', 0.6026490066225165), ('n_features_in_', 38)]
  *FOLD R^2: -0.0887 (MSE: 0.5717; MAE: 0.5784; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4139537063290452), ('intercept_', 0.6212624584717606), ('n_features_in_', 38)]
  *FOLD R^2: -0.0911 (MSE: 0.2756; MAE: 0.4569; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3339889515019671), ('intercept_', 0.6721854304635762), ('n_features_in_', 38)]
  *FOLD R^2: -0.0327 (MSE: 0.5831; MAE: 0.6248; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0386
*Overall FOLDS R^2:    -0.1019 (+- 0.0244)
*R (sqrt R^2):         nan
*Pearson r:            -0.0274 (p = 0.59566)
*Folds Pearson r:      0.0946 (p = 0.38483)
*Spearman rho:         -0.0187 (p = 0.71675)
*Mean Squared Error:   0.4063
*Mean Absolute Error:  0.5263
*Train_Mean MAE:       0.0823

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4068308716746104), ('intercept_', 0.6777408637873755), ('n_features_in_', 38)]
  *FOLD R^2: -0.0387 (MSE: 0.7611; MAE: 0.6713; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.46518822221874584), ('intercept_', 0.685430463576159), ('n_features_in_', 38)]
  *FOLD R^2: 0.0037 (MSE: 0.5048; MAE: 0.5800; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4931421323639792), ('intercept_', 0.6556291390728475), ('n_features_in_', 38)]
  *FOLD R^2: 0.0584 (MSE: 0.3907; MAE: 0.5042; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5062782530924412), ('intercept_', 0.6378737541528239), ('n_features_in_', 38)]
  *FOLD R^2: -0.1061 (MSE: 0.3585; MAE: 0.4517; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.47064208002685337), ('intercept_', 0.6854304635761584), ('n_features_in_', 38)]
  *FOLD R^2: -0.0933 (MSE: 0.4956; MAE: 0.5831; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0208
*Overall FOLDS R^2:    -0.0352 (+- 0.0273)
*R (sqrt R^2):         nan
*Pearson r:            0.0899 (p = 0.08135)
*Folds Pearson r:      0.1123 (p = 0.52427)
*Spearman rho:         0.1308 (p = 0.01100)
*Mean Squared Error:   0.5024
*Mean Absolute Error:  0.5581
*Train_Mean MAE:       0.1428

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4655410262154016), ('intercept_', 0.7009966777408653), ('n_features_in_', 38)]
  *FOLD R^2: -0.0584 (MSE: 0.6773; MAE: 0.6239; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5212069176425752), ('intercept_', 0.7384105960264903), ('n_features_in_', 38)]
  *FOLD R^2: 0.0366 (MSE: 0.4532; MAE: 0.5301; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5177134480190211), ('intercept_', 0.6986754966887416), ('n_features_in_', 38)]
  *FOLD R^2: 0.0339 (MSE: 0.4637; MAE: 0.5340; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5266486076691236), ('intercept_', 0.7043189368770758), ('n_features_in_', 38)]
  *FOLD R^2: -0.0204 (MSE: 0.4457; MAE: 0.4900; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4896887277800669), ('intercept_', 0.7516556291390729), ('n_features_in_', 38)]
  *FOLD R^2: -0.0141 (MSE: 0.5704; MAE: 0.6245; mean train mae: 0.6167)
*Overall R^2:          0.0065
*Overall FOLDS R^2:    -0.0045 (+- 0.0160)
*R (sqrt R^2):         0.0808
*Pearson r:            0.1333 (p = 0.00955)
*Folds Pearson r:      0.1691 (p = 0.35215)
*Spearman rho:         0.1201 (p = 0.01968)
*Mean Squared Error:   0.5223
*Mean Absolute Error:  0.5605
*Train_Mean MAE:       0.1337

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.2487740396485587), ('intercept_', 2.06312292358804), ('n_features_in_', 38)]
  *FOLD R^2: -0.0889 (MSE: 3.0630; MAE: 1.4414; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.394958963520474), ('intercept_', 2.105960264900663), ('n_features_in_', 38)]
  *FOLD R^2: 0.0072 (MSE: 2.2920; MAE: 1.2418; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.348101360771264), ('intercept_', 1.9569536423841043), ('n_features_in_', 38)]
  *FOLD R^2: -0.0548 (MSE: 2.5533; MAE: 1.3215; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)

In [3]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:50:22
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CELVAL1', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.38196559110993006), ('intercept_', 0.6666666666666667), ('n_features_in_', 38)]
  *FOLD R^2: 0.0134 (MSE: 0.1867; MAE: 0.4053; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.33741934227746206), ('intercept_', 0.6549295774647889), ('n_features_in_', 38)]
  *FOLD R^2: -0.0105 (MSE: 0.3631; MAE: 0.5074; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.2961478838474807), ('intercept_', 0.6842105263157896), ('n_features_in_', 38)]
  *FOLD R^2: -0.0750 (MSE: 0.5080; MAE: 0.5561; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.33026111118977586), ('intercept_', 0.6912280701754386), ('n_features_in_', 38)]
  *FOLD R^2: -0.0022 (MSE: 0.3980; MAE: 0.5136; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3550211684747049), ('intercept_', 0.7157894736842106), ('n_features_in_', 38)]
  *FOLD R^2: -0.0712 (MSE: 0.2954; MAE: 0.4975; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0127
*Overall FOLDS R^2:    -0.0291 (+- 0.0164)
*R (sqrt R^2):         nan
*Pearson r:            0.0469 (p = 0.37731)
*Folds Pearson r:      0.1201 (p = 0.38042)
*Spearman rho:         0.0727 (p = 0.17101)
*Mean Squared Error:   0.3503
*Mean Absolute Error:  0.4960
*Train_Mean MAE:       0.0710

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5153153248873551), ('intercept_', 0.6596491228070186), ('n_features_in_', 38)]
  *FOLD R^2: -0.0239 (MSE: 0.6622; MAE: 0.5787; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.573999872151638), ('intercept_', 0.6549295774647889), ('n_features_in_', 38)]
  *FOLD R^2: 0.0496 (MSE: 0.4158; MAE: 0.5128; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.47123877359909483), ('intercept_', 0.6561403508771928), ('n_features_in_', 38)]
  *FOLD R^2: -0.0949 (MSE: 0.8241; MAE: 0.6730; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5452765839068197), ('intercept_', 0.6842105263157895), ('n_features_in_', 38)]
  *FOLD R^2: -0.0062 (MSE: 0.5170; MAE: 0.5800; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5777943369145881), ('intercept_', 0.7157894736842106), ('n_features_in_', 38)]
  *FOLD R^2: -0.0680 (MSE: 0.3873; MAE: 0.5365; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0177
*Overall FOLDS R^2:    -0.0287 (+- 0.0224)
*R (sqrt R^2):         nan
*Pearson r:            0.0645 (p = 0.22443)
*Folds Pearson r:      0.1199 (p = 0.45925)
*Spearman rho:         0.1604 (p = 0.00240)
*Mean Squared Error:   0.5609
*Mean Absolute Error:  0.5760
*Train_Mean MAE:       0.1136

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10.0), ('best_score_', -0.6260406753311126), ('intercept_', 0.863157894736843), ('n_features_in_', 38)]
  *FOLD R^2: -0.0157 (MSE: 0.6758; MAE: 0.6298; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5790428494670636), ('intercept_', 0.8063380281690148), ('n_features_in_', 38)]
  *FOLD R^2: -0.0031 (MSE: 0.7795; MAE: 0.6272; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5753398981983543), ('intercept_', 0.831578947368421), ('n_features_in_', 38)]
  *FOLD R^2: -0.0631 (MSE: 0.8781; MAE: 0.6497; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6209389121520026), ('intercept_', 0.8596491228070168), ('n_features_in_', 38)]
  *FOLD R^2: -0.1989 (MSE: 0.7872; MAE: 0.6214; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7041597820464952), ('intercept_', 0.8947368421052638), ('n_features_in_', 38)]
  *FOLD R^2: 0.1265 (MSE: 0.3389; MAE: 0.4446; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0219
*Overall FOLDS R^2:    -0.0308 (+- 0.0469)
*R (sqrt R^2):         nan
*Pearson r:            0.1618 (p = 0.00220)
*Folds Pearson r:      0.1989 (p = 0.33345)
*Spearman rho:         0.2028 (p = 0.00012)
*Mean Squared Error:   0.6921
*Mean Absolute Error:  0.5946
*Train_Mean MAE:       0.2293

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.8061927019686865), ('intercept_', 2.189473684210528), ('n_features_in_', 38)]
  *FOLD R^2: 0.1023 (MSE: 2.3058; MAE: 1.2302; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.670074699338019), ('intercept_', 2.1161971830985937), ('n_features_in_', 38)]
  *FOLD R^2: 0.0428 (MSE: 2.8138; MAE: 1.2931; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.2886308433360436), ('intercept_', 2.1719298245614036), ('n_features_in_', 38)]
  *FOLD R^2: -0.1143 (MSE: 4.3032; MAE: 1.5213; mean train mae: 1.4677)
Fold 3

In [4]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:50:36
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL2', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6109242082620434), ('intercept_', 0.8561403508771933), ('n_features_in_', 38)]
  *FOLD R^2: -0.0287 (MSE: 0.7432; MAE: 0.5656; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6309826543832363), ('intercept_', 0.8666666666666667), ('n_features_in_', 38)]
  *FOLD R^2: 0.0574 (MSE: 0.7333; MAE: 0.6458; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6688076029838336), ('intercept_', 0.8697183098591554), ('n_features_in_', 38)]
  *FOLD R^2: -0.0011 (MSE: 0.5544; MAE: 0.5609; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5593402630694267), ('intercept_', 0.8245614035087723), ('n_features_in_', 38)]
  *FOLD R^2: -0.1296 (MSE: 1.1446; MAE: 0.7926; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7090218519577361), ('intercept_', 0.8526315789473677), ('n_features_in_', 38)]
  *FOLD R^2: -0.0037 (MSE: 0.4042; MAE: 0.4504; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0254
*Overall FOLDS R^2:    -0.0211 (+- 0.0274)
*R (sqrt R^2):         nan
*Pearson r:            0.1758 (p = 0.00087)
*Folds Pearson r:      0.1868 (p = 0.18604)
*Spearman rho:         0.2600 (p = 0.00000)
*Mean Squared Error:   0.7155
*Mean Absolute Error:  0.6030
*Train_Mean MAE:       0.2375

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.757225332321774), ('intercept_', 0.8175438596491228), ('n_features_in_', 38)]
  *FOLD R^2: -0.0502 (MSE: 1.0187; MAE: 0.6693; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.778423053477578), ('intercept_', 0.8526315789473685), ('n_features_in_', 38)]
  *FOLD R^2: 0.0077 (MSE: 0.9311; MAE: 0.7297; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8315334819046544), ('intercept_', 0.859154929577465), ('n_features_in_', 38)]
  *FOLD R^2: 0.0325 (MSE: 0.7239; MAE: 0.5862; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7711679889070302), ('intercept_', 0.8385964912280702), ('n_features_in_', 38)]
  *FOLD R^2: 0.0256 (MSE: 0.9588; MAE: 0.7143; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8916664878948121), ('intercept_', 0.8596491228070173), ('n_features_in_', 38)]
  *FOLD R^2: -0.0708 (MSE: 0.4800; MAE: 0.4870; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0007
*Overall FOLDS R^2:    -0.0110 (+- 0.0186)
*R (sqrt R^2):         nan
*Pearson r:            0.0626 (p = 0.23864)
*Folds Pearson r:      0.0851 (p = 0.34937)
*Spearman rho:         0.0824 (p = 0.12063)
*Mean Squared Error:   0.8222
*Mean Absolute Error:  0.6372
*Train_Mean MAE:       0.0945

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8181084985813099), ('intercept_', 1.0140350877192983), ('n_features_in_', 38)]
  *FOLD R^2: -0.0534 (MSE: 1.0185; MAE: 0.6625; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8801686229380782), ('intercept_', 1.0280701754385966), ('n_features_in_', 38)]
  *FOLD R^2: 0.0762 (MSE: 0.8196; MAE: 0.6709; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9104524052982598), ('intercept_', 1.0492957746478873), ('n_features_in_', 38)]
  *FOLD R^2: 0.1413 (MSE: 0.6995; MAE: 0.6580; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7849455676989376), ('intercept_', 1.0385964912280699), ('n_features_in_', 38)]
  *FOLD R^2: 0.0538 (MSE: 1.1720; MAE: 0.8343; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8991966490609649), ('intercept_', 0.9964912280701747), ('n_features_in_', 38)]
  *FOLD R^2: -0.1260 (MSE: 0.7389; MAE: 0.5791; mean train mae: 0.4251)
*Overall R^2:          0.0313
*Overall FOLDS R^2:    0.0184 (+- 0.0428)
*R (sqrt R^2):         0.1770
*Pearson r:            0.1840 (p = 0.00048)
*Folds Pearson r:      0.2051 (p = 0.39746)
*Spearman rho:         0.2638 (p = 0.00000)
*Mean Squared Error:   0.8892
*Mean Absolute Error:  0.6809
*Train_Mean MAE:       0.1752

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.507395573739204), ('intercept_', 2.6877192982456144), ('n_features_in_', 38)]
  *FOLD R^2: -0.0597 (MSE: 5.8190; MAE: 1.6919; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.805697437159476), ('intercept_', 2.7473684210526317), ('n_features_in_', 38)]
  *FOLD R^2: 0.0443 (MSE: 5.1213; MAE: 1.7960; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -5.006901436062988), ('intercept_', 2.778169014084509), ('n_features_in_', 38)]
  *FOLD R^2: 0.0905 (MSE: 3.9661; MAE: 1.5849; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]

### DLATK Feature Extraction with OpenSmile Features

Running DLATK predictions using OpenSmile eGeMAPSv02 acoustic features (88 features)

In [5]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:56:12
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6013958317154573), ('intercept_', 0.856140350877193), ('n_features_in_', 88)]
  *FOLD R^2: -0.0320 (MSE: 0.7456; MAE: 0.5586; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6305390949586623), ('intercept_', 0.8666666666666667), ('n_features_in_', 88)]
  *FOLD R^2: 0.1667 (MSE: 0.6483; MAE: 0.5965; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6215840544310838), ('intercept_', 0.8697183098591549), ('n_features_in_', 88)]
  *FOLD R^2: -0.5856 (MSE: 0.8781; MAE: 0.7148; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5539036398183894), ('intercept_', 0.8245614035087719), ('n_features_in_', 88)]
  *FOLD R^2: 0.0163 (MSE: 0.9968; MAE: 0.7539; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.692674108714771), ('intercept_', 0.8526315789473684), ('n_features_in_', 88)]
  *FOLD R^2: -7.6113 (MSE: 3.4677; MAE: 0.6135; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.9290
*Overall FOLDS R^2:    -1.6092 (+- 1.3469)
*R (sqrt R^2):         nan
*Pearson r:            0.0558 (p = 0.29336)
*Folds Pearson r:      0.1565 (p = 0.46918)
*Spearman rho:         0.2529 (p = 0.00000)
*Mean Squared Error:   1.3460
*Mean Absolute Error:  0.6476
*Train_Mean MAE:       0.2750

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7439083475989487), ('intercept_', 0.8175438596491228), ('n_features_in_', 88)]
  *FOLD R^2: -0.0517 (MSE: 1.0202; MAE: 0.6763; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7526712406290262), ('intercept_', 0.8526315789473684), ('n_features_in_', 88)]
  *FOLD R^2: -0.1104 (MSE: 1.0419; MAE: 0.7792; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7968574424082487), ('intercept_', 0.8591549295774648), ('n_features_in_', 88)]
  *FOLD R^2: -0.1207 (MSE: 0.8386; MAE: 0.6828; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7715502600838975), ('intercept_', 0.8385964912280702), ('n_features_in_', 88)]
  *FOLD R^2: 0.0650 (MSE: 0.9200; MAE: 0.7366; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8942989703608037), ('intercept_', 0.8596491228070176), ('n_features_in_', 88)]
  *FOLD R^2: -1.1751 (MSE: 0.9751; MAE: 0.5514; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1670
*Overall FOLDS R^2:    -0.2786 (+- 0.2026)
*R (sqrt R^2):         nan
*Pearson r:            0.0430 (p = 0.41887)
*Folds Pearson r:      0.0492 (p = 0.66190)
*Spearman rho:         0.0414 (p = 0.43630)
*Mean Squared Error:   0.9588
*Mean Absolute Error:  0.6853
*Train_Mean MAE:       0.2119

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7859701790435456), ('intercept_', 1.0140350877192983), ('n_features_in_', 88)]
  *FOLD R^2: -0.1029 (MSE: 1.0664; MAE: 0.6897; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.864450201619396), ('intercept_', 1.0280701754385966), ('n_features_in_', 88)]
  *FOLD R^2: 0.1480 (MSE: 0.7559; MAE: 0.6577; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8449220171310741), ('intercept_', 1.0492957746478873), ('n_features_in_', 88)]
  *FOLD R^2: -1.7340 (MSE: 2.2272; MAE: 0.9300; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7539296647682849), ('intercept_', 1.03859649122807), ('n_features_in_', 88)]
  *FOLD R^2: 0.0046 (MSE: 1.2329; MAE: 0.8957; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8734793548515393), ('intercept_', 0.9964912280701754), ('n_features_in_', 88)]
  *FOLD R^2: -2.6530 (MSE: 2.3972; MAE: 0.6641; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.6754
*Overall FOLDS R^2:    -0.8675 (+- 0.5026)
*R (sqrt R^2):         nan
*Pearson r:            0.0537 (p = 0.31226)
*Folds Pearson r:      0.1139 (p = 0.35973)
*Spearman rho:         0.2281 (p = 0.00001)
*Mean Squared Error:   1.5378
*Mean Absolute Error:  0.7679
*Train_Mean MAE:       0.3003

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.347595930626157), ('intercept_', 2.687719298245614), ('n_features_in_', 88)]
  *FOLD R^2: -0.0789 (MSE: 5.9241; MAE: 1.6767; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.6094030451080235), ('intercept_', 2.7473684210526317), ('n_features_in_', 88)]
  *FOLD R^2: 0.0401 (MSE: 5.1440; MAE: 1.7935; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.569278489729663), ('intercept_', 2.778169014084507), ('n_features_in_', 88)]
  *FOLD R^2: -1.1697 (MSE: 9.4620; MAE: 2.2230; mean train mae: 1.6373)
Fold 3

In [6]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:56:32
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.37745962838023134), ('intercept_', 0.6666666666666666), ('n_features_in_', 88)]
  *FOLD R^2: 0.0417 (MSE: 0.1813; MAE: 0.3831; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.3315821645542275), ('intercept_', 0.6549295774647886), ('n_features_in_', 88)]
  *FOLD R^2: -0.0141 (MSE: 0.3644; MAE: 0.4832; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.28610491241036107), ('intercept_', 0.6842105263157895), ('n_features_in_', 88)]
  *FOLD R^2: -0.2699 (MSE: 0.6001; MAE: 0.5685; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.31560245663350656), ('intercept_', 0.6912280701754385), ('n_features_in_', 88)]
  *FOLD R^2: -0.1564 (MSE: 0.4593; MAE: 0.5335; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3516323075799341), ('intercept_', 0.7157894736842105), ('n_features_in_', 88)]
  *FOLD R^2: -0.0724 (MSE: 0.2957; MAE: 0.4890; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0990
*Overall FOLDS R^2:    -0.0942 (+- 0.0490)
*R (sqrt R^2):         nan
*Pearson r:            0.0672 (p = 0.20581)
*Folds Pearson r:      0.1204 (p = 0.42667)
*Spearman rho:         0.1103 (p = 0.03745)
*Mean Squared Error:   0.3801
*Mean Absolute Error:  0.4915
*Train_Mean MAE:       0.1556

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4712882561979696), ('intercept_', 0.6596491228070175), ('n_features_in_', 88)]
  *FOLD R^2: 0.1096 (MSE: 0.5758; MAE: 0.5334; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5235634409756751), ('intercept_', 0.6549295774647889), ('n_features_in_', 88)]
  *FOLD R^2: -0.0115 (MSE: 0.4425; MAE: 0.4848; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4499062979332912), ('intercept_', 0.656140350877193), ('n_features_in_', 88)]
  *FOLD R^2: -22.6633 (MSE: 17.8097; MAE: 1.1238; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4958752005204555), ('intercept_', 0.6842105263157894), ('n_features_in_', 88)]
  *FOLD R^2: -0.0060 (MSE: 0.5169; MAE: 0.5611; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5206463348668338), ('intercept_', 0.7157894736842105), ('n_features_in_', 88)]
  *FOLD R^2: -0.2359 (MSE: 0.4482; MAE: 0.5195; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -6.1648
*Overall FOLDS R^2:    -4.5614 (+- 4.0480)
*R (sqrt R^2):         nan
*Pearson r:            0.0625 (p = 0.23925)
*Folds Pearson r:      0.2042 (p = 0.19790)
*Spearman rho:         0.3007 (p = 0.00000)
*Mean Squared Error:   3.9487
*Mean Absolute Error:  0.6441
*Train_Mean MAE:       0.3230

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6285599679024488), ('intercept_', 0.863157894736842), ('n_features_in_', 88)]
  *FOLD R^2: 0.2011 (MSE: 0.5315; MAE: 0.5481; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5455758048996031), ('intercept_', 0.8063380281690142), ('n_features_in_', 88)]
  *FOLD R^2: -0.0971 (MSE: 0.8524; MAE: 0.6688; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5833270333531599), ('intercept_', 0.8315789473684211), ('n_features_in_', 88)]
  *FOLD R^2: 0.0352 (MSE: 0.7969; MAE: 0.6051; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5956621059599653), ('intercept_', 0.8596491228070173), ('n_features_in_', 88)]
  *FOLD R^2: -0.0462 (MSE: 0.6869; MAE: 0.6154; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.638697510761382), ('intercept_', 0.8947368421052632), ('n_features_in_', 88)]
  *FOLD R^2: -0.2858 (MSE: 0.4989; MAE: 0.5462; mean train mae: 0.4618)
*Overall R^2:          0.0051
*Overall FOLDS R^2:    -0.0385 (+- 0.0714)
*R (sqrt R^2):         0.0711
*Pearson r:            0.2154 (p = 0.00004)
*Folds Pearson r:      0.2384 (p = 0.13396)
*Spearman rho:         0.2594 (p = 0.00000)
*Mean Squared Error:   0.6738
*Mean Absolute Error:  0.5969
*Train_Mean MAE:       0.2549

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.538745597604222), ('intercept_', 2.189473684210526), ('n_features_in_', 88)]
  *FOLD R^2: 0.2561 (MSE: 1.9108; MAE: 1.0737; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.293441549339383), ('intercept_', 2.1161971830985915), ('n_features_in_', 88)]
  *FOLD R^2: -0.0470 (MSE: 3.0777; MAE: 1.3207; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.200451812620702), ('intercept_', 2.1719298245614036), ('n_features_in_', 88)]
  *FOLD R^2: -6.0778 (MSE: 27.3341; MAE: 1.9650; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:56:56
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5153532481179527), ('intercept_', 0.8006644518272426), ('n_features_in_', 88)]
  *FOLD R^2: 0.0237 (MSE: 0.2792; MAE: 0.4015; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4295259211058377), ('intercept_', 0.7748344370860927), ('n_features_in_', 88)]
  *FOLD R^2: 0.0291 (MSE: 0.6559; MAE: 0.6095; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5115371092723986), ('intercept_', 0.8239202657807309), ('n_features_in_', 88)]
  *FOLD R^2: 0.0491 (MSE: 0.3100; MAE: 0.4308; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4432934824815905), ('intercept_', 0.7649006622516556), ('n_features_in_', 88)]
  *FOLD R^2: 0.0573 (MSE: 0.5826; MAE: 0.5081; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4338913110931489), ('intercept_', 0.8013245033112583), ('n_features_in_', 88)]
  *FOLD R^2: 0.0562 (MSE: 0.6000; MAE: 0.5415; mean train mae: 0.5997)
*Overall R^2:          0.0578
*Overall FOLDS R^2:    0.0431 (+- 0.0063)
*R (sqrt R^2):         0.2403
*Pearson r:            0.2441 (p = 0.00000)
*Folds Pearson r:      0.2749 (p = 0.02862)
*Spearman rho:         0.2625 (p = 0.00000)
*Mean Squared Error:   0.4845
*Mean Absolute Error:  0.4979
*Train_Mean MAE:       0.1587

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7075040436976902), ('intercept_', 0.7508305647840532), ('n_features_in_', 88)]
  *FOLD R^2: 0.0218 (MSE: 0.5745; MAE: 0.5492; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6929983204301345), ('intercept_', 0.7715231788079471), ('n_features_in_', 88)]
  *FOLD R^2: -0.0710 (MSE: 0.6504; MAE: 0.6461; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6891600002387075), ('intercept_', 0.7840531561461794), ('n_features_in_', 88)]
  *FOLD R^2: 0.0075 (MSE: 0.6413; MAE: 0.6035; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6345819023906554), ('intercept_', 0.7350993377483444), ('n_features_in_', 88)]
  *FOLD R^2: -0.0283 (MSE: 0.8416; MAE: 0.6604; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6607658123311277), ('intercept_', 0.7516556291390728), ('n_features_in_', 88)]
  *FOLD R^2: 0.0574 (MSE: 0.7614; MAE: 0.5914; mean train mae: 0.6564)
*Overall R^2:          0.0062
*Overall FOLDS R^2:    -0.0025 (+- 0.0196)
*R (sqrt R^2):         0.0787
*Pearson r:            0.1220 (p = 0.01783)
*Folds Pearson r:      0.1206 (p = 0.30916)
*Spearman rho:         0.1202 (p = 0.01960)
*Mean Squared Error:   0.6934
*Mean Absolute Error:  0.6100
*Train_Mean MAE:       0.1389

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7836759992353012), ('intercept_', 1.0099667774086378), ('n_features_in_', 88)]
  *FOLD R^2: -0.1123 (MSE: 0.7580; MAE: 0.6557; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7424189473119419), ('intercept_', 0.9867549668874173), ('n_features_in_', 88)]
  *FOLD R^2: 0.0247 (MSE: 0.8957; MAE: 0.6988; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8015042434889175), ('intercept_', 1.0332225913621262), ('n_features_in_', 88)]
  *FOLD R^2: -0.1223 (MSE: 0.6410; MAE: 0.6116; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6931761540423712), ('intercept_', 0.956953642384106), ('n_features_in_', 88)]
  *FOLD R^2: -0.0319 (MSE: 1.0468; MAE: 0.7354; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7138704324613242), ('intercept_', 1.0), ('n_features_in_', 88)]
  *FOLD R^2: 0.0425 (MSE: 0.9318; MAE: 0.7132; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0155
*Overall FOLDS R^2:    -0.0399 (+- 0.0304)
*R (sqrt R^2):         nan
*Pearson r:            0.1891 (p = 0.00022)
*Folds Pearson r:      0.2034 (p = 0.09208)
*Spearman rho:         0.2656 (p = 0.00000)
*Mean Squared Error:   0.8538
*Mean Absolute Error:  0.6827
*Train_Mean MAE:       0.2856

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.706010418410863), ('intercept_', 2.5614617940199333), ('n_features_in_', 88)]
  *FOLD R^2: -0.1778 (MSE: 3.3318; MAE: 1.4659; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.4753578198223782), ('intercept_', 2.533112582781457), ('n_features_in_', 88)]
  *FOLD R^2: 0.0221 (MSE: 4.0394; MAE: 1.5957; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.676466302159648), ('intercept_', 2.6411960132890364), ('n_features_in_', 88)]
  *FOLD R^2: 0.0498 (MSE: 2.9434; MAE: 1.3000; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]

In [8]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:57:13
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL1', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.41247741956996087), ('intercept_', 0.6843853820598007), ('n_features_in_', 88)]
  *FOLD R^2: -0.1559 (MSE: 0.3186; MAE: 0.4962; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10.0), ('best_score_', -0.397177354011008), ('intercept_', 0.6821192052980134), ('n_features_in_', 88)]
  *FOLD R^2: -31.1159 (MSE: 7.9933; MAE: 0.8426; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10.0), ('best_score_', -0.3347106832481923), ('intercept_', 0.6026490066225165), ('n_features_in_', 88)]
  *FOLD R^2: -0.4226 (MSE: 0.7471; MAE: 0.6334; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.39897473647841913), ('intercept_', 0.6212624584717606), ('n_features_in_', 88)]
  *FOLD R^2: -0.5886 (MSE: 0.4013; MAE: 0.5390; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.3064823320385828), ('intercept_', 0.6721854304635762), ('n_features_in_', 88)]
  *FOLD R^2: -0.2532 (MSE: 0.7076; MAE: 0.6781; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -4.1757
*Overall FOLDS R^2:    -6.5072 (+- 5.5031)
*R (sqrt R^2):         nan
*Pearson r:            0.0404 (p = 0.43364)
*Folds Pearson r:      -0.0082 (p = 0.35009)
*Spearman rho:         -0.0376 (p = 0.46631)
*Mean Squared Error:   2.0247
*Mean Absolute Error:  0.6372
*Train_Mean MAE:       0.2948

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40033609263435294), ('intercept_', 0.6777408637873754), ('n_features_in_', 88)]
  *FOLD R^2: -0.0215 (MSE: 0.7484; MAE: 0.6562; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.42613474001876805), ('intercept_', 0.6854304635761589), ('n_features_in_', 88)]
  *FOLD R^2: -0.8188 (MSE: 0.9215; MAE: 0.6277; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.45771093335981855), ('intercept_', 0.6556291390728476), ('n_features_in_', 88)]
  *FOLD R^2: -0.0040 (MSE: 0.4166; MAE: 0.4908; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4628800143029414), ('intercept_', 0.6378737541528239), ('n_features_in_', 88)]
  *FOLD R^2: -0.1354 (MSE: 0.3680; MAE: 0.4439; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4272006819973786), ('intercept_', 0.6854304635761589), ('n_features_in_', 88)]
  *FOLD R^2: -0.2132 (MSE: 0.5500; MAE: 0.6019; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.2204
*Overall FOLDS R^2:    -0.2386 (+- 0.1342)
*R (sqrt R^2):         nan
*Pearson r:            0.1185 (p = 0.02143)
*Folds Pearson r:      0.1420 (p = 0.35202)
*Spearman rho:         0.1963 (p = 0.00013)
*Mean Squared Error:   0.6007
*Mean Absolute Error:  0.5640
*Train_Mean MAE:       0.2502

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4677235849586193), ('intercept_', 0.7009966777408638), ('n_features_in_', 88)]
  *FOLD R^2: -0.0836 (MSE: 0.6934; MAE: 0.6456; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5211094722837911), ('intercept_', 0.7384105960264901), ('n_features_in_', 88)]
  *FOLD R^2: -0.1731 (MSE: 0.5518; MAE: 0.5592; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5159568119518371), ('intercept_', 0.6986754966887417), ('n_features_in_', 88)]
  *FOLD R^2: 0.0044 (MSE: 0.4779; MAE: 0.5492; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5260890569527645), ('intercept_', 0.7043189368770764), ('n_features_in_', 88)]
  *FOLD R^2: 0.0186 (MSE: 0.4287; MAE: 0.4711; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4971629067897145), ('intercept_', 0.7516556291390728), ('n_features_in_', 88)]
  *FOLD R^2: 0.0003 (MSE: 0.5623; MAE: 0.6067; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0327
*Overall FOLDS R^2:    -0.0467 (+- 0.0325)
*R (sqrt R^2):         nan
*Pearson r:            0.0908 (p = 0.07840)
*Folds Pearson r:      0.1146 (p = 0.38741)
*Spearman rho:         0.1122 (p = 0.02934)
*Mean Squared Error:   0.5429
*Mean Absolute Error:  0.5663
*Train_Mean MAE:       0.1429

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.2291632739083784), ('intercept_', 2.0631229235880393), ('n_features_in_', 88)]
  *FOLD R^2: -0.0861 (MSE: 3.0552; MAE: 1.4588; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.214050748956981), ('intercept_', 2.1059602649006623), ('n_features_in_', 88)]
  *FOLD R^2: -4.1598 (MSE: 11.9120; MAE: 1.5820; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.2552898702201047), ('intercept_', 1.9569536423841056), ('n_features_in_', 88)]
  *FOLD R^2: -0.1846 (MSE: 2.8676; MAE: 1.4328; mean train mae: 1.3755)
Fold 3

In [9]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:57:49
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL2', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5382117547682603), ('intercept_', 0.8006644518272426), ('n_features_in_', 512)]
  *FOLD R^2: -0.1758 (MSE: 0.3363; MAE: 0.4261; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4739269581691164), ('intercept_', 0.7748344370860927), ('n_features_in_', 512)]
  *FOLD R^2: -0.0066 (MSE: 0.6800; MAE: 0.6074; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5577486709647754), ('intercept_', 0.8239202657807309), ('n_features_in_', 512)]
  *FOLD R^2: -0.0488 (MSE: 0.3419; MAE: 0.4725; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4649673238465466), ('intercept_', 0.7649006622516556), ('n_features_in_', 512)]
  *FOLD R^2: -0.0771 (MSE: 0.6656; MAE: 0.5780; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4727679883476832), ('intercept_', 0.8013245033112583), ('n_features_in_', 512)]
  *FOLD R^2: -0.0031 (MSE: 0.6377; MAE: 0.5602; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0332
*Overall FOLDS R^2:    -0.0623 (+- 0.0282)
*R (sqrt R^2):         nan
*Pearson r:            0.0342 (p = 0.50758)
*Folds Pearson r:      0.0584 (p = 0.57554)
*Spearman rho:         0.0480 (p = 0.35262)
*Mean Squared Error:   0.5313
*Mean Absolute Error:  0.5284
*Train_Mean MAE:       0.1148

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7078121036149159), ('intercept_', 0.7508305647840532), ('n_features_in_', 512)]
  *FOLD R^2: -0.0135 (MSE: 0.5952; MAE: 0.5636; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7117950860673005), ('intercept_', 0.7715231788079471), ('n_features_in_', 512)]
  *FOLD R^2: -0.0225 (MSE: 0.6209; MAE: 0.6267; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.702850733262524), ('intercept_', 0.7840531561461794), ('n_features_in_', 512)]
  *FOLD R^2: -0.0319 (MSE: 0.6667; MAE: 0.6242; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.656355251949414), ('intercept_', 0.7350993377483444), ('n_features_in_', 512)]
  *FOLD R^2: -0.0168 (MSE: 0.8322; MAE: 0.6616; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6609208921430831), ('intercept_', 0.7516556291390728), ('n_features_in_', 512)]
  *FOLD R^2: 0.0197 (MSE: 0.7919; MAE: 0.6537; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0047
*Overall FOLDS R^2:    -0.0130 (+- 0.0078)
*R (sqrt R^2):         nan
*Pearson r:            0.1130 (p = 0.02819)
*Folds Pearson r:      0.1230 (p = 0.29953)
*Spearman rho:         0.0848 (p = 0.10002)
*Mean Squared Error:   0.7010
*Mean Absolute Error:  0.6258
*Train_Mean MAE:       0.1635

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8480683502237961), ('intercept_', 1.0099667774086378), ('n_features_in_', 512)]
  *FOLD R^2: -0.1501 (MSE: 0.7837; MAE: 0.6205; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8264574961700721), ('intercept_', 0.9867549668874173), ('n_features_in_', 512)]
  *FOLD R^2: 0.0203 (MSE: 0.8997; MAE: 0.7033; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8851955440205466), ('intercept_', 1.0332225913621262), ('n_features_in_', 512)]
  *FOLD R^2: -0.1328 (MSE: 0.6470; MAE: 0.5626; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7636226541154103), ('intercept_', 0.956953642384106), ('n_features_in_', 512)]
  *FOLD R^2: -0.0636 (MSE: 1.0789; MAE: 0.7373; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.767386563198655), ('intercept_', 1.0), ('n_features_in_', 512)]
  *FOLD R^2: -0.0589 (MSE: 1.0305; MAE: 0.7410; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0549
*Overall FOLDS R^2:    -0.0770 (+- 0.0272)
*R (sqrt R^2):         nan
*Pearson r:            0.0196 (p = 0.70431)
*Folds Pearson r:      0.0222 (p = 0.55875)
*Spearman rho:         0.0546 (p = 0.29003)
*Mean Squared Error:   0.8870
*Mean Absolute Error:  0.6725
*Train_Mean MAE:       0.1831

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.9174730613794653), ('intercept_', 2.5614617940199333), ('n_features_in_', 512)]
  *FOLD R^2: -0.1084 (MSE: 3.1355; MAE: 1.2804; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.8396937434144967), ('intercept_', 2.533112582781457), ('n_features_in_', 512)]
  *FOLD R^2: 0.0538 (MSE: 3.9084; MAE: 1.5884; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.990070895786507), ('intercept_', 2.6411960132890364), ('n_features_in_', 512)]

In [10]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 17:59:08
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40217809325063764), ('intercept_', 0.6843853820598007), ('n_features_in_', 512)]
  *FOLD R^2: -0.1953 (MSE: 0.3294; MAE: 0.5065; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3966986679484005), ('intercept_', 0.6821192052980133), ('n_features_in_', 512)]
  *FOLD R^2: -0.1556 (MSE: 0.2876; MAE: 0.4652; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3367115425732341), ('intercept_', 0.6026490066225165), ('n_features_in_', 512)]
  *FOLD R^2: -0.0436 (MSE: 0.5481; MAE: 0.5435; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4025058555464382), ('intercept_', 0.6212624584717608), ('n_features_in_', 512)]
  *FOLD R^2: -0.1113 (MSE: 0.2807; MAE: 0.4398; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.32459129344120635), ('intercept_', 0.6721854304635762), ('n_features_in_', 512)]
  *FOLD R^2: -0.0037 (MSE: 0.5667; MAE: 0.6159; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0276
*Overall FOLDS R^2:    -0.1019 (+- 0.0315)
*R (sqrt R^2):         nan
*Pearson r:            0.1071 (p = 0.03774)
*Folds Pearson r:      0.1267 (p = 0.41180)
*Spearman rho:         0.1077 (p = 0.03663)
*Mean Squared Error:   0.4020
*Mean Absolute Error:  0.5140
*Train_Mean MAE:       0.1477

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4176567419720751), ('intercept_', 0.6777408637873754), ('n_features_in_', 512)]
  *FOLD R^2: -0.1490 (MSE: 0.8419; MAE: 0.7225; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4557312256429714), ('intercept_', 0.6854304635761589), ('n_features_in_', 512)]
  *FOLD R^2: -0.1479 (MSE: 0.5816; MAE: 0.6080; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4977610897120042), ('intercept_', 0.6556291390728477), ('n_features_in_', 512)]
  *FOLD R^2: -0.0190 (MSE: 0.4228; MAE: 0.4672; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4980609526014787), ('intercept_', 0.6378737541528239), ('n_features_in_', 512)]
  *FOLD R^2: -0.2631 (MSE: 0.4094; MAE: 0.5111; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.488714310475175), ('intercept_', 0.6854304635761589), ('n_features_in_', 512)]
  *FOLD R^2: -0.0295 (MSE: 0.4667; MAE: 0.5709; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1071
*Overall FOLDS R^2:    -0.1217 (+- 0.0402)
*R (sqrt R^2):         nan
*Pearson r:            -0.0141 (p = 0.78479)
*Folds Pearson r:      -0.0093 (p = 0.34103)
*Spearman rho:         -0.0049 (p = 0.92514)
*Mean Squared Error:   0.5449
*Mean Absolute Error:  0.5762
*Train_Mean MAE:       0.1747

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.48566295272099974), ('intercept_', 0.7009966777408638), ('n_features_in_', 512)]
  *FOLD R^2: -0.1213 (MSE: 0.7175; MAE: 0.6679; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5411122919122364), ('intercept_', 0.7384105960264901), ('n_features_in_', 512)]
  *FOLD R^2: -0.0191 (MSE: 0.4794; MAE: 0.5707; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5386136806432341), ('intercept_', 0.6986754966887417), ('n_features_in_', 512)]
  *FOLD R^2: -0.0196 (MSE: 0.4894; MAE: 0.5479; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5320209263978746), ('intercept_', 0.7043189368770764), ('n_features_in_', 512)]
  *FOLD R^2: -0.1462 (MSE: 0.5007; MAE: 0.5476; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100000.0), ('best_score_', -0.512839106411848), ('intercept_', 0.7516556291390728), ('n_features_in_', 512)]
  *FOLD R^2: -0.0429 (MSE: 0.5866; MAE: 0.6178; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0557
*Overall FOLDS R^2:    -0.0698 (+- 0.0239)
*R (sqrt R^2):         nan
*Pearson r:            -0.0727 (p = 0.15882)
*Folds Pearson r:      0.0678 (p = 0.38431)
*Spearman rho:         -0.1051 (p = 0.04137)
*Mean Squared Error:   0.5550
*Mean Absolute Error:  0.5905
*Train_Mean MAE:       0.0738

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.2760565652769937), ('intercept_', 2.0631229235880397), ('n_features_in_', 512)]
  *FOLD R^2: -0.1685 (MSE: 3.2871; MAE: 1.4505; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.34921529839427), ('intercept_', 2.1059602649006623), ('n_features_in_', 512)]
  *FOLD R^2: -0.0997 (MSE: 2.5388; MAE: 1.2956; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [11]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:00:41
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CEL_Total', 'CELVAL1', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6857366938963718), ('intercept_', 0.856140350877193), ('n_features_in_', 512)]
  *FOLD R^2: -0.0152 (MSE: 0.7334; MAE: 0.5708; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6703650888446108), ('intercept_', 0.8666666666666667), ('n_features_in_', 512)]
  *FOLD R^2: -0.0171 (MSE: 0.7913; MAE: 0.6462; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7060731684030046), ('intercept_', 0.8697183098591549), ('n_features_in_', 512)]
  *FOLD R^2: -0.2612 (MSE: 0.6985; MAE: 0.6377; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6110174695997924), ('intercept_', 0.8245614035087719), ('n_features_in_', 512)]
  *FOLD R^2: -0.0523 (MSE: 1.0663; MAE: 0.7348; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.760316722805824), ('intercept_', 0.8526315789473684), ('n_features_in_', 512)]
  *FOLD R^2: -0.1132 (MSE: 0.4483; MAE: 0.4644; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0712
*Overall FOLDS R^2:    -0.0918 (+- 0.0411)
*R (sqrt R^2):         nan
*Pearson r:            -0.0946 (p = 0.07466)
*Folds Pearson r:      -0.0694 (p = 0.70086)
*Spearman rho:         -0.0787 (p = 0.13819)
*Mean Squared Error:   0.7474
*Mean Absolute Error:  0.6108
*Train_Mean MAE:       0.1127

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7358800244900743), ('intercept_', 0.8175438596491228), ('n_features_in_', 512)]
  *FOLD R^2: -0.0115 (MSE: 0.9812; MAE: 0.6774; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.718196041855641), ('intercept_', 0.8526315789473684), ('n_features_in_', 512)]
  *FOLD R^2: -0.0874 (MSE: 1.0203; MAE: 0.7882; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8122374276655034), ('intercept_', 0.8591549295774648), ('n_features_in_', 512)]
  *FOLD R^2: -0.0042 (MSE: 0.7514; MAE: 0.6504; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7483708337323982), ('intercept_', 0.8385964912280702), ('n_features_in_', 512)]
  *FOLD R^2: -0.0244 (MSE: 1.0080; MAE: 0.7605; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8635687450435107), ('intercept_', 0.8596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.0230 (MSE: 0.4586; MAE: 0.5094; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0268
*Overall FOLDS R^2:    -0.0301 (+- 0.0132)
*R (sqrt R^2):         nan
*Pearson r:            0.0930 (p = 0.07975)
*Folds Pearson r:      0.1075 (p = 0.34592)
*Spearman rho:         0.0606 (p = 0.25447)
*Mean Squared Error:   0.8437
*Mean Absolute Error:  0.6771
*Train_Mean MAE:       0.1981

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8651001543874198), ('intercept_', 1.0140350877192983), ('n_features_in_', 512)]
  *FOLD R^2: -0.1111 (MSE: 1.0743; MAE: 0.6995; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9002919172995146), ('intercept_', 1.0280701754385966), ('n_features_in_', 512)]
  *FOLD R^2: -0.0907 (MSE: 0.9676; MAE: 0.7583; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9126080425552872), ('intercept_', 1.0492957746478873), ('n_features_in_', 512)]
  *FOLD R^2: -0.1344 (MSE: 0.9241; MAE: 0.7198; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8297066242911633), ('intercept_', 1.03859649122807), ('n_features_in_', 512)]
  *FOLD R^2: -0.0305 (MSE: 1.2765; MAE: 0.8559; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9360372563584917), ('intercept_', 0.9964912280701754), ('n_features_in_', 512)]
  *FOLD R^2: -0.1140 (MSE: 0.7310; MAE: 0.5402; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0835
*Overall FOLDS R^2:    -0.0962 (+- 0.0159)
*R (sqrt R^2):         nan
*Pearson r:            -0.0670 (p = 0.20696)
*Folds Pearson r:      -0.0806 (p = 0.54396)
*Spearman rho:         -0.0523 (p = 0.32504)
*Mean Squared Error:   0.9945
*Mean Absolute Error:  0.7148
*Train_Mean MAE:       0.1694

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.7841617059655315), ('intercept_', 2.687719298245614), ('n_features_in_', 512)]
  *FOLD R^2: -0.0506 (MSE: 5.7686; MAE: 1.6922; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.677625662977977), ('intercept_', 2.7473684210526317), ('n_features_in_', 512)]
  *FOLD R^2: -0.1025 (MSE: 5.9079; MAE: 1.9095; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [12]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:03:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CEL_Total', 'CELVAL2', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3863843593512378), ('intercept_', 0.6666666666666666), ('n_features_in_', 512)]
  *FOLD R^2: -0.0347 (MSE: 0.1958; MAE: 0.4181; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.338239534652165), ('intercept_', 0.6549295774647887), ('n_features_in_', 512)]
  *FOLD R^2: -0.1315 (MSE: 0.4066; MAE: 0.5411; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3165685639744906), ('intercept_', 0.6842105263157895), ('n_features_in_', 512)]
  *FOLD R^2: -0.0003 (MSE: 0.4727; MAE: 0.5506; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.33518865937445386), ('intercept_', 0.6912280701754386), ('n_features_in_', 512)]
  *FOLD R^2: -0.0051 (MSE: 0.3992; MAE: 0.5215; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.36043543878388595), ('intercept_', 0.7157894736842105), ('n_features_in_', 512)]
  *FOLD R^2: -0.1006 (MSE: 0.3035; MAE: 0.4989; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0284
*Overall FOLDS R^2:    -0.0544 (+- 0.0235)
*R (sqrt R^2):         nan
*Pearson r:            -0.2062 (p = 0.00009)
*Folds Pearson r:      -0.1369 (p = 0.42923)
*Spearman rho:         -0.2195 (p = 0.00003)
*Mean Squared Error:   0.3557
*Mean Absolute Error:  0.5061
*Train_Mean MAE:       0.0236

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5294362839179927), ('intercept_', 0.6596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.0797 (MSE: 0.6983; MAE: 0.6342; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5755177098663583), ('intercept_', 0.6549295774647887), ('n_features_in_', 512)]
  *FOLD R^2: -0.1078 (MSE: 0.4847; MAE: 0.5730; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5029119483486146), ('intercept_', 0.656140350877193), ('n_features_in_', 512)]
  *FOLD R^2: -0.0107 (MSE: 0.7607; MAE: 0.6818; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5640065353408438), ('intercept_', 0.6842105263157895), ('n_features_in_', 512)]
  *FOLD R^2: -0.0060 (MSE: 0.5169; MAE: 0.5860; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5936777358805922), ('intercept_', 0.7157894736842105), ('n_features_in_', 512)]
  *FOLD R^2: -0.1200 (MSE: 0.4061; MAE: 0.5575; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0398
*Overall FOLDS R^2:    -0.0649 (+- 0.0214)
*R (sqrt R^2):         nan
*Pearson r:            -0.0791 (p = 0.13639)
*Folds Pearson r:      -0.1095 (p = 0.51819)
*Spearman rho:         -0.1381 (p = 0.00908)
*Mean Squared Error:   0.5731
*Mean Absolute Error:  0.6064
*Train_Mean MAE:       0.0584

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6651744848889748), ('intercept_', 0.8631578947368421), ('n_features_in_', 512)]
  *FOLD R^2: -0.0261 (MSE: 0.6827; MAE: 0.6020; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6120883544127839), ('intercept_', 0.8063380281690141), ('n_features_in_', 512)]
  *FOLD R^2: -0.1403 (MSE: 0.8860; MAE: 0.6814; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6239204845130102), ('intercept_', 0.8315789473684211), ('n_features_in_', 512)]
  *FOLD R^2: -0.0167 (MSE: 0.8398; MAE: 0.6248; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6317203588078337), ('intercept_', 0.8596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.1819 (MSE: 0.7760; MAE: 0.6112; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7308612231811822), ('intercept_', 0.8947368421052632), ('n_features_in_', 512)]
  *FOLD R^2: -0.0823 (MSE: 0.4199; MAE: 0.4514; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0651
*Overall FOLDS R^2:    -0.0894 (+- 0.0286)
*R (sqrt R^2):         nan
*Pearson r:            0.0016 (p = 0.97608)
*Folds Pearson r:      0.0541 (p = 0.48877)
*Spearman rho:         0.0587 (p = 0.26921)
*Mean Squared Error:   0.7214
*Mean Absolute Error:  0.5944
*Train_Mean MAE:       0.1632

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.886868447765419), ('intercept_', 2.1894736842105265), ('n_features_in_', 512)]
  *FOLD R^2: -0.1151 (MSE: 2.8642; MAE: 1.3557; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.7026616749716683), ('intercept_', 2.1161971830985915), ('n_features_in_', 512)]
  *FOLD R^2: -0.2622 (MSE: 3.7104; MAE: 1.5417; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [13]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:17:45
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5437399025100528), ('intercept_', 0.8006644518272426), ('n_features_in_', 512)]
  *FOLD R^2: -0.1141 (MSE: 0.3186; MAE: 0.4195; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.47492524214260684), ('intercept_', 0.7748344370860927), ('n_features_in_', 512)]
  *FOLD R^2: 0.0372 (MSE: 0.6504; MAE: 0.6006; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5573144007344357), ('intercept_', 0.8239202657807309), ('n_features_in_', 512)]
  *FOLD R^2: -0.0449 (MSE: 0.3406; MAE: 0.4740; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.46655772802219314), ('intercept_', 0.7649006622516556), ('n_features_in_', 512)]
  *FOLD R^2: -0.0524 (MSE: 0.6504; MAE: 0.5713; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4680871193397735), ('intercept_', 0.8013245033112583), ('n_features_in_', 512)]
  *FOLD R^2: -0.0132 (MSE: 0.6442; MAE: 0.5658; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0109
*Overall FOLDS R^2:    -0.0375 (+- 0.0222)
*R (sqrt R^2):         nan
*Pearson r:            0.1005 (p = 0.05123)
*Folds Pearson r:      0.1073 (p = 0.44343)
*Spearman rho:         0.1049 (p = 0.04176)
*Mean Squared Error:   0.5198
*Mean Absolute Error:  0.5258
*Train_Mean MAE:       0.1404

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7100629018605751), ('intercept_', 0.7508305647840532), ('n_features_in_', 512)]
  *FOLD R^2: 0.0147 (MSE: 0.5787; MAE: 0.5541; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7095440324792569), ('intercept_', 0.7715231788079471), ('n_features_in_', 512)]
  *FOLD R^2: -0.0045 (MSE: 0.6100; MAE: 0.6191; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7034754242508203), ('intercept_', 0.7840531561461794), ('n_features_in_', 512)]
  *FOLD R^2: -0.0212 (MSE: 0.6598; MAE: 0.6155; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6574526734691677), ('intercept_', 0.7350993377483444), ('n_features_in_', 512)]
  *FOLD R^2: -0.0063 (MSE: 0.8236; MAE: 0.6562; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6596135981698841), ('intercept_', 0.7516556291390728), ('n_features_in_', 512)]
  *FOLD R^2: 0.0234 (MSE: 0.7890; MAE: 0.6498; mean train mae: 0.6564)
*Overall R^2:          0.0084
*Overall FOLDS R^2:    0.0012 (+- 0.0071)
*R (sqrt R^2):         0.0917
*Pearson r:            0.1334 (p = 0.00952)
*Folds Pearson r:      0.1438 (p = 0.22544)
*Spearman rho:         0.1119 (p = 0.02981)
*Mean Squared Error:   0.6918
*Mean Absolute Error:  0.6188
*Train_Mean MAE:       0.1506

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8494894434548638), ('intercept_', 1.0099667774086378), ('n_features_in_', 512)]
  *FOLD R^2: -0.0812 (MSE: 0.7368; MAE: 0.6066; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.817549045416928), ('intercept_', 0.9867549668874173), ('n_features_in_', 512)]
  *FOLD R^2: 0.0528 (MSE: 0.8699; MAE: 0.6840; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8763993491729659), ('intercept_', 1.0332225913621262), ('n_features_in_', 512)]
  *FOLD R^2: -0.1289 (MSE: 0.6448; MAE: 0.5596; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7650341598515706), ('intercept_', 0.956953642384106), ('n_features_in_', 512)]
  *FOLD R^2: -0.0369 (MSE: 1.0518; MAE: 0.7145; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7645757172601444), ('intercept_', 1.0), ('n_features_in_', 512)]
  *FOLD R^2: -0.0438 (MSE: 1.0157; MAE: 0.7342; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0262
*Overall FOLDS R^2:    -0.0476 (+- 0.0268)
*R (sqrt R^2):         nan
*Pearson r:            0.0651 (p = 0.20734)
*Folds Pearson r:      0.0737 (p = 0.60289)
*Spearman rho:         0.0893 (p = 0.08326)
*Mean Squared Error:   0.8629
*Mean Absolute Error:  0.6594
*Train_Mean MAE:       0.1735

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.9687968727570238), ('intercept_', 2.5614617940199333), ('n_features_in_', 512)]
  *FOLD R^2: -0.0414 (MSE: 2.9461; MAE: 1.2535; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.814841115943813), ('intercept_', 2.533112582781457), ('n_features_in_', 512)]
  *FOLD R^2: 0.0731 (MSE: 3.8287; MAE: 1.5543; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.98218919424353), ('intercept_', 2.6411960132890364), ('n_features_in_', 512)]
  *FOLD R^2: -0.0799 (MSE: 3.3453; MAE: 1.3734; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]

In [14]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:19:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4118511977123811), ('intercept_', 0.6843853820598007), ('n_features_in_', 512)]
  *FOLD R^2: -0.1843 (MSE: 0.3264; MAE: 0.5061; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40749569101012406), ('intercept_', 0.6821192052980133), ('n_features_in_', 512)]
  *FOLD R^2: -0.1415 (MSE: 0.2841; MAE: 0.4651; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3391612239341461), ('intercept_', 0.6026490066225165), ('n_features_in_', 512)]
  *FOLD R^2: -0.0738 (MSE: 0.5639; MAE: 0.5464; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.41042847597262816), ('intercept_', 0.6212624584717608), ('n_features_in_', 512)]
  *FOLD R^2: -0.1508 (MSE: 0.2907; MAE: 0.4535; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3271702401741899), ('intercept_', 0.6721854304635762), ('n_features_in_', 512)]
  *FOLD R^2: -0.0422 (MSE: 0.5885; MAE: 0.6274; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0485
*Overall FOLDS R^2:    -0.1185 (+- 0.0234)
*R (sqrt R^2):         nan
*Pearson r:            0.0636 (p = 0.21802)
*Folds Pearson r:      0.0926 (p = 0.57534)
*Spearman rho:         0.0743 (p = 0.15006)
*Mean Squared Error:   0.4102
*Mean Absolute Error:  0.5195
*Train_Mean MAE:       0.1400

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.41961687992354985), ('intercept_', 0.6777408637873754), ('n_features_in_', 512)]
  *FOLD R^2: -0.1752 (MSE: 0.8611; MAE: 0.7322; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4637581282678069), ('intercept_', 0.6854304635761589), ('n_features_in_', 512)]
  *FOLD R^2: -0.1252 (MSE: 0.5701; MAE: 0.6077; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.49901867929056176), ('intercept_', 0.6556291390728477), ('n_features_in_', 512)]
  *FOLD R^2: -0.0375 (MSE: 0.4305; MAE: 0.4749; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5058806575342769), ('intercept_', 0.6378737541528239), ('n_features_in_', 512)]
  *FOLD R^2: -0.2760 (MSE: 0.4136; MAE: 0.5189; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4960889571942993), ('intercept_', 0.6854304635761589), ('n_features_in_', 512)]
  *FOLD R^2: -0.0385 (MSE: 0.4708; MAE: 0.5722; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1168
*Overall FOLDS R^2:    -0.1305 (+- 0.0402)
*R (sqrt R^2):         nan
*Pearson r:            -0.0465 (p = 0.36751)
*Folds Pearson r:      -0.0317 (p = 0.34810)
*Spearman rho:         -0.0337 (p = 0.51422)
*Mean Squared Error:   0.5497
*Mean Absolute Error:  0.5814
*Train_Mean MAE:       0.1653

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.486786207388827), ('intercept_', 0.7009966777408638), ('n_features_in_', 512)]
  *FOLD R^2: -0.1158 (MSE: 0.7140; MAE: 0.6630; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5411173497276459), ('intercept_', 0.7384105960264901), ('n_features_in_', 512)]
  *FOLD R^2: -0.0190 (MSE: 0.4793; MAE: 0.5707; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5386237261327398), ('intercept_', 0.6986754966887417), ('n_features_in_', 512)]
  *FOLD R^2: -0.0196 (MSE: 0.4894; MAE: 0.5478; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5318660196821955), ('intercept_', 0.7043189368770764), ('n_features_in_', 512)]
  *FOLD R^2: -0.1534 (MSE: 0.5038; MAE: 0.5500; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100000.0), ('best_score_', -0.5127516883817929), ('intercept_', 0.7516556291390728), ('n_features_in_', 512)]
  *FOLD R^2: -0.0433 (MSE: 0.5868; MAE: 0.6174; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0556
*Overall FOLDS R^2:    -0.0702 (+- 0.0244)
*R (sqrt R^2):         nan
*Pearson r:            -0.0882 (p = 0.08737)
*Folds Pearson r:      0.0535 (p = 0.35293)
*Spearman rho:         -0.1107 (p = 0.03158)
*Mean Squared Error:   0.5550
*Mean Absolute Error:  0.5899
*Train_Mean MAE:       0.0708

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.3066613672207046), ('intercept_', 2.0631229235880397), ('n_features_in_', 512)]
  *FOLD R^2: -0.1753 (MSE: 3.3062; MAE: 1.4539; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.3914680429324386), ('intercept_', 2.1059602649006623), ('n_features_in_', 512)]
  *FOLD R^2: -0.0885 (MSE: 2.5129; MAE: 1.2871; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [15]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:22:02
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6887503964598957), ('intercept_', 0.856140350877193), ('n_features_in_', 512)]
  *FOLD R^2: -0.0252 (MSE: 0.7407; MAE: 0.5756; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.675657452212133), ('intercept_', 0.8666666666666667), ('n_features_in_', 512)]
  *FOLD R^2: -0.0166 (MSE: 0.7910; MAE: 0.6455; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7200161219008432), ('intercept_', 0.8697183098591549), ('n_features_in_', 512)]
  *FOLD R^2: -0.2409 (MSE: 0.6872; MAE: 0.6347; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6155109923256668), ('intercept_', 0.8245614035087719), ('n_features_in_', 512)]
  *FOLD R^2: -0.0581 (MSE: 1.0722; MAE: 0.7376; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7653744639638098), ('intercept_', 0.8526315789473684), ('n_features_in_', 512)]
  *FOLD R^2: -0.1732 (MSE: 0.4724; MAE: 0.4717; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0785
*Overall FOLDS R^2:    -0.1028 (+- 0.0397)
*R (sqrt R^2):         nan
*Pearson r:            -0.1264 (p = 0.01702)
*Folds Pearson r:      -0.1088 (p = 0.45012)
*Spearman rho:         -0.1191 (p = 0.02462)
*Mean Squared Error:   0.7525
*Mean Absolute Error:  0.6131
*Train_Mean MAE:       0.1063

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7322042416982852), ('intercept_', 0.8175438596491228), ('n_features_in_', 512)]
  *FOLD R^2: -0.0202 (MSE: 0.9896; MAE: 0.6761; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7203675772431636), ('intercept_', 0.8526315789473684), ('n_features_in_', 512)]
  *FOLD R^2: -0.0716 (MSE: 1.0055; MAE: 0.7777; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8182817502712467), ('intercept_', 0.8591549295774648), ('n_features_in_', 512)]
  *FOLD R^2: -0.0010 (MSE: 0.7490; MAE: 0.6533; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7504293756360172), ('intercept_', 0.8385964912280702), ('n_features_in_', 512)]
  *FOLD R^2: -0.0376 (MSE: 1.0210; MAE: 0.7543; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8649227125690505), ('intercept_', 0.8596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.0603 (MSE: 0.4754; MAE: 0.5099; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0319
*Overall FOLDS R^2:    -0.0381 (+- 0.0115)
*R (sqrt R^2):         nan
*Pearson r:            0.0709 (p = 0.18223)
*Folds Pearson r:      0.0850 (p = 0.44754)
*Spearman rho:         0.0404 (p = 0.44681)
*Mean Squared Error:   0.8478
*Mean Absolute Error:  0.6742
*Train_Mean MAE:       0.1896

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8517755086536056), ('intercept_', 1.0140350877192983), ('n_features_in_', 512)]
  *FOLD R^2: -0.1337 (MSE: 1.0961; MAE: 0.7007; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8987810837199045), ('intercept_', 1.0280701754385966), ('n_features_in_', 512)]
  *FOLD R^2: -0.0545 (MSE: 0.9355; MAE: 0.7350; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9092418647999381), ('intercept_', 1.0492957746478873), ('n_features_in_', 512)]
  *FOLD R^2: -0.1180 (MSE: 0.9108; MAE: 0.7133; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8335021349773952), ('intercept_', 1.03859649122807), ('n_features_in_', 512)]
  *FOLD R^2: -0.0622 (MSE: 1.3157; MAE: 0.9147; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.9380621343546975), ('intercept_', 0.9964912280701754), ('n_features_in_', 512)]
  *FOLD R^2: -0.1089 (MSE: 0.7277; MAE: 0.5378; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0861
*Overall FOLDS R^2:    -0.0955 (+- 0.0140)
*R (sqrt R^2):         nan
*Pearson r:            -0.0534 (p = 0.31459)
*Folds Pearson r:      -0.0520 (p = 0.66456)
*Spearman rho:         -0.0377 (p = 0.47832)
*Mean Squared Error:   0.9969
*Mean Absolute Error:  0.7203
*Train_Mean MAE:       0.1904

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.788490138786829), ('intercept_', 2.687719298245614), ('n_features_in_', 512)]
  *FOLD R^2: -0.0853 (MSE: 5.9591; MAE: 1.7196; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.7457738294086305), ('intercept_', 2.7473684210526317), ('n_features_in_', 512)]
  *FOLD R^2: -0.0888 (MSE: 5.8349; MAE: 1.9009; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

### DLATK Feature Extraction with Whisper Features

Running DLATK predictions using Whisper speech embeddings (mean and median aggregations)

In [16]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:23:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3863531889476826), ('intercept_', 0.6666666666666666), ('n_features_in_', 512)]
  *FOLD R^2: -0.0353 (MSE: 0.1959; MAE: 0.4182; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3388167101509199), ('intercept_', 0.6549295774647887), ('n_features_in_', 512)]
  *FOLD R^2: -0.1232 (MSE: 0.4037; MAE: 0.5392; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3165805235264322), ('intercept_', 0.6842105263157895), ('n_features_in_', 512)]
  *FOLD R^2: -0.0003 (MSE: 0.4727; MAE: 0.5506; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3352051590691486), ('intercept_', 0.6912280701754386), ('n_features_in_', 512)]
  *FOLD R^2: -0.0052 (MSE: 0.3992; MAE: 0.5216; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.3604317665446666), ('intercept_', 0.7157894736842105), ('n_features_in_', 512)]
  *FOLD R^2: -0.1008 (MSE: 0.3035; MAE: 0.4989; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0268
*Overall FOLDS R^2:    -0.0530 (+- 0.0224)
*R (sqrt R^2):         nan
*Pearson r:            -0.2073 (p = 0.00008)
*Folds Pearson r:      -0.1536 (p = 0.36876)
*Spearman rho:         -0.2141 (p = 0.00005)
*Mean Squared Error:   0.3551
*Mean Absolute Error:  0.5058
*Train_Mean MAE:       0.0227

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5300812446533221), ('intercept_', 0.6596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.0082 (MSE: 0.6520; MAE: 0.6119; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5787702408070923), ('intercept_', 0.6549295774647887), ('n_features_in_', 512)]
  *FOLD R^2: -0.1012 (MSE: 0.4818; MAE: 0.5705; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5029148883259169), ('intercept_', 0.656140350877193), ('n_features_in_', 512)]
  *FOLD R^2: -0.0108 (MSE: 0.7608; MAE: 0.6818; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.5640755278430589), ('intercept_', 0.6842105263157895), ('n_features_in_', 512)]
  *FOLD R^2: -0.0062 (MSE: 0.5170; MAE: 0.5860; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.593706790307366), ('intercept_', 0.7157894736842105), ('n_features_in_', 512)]
  *FOLD R^2: -0.1201 (MSE: 0.4062; MAE: 0.5575; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0221
*Overall FOLDS R^2:    -0.0493 (+- 0.0226)
*R (sqrt R^2):         nan
*Pearson r:            -0.1664 (p = 0.00163)
*Folds Pearson r:      -0.1272 (p = 0.55713)
*Spearman rho:         -0.1752 (p = 0.00090)
*Mean Squared Error:   0.5633
*Mean Absolute Error:  0.6015
*Train_Mean MAE:       0.0298

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6704972482055921), ('intercept_', 0.8631578947368421), ('n_features_in_', 512)]
  *FOLD R^2: -0.0178 (MSE: 0.6772; MAE: 0.5996; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6161638599885588), ('intercept_', 0.8063380281690141), ('n_features_in_', 512)]
  *FOLD R^2: -0.1291 (MSE: 0.8773; MAE: 0.6749; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6261748892631128), ('intercept_', 0.8315789473684211), ('n_features_in_', 512)]
  *FOLD R^2: -0.0173 (MSE: 0.8403; MAE: 0.6258; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6380863616247426), ('intercept_', 0.8596491228070176), ('n_features_in_', 512)]
  *FOLD R^2: -0.1690 (MSE: 0.7676; MAE: 0.6033; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7329766188928136), ('intercept_', 0.8947368421052632), ('n_features_in_', 512)]
  *FOLD R^2: -0.0886 (MSE: 0.4224; MAE: 0.4523; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0592
*Overall FOLDS R^2:    -0.0843 (+- 0.0269)
*R (sqrt R^2):         nan
*Pearson r:            0.0013 (p = 0.98118)
*Folds Pearson r:      0.0529 (p = 0.48940)
*Spearman rho:         0.0584 (p = 0.27172)
*Mean Squared Error:   0.7174
*Mean Absolute Error:  0.5914
*Train_Mean MAE:       0.1584

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.892682021173825), ('intercept_', 2.1894736842105265), ('n_features_in_', 512)]
  *FOLD R^2: -0.1059 (MSE: 2.8406; MAE: 1.3540; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.7082709823304105), ('intercept_', 2.1161971830985915), ('n_features_in_', 512)]
  *FOLD R^2: -0.2408 (MSE: 3.6475; MAE: 1.5346; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [17]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:24:08
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5196389799120172), ('intercept_', 0.8006644518272426), ('n_features_in_', 1150)]
  *FOLD R^2: -0.3357 (MSE: 0.3820; MAE: 0.4654; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4524206716351599), ('intercept_', 0.7748344370860927), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0153 (MSE: 0.6652; MAE: 0.6068; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5380342123016574), ('intercept_', 0.8239202657807309), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0351 (MSE: 0.3146; MAE: 0.4465; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4507635465680819), ('intercept_', 0.7649006622516555), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0514 (MSE: 0.6497; MAE: 0.5577; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4537734688984656), ('intercept_', 0.8013245033112583), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0289 (MSE: 0.6174; MAE: 0.5479; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0207
*Overall FOLDS R^2:    -0.0616 (+- 0.0628)
*R (sqrt R^2):         nan
*Pearson r:            0.1225 (p = 0.01738)
*Folds Pearson r:      0.1840 (p = 0.18247)
*Spearman rho:         0.1743 (p = 0.00068)
*Mean Squared Error:   0.5248
*Mean Absolute Error:  0.5245
*Train_Mean MAE:       0.1500

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7106116734704424), ('intercept_', 0.7508305647840532), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0303 (MSE: 0.5694; MAE: 0.5642; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6944676175300836), ('intercept_', 0.7715231788079469), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0734 (MSE: 0.6518; MAE: 0.6529; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6934481016818362), ('intercept_', 0.7840531561461793), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0079 (MSE: 0.6512; MAE: 0.6122; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6337592743275049), ('intercept_', 0.7350993377483442), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0456 (MSE: 0.8558; MAE: 0.6758; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6603310096499875), ('intercept_', 0.7516556291390728), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0279 (MSE: 0.7853; MAE: 0.6307; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0065
*Overall FOLDS R^2:    -0.0137 (+- 0.0182)
*R (sqrt R^2):         nan
*Pearson r:            0.1562 (p = 0.00235)
*Folds Pearson r:      0.1695 (p = 0.19616)
*Spearman rho:         0.1496 (p = 0.00360)
*Mean Squared Error:   0.7022
*Mean Absolute Error:  0.6270
*Train_Mean MAE:       0.2144

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8232765345629461), ('intercept_', 1.0099667774086378), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0112 (MSE: 0.6890; MAE: 0.5747; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)

In [18]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:25:42
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4044685943968853), ('intercept_', 0.6843853820598006), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1666 (MSE: 0.3215; MAE: 0.5106; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3940965163318701), ('intercept_', 0.6821192052980132), ('n_features_in_', 1150)]
  *FOLD R^2: -0.3695 (MSE: 0.3408; MAE: 0.4752; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.33881548761803704), ('intercept_', 0.6026490066225165), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1773 (MSE: 0.6183; MAE: 0.5663; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.40633045928586586), ('intercept_', 0.6212624584717608), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1180 (MSE: 0.2824; MAE: 0.4604; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3210868586799739), ('intercept_', 0.672185430463576), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0441 (MSE: 0.5895; MAE: 0.6319; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0988
*Overall FOLDS R^2:    -0.1751 (+- 0.0483)
*R (sqrt R^2):         nan
*Pearson r:            0.0953 (p = 0.06457)
*Folds Pearson r:      0.0945 (p = 0.47790)
*Spearman rho:         0.0607 (p = 0.23938)
*Mean Squared Error:   0.4298
*Mean Absolute Error:  0.5287
*Train_Mean MAE:       0.1722

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.40541978295881415), ('intercept_', 0.6777408637873754), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0748 (MSE: 0.7875; MAE: 0.6880; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4184221744005947), ('intercept_', 0.685430463576159), ('n_features_in_', 1150)]
  *FOLD R^2: -0.2630 (MSE: 0.6399; MAE: 0.6127; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.46128590934039765), ('intercept_', 0.6556291390728478), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1517 (MSE: 0.4779; MAE: 0.4880; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.481976964356474), ('intercept_', 0.6378737541528238), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1426 (MSE: 0.3703; MAE: 0.4624; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4596421571202348), ('intercept_', 0.685430463576159), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0699 (MSE: 0.4850; MAE: 0.5841; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1221
*Overall FOLDS R^2:    -0.1404 (+- 0.0313)
*R (sqrt R^2):         nan
*Pearson r:            0.0747 (p = 0.14758)
*Folds Pearson r:      0.0517 (p = 0.58339)
*Spearman rho:         0.1065 (p = 0.03876)
*Mean Squared Error:   0.5523
*Mean Absolute Error:  0.5671
*Train_Mean MAE:       0.2229

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.46781763180229885), ('intercept_', 0.7009966777408637), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0602 (MSE: 0.6784; MAE: 0.6384; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)

In [19]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:26:51
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6326855590770728), ('intercept_', 0.8561403508771929), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0533 (MSE: 0.7610; MAE: 0.5982; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6458912262670828), ('intercept_', 0.8666666666666667), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0475 (MSE: 0.7411; MAE: 0.6277; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6556200460225011), ('intercept_', 0.8697183098591549), ('n_features_in_', 1150)]
  *FOLD R^2: -0.2641 (MSE: 0.7001; MAE: 0.6668; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5821629477949298), ('intercept_', 0.8245614035087717), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0384 (MSE: 1.0522; MAE: 0.7581; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7081337292609418), ('intercept_', 0.8526315789473683), ('n_features_in_', 1150)]
  *FOLD R^2: -4.4525 (MSE: 2.1957; MAE: 0.6260; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.5606
*Overall FOLDS R^2:    -0.9522 (+- 0.7840)
*R (sqrt R^2):         nan
*Pearson r:            0.0432 (p = 0.41626)
*Folds Pearson r:      0.1126 (p = 0.47389)
*Spearman rho:         0.1370 (p = 0.00968)
*Mean Squared Error:   1.0889
*Mean Absolute Error:  0.6554
*Train_Mean MAE:       0.2662

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7127316092506615), ('intercept_', 0.8175438596491227), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0382 (MSE: 1.0071; MAE: 0.6999; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7149038520625681), ('intercept_', 0.8526315789473684), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0847 (MSE: 1.0177; MAE: 0.7961; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8087116358744898), ('intercept_', 0.8591549295774648), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0149 (MSE: 0.7371; MAE: 0.6214; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7434967548912004), ('intercept_', 0.8385964912280701), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0268 (MSE: 1.0103; MAE: 0.7884; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8306973212850309), ('intercept_', 0.8596491228070176), ('n_features_in_', 1150)]
  *FOLD R^2: -0.3491 (MSE: 0.6049; MAE: 0.6005; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0650
*Overall FOLDS R^2:    -0.0968 (+- 0.0582)
*R (sqrt R^2):         nan
*Pearson r:            0.0933 (p = 0.07867)
*Folds Pearson r:      0.1182 (p = 0.37522)
*Spearman rho:         0.1011 (p = 0.05672)
*Mean Squared Error:   0.8750
*Mean Absolute Error:  0.7010
*Train_Mean MAE:       0.2405

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7772176497110906), ('intercept_', 1.0140350877192985), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1650 (MSE: 1.1264; MAE: 0.7129; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)

In [20]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:27:57
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL3', 'CELVAL1', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.38631953174544925), ('intercept_', 0.6666666666666666), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0356 (MSE: 0.1960; MAE: 0.4184; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3360117942475318), ('intercept_', 0.6549295774647887), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1404 (MSE: 0.4098; MAE: 0.5433; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3120938654938099), ('intercept_', 0.6842105263157896), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1177 (MSE: 0.5282; MAE: 0.5292; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3337185211117132), ('intercept_', 0.6912280701754386), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0361 (MSE: 0.4115; MAE: 0.5294; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000000.0), ('best_score_', -0.36041103925016316), ('intercept_', 0.7157894736842105), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1004 (MSE: 0.3034; MAE: 0.4989; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0694
*Overall FOLDS R^2:    -0.0860 (+- 0.0192)
*R (sqrt R^2):         nan
*Pearson r:            -0.0664 (p = 0.21116)
*Folds Pearson r:      -0.0733 (p = 0.55008)
*Spearman rho:         -0.0921 (p = 0.08262)
*Mean Squared Error:   0.3699
*Mean Absolute Error:  0.5039
*Train_Mean MAE:       0.0718

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.51755214679779), ('intercept_', 0.6596491228070174), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0447 (MSE: 0.6756; MAE: 0.6186; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5707557185872477), ('intercept_', 0.6549295774647887), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0960 (MSE: 0.4795; MAE: 0.5619; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4775008552196204), ('intercept_', 0.656140350877193), ('n_features_in_', 1150)]
  *FOLD R^2: -0.4687 (MSE: 1.1054; MAE: 0.7166; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5403450520495304), ('intercept_', 0.6842105263157895), ('n_features_in_', 1150)]
  *FOLD R^2: -0.1588 (MSE: 0.5954; MAE: 0.6076; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5927520485300712), ('intercept_', 0.7157894736842105), ('n_features_in_', 1150)]
  *FOLD R^2: -0.0662 (MSE: 0.3866; MAE: 0.5398; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1758
*Overall FOLDS R^2:    -0.1669 (+- 0.0696)
*R (sqrt R^2):         nan
*Pearson r:            0.0397 (p = 0.45567)
*Folds Pearson r:      0.0443 (p = 0.39784)
*Spearman rho:         0.0280 (p = 0.59819)
*Mean Squared Error:   0.6480
*Mean Absolute Error:  0.6088
*Train_Mean MAE:       0.1715

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6580303582044601), ('intercept_', 0.8631578947368421), ('n_features_in_', 1150)]
  *FOLD R^2: 0.0621 (MSE: 0.6240; MAE: 0.5724; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)

In [22]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 03:51:37
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5431148422076145), ('intercept_', 0.8006644518272424), ('n_features_in_', 103)]
  *FOLD R^2: 0.0416 (MSE: 0.2741; MAE: 0.3772; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.44073539386568067), ('intercept_', 0.7748344370860926), ('n_features_in_', 103)]
  *FOLD R^2: 0.0021 (MSE: 0.6741; MAE: 0.6132; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5278155569277291), ('intercept_', 0.8239202657807307), ('n_features_in_', 103)]
  *FOLD R^2: -0.0353 (MSE: 0.3375; MAE: 0.4761; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4631951412173985), ('intercept_', 0.7649006622516556), ('n_features_in_', 103)]
  *FOLD R^2: -0.0143 (MSE: 0.6268; MAE: 0.5467; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.44946868106473953), ('intercept_', 0.8013245033112584), ('n_features_in_', 103)]
  *FOLD R^2: -0.0053 (MSE: 0.6391; MAE: 0.5949; mean train mae: 0.5997)
*Overall R^2:          0.0097
*Overall FOLDS R^2:    -0.0022 (+- 0.0113)
*R (sqrt R^2):         0.0983
*Pearson r:            0.1450 (p = 0.00479)
*Folds Pearson r:      0.1661 (p = 0.22388)
*Spearman rho:         0.1473 (p = 0.00416)
*Mean Squared Error:   0.5093
*Mean Absolute Error:  0.5211
*Train_Mean MAE:       0.1324

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7062804132515896), ('intercept_', 0.7508305647840531), ('n_features_in_', 103)]
  *FOLD R^2: 0.0346 (MSE: 0.5669; MAE: 0.5120; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7046645939162716), ('intercept_', 0.7715231788079472), ('n_features_in_', 103)]
  *FOLD R^2: 0.0686 (MSE: 0.5656; MAE: 0.5961; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6752646176623377), ('intercept_', 0.7840531561461794), ('n_features_in_', 103)]
  *FOLD R^2: -0.0078 (MSE: 0.6512; MAE: 0.6297; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.652247980186559), ('intercept_', 0.7350993377483444), ('n_features_in_', 103)]
  *FOLD R^2: 0.0178 (MSE: 0.8039; MAE: 0.6282; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6214987620007656), ('intercept_', 0.7516556291390727), ('n_features_in_', 103)]
  *FOLD R^2: -0.0619 (MSE: 0.8578; MAE: 0.6979; mean train mae: 0.6564)
*Overall R^2:          0.0130
*Overall FOLDS R^2:    0.0103 (+- 0.0196)
*R (sqrt R^2):         0.1139
*Pearson r:            0.1285 (p = 0.01250)
*Folds Pearson r:      0.1465 (p = 0.29971)
*Spearman rho:         0.1457 (p = 0.00458)
*Mean Squared Error:   0.6887
*Mean Absolute Error:  0.6126
*Train_Mean MAE:       0.1243

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8183849943584082), ('intercept_', 1.0099667774086376), ('n_features_in_', 103)]
  *FOLD R^2: -0.2905 (MSE: 0.8794; MAE: 0.7189; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.794322365689736), ('intercept_', 0.9867549668874176), ('n_features_in_', 103)]
  *FOLD R^2: 0.0274 (MSE: 0.8932; MAE: 0.6517; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8550046796205164), ('intercept_', 1.0332225913621262), ('n_features_in_', 103)]
  *FOLD R^2: -0.0871 (MSE: 0.6209; MAE: 0.5506; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7584590665648399), ('intercept_', 0.956953642384106), ('n_features_in_', 103)]
  *FOLD R^2: -0.0303 (MSE: 1.0451; MAE: 0.6954; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7710478626200065), ('intercept_', 1.0), ('n_features_in_', 103)]
  *FOLD R^2: 0.0036 (MSE: 0.9697; MAE: 0.7058; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0477
*Overall FOLDS R^2:    -0.0754 (+- 0.0511)
*R (sqrt R^2):         nan
*Pearson r:            0.0419 (p = 0.41770)
*Folds Pearson r:      0.0838 (p = 0.52744)
*Spearman rho:         0.0350 (p = 0.49848)
*Mean Squared Error:   0.8810
*Mean Absolute Error:  0.6643
*Train_Mean MAE:       0.1732

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.94973411910004), ('intercept_', 2.561461794019932), ('n_features_in_', 103)]
  *FOLD R^2: -0.0319 (MSE: 2.9191; MAE: 1.3156; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.699632917724529), ('intercept_', 2.5331125827814573), ('n_features_in_', 103)]
  *FOLD R^2: 0.0687 (MSE: 3.8466; MAE: 1.5216; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.8058548936357353), ('intercept_', 2.641196013289036), ('n_features_in_', 103)]
  *FOLD R^2: -0.1385 (MSE: 3.5265; MAE: 1.5040; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)

In [23]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 03:51:54
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.39162123978096053), ('intercept_', 0.6843853820598008), ('n_features_in_', 103)]
  *FOLD R^2: -0.0747 (MSE: 0.2962; MAE: 0.4813; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.39191387399375505), ('intercept_', 0.6821192052980133), ('n_features_in_', 103)]
  *FOLD R^2: -0.0935 (MSE: 0.2722; MAE: 0.4660; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3402408871228896), ('intercept_', 0.6026490066225164), ('n_features_in_', 103)]
  *FOLD R^2: -0.0199 (MSE: 0.5356; MAE: 0.5582; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.37894708966522667), ('intercept_', 0.6212624584717618), ('n_features_in_', 103)]
  *FOLD R^2: -0.5530 (MSE: 0.3923; MAE: 0.4828; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.31972255657735593), ('intercept_', 0.6721854304635764), ('n_features_in_', 103)]
  *FOLD R^2: 0.0056 (MSE: 0.5615; MAE: 0.6129; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0511
*Overall FOLDS R^2:    -0.1471 (+- 0.0922)
*R (sqrt R^2):         nan
*Pearson r:            0.0679 (p = 0.18806)
*Folds Pearson r:      0.1860 (p = 0.29231)
*Spearman rho:         0.1262 (p = 0.01419)
*Mean Squared Error:   0.4112
*Mean Absolute Error:  0.5200
*Train_Mean MAE:       0.1266

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40152835083992044), ('intercept_', 0.6777408637873753), ('n_features_in_', 103)]
  *FOLD R^2: 0.0763 (MSE: 0.6768; MAE: 0.6231; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.45248353445450956), ('intercept_', 0.6854304635761588), ('n_features_in_', 103)]
  *FOLD R^2: 0.0602 (MSE: 0.4762; MAE: 0.5476; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4769070539497143), ('intercept_', 0.6556291390728476), ('n_features_in_', 103)]
  *FOLD R^2: 0.0826 (MSE: 0.3806; MAE: 0.4635; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4810322038439071), ('intercept_', 0.6378737541528238), ('n_features_in_', 103)]
  *FOLD R^2: -0.0776 (MSE: 0.3492; MAE: 0.4751; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4597070635609229), ('intercept_', 0.6854304635761588), ('n_features_in_', 103)]
  *FOLD R^2: 0.0296 (MSE: 0.4399; MAE: 0.5524; mean train mae: 0.5726)
*Overall R^2:          0.0556
*Overall FOLDS R^2:    0.0342 (+- 0.0263)
*R (sqrt R^2):         0.2359
*Pearson r:            0.2361 (p = 0.00000)
*Folds Pearson r:      0.2362 (p = 0.12682)
*Spearman rho:         0.2500 (p = 0.00000)
*Mean Squared Error:   0.4648
*Mean Absolute Error:  0.5324
*Train_Mean MAE:       0.1375

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.47945824124022807), ('intercept_', 0.7009966777408638), ('n_features_in_', 103)]
  *FOLD R^2: 0.0507 (MSE: 0.6075; MAE: 0.5833; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5201521494866543), ('intercept_', 0.7384105960264902), ('n_features_in_', 103)]
  *FOLD R^2: 0.0591 (MSE: 0.4426; MAE: 0.5244; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5059907553904932), ('intercept_', 0.6986754966887417), ('n_features_in_', 103)]
  *FOLD R^2: 0.0302 (MSE: 0.4655; MAE: 0.5133; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5115237809743829), ('intercept_', 0.7043189368770764), ('n_features_in_', 103)]
  *FOLD R^2: -0.0378 (MSE: 0.4533; MAE: 0.5103; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4894777108655071), ('intercept_', 0.7516556291390726), ('n_features_in_', 103)]
  *FOLD R^2: 0.0103 (MSE: 0.5567; MAE: 0.6142; mean train mae: 0.6167)
*Overall R^2:          0.0389
*Overall FOLDS R^2:    0.0225 (+- 0.0155)
*R (sqrt R^2):         0.1973
*Pearson r:            0.1982 (p = 0.00011)
*Folds Pearson r:      0.2029 (p = 0.16910)
*Spearman rho:         0.2067 (p = 0.00005)
*Mean Squared Error:   0.5053
*Mean Absolute Error:  0.5491
*Train_Mean MAE:       0.1161

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.2133690579584915), ('intercept_', 2.0631229235880397), ('n_features_in_', 103)]
  *FOLD R^2: 0.1092 (MSE: 2.5059; MAE: 1.2536; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.255448260156118), ('intercept_', 2.1059602649006623), ('n_features_in_', 103)]
  *FOLD R^2: 0.0430 (MSE: 2.2093; MAE: 1.2252; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.281912661011146), ('intercept_', 1.9569536423841059), ('n_features_in_', 103)]
  *FOLD R^2: 0.1082 (MSE: 2.1587; MAE: 1.2213; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [24]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 03:52:09
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.632361529934446), ('intercept_', 0.8561403508771926), ('n_features_in_', 103)]
  *FOLD R^2: 0.0053 (MSE: 0.7186; MAE: 0.6133; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6455479010992021), ('intercept_', 0.8666666666666669), ('n_features_in_', 103)]
  *FOLD R^2: 0.0618 (MSE: 0.7300; MAE: 0.6172; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6498589090848491), ('intercept_', 0.8697183098591545), ('n_features_in_', 103)]
  *FOLD R^2: -0.1390 (MSE: 0.6308; MAE: 0.6175; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5814361300872646), ('intercept_', 0.824561403508772), ('n_features_in_', 103)]
  *FOLD R^2: 0.0265 (MSE: 0.9865; MAE: 0.6873; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7078078580933331), ('intercept_', 0.8526315789473685), ('n_features_in_', 103)]
  *FOLD R^2: -0.0266 (MSE: 0.4134; MAE: 0.4428; mean train mae: 0.4148)
*Overall R^2:          0.0030
*Overall FOLDS R^2:    -0.0144 (+- 0.0307)
*R (sqrt R^2):         0.0546
*Pearson r:            0.1543 (p = 0.00351)
*Folds Pearson r:      0.1452 (p = 0.17271)
*Spearman rho:         0.1397 (p = 0.00832)
*Mean Squared Error:   0.6957
*Mean Absolute Error:  0.5957
*Train_Mean MAE:       0.1731

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7576503781770731), ('intercept_', 0.8175438596491226), ('n_features_in_', 103)]
  *FOLD R^2: 0.0558 (MSE: 0.9159; MAE: 0.6720; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7666116333822711), ('intercept_', 0.8526315789473685), ('n_features_in_', 103)]
  *FOLD R^2: 0.0498 (MSE: 0.8915; MAE: 0.7269; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7877752535414216), ('intercept_', 0.8591549295774644), ('n_features_in_', 103)]
  *FOLD R^2: -0.0482 (MSE: 0.7843; MAE: 0.6944; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7414322039913176), ('intercept_', 0.8385964912280701), ('n_features_in_', 103)]
  *FOLD R^2: -0.0093 (MSE: 0.9930; MAE: 0.7045; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8691201094989296), ('intercept_', 0.8596491228070176), ('n_features_in_', 103)]
  *FOLD R^2: 0.0014 (MSE: 0.4477; MAE: 0.4535; mean train mae: 0.4618)
*Overall R^2:          0.0185
*Overall FOLDS R^2:    0.0099 (+- 0.0173)
*R (sqrt R^2):         0.1360
*Pearson r:            0.1529 (p = 0.00383)
*Folds Pearson r:      0.1708 (p = 0.28909)
*Spearman rho:         0.1794 (p = 0.00067)
*Mean Squared Error:   0.8064
*Mean Absolute Error:  0.6504
*Train_Mean MAE:       0.1581

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8621585966969098), ('intercept_', 1.0140350877192987), ('n_features_in_', 103)]
  *FOLD R^2: 0.0453 (MSE: 0.9231; MAE: 0.7284; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8631240234009574), ('intercept_', 1.0280701754385972), ('n_features_in_', 103)]
  *FOLD R^2: -0.0802 (MSE: 0.9583; MAE: 0.7847; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8621299665087857), ('intercept_', 1.0492957746478873), ('n_features_in_', 103)]
  *FOLD R^2: -0.1029 (MSE: 0.8985; MAE: 0.7423; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8067368093704675), ('intercept_', 1.0385964912280699), ('n_features_in_', 103)]
  *FOLD R^2: 0.0433 (MSE: 1.1850; MAE: 0.8560; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8907047489686324), ('intercept_', 0.9964912280701755), ('n_features_in_', 103)]
  *FOLD R^2: -0.1895 (MSE: 0.7805; MAE: 0.6321; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0338
*Overall FOLDS R^2:    -0.0568 (+- 0.0404)
*R (sqrt R^2):         nan
*Pearson r:            0.1581 (p = 0.00277)
*Folds Pearson r:      0.1494 (p = 0.22632)
*Spearman rho:         0.1759 (p = 0.00086)
*Mean Squared Error:   0.9489
*Mean Absolute Error:  0.7487
*Train_Mean MAE:       0.2833

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.64892392163592), ('intercept_', 2.6877192982456135), ('n_features_in_', 103)]
  *FOLD R^2: 0.0791 (MSE: 5.0564; MAE: 1.6229; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.734999283475365), ('intercept_', 2.747368421052632), ('n_features_in_', 103)]
  *FOLD R^2: 0.0497 (MSE: 5.0928; MAE: 1.7588; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.685522343372009), ('intercept_', 2.778169014084506), ('n_features_in_', 103)]
  *FOLD R^2: -0.1242 (MSE: 4.9027; MAE: 1.7969; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)

In [25]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 03:52:24
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CEL_Total', 'CELVAL2', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3743390180899727), ('intercept_', 0.6666666666666664), ('n_features_in_', 103)]
  *FOLD R^2: -0.0456 (MSE: 0.1979; MAE: 0.4132; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.33156795666700817), ('intercept_', 0.6549295774647886), ('n_features_in_', 103)]
  *FOLD R^2: -0.0609 (MSE: 0.3813; MAE: 0.5095; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3022652504128211), ('intercept_', 0.6842105263157893), ('n_features_in_', 103)]
  *FOLD R^2: -0.0254 (MSE: 0.4845; MAE: 0.5429; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3277774643039147), ('intercept_', 0.6912280701754386), ('n_features_in_', 103)]
  *FOLD R^2: -0.0118 (MSE: 0.4018; MAE: 0.5221; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.35310868153318503), ('intercept_', 0.7157894736842103), ('n_features_in_', 103)]
  *FOLD R^2: -0.0471 (MSE: 0.2887; MAE: 0.4785; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0146
*Overall FOLDS R^2:    -0.0382 (+- 0.0078)
*R (sqrt R^2):         nan
*Pearson r:            0.0358 (p = 0.50110)
*Folds Pearson r:      0.0683 (p = 0.57570)
*Spearman rho:         0.0648 (p = 0.22253)
*Mean Squared Error:   0.3509
*Mean Absolute Error:  0.4933
*Train_Mean MAE:       0.0762

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.518264043505016), ('intercept_', 0.6596491228070174), ('n_features_in_', 103)]
  *FOLD R^2: 0.0797 (MSE: 0.5951; MAE: 0.5737; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5516801951049557), ('intercept_', 0.6549295774647884), ('n_features_in_', 103)]
  *FOLD R^2: -0.0615 (MSE: 0.4644; MAE: 0.5662; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4705056803552253), ('intercept_', 0.6561403508771927), ('n_features_in_', 103)]
  *FOLD R^2: -0.0568 (MSE: 0.7954; MAE: 0.6726; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.527133512627567), ('intercept_', 0.6842105263157892), ('n_features_in_', 103)]
  *FOLD R^2: -0.0568 (MSE: 0.5429; MAE: 0.5871; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5757902277238856), ('intercept_', 0.7157894736842102), ('n_features_in_', 103)]
  *FOLD R^2: -0.0496 (MSE: 0.3806; MAE: 0.5253; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0078
*Overall FOLDS R^2:    -0.0290 (+- 0.0244)
*R (sqrt R^2):         nan
*Pearson r:            0.0784 (p = 0.13991)
*Folds Pearson r:      0.1039 (p = 0.53255)
*Spearman rho:         0.0628 (p = 0.23760)
*Mean Squared Error:   0.5554
*Mean Absolute Error:  0.5849
*Train_Mean MAE:       0.1161

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100000.0), ('best_score_', -0.6843132165495392), ('intercept_', 0.8631578947368421), ('n_features_in_', 103)]
  *FOLD R^2: -0.0050 (MSE: 0.6687; MAE: 0.5958; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6393935237319524), ('intercept_', 0.806338028169014), ('n_features_in_', 103)]
  *FOLD R^2: -0.0827 (MSE: 0.8412; MAE: 0.6252; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6281993566770466), ('intercept_', 0.831578947368421), ('n_features_in_', 103)]
  *FOLD R^2: -0.0787 (MSE: 0.8911; MAE: 0.6576; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6630887429153153), ('intercept_', 0.8596491228070173), ('n_features_in_', 103)]
  *FOLD R^2: -0.0962 (MSE: 0.7198; MAE: 0.6042; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7343686834966943), ('intercept_', 0.8947368421052629), ('n_features_in_', 103)]
  *FOLD R^2: -0.1367 (MSE: 0.4410; MAE: 0.4796; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0523
*Overall FOLDS R^2:    -0.0798 (+- 0.0191)
*R (sqrt R^2):         nan
*Pearson r:            -0.1004 (p = 0.05844)
*Folds Pearson r:      -0.0412 (p = 0.42385)
*Spearman rho:         -0.0523 (p = 0.32466)
*Mean Squared Error:   0.7127
*Mean Absolute Error:  0.5926
*Train_Mean MAE:       0.0851

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.9022868884693227), ('intercept_', 2.189473684210526), ('n_features_in_', 103)]
  *FOLD R^2: 0.0828 (MSE: 2.3558; MAE: 1.2070; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.7005854813654913), ('intercept_', 2.116197183098591), ('n_features_in_', 103)]
  *FOLD R^2: -0.0885 (MSE: 3.1997; MAE: 1.4240; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

### DLATK Feature Extraction with Text Features

Running DLATK predictions using text-based features (categories, LIWC, word embeddings)

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:54:36
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.47938642498483997), ('intercept_', 0.8006644518272424), ('n_features_in_', 51)]
  *FOLD R^2: -0.0973 (MSE: 0.3138; MAE: 0.4325; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.40465310421959816), ('intercept_', 0.7748344370860927), ('n_features_in_', 51)]
  *FOLD R^2: 0.0715 (MSE: 0.6273; MAE: 0.5717; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.49916164214082015), ('intercept_', 0.8239202657807305), ('n_features_in_', 51)]
  *FOLD R^2: -0.3013 (MSE: 0.4242; MAE: 0.5112; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4077665658892247), ('intercept_', 0.7649006622516556), ('n_features_in_', 51)]
  *FOLD R^2: -0.2819 (MSE: 0.7921; MAE: 0.6434; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.40481386665557445), ('intercept_', 0.8013245033112579), ('n_features_in_', 51)]
  *FOLD R^2: -0.1632 (MSE: 0.7395; MAE: 0.6536; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1246
*Overall FOLDS R^2:    -0.1544 (+- 0.0607)
*R (sqrt R^2):         nan
*Pearson r:            0.1802 (p = 0.00044)
*Folds Pearson r:      0.1865 (p = 0.09172)
*Spearman rho:         0.1572 (p = 0.00221)
*Mean Squared Error:   0.5783
*Mean Absolute Error:  0.5620
*Train_Mean MAE:       0.2972

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6552753033830919), ('intercept_', 0.7508305647840533), ('n_features_in_', 51)]
  *FOLD R^2: -0.0727 (MSE: 0.6299; MAE: 0.5502; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6494899213517316), ('intercept_', 0.7715231788079471), ('n_features_in_', 51)]
  *FOLD R^2: -0.0805 (MSE: 0.6562; MAE: 0.6124; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6546505870602782), ('intercept_', 0.7840531561461793), ('n_features_in_', 51)]
  *FOLD R^2: -0.6172 (MSE: 1.0449; MAE: 0.7746; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6030838348225326), ('intercept_', 0.7350993377483445), ('n_features_in_', 51)]
  *FOLD R^2: -0.2641 (MSE: 1.0346; MAE: 0.7418; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6248730373177881), ('intercept_', 0.7516556291390728), ('n_features_in_', 51)]
  *FOLD R^2: 0.0208 (MSE: 0.7910; MAE: 0.6568; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1916
*Overall FOLDS R^2:    -0.2027 (+- 0.1015)
*R (sqrt R^2):         nan
*Pearson r:            0.0527 (p = 0.30701)
*Folds Pearson r:      0.0801 (p = 0.30126)
*Spearman rho:         0.1240 (p = 0.01601)
*Mean Squared Error:   0.8314
*Mean Absolute Error:  0.6671
*Train_Mean MAE:       0.2925

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.675347937264882), ('intercept_', 1.0099667774086376), ('n_features_in_', 51)]
  *FOLD R^2: -0.3024 (MSE: 0.8875; MAE: 0.7290; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.706116266259072), ('intercept_', 0.9867549668874172), ('n_features_in_', 51)]
  *FOLD R^2: 0.1508 (MSE: 0.7799; MAE: 0.6760; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7030790843788456), ('intercept_', 1.0332225913621258), ('n_features_in_', 51)]
  *FOLD R^2: -2.3084 (MSE: 1.8896; MAE: 0.9193; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6554709882227447), ('intercept_', 0.956953642384106), ('n_features_in_', 51)]
  *FOLD R^2: 0.0708 (MSE: 0.9425; MAE: 0.7067; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6867262121617216), ('intercept_', 0.9999999999999997), ('n_features_in_', 51)]
  *FOLD R^2: 0.0499 (MSE: 0.9246; MAE: 0.7148; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.2921
*Overall FOLDS R^2:    -0.4679 (+- 0.4174)
*R (sqrt R^2):         nan
*Pearson r:            0.1019 (p = 0.04794)
*Folds Pearson r:      0.1797 (p = 0.12490)
*Spearman rho:         0.1925 (p = 0.00017)
*Mean Squared Error:   1.0865
*Mean Absolute Error:  0.7496
*Train_Mean MAE:       0.3875

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.025320255054253), ('intercept_', 2.5614617940199333), ('n_features_in_', 51)]
  *FOLD R^2: -0.1669 (MSE: 3.3010; MAE: 1.3800; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.05840227678306), ('intercept_', 2.533112582781457), ('n_features_in_', 51)]
  *FOLD R^2: 0.2065 (MSE: 3.2774; MAE: 1.4277; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -3.087789281180741), ('intercept_', 2.6411960132890355), ('n_features_in_', 51)]
  *FOLD R^2: -1.2572 (MSE: 6.9919; MAE: 1.9443; mean train mae: 1.4211)
Fold 3

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:57:42
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3945761162890433), ('intercept_', 0.6843853820598007), ('n_features_in_', 51)]
  *FOLD R^2: 0.1019 (MSE: 0.2475; MAE: 0.4225; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.3867046219161841), ('intercept_', 0.6821192052980134), ('n_features_in_', 51)]
  *FOLD R^2: -0.5070 (MSE: 0.3751; MAE: 0.5579; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.34100702108686526), ('intercept_', 0.6026490066225165), ('n_features_in_', 51)]
  *FOLD R^2: -0.0912 (MSE: 0.5730; MAE: 0.5683; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3986040195236149), ('intercept_', 0.6212624584717609), ('n_features_in_', 51)]
  *FOLD R^2: -0.0244 (MSE: 0.2588; MAE: 0.4403; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.30999640105883164), ('intercept_', 0.6721854304635765), ('n_features_in_', 51)]
  *FOLD R^2: -0.1486 (MSE: 0.6485; MAE: 0.6397; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0729
*Overall FOLDS R^2:    -0.1339 (+- 0.0914)
*R (sqrt R^2):         nan
*Pearson r:            0.0507 (p = 0.32577)
*Folds Pearson r:      0.1076 (p = 0.21560)
*Spearman rho:         0.0539 (p = 0.29665)
*Mean Squared Error:   0.4197
*Mean Absolute Error:  0.5252
*Train_Mean MAE:       0.1391

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40800339483378656), ('intercept_', 0.6777408637873753), ('n_features_in_', 51)]
  *FOLD R^2: 0.0935 (MSE: 0.6642; MAE: 0.6158; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.43792477987135375), ('intercept_', 0.6854304635761586), ('n_features_in_', 51)]
  *FOLD R^2: -0.1383 (MSE: 0.5767; MAE: 0.6438; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4743453162845371), ('intercept_', 0.6556291390728477), ('n_features_in_', 51)]
  *FOLD R^2: 0.0534 (MSE: 0.3928; MAE: 0.4890; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.48920591197030455), ('intercept_', 0.6378737541528239), ('n_features_in_', 51)]
  *FOLD R^2: 0.0239 (MSE: 0.3164; MAE: 0.4489; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4495342607959374), ('intercept_', 0.6854304635761589), ('n_features_in_', 51)]
  *FOLD R^2: -0.2616 (MSE: 0.5719; MAE: 0.5982; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0246
*Overall FOLDS R^2:    -0.0458 (+- 0.0597)
*R (sqrt R^2):         nan
*Pearson r:            0.1604 (p = 0.00179)
*Folds Pearson r:      0.2126 (p = 0.19565)
*Spearman rho:         0.2109 (p = 0.00004)
*Mean Squared Error:   0.5043
*Mean Absolute Error:  0.5590
*Train_Mean MAE:       0.1875

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4708191354533196), ('intercept_', 0.7009966777408638), ('n_features_in_', 51)]
  *FOLD R^2: 0.0389 (MSE: 0.6150; MAE: 0.5758; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5158865910808634), ('intercept_', 0.7384105960264901), ('n_features_in_', 51)]
  *FOLD R^2: 0.0483 (MSE: 0.4477; MAE: 0.5450; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5101182618582917), ('intercept_', 0.6986754966887417), ('n_features_in_', 51)]
  *FOLD R^2: -0.0009 (MSE: 0.4805; MAE: 0.5409; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5177472556739477), ('intercept_', 0.7043189368770765), ('n_features_in_', 51)]
  *FOLD R^2: -0.0519 (MSE: 0.4595; MAE: 0.4956; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4893660440848812), ('intercept_', 0.7516556291390728), ('n_features_in_', 51)]
  *FOLD R^2: 0.0055 (MSE: 0.5594; MAE: 0.6096; mean train mae: 0.6167)
*Overall R^2:          0.0251
*Overall FOLDS R^2:    0.0080 (+- 0.0158)
*R (sqrt R^2):         0.1584
*Pearson r:            0.1603 (p = 0.00180)
*Folds Pearson r:      0.1701 (p = 0.26586)
*Spearman rho:         0.1972 (p = 0.00012)
*Mean Squared Error:   0.5125
*Mean Absolute Error:  0.5533
*Train_Mean MAE:       0.1049

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.2350566482346244), ('intercept_', 2.0631229235880397), ('n_features_in_', 51)]
  *FOLD R^2: 0.1803 (MSE: 2.3057; MAE: 1.1724; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.188169071784472), ('intercept_', 2.105960264900662), ('n_features_in_', 51)]
  *FOLD R^2: -0.1948 (MSE: 2.7582; MAE: 1.3849; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.315604708480516), ('intercept_', 1.9569536423841059), ('n_features_in_', 51)]
  *FOLD R^2: 0.0230 (MSE: 2.3650; MAE: 1.2926; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:58:08
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6085210068346334), ('intercept_', 0.8561403508771932), ('n_features_in_', 51)]
  *FOLD R^2: -0.1793 (MSE: 0.8520; MAE: 0.6644; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6094918196860806), ('intercept_', 0.8666666666666666), ('n_features_in_', 51)]
  *FOLD R^2: -0.4369 (MSE: 1.1179; MAE: 0.8276; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6722424426411303), ('intercept_', 0.8697183098591552), ('n_features_in_', 51)]
  *FOLD R^2: -1.0882 (MSE: 1.1565; MAE: 0.7758; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5889702126420046), ('intercept_', 0.8245614035087719), ('n_features_in_', 51)]
  *FOLD R^2: -0.0750 (MSE: 1.0893; MAE: 0.7424; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.694083988704895), ('intercept_', 0.8526315789473683), ('n_features_in_', 51)]
  *FOLD R^2: -0.3757 (MSE: 0.5540; MAE: 0.5595; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.3680
*Overall FOLDS R^2:    -0.4310 (+- 0.1581)
*R (sqrt R^2):         nan
*Pearson r:            -0.0687 (p = 0.19607)
*Folds Pearson r:      -0.0682 (p = 0.51438)
*Spearman rho:         -0.0818 (p = 0.12354)
*Mean Squared Error:   0.9545
*Mean Absolute Error:  0.7141
*Train_Mean MAE:       0.3204

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.6907505854395327), ('intercept_', 0.8175438596491229), ('n_features_in_', 51)]
  *FOLD R^2: -0.0931 (MSE: 1.0603; MAE: 0.7385; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7255374834504377), ('intercept_', 0.8526315789473683), ('n_features_in_', 51)]
  *FOLD R^2: -0.3706 (MSE: 1.2860; MAE: 0.8679; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7548200313284759), ('intercept_', 0.8591549295774648), ('n_features_in_', 51)]
  *FOLD R^2: -1.3449 (MSE: 1.7546; MAE: 0.9481; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.710595913445933), ('intercept_', 0.8385964912280699), ('n_features_in_', 51)]
  *FOLD R^2: -0.6596 (MSE: 1.6329; MAE: 1.0125; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8064402393824277), ('intercept_', 0.8596491228070177), ('n_features_in_', 51)]
  *FOLD R^2: -0.4882 (MSE: 0.6672; MAE: 0.6778; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.5597
*Overall FOLDS R^2:    -0.5912 (+- 0.1876)
*R (sqrt R^2):         nan
*Pearson r:            0.0119 (p = 0.82332)
*Folds Pearson r:      0.0498 (p = 0.29991)
*Spearman rho:         0.0603 (p = 0.25629)
*Mean Squared Error:   1.2815
*Mean Absolute Error:  0.8492
*Train_Mean MAE:       0.4665

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8007840781185642), ('intercept_', 1.014035087719299), ('n_features_in_', 51)]
  *FOLD R^2: -0.1575 (MSE: 1.1192; MAE: 0.7902; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7769973711906195), ('intercept_', 1.028070175438597), ('n_features_in_', 51)]
  *FOLD R^2: -0.7867 (MSE: 1.5851; MAE: 0.9892; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7963034571528815), ('intercept_', 1.0492957746478875), ('n_features_in_', 51)]
  *FOLD R^2: -1.9812 (MSE: 2.4285; MAE: 1.0753; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.7637141247809265), ('intercept_', 1.0385964912280699), ('n_features_in_', 51)]
  *FOLD R^2: -0.3393 (MSE: 1.6590; MAE: 1.0542; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.8132886874950452), ('intercept_', 0.9964912280701758), ('n_features_in_', 51)]
  *FOLD R^2: -0.2719 (MSE: 0.8347; MAE: 0.6276; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.6645
*Overall FOLDS R^2:    -0.7073 (+- 0.3004)
*R (sqrt R^2):         nan
*Pearson r:            -0.0535 (p = 0.31452)
*Folds Pearson r:      -0.0192 (p = 0.49022)
*Spearman rho:         -0.0382 (p = 0.47237)
*Mean Squared Error:   1.5278
*Mean Absolute Error:  0.9078
*Train_Mean MAE:       0.4537

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.152067308528868), ('intercept_', 2.687719298245615), ('n_features_in_', 51)]
  *FOLD R^2: -0.1095 (MSE: 6.0921; MAE: 1.8554; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.056986172388141), ('intercept_', 2.7473684210526317), ('n_features_in_', 51)]
  *FOLD R^2: -0.7700 (MSE: 9.4852; MAE: 2.4126; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -4.341783185324633), ('intercept_', 2.7781690140845074), ('n_features_in_', 51)]
  *FOLD R^2: -2.0529 (MSE: 13.3133; MAE: 2.5340; mean train mae: 1.6373)
Fold 3

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 18:58:26
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL2', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3680900356452724), ('intercept_', 0.6666666666666667), ('n_features_in_', 51)]
  *FOLD R^2: -0.1490 (MSE: 0.2175; MAE: 0.4056; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.33343262531849505), ('intercept_', 0.6549295774647887), ('n_features_in_', 51)]
  *FOLD R^2: -0.0780 (MSE: 0.3874; MAE: 0.5176; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.2967288667395495), ('intercept_', 0.6842105263157895), ('n_features_in_', 51)]
  *FOLD R^2: 0.0066 (MSE: 0.4694; MAE: 0.5447; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.32526119915191953), ('intercept_', 0.6912280701754386), ('n_features_in_', 51)]
  *FOLD R^2: 0.0085 (MSE: 0.3938; MAE: 0.5225; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3528966841284541), ('intercept_', 0.7157894736842105), ('n_features_in_', 51)]
  *FOLD R^2: -0.0282 (MSE: 0.2835; MAE: 0.4839; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0131
*Overall FOLDS R^2:    -0.0480 (+- 0.0266)
*R (sqrt R^2):         nan
*Pearson r:            0.0551 (p = 0.30014)
*Folds Pearson r:      0.0663 (p = 0.49072)
*Spearman rho:         0.0548 (p = 0.30220)
*Mean Squared Error:   0.3504
*Mean Absolute Error:  0.4949
*Train_Mean MAE:       0.0759

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.45960510317654), ('intercept_', 0.6596491228070177), ('n_features_in_', 51)]
  *FOLD R^2: -0.3480 (MSE: 0.8717; MAE: 0.7105; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5119272421783465), ('intercept_', 0.6549295774647885), ('n_features_in_', 51)]
  *FOLD R^2: -0.0581 (MSE: 0.4629; MAE: 0.5482; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.4492647215300939), ('intercept_', 0.6561403508771931), ('n_features_in_', 51)]
  *FOLD R^2: -0.0763 (MSE: 0.8100; MAE: 0.7173; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5015015224050199), ('intercept_', 0.6842105263157895), ('n_features_in_', 51)]
  *FOLD R^2: 0.0650 (MSE: 0.4804; MAE: 0.5403; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.5566918199554026), ('intercept_', 0.7157894736842104), ('n_features_in_', 51)]
  *FOLD R^2: 0.2274 (MSE: 0.2802; MAE: 0.4156; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0537
*Overall FOLDS R^2:    -0.0380 (+- 0.0846)
*R (sqrt R^2):         nan
*Pearson r:            0.2452 (p = 0.00000)
*Folds Pearson r:      0.2753 (p = 0.11218)
*Spearman rho:         0.2420 (p = 0.00000)
*Mean Squared Error:   0.5807
*Mean Absolute Error:  0.5863
*Train_Mean MAE:       0.2958

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6606773291915473), ('intercept_', 0.8631578947368421), ('n_features_in_', 51)]
  *FOLD R^2: 0.0081 (MSE: 0.6600; MAE: 0.6038; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -0.586900874918076), ('intercept_', 0.8063380281690135), ('n_features_in_', 51)]
  *FOLD R^2: -0.1737 (MSE: 0.9120; MAE: 0.6935; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6227183435277157), ('intercept_', 0.8315789473684211), ('n_features_in_', 51)]
  *FOLD R^2: -0.0663 (MSE: 0.8808; MAE: 0.6494; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6394646291554875), ('intercept_', 0.8596491228070174), ('n_features_in_', 51)]
  *FOLD R^2: -0.0938 (MSE: 0.7182; MAE: 0.6206; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7153934107935652), ('intercept_', 0.8947368421052632), ('n_features_in_', 51)]
  *FOLD R^2: -0.0956 (MSE: 0.4251; MAE: 0.4693; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0627
*Overall FOLDS R^2:    -0.0843 (+- 0.0261)
*R (sqrt R^2):         nan
*Pearson r:            0.0107 (p = 0.84065)
*Folds Pearson r:      -0.0408 (p = 0.37428)
*Spearman rho:         -0.0662 (p = 0.21256)
*Mean Squared Error:   0.7198
*Mean Absolute Error:  0.6076
*Train_Mean MAE:       0.1357

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.584379956630259), ('intercept_', 2.189473684210527), ('n_features_in_', 51)]
  *FOLD R^2: -0.3415 (MSE: 3.4456; MAE: 1.4783; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.4393390251502294), ('intercept_', 2.1161971830985906), ('n_features_in_', 51)]
  *FOLD R^2: -0.0298 (MSE: 3.0271; MAE: 1.4529; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 100.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 100.0), ('best_score_', -2.320698851466591), ('intercept_', 2.1719298245614036), ('n_features_in_', 51)]
  *FOLD R^2: -0.1273 (MSE: 4.3535; MAE: 1.6514; mean train mae: 1.4677)
Fold 3

In [31]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 19:08:16
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL2', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.510069412689412), ('intercept_', 0.8006644518272426), ('n_features_in_', 1486)]
  *FOLD R^2: -0.1240 (MSE: 0.3215; MAE: 0.4161; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.43170475924186436), ('intercept_', 0.7748344370860927), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0175 (MSE: 0.6637; MAE: 0.6222; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5090865721015098), ('intercept_', 0.823920265780731), ('n_features_in_', 1486)]
  *FOLD R^2: -0.0664 (MSE: 0.3477; MAE: 0.4823; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4427306056146814), ('intercept_', 0.7649006622516556), ('n_features_in_', 1486)]
  *FOLD R^2: -0.1280 (MSE: 0.6970; MAE: 0.5944; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4128957837133799), ('intercept_', 0.8013245033112583), ('n_features_in_', 1486)]
  *FOLD R^2: -0.0453 (MSE: 0.6645; MAE: 0.6171; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0458
*Overall FOLDS R^2:    -0.0692 (+- 0.0241)
*R (sqrt R^2):         nan
*Pearson r:            0.1051 (p = 0.04143)
*Folds Pearson r:      0.1197 (p = 0.37215)
*Spearman rho:         0.1094 (p = 0.03365)
*Mean Squared Error:   0.5378
*Mean Absolute Error:  0.5459
*Train_Mean MAE:       0.1947

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6899094191572579), ('intercept_', 0.7508305647840532), ('n_features_in_', 1486)]
  *FOLD R^2: -0.2434 (MSE: 0.7302; MAE: 0.6238; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6949204351715507), ('intercept_', 0.7715231788079471), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0067 (MSE: 0.6032; MAE: 0.6121; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6882526829617955), ('intercept_', 0.7840531561461794), ('n_features_in_', 1486)]
  *FOLD R^2: -0.0031 (MSE: 0.6481; MAE: 0.6354; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6515276275622622), ('intercept_', 0.7350993377483444), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0077 (MSE: 0.8122; MAE: 0.6434; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6468681834535552), ('intercept_', 0.7516556291390728), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0003 (MSE: 0.8076; MAE: 0.6596; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0321
*Overall FOLDS R^2:    -0.0464 (+- 0.0441)
*R (sqrt R^2):         nan
*Pearson r:            -0.0016 (p = 0.97532)
*Folds Pearson r:      0.0629 (p = 0.37720)
*Spearman rho:         0.0489 (p = 0.34411)
*Mean Squared Error:   0.7201
*Mean Absolute Error:  0.6348
*Train_Mean MAE:       0.0931

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.744360636163393), ('intercept_', 1.0099667774086378), ('n_features_in_', 1486)]
  *FOLD R^2: -0.1653 (MSE: 0.7941; MAE: 0.6265; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7677414092330294), ('intercept_', 0.9867549668874173), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0645 (MSE: 0.8592; MAE: 0.6825; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7639507644094549), ('intercept_', 1.0332225913621262), ('n_features_in_', 1486)]
  *FOLD R^2: -0.1224 (MSE: 0.6411; MAE: 0.6035; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7479816068980528), ('intercept_', 0.956953642384106), ('n_features_in_', 1486)]
  *FOLD R^2: -0.0792 (MSE: 1.0947; MAE: 0.7719; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7306324305362724), ('intercept_', 0.9999999999999999), ('n_features_in_', 1486)]
  *FOLD R^2: -0.0249 (MSE: 0.9974; MAE: 0.7432; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0423
*Overall FOLDS R^2:    -0.0655 (+- 0.0357)
*R (sqrt R^2):         nan
*Pearson r:            0.1200 (p = 0.01974)
*Folds Pearson r:      0.1353 (p = 0.37656)
*Spearman rho:         0.1340 (p = 0.00921)
*Mean Squared Error:   0.8764
*Mean Absolute Error:  0.6851
*Train_Mean MAE:       0.2555

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.465657888779706), ('intercept_', 2.5614617940199333), ('n_features_in_', 1486)]
  *FOLD R^2: -0.2155 (MSE: 3.4386; MAE: 1.3661; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -3.51370185011422), ('intercept_', 2.533112582781457), ('n_features_in_', 1486)]
  *FOLD R^2: 0.0806 (MSE: 3.7976; MAE: 1.4981; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [32]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 19:09:31
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CELVAL1', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.39600253422168735), ('intercept_', 0.6843853820598007), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0303 (MSE: 0.2840; MAE: 0.4568; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3825887240637113), ('intercept_', 0.6821192052980133), ('n_features_in_', 1290)]
  *FOLD R^2: -0.1777 (MSE: 0.2931; MAE: 0.4774; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3386218537049411), ('intercept_', 0.6026490066225165), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0825 (MSE: 0.5685; MAE: 0.5763; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3841118516532816), ('intercept_', 0.6212624584717606), ('n_features_in_', 1290)]
  *FOLD R^2: -0.1125 (MSE: 0.2810; MAE: 0.4486; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3009539181366543), ('intercept_', 0.672185430463576), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0228 (MSE: 0.5775; MAE: 0.5958; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0230
*Overall FOLDS R^2:    -0.0852 (+- 0.0255)
*R (sqrt R^2):         nan
*Pearson r:            0.1224 (p = 0.01738)
*Folds Pearson r:      0.1887 (p = 0.23339)
*Spearman rho:         0.1511 (p = 0.00327)
*Mean Squared Error:   0.4002
*Mean Absolute Error:  0.5107
*Train_Mean MAE:       0.1495

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4134073711385113), ('intercept_', 0.6777408637873754), ('n_features_in_', 1290)]
  *FOLD R^2: 0.0506 (MSE: 0.6956; MAE: 0.6486; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4393020069719198), ('intercept_', 0.6854304635761589), ('n_features_in_', 1290)]
  *FOLD R^2: 0.0558 (MSE: 0.4784; MAE: 0.5853; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.46052843856633563), ('intercept_', 0.6556291390728477), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0299 (MSE: 0.4273; MAE: 0.4895; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4952793995365671), ('intercept_', 0.6378737541528239), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0620 (MSE: 0.3442; MAE: 0.4758; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.45019706748300226), ('intercept_', 0.6854304635761589), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0187 (MSE: 0.4618; MAE: 0.5293; mean train mae: 0.5726)
*Overall R^2:          0.0214
*Overall FOLDS R^2:    -0.0009 (+- 0.0208)
*R (sqrt R^2):         0.1461
*Pearson r:            0.2011 (p = 0.00008)
*Folds Pearson r:      0.2306 (p = 0.08247)
*Spearman rho:         0.2310 (p = 0.00001)
*Mean Squared Error:   0.4817
*Mean Absolute Error:  0.5458
*Train_Mean MAE:       0.1759

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.47756699566582794), ('intercept_', 0.7009966777408638), ('n_features_in_', 1290)]
  *FOLD R^2: -0.1287 (MSE: 0.7222; MAE: 0.6528; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5207109958025598), ('intercept_', 0.7384105960264901), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0085 (MSE: 0.4744; MAE: 0.5686; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.517814731615465), ('intercept_', 0.6986754966887417), ('n_features_in_', 1290)]
  *FOLD R^2: -0.1535 (MSE: 0.5537; MAE: 0.5620; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5314242004767561), ('intercept_', 0.7043189368770764), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0020 (MSE: 0.4377; MAE: 0.5067; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4969640037373568), ('intercept_', 0.7516556291390728), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0202 (MSE: 0.5739; MAE: 0.6124; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0510
*Overall FOLDS R^2:    -0.0626 (+- 0.0290)
*R (sqrt R^2):         nan
*Pearson r:            0.0424 (p = 0.41149)
*Folds Pearson r:      0.0739 (p = 0.54712)
*Spearman rho:         0.0534 (p = 0.30152)
*Mean Squared Error:   0.5525
*Mean Absolute Error:  0.5805
*Train_Mean MAE:       0.1254

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.1887313629077485), ('intercept_', 2.0631229235880397), ('n_features_in_', 1290)]
  *FOLD R^2: 0.0659 (MSE: 2.6277; MAE: 1.3072; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.180683288617823), ('intercept_', 2.1059602649006623), ('n_features_in_', 1290)]
  *FOLD R^2: -0.0168 (MSE: 2.3474; MAE: 1.3129; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.2522907674727), ('intercept_', 1.9569536423841059), ('n_features_in_', 1290)]

In [33]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 19:10:35
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL1', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6100733427128869), ('intercept_', 0.8561403508771931), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0865 (MSE: 0.7849; MAE: 0.6065; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6531438337291354), ('intercept_', 0.8666666666666667), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0385 (MSE: 0.8080; MAE: 0.6790; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6133570791036906), ('intercept_', 0.8697183098591551), ('n_features_in_', 1484)]
  *FOLD R^2: -0.4367 (MSE: 0.7957; MAE: 0.7135; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5664616925935648), ('intercept_', 0.8245614035087719), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0612 (MSE: 1.0753; MAE: 0.7511; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7101566430304469), ('intercept_', 0.8526315789473685), ('n_features_in_', 1484)]
  *FOLD R^2: 0.0506 (MSE: 0.3823; MAE: 0.5036; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1025
*Overall FOLDS R^2:    -0.1145 (+- 0.0750)
*R (sqrt R^2):         nan
*Pearson r:            0.0535 (p = 0.31434)
*Folds Pearson r:      0.0575 (p = 0.34874)
*Spearman rho:         0.0430 (p = 0.41832)
*Mean Squared Error:   0.7693
*Mean Absolute Error:  0.6509
*Train_Mean MAE:       0.2411

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7556676826097692), ('intercept_', 0.8175438596491228), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0160 (MSE: 0.9856; MAE: 0.6671; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7646712967965156), ('intercept_', 0.8526315789473684), ('n_features_in_', 1484)]
  *FOLD R^2: 0.0012 (MSE: 0.9372; MAE: 0.7248; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8059275641940193), ('intercept_', 0.8591549295774648), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0414 (MSE: 0.7793; MAE: 0.6401; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7680138876298825), ('intercept_', 0.8385964912280702), ('n_features_in_', 1484)]
  *FOLD R^2: 0.0184 (MSE: 0.9659; MAE: 0.7017; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8921358678736192), ('intercept_', 0.8596491228070176), ('n_features_in_', 1484)]
  *FOLD R^2: 0.0403 (MSE: 0.4302; MAE: 0.4479; mean train mae: 0.4618)
*Overall R^2:          0.0026
*Overall FOLDS R^2:    0.0005 (+- 0.0125)
*R (sqrt R^2):         0.0507
*Pearson r:            0.0602 (p = 0.25693)
*Folds Pearson r:      0.0858 (p = 0.31510)
*Spearman rho:         0.0700 (p = 0.18750)
*Mean Squared Error:   0.8195
*Mean Absolute Error:  0.6363
*Train_Mean MAE:       0.0652

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7861243257943334), ('intercept_', 1.0140350877192985), ('n_features_in_', 1484)]
  *FOLD R^2: -0.1148 (MSE: 1.0779; MAE: 0.7554; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8144545722641526), ('intercept_', 1.0280701754385966), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0962 (MSE: 0.9725; MAE: 0.7536; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.799179225515068), ('intercept_', 1.0492957746478873), ('n_features_in_', 1484)]
  *FOLD R^2: -0.2838 (MSE: 1.0458; MAE: 0.8131; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8182156679952176), ('intercept_', 1.03859649122807), ('n_features_in_', 1484)]
  *FOLD R^2: 0.0393 (MSE: 1.1899; MAE: 0.8247; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.8375035129528808), ('intercept_', 0.9964912280701754), ('n_features_in_', 1484)]
  *FOLD R^2: -0.1267 (MSE: 0.7394; MAE: 0.6284; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0951
*Overall FOLDS R^2:    -0.1164 (+- 0.0459)
*R (sqrt R^2):         nan
*Pearson r:            0.0310 (p = 0.55988)
*Folds Pearson r:      0.0985 (p = 0.36552)
*Spearman rho:         0.0305 (p = 0.56615)
*Mean Squared Error:   1.0052
*Mean Absolute Error:  0.7552
*Train_Mean MAE:       0.2314

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.22861904532643), ('intercept_', 2.6877192982456144), ('n_features_in_', 1484)]
  *FOLD R^2: -0.1114 (MSE: 6.1027; MAE: 1.7087; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.401818597262659), ('intercept_', 2.7473684210526317), ('n_features_in_', 1484)]
  *FOLD R^2: -0.0869 (MSE: 5.8247; MAE: 1.8475; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -4.326118671640615), ('intercept_', 2.7781690140845074), ('n_features_in_', 1484)]

In [35]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 19:13:09
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CELVAL1', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.34561607075602285), ('intercept_', 0.6666666666666666), ('n_features_in_', 1204)]
  *FOLD R^2: -0.1219 (MSE: 0.2123; MAE: 0.4145; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3272491068113719), ('intercept_', 0.6549295774647887), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0030 (MSE: 0.3604; MAE: 0.4892; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.2770595800702152), ('intercept_', 0.6842105263157896), ('n_features_in_', 1204)]
  *FOLD R^2: -0.1132 (MSE: 0.5260; MAE: 0.5725; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3170645982193411), ('intercept_', 0.6912280701754386), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0483 (MSE: 0.3779; MAE: 0.5015; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.35006379608102584), ('intercept_', 0.7157894736842105), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0438 (MSE: 0.2878; MAE: 0.4855; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0204
*Overall FOLDS R^2:    -0.0467 (+- 0.0290)
*R (sqrt R^2):         nan
*Pearson r:            0.1102 (p = 0.03761)
*Folds Pearson r:      0.1654 (p = 0.31562)
*Spearman rho:         0.1068 (p = 0.04403)
*Mean Squared Error:   0.3529
*Mean Absolute Error:  0.4927
*Train_Mean MAE:       0.1269

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.47764309085487083), ('intercept_', 0.6596491228070176), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0480 (MSE: 0.6157; MAE: 0.5923; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5338488408219156), ('intercept_', 0.6549295774647887), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0443 (MSE: 0.4181; MAE: 0.5055; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4628419875538792), ('intercept_', 0.656140350877193), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0996 (MSE: 0.8276; MAE: 0.7251; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5166316853556074), ('intercept_', 0.6842105263157895), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0774 (MSE: 0.5536; MAE: 0.5606; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.56071870997104), ('intercept_', 0.7157894736842105), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0107 (MSE: 0.3588; MAE: 0.4956; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0059
*Overall FOLDS R^2:    -0.0148 (+- 0.0277)
*R (sqrt R^2):         nan
*Pearson r:            0.1714 (p = 0.00117)
*Folds Pearson r:      0.1883 (p = 0.27995)
*Spearman rho:         0.1679 (p = 0.00148)
*Mean Squared Error:   0.5544
*Mean Absolute Error:  0.5756
*Train_Mean MAE:       0.2082

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6631443958879394), ('intercept_', 0.8631578947368421), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0380 (MSE: 0.6906; MAE: 0.6266; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6288235717306906), ('intercept_', 0.8063380281690141), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0924 (MSE: 0.8488; MAE: 0.6849; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6203039894476502), ('intercept_', 0.8315789473684211), ('n_features_in_', 1204)]
  *FOLD R^2: -0.0512 (MSE: 0.8683; MAE: 0.6475; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6272095633313979), ('intercept_', 0.8596491228070176), ('n_features_in_', 1204)]
  *FOLD R^2: -0.1298 (MSE: 0.7419; MAE: 0.6115; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6935704031399245), ('intercept_', 0.8947368421052632), ('n_features_in_', 1204)]
  *FOLD R^2: -0.3653 (MSE: 0.5298; MAE: 0.5512; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0870
*Overall FOLDS R^2:    -0.1353 (+- 0.0534)
*R (sqrt R^2):         nan
*Pearson r:            0.0004 (p = 0.99435)
*Folds Pearson r:      -0.0527 (p = 0.30033)
*Spearman rho:         -0.0179 (p = 0.73702)
*Mean Squared Error:   0.7362
*Mean Absolute Error:  0.6245
*Train_Mean MAE:       0.1816

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.442937201881751), ('intercept_', 2.1894736842105265), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0584 (MSE: 2.4185; MAE: 1.2240; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -2.4618963704568557), ('intercept_', 2.1161971830985915), ('n_features_in_', 1204)]
  *FOLD R^2: 0.0600 (MSE: 2.7631; MAE: 1.3150; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:00:02
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4967052004977583), ('intercept_', 0.8006644518272424), ('n_features_in_', 1640)]
  *FOLD R^2: -0.0661 (MSE: 0.3049; MAE: 0.4034; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.41941700619599626), ('intercept_', 0.7748344370860927), ('n_features_in_', 1640)]
  *FOLD R^2: 0.0391 (MSE: 0.6492; MAE: 0.6115; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.49505060314699), ('intercept_', 0.8239202657807307), ('n_features_in_', 1640)]
  *FOLD R^2: -0.0929 (MSE: 0.3563; MAE: 0.4882; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.43410587036404613), ('intercept_', 0.7649006622516556), ('n_features_in_', 1640)]
  *FOLD R^2: -0.1365 (MSE: 0.7023; MAE: 0.6049; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4012045508333802), ('intercept_', 0.8013245033112583), ('n_features_in_', 1640)]
  *FOLD R^2: -0.0027 (MSE: 0.6375; MAE: 0.6043; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0287
*Overall FOLDS R^2:    -0.0518 (+- 0.0281)
*R (sqrt R^2):         nan
*Pearson r:            0.1468 (p = 0.00430)
*Folds Pearson r:      0.1580 (p = 0.24700)
*Spearman rho:         0.1508 (p = 0.00334)
*Mean Squared Error:   0.5290
*Mean Absolute Error:  0.5420
*Train_Mean MAE:       0.2106

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6853247747869666), ('intercept_', 0.7508305647840532), ('n_features_in_', 1640)]
  *FOLD R^2: -0.0087 (MSE: 0.5923; MAE: 0.5473; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6863307649147005), ('intercept_', 0.7715231788079471), ('n_features_in_', 1640)]
  *FOLD R^2: 0.0221 (MSE: 0.5938; MAE: 0.6078; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6781793359353705), ('intercept_', 0.7840531561461794), ('n_features_in_', 1640)]
  *FOLD R^2: 0.0034 (MSE: 0.6439; MAE: 0.6337; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6435649492531891), ('intercept_', 0.7350993377483444), ('n_features_in_', 1640)]
  *FOLD R^2: 0.0119 (MSE: 0.8087; MAE: 0.6380; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6349018390887772), ('intercept_', 0.7516556291390728), ('n_features_in_', 1640)]
  *FOLD R^2: -0.0033 (MSE: 0.8105; MAE: 0.6648; mean train mae: 0.6564)
*Overall R^2:          0.0118
*Overall FOLDS R^2:    0.0051 (+- 0.0049)
*R (sqrt R^2):         0.1085
*Pearson r:            0.1089 (p = 0.03455)
*Folds Pearson r:      0.1076 (p = 0.42369)
*Spearman rho:         0.1095 (p = 0.03360)
*Mean Squared Error:   0.6895
*Mean Absolute Error:  0.6182
*Train_Mean MAE:       0.0702

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7178063247667922), ('intercept_', 1.0099667774086378), ('n_features_in_', 1640)]
  *FOLD R^2: -0.1698 (MSE: 0.7971; MAE: 0.6270; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7502048230905413), ('intercept_', 0.9867549668874172), ('n_features_in_', 1640)]
  *FOLD R^2: 0.1256 (MSE: 0.8031; MAE: 0.6533; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7313306393680317), ('intercept_', 1.0332225913621262), ('n_features_in_', 1640)]
  *FOLD R^2: -0.2557 (MSE: 0.7172; MAE: 0.6413; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)

In [27]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SFemale50_cp_w$stratified_female$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:01:03
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CELVAL1', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.39380725553117685), ('intercept_', 0.6843853820598007), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0006 (MSE: 0.2758; MAE: 0.4793; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3800412394562505), ('intercept_', 0.6821192052980133), ('n_features_in_', 1444)]
  *FOLD R^2: -0.2250 (MSE: 0.3049; MAE: 0.4813; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.33715922134709414), ('intercept_', 0.6026490066225165), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0688 (MSE: 0.5613; MAE: 0.5709; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.38061058176448315), ('intercept_', 0.6212624584717609), ('n_features_in_', 1444)]
  *FOLD R^2: -0.1281 (MSE: 0.2849; MAE: 0.4430; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.2975132467000408), ('intercept_', 0.6721854304635763), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0290 (MSE: 0.5810; MAE: 0.5941; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0249
*Overall FOLDS R^2:    -0.0903 (+- 0.0357)
*R (sqrt R^2):         nan
*Pearson r:            0.1018 (p = 0.04816)
*Folds Pearson r:      0.2041 (p = 0.26357)
*Spearman rho:         0.1353 (p = 0.00853)
*Mean Squared Error:   0.4009
*Mean Absolute Error:  0.5134
*Train_Mean MAE:       0.1340

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40606607133368067), ('intercept_', 0.6777408637873754), ('n_features_in_', 1444)]
  *FOLD R^2: 0.0335 (MSE: 0.7081; MAE: 0.6431; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.43313599146853204), ('intercept_', 0.6854304635761589), ('n_features_in_', 1444)]
  *FOLD R^2: 0.0593 (MSE: 0.4766; MAE: 0.5886; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4606543252995394), ('intercept_', 0.6556291390728477), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0045 (MSE: 0.4168; MAE: 0.4725; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4878373201889062), ('intercept_', 0.637873754152824), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0642 (MSE: 0.3449; MAE: 0.4657; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.44731535432824027), ('intercept_', 0.6854304635761589), ('n_features_in_', 1444)]
  *FOLD R^2: -0.0067 (MSE: 0.4564; MAE: 0.5169; mean train mae: 0.5726)
*Overall R^2:          0.0231
*Overall FOLDS R^2:    0.0035 (+- 0.0187)
*R (sqrt R^2):         0.1520
*Pearson r:            0.2338 (p = 0.00000)
*Folds Pearson r:      0.2304 (p = 0.05365)
*Spearman rho:         0.2615 (p = 0.00000)
*Mean Squared Error:   0.4808
*Mean Absolute Error:  0.5374
*Train_Mean MAE:       0.2272

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4744706812853716), ('intercept_', 0.7009966777408638), ('n_features_in_', 1444)]
  *FOLD R^2: 0.0153 (MSE: 0.6301; MAE: 0.6021; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5167630942853275), ('intercept_', 0.7384105960264901), ('n_features_in_', 1444)]
  *FOLD R^2: 0.0096 (MSE: 0.4659; MAE: 0.5596; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5114891796683146), ('intercept_', 0.6986754966887417), ('n_features_in_', 1444)]
  *FOLD R^2: 0.0091 (MSE: 0.4756; MAE: 0.5249; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]

In [28]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Swhite50_cp_w$stratified_white$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:02:01
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5978395910937186), ('intercept_', 0.8561403508771929), ('n_features_in_', 1638)]
  *FOLD R^2: -0.0553 (MSE: 0.7624; MAE: 0.5983; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6411209269377475), ('intercept_', 0.8666666666666667), ('n_features_in_', 1638)]
  *FOLD R^2: -0.0511 (MSE: 0.8178; MAE: 0.6932; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5979207630939624), ('intercept_', 0.8697183098591548), ('n_features_in_', 1638)]
  *FOLD R^2: -0.5113 (MSE: 0.8370; MAE: 0.7309; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5579790686785837), ('intercept_', 0.824561403508772), ('n_features_in_', 1638)]
  *FOLD R^2: -0.0752 (MSE: 1.0895; MAE: 0.7516; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6908292809510315), ('intercept_', 0.8526315789473684), ('n_features_in_', 1638)]
  *FOLD R^2: 0.0159 (MSE: 0.3963; MAE: 0.5114; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1190
*Overall FOLDS R^2:    -0.1354 (+- 0.0852)
*R (sqrt R^2):         nan
*Pearson r:            0.0555 (p = 0.29646)
*Folds Pearson r:      0.0606 (p = 0.32317)
*Spearman rho:         0.0542 (p = 0.30812)
*Mean Squared Error:   0.7808
*Mean Absolute Error:  0.6573
*Train_Mean MAE:       0.2613

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7410709759965375), ('intercept_', 0.8175438596491227), ('n_features_in_', 1638)]
  *FOLD R^2: -0.1227 (MSE: 1.0891; MAE: 0.7260; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7547489573090778), ('intercept_', 0.8526315789473684), ('n_features_in_', 1638)]
  *FOLD R^2: 0.0153 (MSE: 0.9239; MAE: 0.7230; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7904756686976023), ('intercept_', 0.8591549295774648), ('n_features_in_', 1638)]
  *FOLD R^2: -0.0585 (MSE: 0.7920; MAE: 0.6505; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.7554727334628483), ('intercept_', 0.8385964912280702), ('n_features_in_', 1638)]
  *FOLD R^2: 0.0188 (MSE: 0.9654; MAE: 0.6900; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.8761521614301261), ('intercept_', 0.8596491228070176), ('n_features_in_', 1638)]
  *FOLD R^2: 0.0547 (MSE: 0.4238; MAE: 0.4465; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0208
*Overall FOLDS R^2:    -0.0185 (+- 0.0285)
*R (sqrt R^2):         nan
*Pearson r:            0.0482 (p = 0.36439)
*Folds Pearson r:      0.0937 (p = 0.28322)
*Spearman rho:         0.0582 (p = 0.27336)
*Mean Squared Error:   0.8387
*Mean Absolute Error:  0.6472
*Train_Mean MAE:       0.1213

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7625595509759326), ('intercept_', 1.0140350877192983), ('n_features_in_', 1638)]
  *FOLD R^2: -0.0593 (MSE: 1.0242; MAE: 0.7413; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7784724851301398), ('intercept_', 1.0280701754385966), ('n_features_in_', 1638)]
  *FOLD R^2: -0.1341 (MSE: 1.0061; MAE: 0.7832; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7700426913414193), ('intercept_', 1.049295774647887), ('n_features_in_', 1638)]
  *FOLD R^2: -0.4173 (MSE: 1.1545; MAE: 0.8591; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]

In [29]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Sblack50_cp_w$stratified_black$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:02:52
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL2', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3425562724622618), ('intercept_', 0.6666666666666669), ('n_features_in_', 1358)]
  *FOLD R^2: -0.1433 (MSE: 0.2164; MAE: 0.4059; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.32570703920397476), ('intercept_', 0.6549295774647887), ('n_features_in_', 1358)]
  *FOLD R^2: -0.0197 (MSE: 0.3665; MAE: 0.4899; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.27449513059490477), ('intercept_', 0.6842105263157896), ('n_features_in_', 1358)]
  *FOLD R^2: -0.1150 (MSE: 0.5269; MAE: 0.5719; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.31770711976277477), ('intercept_', 0.6912280701754386), ('n_features_in_', 1358)]
  *FOLD R^2: 0.0477 (MSE: 0.3782; MAE: 0.5006; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.34858168839861503), ('intercept_', 0.7157894736842105), ('n_features_in_', 1358)]
  *FOLD R^2: -0.0297 (MSE: 0.2839; MAE: 0.4822; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0246
*Overall FOLDS R^2:    -0.0520 (+- 0.0308)
*R (sqrt R^2):         nan
*Pearson r:            0.1143 (p = 0.03110)
*Folds Pearson r:      0.1597 (p = 0.33807)
*Spearman rho:         0.1225 (p = 0.02081)
*Mean Squared Error:   0.3544
*Mean Absolute Error:  0.4901
*Train_Mean MAE:       0.1353

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.47424957839676407), ('intercept_', 0.6596491228070177), ('n_features_in_', 1358)]
  *FOLD R^2: 0.0563 (MSE: 0.6103; MAE: 0.5866; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5261305178245946), ('intercept_', 0.6549295774647887), ('n_features_in_', 1358)]
  *FOLD R^2: 0.0384 (MSE: 0.4207; MAE: 0.5051; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4566795388375565), ('intercept_', 0.656140350877193), ('n_features_in_', 1358)]
  *FOLD R^2: -0.1169 (MSE: 0.8406; MAE: 0.7209; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5126504076079906), ('intercept_', 0.6842105263157895), ('n_features_in_', 1358)]
  *FOLD R^2: -0.0915 (MSE: 0.5608; MAE: 0.5647; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5590192304216314), ('intercept_', 0.7157894736842105), ('n_features_in_', 1358)]
  *FOLD R^2: 0.0343 (MSE: 0.3502; MAE: 0.4865; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0091
*Overall FOLDS R^2:    -0.0159 (+- 0.0326)
*R (sqrt R^2):         nan
*Pearson r:            0.1841 (p = 0.00048)
*Folds Pearson r:      0.2009 (p = 0.27256)
*Spearman rho:         0.1669 (p = 0.00158)
*Mean Squared Error:   0.5561
*Mean Absolute Error:  0.5726
*Train_Mean MAE:       0.2311

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6628726718055328), ('intercept_', 0.8631578947368423), ('n_features_in_', 1358)]
  *FOLD R^2: -0.0316 (MSE: 0.6864; MAE: 0.6187; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6206670869608416), ('intercept_', 0.8063380281690142), ('n_features_in_', 1358)]
  *FOLD R^2: -0.1129 (MSE: 0.8648; MAE: 0.7014; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6161050869135747), ('intercept_', 0.8315789473684212), ('n_features_in_', 1358)]
  *FOLD R^2: -0.0642 (MSE: 0.8791; MAE: 0.6501; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]

In [30]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SMale50_cp_w$stratified_male$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:03:42
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.49189781773334257), ('intercept_', 0.8006644518272426), ('n_features_in_', 2790)]
  *FOLD R^2: -0.2280 (MSE: 0.3512; MAE: 0.4593; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.43097382566829373), ('intercept_', 0.7748344370860927), ('n_features_in_', 2790)]
  *FOLD R^2: 0.0370 (MSE: 0.6505; MAE: 0.6049; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.5182089355881409), ('intercept_', 0.8239202657807309), ('n_features_in_', 2790)]
  *FOLD R^2: 0.0762 (MSE: 0.3012; MAE: 0.4447; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.4259892807313138), ('intercept_', 0.7649006622516555), ('n_features_in_', 2790)]
  *FOLD R^2: -0.1312 (MSE: 0.6990; MAE: 0.6034; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.405285873314718), ('intercept_', 0.8013245033112584), ('n_features_in_', 2790)]
  *FOLD R^2: -0.0046 (MSE: 0.6386; MAE: 0.5679; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0249
*Overall FOLDS R^2:    -0.0501 (+- 0.0505)
*R (sqrt R^2):         nan
*Pearson r:            0.1435 (p = 0.00524)
*Folds Pearson r:      0.2032 (p = 0.25021)
*Spearman rho:         0.1870 (p = 0.00026)
*Mean Squared Error:   0.5270
*Mean Absolute Error:  0.5356
*Train_Mean MAE:       0.1903

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.657573213775845), ('intercept_', 0.750830564784053), ('n_features_in_', 2790)]
  *FOLD R^2: -0.1087 (MSE: 0.6511; MAE: 0.5962; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.6679225467792109), ('intercept_', 0.7715231788079469), ('n_features_in_', 2790)]
  *FOLD R^2: -0.0279 (MSE: 0.6242; MAE: 0.6062; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6734572237901046), ('intercept_', 0.7840531561461794), ('n_features_in_', 2790)]
  *FOLD R^2: 0.0165 (MSE: 0.6355; MAE: 0.6164; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Training regression model: ridgehighcv]

#### SVR Predictions with OpenSmile Features

Support Vector Regression model predictions using OpenSmile acoustic features

In [31]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SFemale50_cp_w$stratified_female$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:05:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL2', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.38959806748178055), ('intercept_', 0.6843853820598008), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0704 (MSE: 0.2950; MAE: 0.4839; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.37376201696980316), ('intercept_', 0.6821192052980133), ('n_features_in_', 2594)]
  *FOLD R^2: -0.2048 (MSE: 0.2999; MAE: 0.4680; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3333838616113936), ('intercept_', 0.6026490066225165), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0375 (MSE: 0.5449; MAE: 0.5572; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.38785318912923455), ('intercept_', 0.6212624584717608), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0628 (MSE: 0.2685; MAE: 0.4467; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.2975780565908129), ('intercept_', 0.6721854304635763), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0024 (MSE: 0.5660; MAE: 0.5955; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0078
*Overall FOLDS R^2:    -0.0756 (+- 0.0308)
*R (sqrt R^2):         nan
*Pearson r:            0.1267 (p = 0.01382)
*Folds Pearson r:      0.1834 (p = 0.18472)
*Spearman rho:         0.1589 (p = 0.00196)
*Mean Squared Error:   0.3942
*Mean Absolute Error:  0.5100
*Train_Mean MAE:       0.1353

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.38699775308008505), ('intercept_', 0.6777408637873756), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0620 (MSE: 0.7781; MAE: 0.6911; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.40268532280055086), ('intercept_', 0.6854304635761589), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0598 (MSE: 0.5370; MAE: 0.5926; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.43779541541358163), ('intercept_', 0.6556291390728478), ('n_features_in_', 2594)]
  *FOLD R^2: -0.0075 (MSE: 0.4180; MAE: 0.4420; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Training regression model: ridgehighcv]

In [32]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Swhite50_cp_w$stratified_white$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:06:18
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5909979635600616), ('intercept_', 0.8561403508771932), ('n_features_in_', 2788)]
  *FOLD R^2: -0.0296 (MSE: 0.7438; MAE: 0.6098; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.6169675379388941), ('intercept_', 0.8666666666666667), ('n_features_in_', 2788)]
  *FOLD R^2: 0.0524 (MSE: 0.7372; MAE: 0.6282; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.581056457268712), ('intercept_', 0.869718309859155), ('n_features_in_', 2788)]
  *FOLD R^2: -0.3911 (MSE: 0.7704; MAE: 0.6804; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5467324218884084), ('intercept_', 0.8245614035087719), ('n_features_in_', 2788)]
  *FOLD R^2: -0.0585 (MSE: 1.0725; MAE: 0.7544; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.651038349246483), ('intercept_', 0.8526315789473685), ('n_features_in_', 2788)]
  *FOLD R^2: -0.4147 (MSE: 0.5697; MAE: 0.5607; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1160
*Overall FOLDS R^2:    -0.1683 (+- 0.0873)
*R (sqrt R^2):         nan
*Pearson r:            0.0829 (p = 0.11843)
*Folds Pearson r:      0.0975 (p = 0.15421)
*Spearman rho:         0.0885 (p = 0.09541)
*Mean Squared Error:   0.7787
*Mean Absolute Error:  0.6468
*Train_Mean MAE:       0.2543

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.684800360738218), ('intercept_', 0.8175438596491229), ('n_features_in_', 2788)]
  *FOLD R^2: -0.0722 (MSE: 1.0401; MAE: 0.7397; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7087375696950796), ('intercept_', 0.8526315789473685), ('n_features_in_', 2788)]
  *FOLD R^2: -0.0707 (MSE: 1.0047; MAE: 0.8036; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2788)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.7590727518607812), ('intercept_', 0.8591549295774648), ('n_features_in_', 2788)]
  *FOLD R^2: -0.1867 (MSE: 0.8880; MAE: 0.7331; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Training regression model: ridgehighcv]

In [33]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Sblack50_cp_w$stratified_black$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model ridgehighcv --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:07:27
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3712317444768745), ('intercept_', 0.6666666666666667), ('n_features_in_', 2508)]
  *FOLD R^2: -0.1930 (MSE: 0.2258; MAE: 0.4222; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.3263575985190771), ('intercept_', 0.6549295774647887), ('n_features_in_', 2508)]
  *FOLD R^2: -0.1828 (MSE: 0.4251; MAE: 0.5367; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.2838367306257769), ('intercept_', 0.6842105263157895), ('n_features_in_', 2508)]
  *FOLD R^2: -0.2001 (MSE: 0.5671; MAE: 0.5617; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.32404175337346264), ('intercept_', 0.6912280701754386), ('n_features_in_', 2508)]
  *FOLD R^2: -0.0082 (MSE: 0.4004; MAE: 0.5265; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.3519337993381862), ('intercept_', 0.7157894736842105), ('n_features_in_', 2508)]
  *FOLD R^2: -0.0358 (MSE: 0.2856; MAE: 0.4820; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1013
*Overall FOLDS R^2:    -0.1240 (+- 0.0375)
*R (sqrt R^2):         nan
*Pearson r:            0.0181 (p = 0.73336)
*Folds Pearson r:      0.0557 (p = 0.55647)
*Spearman rho:         0.0271 (p = 0.60970)
*Mean Squared Error:   0.3809
*Mean Absolute Error:  0.5059
*Train_Mean MAE:       0.1352

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.46665184919631203), ('intercept_', 0.6596491228070176), ('n_features_in_', 2508)]
  *FOLD R^2: -0.0076 (MSE: 0.6516; MAE: 0.6113; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 1000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 1000.0), ('best_score_', -0.5265448329188315), ('intercept_', 0.6549295774647887), ('n_features_in_', 2508)]
  *FOLD R^2: -0.1014 (MSE: 0.4818; MAE: 0.5466; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]
model: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
  selected alpha: 10000.000000
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: RidgeCV(alphas=array([1.e+01, 1.e+02, 1.e+00, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))
settings:  [('fit_intercept', True), ('scoring', None), ('cv', None), ('gcv_mode', None), ('store_cv_results', None), ('alpha_per_target', False), ('_store_cv_results', False), ('alpha_', 10000.0), ('best_score_', -0.4693037692877678), ('intercept_', 0.656140350877193), ('n_features_in_', 2508)]
  *FOLD R^2: 0.0041 (MSE: 0.7495; MAE: 0.6641; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Training regression model: ridgehighcv]

### SVR model

In [48]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:16:19
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0758)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 600)]
  *FOLD R^2: -0.3241 (MSE: 0.3787; MAE: 0.4357; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0814)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 469)]
  *FOLD R^2: -0.0684 (MSE: 0.7218; MAE: 0.6303; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0115)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 438)]
  *FOLD R^2: -0.0372 (MSE: 0.3381; MAE: 0.4857; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0600)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 534)]
  *FOLD R^2: -0.0525 (MSE: 0.6504; MAE: 0.5434; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0268)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 558)]
  *FOLD R^2: 0.0737 (MSE: 0.5889; MAE: 0.5457; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0397
*Overall FOLDS R^2:    -0.0817 (+- 0.0586)
*R (sqrt R^2):         nan
*Pearson r:            0.1487 (p = 0.00380)
*Folds Pearson r:      0.1424 (p = 0.41005)
*Spearman rho:         0.1679 (p = 0.00107)
*Mean Squared Error:   0.5346
*Mean Absolute Error:  0.5278
*Train_Mean MAE:       0.2018

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 228)]
  *FOLD R^2: 0.0199 (MSE: 0.5756; MAE: 0.5266; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: 0.0102)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 231)]
  *FOLD R^2: 0.0042 (MSE: 0.6047; MAE: 0.5961; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0050)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 231)]
  *FOLD R^2: -0.0384 (MSE: 0.6709; MAE: 0.6256; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0676)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 660)]
  *FOLD R^2: -0.1642 (MSE: 0.9529; MAE: 0.7075; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: 0.0034)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 237)]
  *FOLD R^2: 0.0038 (MSE: 0.8047; MAE: 0.6401; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0338
*Overall FOLDS R^2:    -0.0349 (+- 0.0302)
*R (sqrt R^2):         nan
*Pearson r:            0.0125 (p = 0.80870)
*Folds Pearson r:      0.1061 (p = 0.44532)
*Spearman rho:         0.0444 (p = 0.39005)
*Mean Squared Error:   0.7213
*Mean Absolute Error:  0.6190
*Train_Mean MAE:       0.1094

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0401)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 594)]
  *FOLD R^2: -0.0379 (MSE: 0.7073; MAE: 0.5952; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0562)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 484)]
  *FOLD R^2: 0.0374 (MSE: 0.8841; MAE: 0.6775; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0549)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 508)]
  *FOLD R^2: 0.0381 (MSE: 0.5494; MAE: 0.5183; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1400)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 580)]
  *FOLD R^2: -0.1845 (MSE: 1.2016; MAE: 0.7576; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0441)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 594)]
  *FOLD R^2: 0.0495 (MSE: 0.9250; MAE: 0.6281; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0136
*Overall FOLDS R^2:    -0.0195 (+- 0.0394)
*R (sqrt R^2):         nan
*Pearson r:            0.1688 (p = 0.00100)
*Folds Pearson r:      0.1751 (p = 0.11653)
*Spearman rho:         0.2583 (p = 0.00000)
*Mean Squared Error:   0.8523
*Mean Absolute Error:  0.6349
*Train_Mean MAE:       0.2374

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0802)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 329)]
  *FOLD R^2: 0.0407 (MSE: 2.7139; MAE: 1.2572; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.1032)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 368)]
  *FOLD R^2: 0.0268 (MSE: 4.0198; MAE: 1.5247; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.1029)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 336)]
  *FOLD R^2: 0.0293 (MSE: 3.0069; MAE: 1.3271; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)

In [49]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:16:28
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0011)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 523)]
  *FOLD R^2: -0.0608 (MSE: 0.2924; MAE: 0.5027; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0720)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 513)]
  *FOLD R^2: -0.1329 (MSE: 0.2820; MAE: 0.4715; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0314)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: -0.1314 (MSE: 0.5942; MAE: 0.5872; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0649)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 567)]
  *FOLD R^2: -0.1397 (MSE: 0.2879; MAE: 0.4460; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0471)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 531)]
  *FOLD R^2: -0.0344 (MSE: 0.5841; MAE: 0.6107; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0416
*Overall FOLDS R^2:    -0.0999 (+- 0.0195)
*R (sqrt R^2):         nan
*Pearson r:            0.0270 (p = 0.60139)
*Folds Pearson r:      0.0785 (p = 0.47211)
*Spearman rho:         0.0677 (p = 0.18957)
*Mean Squared Error:   0.4075
*Mean Absolute Error:  0.5234
*Train_Mean MAE:       0.1053

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0381)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 474)]
  *FOLD R^2: -0.0971 (MSE: 0.8038; MAE: 0.6924; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0483)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: -0.0488 (MSE: 0.5314; MAE: 0.6007; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0346)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: -0.2191 (MSE: 0.5058; MAE: 0.5948; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0238)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 527)]
  *FOLD R^2: -0.0472 (MSE: 0.3394; MAE: 0.4902; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0657)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 177)]
  *FOLD R^2: -0.0968 (MSE: 0.4972; MAE: 0.5857; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0885
*Overall FOLDS R^2:    -0.1018 (+- 0.0280)
*R (sqrt R^2):         nan
*Pearson r:            -0.0325 (p = 0.52898)
*Folds Pearson r:      -0.0377 (p = 0.28404)
*Spearman rho:         -0.0302 (p = 0.55908)
*Mean Squared Error:   0.5357
*Mean Absolute Error:  0.5927
*Train_Mean MAE:       0.1430

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0452)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 497)]
  *FOLD R^2: -0.0902 (MSE: 0.6976; MAE: 0.6343; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0121)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 664)]
  *FOLD R^2: -0.0475 (MSE: 0.4928; MAE: 0.5485; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0213)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 505)]
  *FOLD R^2: -0.1616 (MSE: 0.5576; MAE: 0.5934; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0154)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 673)]
  *FOLD R^2: -0.0176 (MSE: 0.4445; MAE: 0.5227; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0014)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 171)]
  *FOLD R^2: -0.1055 (MSE: 0.6218; MAE: 0.6260; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0707
*Overall FOLDS R^2:    -0.0845 (+- 0.0221)
*R (sqrt R^2):         nan
*Pearson r:            -0.0140 (p = 0.78641)
*Folds Pearson r:      0.1042 (p = 0.45791)
*Spearman rho:         -0.0304 (p = 0.55650)
*Mean Squared Error:   0.5629
*Mean Absolute Error:  0.5849
*Train_Mean MAE:       0.1364

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0678)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 156)]
  *FOLD R^2: -0.1300 (MSE: 3.1787; MAE: 1.4919; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0559)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 167)]
  *FOLD R^2: -0.0147 (MSE: 2.3425; MAE: 1.2362; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0580)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 340)]
  *FOLD R^2: -0.1802 (MSE: 2.8568; MAE: 1.4507; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Performing grid search for parameters over training]

In [50]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:16:38
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL1', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0001)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 496)]
  *FOLD R^2: -0.1419 (MSE: 0.2161; MAE: 0.4336; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0079)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 533)]
  *FOLD R^2: -0.0388 (MSE: 0.3733; MAE: 0.5082; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0246)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 515)]
  *FOLD R^2: -0.0132 (MSE: 0.4787; MAE: 0.5320; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0138)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 736)]
  *FOLD R^2: 0.0006 (MSE: 0.3969; MAE: 0.5264; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0037)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 490)]
  *FOLD R^2: -0.0048 (MSE: 0.2771; MAE: 0.4823; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0076
*Overall FOLDS R^2:    -0.0396 (+- 0.0236)
*R (sqrt R^2):         nan
*Pearson r:            0.1035 (p = 0.05108)
*Folds Pearson r:      0.1168 (p = 0.34440)
*Spearman rho:         0.0981 (p = 0.06456)
*Mean Squared Error:   0.3485
*Mean Absolute Error:  0.4965
*Train_Mean MAE:       0.0989

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0045)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 455)]
  *FOLD R^2: -0.0625 (MSE: 0.6871; MAE: 0.6250; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0062)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 187)]
  *FOLD R^2: -0.0109 (MSE: 0.4423; MAE: 0.5149; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0145)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 144)]
  *FOLD R^2: -0.0516 (MSE: 0.7915; MAE: 0.6628; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0164)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 546)]
  *FOLD R^2: -0.0918 (MSE: 0.5609; MAE: 0.6023; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0169)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 181)]
  *FOLD R^2: -0.0949 (MSE: 0.3970; MAE: 0.5202; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0440
*Overall FOLDS R^2:    -0.0623 (+- 0.0137)
*R (sqrt R^2):         nan
*Pearson r:            0.0457 (p = 0.39046)
*Folds Pearson r:      0.0506 (p = 0.72080)
*Spearman rho:         0.0647 (p = 0.22330)
*Mean Squared Error:   0.5754
*Mean Absolute Error:  0.5849
*Train_Mean MAE:       0.1458

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0577)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 594)]
  *FOLD R^2: 0.1201 (MSE: 0.5855; MAE: 0.5377; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0860)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 521)]
  *FOLD R^2: -0.0594 (MSE: 0.8231; MAE: 0.6491; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1146)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 650)]
  *FOLD R^2: -0.0960 (MSE: 0.9053; MAE: 0.6333; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0715)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 498)]
  *FOLD R^2: -0.2080 (MSE: 0.7932; MAE: 0.6527; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0328)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 133)]
  *FOLD R^2: 0.0462 (MSE: 0.3701; MAE: 0.4291; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0274
*Overall FOLDS R^2:    -0.0394 (+- 0.0509)
*R (sqrt R^2):         nan
*Pearson r:            0.1149 (p = 0.03016)
*Folds Pearson r:      0.2055 (p = 0.35561)
*Spearman rho:         0.1879 (p = 0.00036)
*Mean Squared Error:   0.6958
*Mean Absolute Error:  0.5806
*Train_Mean MAE:       0.1865

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0487)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 299)]
  *FOLD R^2: 0.0663 (MSE: 2.3983; MAE: 1.2436; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0773)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 317)]
  *FOLD R^2: -0.0854 (MSE: 3.1907; MAE: 1.4329; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1196)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 344)]
  *FOLD R^2: -0.1030 (MSE: 4.2596; MAE: 1.5043; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]

In [51]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:16:48
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0982)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 495)]
  *FOLD R^2: -0.0085 (MSE: 0.7286; MAE: 0.5559; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0692)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 451)]
  *FOLD R^2: 0.1243 (MSE: 0.6813; MAE: 0.6052; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0655)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 600)]
  *FOLD R^2: 0.0809 (MSE: 0.5090; MAE: 0.5159; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0803)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 465)]
  *FOLD R^2: 0.0526 (MSE: 0.9600; MAE: 0.7238; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0755)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 481)]
  *FOLD R^2: -0.1046 (MSE: 0.4448; MAE: 0.4889; mean train mae: 0.4148)
*Overall R^2:          0.0479
*Overall FOLDS R^2:    0.0289 (+- 0.0356)
*R (sqrt R^2):         0.2189
*Pearson r:            0.2564 (p = 0.00000)
*Folds Pearson r:      0.2383 (p = 0.12839)
*Spearman rho:         0.2920 (p = 0.00000)
*Mean Squared Error:   0.6643
*Mean Absolute Error:  0.5778
*Train_Mean MAE:       0.2371

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0433)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 418)]
  *FOLD R^2: -0.1182 (MSE: 1.0847; MAE: 0.7140; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: 0.0105)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 223)]
  *FOLD R^2: 0.0265 (MSE: 0.9134; MAE: 0.7176; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: 0.0141)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 220)]
  *FOLD R^2: 0.0086 (MSE: 0.7418; MAE: 0.6180; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0057)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 223)]
  *FOLD R^2: 0.0045 (MSE: 0.9795; MAE: 0.7174; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: 0.0197)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 205)]
  *FOLD R^2: -0.0126 (MSE: 0.4540; MAE: 0.4640; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0156
*Overall FOLDS R^2:    -0.0182 (+- 0.0230)
*R (sqrt R^2):         nan
*Pearson r:            0.0214 (p = 0.68712)
*Folds Pearson r:      0.0977 (p = 0.51459)
*Spearman rho:         0.0817 (p = 0.12405)
*Mean Squared Error:   0.8344
*Mean Absolute Error:  0.6461
*Train_Mean MAE:       0.0740

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0955)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 352)]
  *FOLD R^2: -0.0845 (MSE: 1.0486; MAE: 0.6733; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0431)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 346)]
  *FOLD R^2: 0.0526 (MSE: 0.8404; MAE: 0.6854; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0652)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 335)]
  *FOLD R^2: 0.0251 (MSE: 0.7942; MAE: 0.6584; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0470)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 604)]
  *FOLD R^2: 0.0386 (MSE: 1.1908; MAE: 0.8257; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1143)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 640)]
  *FOLD R^2: -0.2409 (MSE: 0.8143; MAE: 0.6597; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0211
*Overall FOLDS R^2:    -0.0418 (+- 0.0495)
*R (sqrt R^2):         nan
*Pearson r:            0.1385 (p = 0.00888)
*Folds Pearson r:      0.1430 (p = 0.37485)
*Spearman rho:         0.2087 (p = 0.00007)
*Mean Squared Error:   0.9373
*Mean Absolute Error:  0.7004
*Train_Mean MAE:       0.2462

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.1404)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 289)]
  *FOLD R^2: -0.0952 (MSE: 6.0135; MAE: 1.6701; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0996)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 298)]
  *FOLD R^2: 0.1132 (MSE: 4.7524; MAE: 1.6667; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0854)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 38), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 307)]
  *FOLD R^2: 0.0501 (MSE: 4.1422; MAE: 1.5466; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0333)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()

In [52]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:16:57
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1076)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 215)]
  *FOLD R^2: -0.0631 (MSE: 0.7681; MAE: 0.5513; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0851)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 448)]
  *FOLD R^2: 0.0098 (MSE: 0.7704; MAE: 0.6378; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1202)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 199)]
  *FOLD R^2: -0.0182 (MSE: 0.5639; MAE: 0.5539; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0854)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 192)]
  *FOLD R^2: 0.0900 (MSE: 0.9221; MAE: 0.6639; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0865)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 424)]
  *FOLD R^2: -0.0051 (MSE: 0.4047; MAE: 0.4090; mean train mae: 0.4148)
*Overall R^2:          0.0176
*Overall FOLDS R^2:    0.0027 (+- 0.0224)
*R (sqrt R^2):         0.1326
*Pearson r:            0.1505 (p = 0.00442)
*Folds Pearson r:      0.1363 (p = 0.40863)
*Spearman rho:         0.1984 (p = 0.00016)
*Mean Squared Error:   0.6855
*Mean Absolute Error:  0.5632
*Train_Mean MAE:       0.1181

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0382)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 504)]
  *FOLD R^2: 0.0090 (MSE: 0.9613; MAE: 0.6544; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0633)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 448)]
  *FOLD R^2: 0.0070 (MSE: 0.9318; MAE: 0.7270; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 482)]
  *FOLD R^2: -0.0018 (MSE: 0.7496; MAE: 0.6192; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0027)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 470)]
  *FOLD R^2: -0.0199 (MSE: 1.0035; MAE: 0.7426; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0495)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 411)]
  *FOLD R^2: -0.0133 (MSE: 0.4543; MAE: 0.4485; mean train mae: 0.4618)
*Overall R^2:          0.0021
*Overall FOLDS R^2:    -0.0038 (+- 0.0050)
*R (sqrt R^2):         0.0459
*Pearson r:            0.0534 (p = 0.31504)
*Folds Pearson r:      0.1623 (p = 0.29436)
*Spearman rho:         0.0755 (p = 0.15497)
*Mean Squared Error:   0.8199
*Mean Absolute Error:  0.6383
*Train_Mean MAE:       0.0559

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1063)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 230)]
  *FOLD R^2: -0.1179 (MSE: 1.0809; MAE: 0.6678; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0917)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 472)]
  *FOLD R^2: 0.0150 (MSE: 0.8739; MAE: 0.7027; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0617)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 428)]
  *FOLD R^2: -0.0285 (MSE: 0.8378; MAE: 0.7074; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0588)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 217)]
  *FOLD R^2: 0.0389 (MSE: 1.1905; MAE: 0.8232; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1108)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 402)]
  *FOLD R^2: -0.0085 (MSE: 0.6618; MAE: 0.4910; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0118
*Overall FOLDS R^2:    -0.0202 (+- 0.0241)
*R (sqrt R^2):         nan
*Pearson r:            0.0360 (p = 0.49790)
*Folds Pearson r:      0.1319 (p = 0.23728)
*Spearman rho:         0.1294 (p = 0.01457)
*Mean Squared Error:   0.9287
*Mean Absolute Error:  0.6785
*Train_Mean MAE:       0.1178

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1197)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 473)]
  *FOLD R^2: 0.0326 (MSE: 5.3117; MAE: 1.5606; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1312)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 420)]
  *FOLD R^2: 0.0211 (MSE: 5.2459; MAE: 1.7970; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1092)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 496)]
  *FOLD R^2: -0.0420 (MSE: 4.5440; MAE: 1.6494; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1030)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)

#### SVR Predictions with Whisper Features

Support Vector Regression using Whisper speech embeddings (mean and median)

In [53]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:17:08
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0117)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 542)]
  *FOLD R^2: -0.0556 (MSE: 0.1998; MAE: 0.4227; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0422)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1040)]
  *FOLD R^2: 0.0236 (MSE: 0.3509; MAE: 0.4544; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0398)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1028)]
  *FOLD R^2: -0.1052 (MSE: 0.5222; MAE: 0.5476; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0531)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1211)]
  *FOLD R^2: -0.2239 (MSE: 0.4861; MAE: 0.5427; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0208)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 513)]
  *FOLD R^2: -0.0797 (MSE: 0.2977; MAE: 0.5033; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0734
*Overall FOLDS R^2:    -0.0881 (+- 0.0360)
*R (sqrt R^2):         nan
*Pearson r:            0.1143 (p = 0.03105)
*Folds Pearson r:      0.0609 (p = 0.47217)
*Spearman rho:         0.0932 (p = 0.07917)
*Mean Squared Error:   0.3713
*Mean Absolute Error:  0.4940
*Train_Mean MAE:       0.1550

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0642)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 200)]
  *FOLD R^2: 0.1391 (MSE: 0.5567; MAE: 0.5039; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0165)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 193)]
  *FOLD R^2: 0.0677 (MSE: 0.4079; MAE: 0.4858; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0608)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 240)]
  *FOLD R^2: 0.0268 (MSE: 0.7325; MAE: 0.6323; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0454)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 908)]
  *FOLD R^2: -0.1421 (MSE: 0.5868; MAE: 0.5952; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0669)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 211)]
  *FOLD R^2: -0.0204 (MSE: 0.3700; MAE: 0.4814; mean train mae: 0.5574)
*Overall R^2:          0.0375
*Overall FOLDS R^2:    0.0142 (+- 0.0421)
*R (sqrt R^2):         0.1937
*Pearson r:            0.2341 (p = 0.00001)
*Folds Pearson r:      0.2525 (p = 0.11706)
*Spearman rho:         0.2730 (p = 0.00000)
*Mean Squared Error:   0.5304
*Mean Absolute Error:  0.5396
*Train_Mean MAE:       0.2154

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0577)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 199)]
  *FOLD R^2: 0.1563 (MSE: 0.5614; MAE: 0.5335; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1353)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 851)]
  *FOLD R^2: -0.1261 (MSE: 0.8750; MAE: 0.6567; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0867)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 207)]
  *FOLD R^2: 0.0487 (MSE: 0.7858; MAE: 0.6088; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1302)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1101)]
  *FOLD R^2: -0.0110 (MSE: 0.6639; MAE: 0.5934; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0901)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 200)]
  *FOLD R^2: 0.0545 (MSE: 0.3669; MAE: 0.4308; mean train mae: 0.4618)
*Overall R^2:          0.0385
*Overall FOLDS R^2:    0.0245 (+- 0.0414)
*R (sqrt R^2):         0.1962
*Pearson r:            0.2149 (p = 0.00004)
*Folds Pearson r:      0.2835 (p = 0.10240)
*Spearman rho:         0.2612 (p = 0.00000)
*Mean Squared Error:   0.6512
*Mean Absolute Error:  0.5649
*Train_Mean MAE:       0.1762

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1573)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 585)]
  *FOLD R^2: 0.3390 (MSE: 1.6977; MAE: 1.0103; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1670)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 626)]
  *FOLD R^2: 0.0067 (MSE: 2.9199; MAE: 1.2912; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1394)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 695)]
  *FOLD R^2: 0.0934 (MSE: 3.5014; MAE: 1.3862; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1969)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)

In [54]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:17:20
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1050)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 178)]
  *FOLD R^2: -0.0164 (MSE: 0.2907; MAE: 0.3947; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0968)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 543)]
  *FOLD R^2: -0.0240 (MSE: 0.6918; MAE: 0.6181; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0563)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 529)]
  *FOLD R^2: -0.0793 (MSE: 0.3519; MAE: 0.4841; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0403)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 570)]
  *FOLD R^2: -0.0451 (MSE: 0.6458; MAE: 0.5704; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0762)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 176)]
  *FOLD R^2: 0.0131 (MSE: 0.6274; MAE: 0.5524; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0121
*Overall FOLDS R^2:    -0.0303 (+- 0.0138)
*R (sqrt R^2):         nan
*Pearson r:            0.0825 (p = 0.10957)
*Folds Pearson r:      0.0199 (p = 0.26881)
*Spearman rho:         0.0365 (p = 0.48021)
*Mean Squared Error:   0.5204
*Mean Absolute Error:  0.5235
*Train_Mean MAE:       0.0979

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0261)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 538)]
  *FOLD R^2: -0.0013 (MSE: 0.5880; MAE: 0.5480; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0177)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 544)]
  *FOLD R^2: 0.0024 (MSE: 0.6058; MAE: 0.6118; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0185)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 507)]
  *FOLD R^2: -0.0194 (MSE: 0.6586; MAE: 0.6320; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0178)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 518)]
  *FOLD R^2: -0.0115 (MSE: 0.8279; MAE: 0.6671; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0221)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 562)]
  *FOLD R^2: 0.0008 (MSE: 0.8072; MAE: 0.6555; mean train mae: 0.6564)
*Overall R^2:          0.0008
*Overall FOLDS R^2:    -0.0058 (+- 0.0037)
*R (sqrt R^2):         0.0288
*Pearson r:            0.0367 (p = 0.47778)
*Folds Pearson r:      0.0603 (p = 0.62111)
*Spearman rho:         0.0437 (p = 0.39771)
*Mean Squared Error:   0.6971
*Mean Absolute Error:  0.6227
*Train_Mean MAE:       0.0330

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0970)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 463)]
  *FOLD R^2: -0.0474 (MSE: 0.7137; MAE: 0.5849; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0471)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 346)]
  *FOLD R^2: 0.0113 (MSE: 0.9080; MAE: 0.6784; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0786)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 485)]
  *FOLD R^2: -0.1056 (MSE: 0.6315; MAE: 0.5555; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0834)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 331)]
  *FOLD R^2: -0.0034 (MSE: 1.0179; MAE: 0.6557; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1034)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 206)]
  *FOLD R^2: 0.0397 (MSE: 0.9345; MAE: 0.6678; mean train mae: 0.6533)
*Overall R^2:          0.0007
*Overall FOLDS R^2:    -0.0211 (+- 0.0227)
*R (sqrt R^2):         0.0272
*Pearson r:            0.0867 (p = 0.09290)
*Folds Pearson r:      0.1307 (p = 0.33879)
*Spearman rho:         0.1061 (p = 0.03952)
*Mean Squared Error:   0.8402
*Mean Absolute Error:  0.6281
*Train_Mean MAE:       0.1135

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1263)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 549)]
  *FOLD R^2: -0.0130 (MSE: 2.8656; MAE: 1.2492; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1110)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 574)]
  *FOLD R^2: 0.0024 (MSE: 4.1204; MAE: 1.5938; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0994)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 534)]
  *FOLD R^2: -0.0809 (MSE: 3.3482; MAE: 1.3918; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0880)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)

In [55]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:17:31
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0055)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 558)]
  *FOLD R^2: -0.0661 (MSE: 0.2938; MAE: 0.5026; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0277)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 563)]
  *FOLD R^2: -0.0863 (MSE: 0.2704; MAE: 0.4894; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0295)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 545)]
  *FOLD R^2: -0.1270 (MSE: 0.5919; MAE: 0.5891; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0488)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 619)]
  *FOLD R^2: -0.0995 (MSE: 0.2777; MAE: 0.4620; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0864)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1130)]
  *FOLD R^2: -0.3530 (MSE: 0.7639; MAE: 0.6959; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1215
*Overall FOLDS R^2:    -0.1464 (+- 0.0470)
*R (sqrt R^2):         nan
*Pearson r:            -0.1554 (p = 0.00248)
*Folds Pearson r:      -0.0456 (p = 0.42248)
*Spearman rho:         -0.1333 (p = 0.00956)
*Mean Squared Error:   0.4387
*Mean Absolute Error:  0.5475
*Train_Mean MAE:       0.0747

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0271)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 558)]
  *FOLD R^2: 0.0026 (MSE: 0.7308; MAE: 0.6675; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1346)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1225)]
  *FOLD R^2: -0.0560 (MSE: 0.5351; MAE: 0.5569; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0880)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 957)]
  *FOLD R^2: 0.0196 (MSE: 0.4068; MAE: 0.4801; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0934)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 566)]
  *FOLD R^2: -0.0428 (MSE: 0.3380; MAE: 0.4916; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1206)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 235)]
  *FOLD R^2: -0.2170 (MSE: 0.5517; MAE: 0.5940; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0414
*Overall FOLDS R^2:    -0.0587 (+- 0.0375)
*R (sqrt R^2):         nan
*Pearson r:            0.1224 (p = 0.01740)
*Folds Pearson r:      0.1365 (p = 0.30499)
*Spearman rho:         0.1462 (p = 0.00446)
*Mean Squared Error:   0.5126
*Mean Absolute Error:  0.5582
*Train_Mean MAE:       0.1590

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0503)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 554)]
  *FOLD R^2: -0.0104 (MSE: 0.6465; MAE: 0.6228; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0226)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 588)]
  *FOLD R^2: 0.0154 (MSE: 0.4632; MAE: 0.5756; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0413)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: -0.0625 (MSE: 0.5100; MAE: 0.5766; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0283)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 570)]
  *FOLD R^2: -0.0372 (MSE: 0.4530; MAE: 0.5350; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0287)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 550)]
  *FOLD R^2: -0.0176 (MSE: 0.5724; MAE: 0.6152; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0065
*Overall FOLDS R^2:    -0.0225 (+- 0.0117)
*R (sqrt R^2):         nan
*Pearson r:            0.0217 (p = 0.67506)
*Folds Pearson r:      0.0374 (p = 0.54989)
*Spearman rho:         -0.0103 (p = 0.84210)
*Mean Squared Error:   0.5291
*Mean Absolute Error:  0.5850
*Train_Mean MAE:       0.0591

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0870)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 543)]
  *FOLD R^2: 0.0039 (MSE: 2.8021; MAE: 1.3309; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0747)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 549)]
  *FOLD R^2: -0.0322 (MSE: 2.3830; MAE: 1.2761; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.1196)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 88), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 507)]
  *FOLD R^2: -0.0693 (MSE: 2.5884; MAE: 1.3724; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Performing grid search for parameters over training]

In [56]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:17:43
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0409)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 587)]
  *FOLD R^2: -0.2739 (MSE: 0.3643; MAE: 0.4384; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0215)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 861)]
  *FOLD R^2: -0.0231 (MSE: 0.6912; MAE: 0.6194; mean train mae: 0.6084)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0144)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 231)]
  *FOLD R^2: -0.1279 (MSE: 0.3677; MAE: 0.4599; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0234)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 379)]
  *FOLD R^2: -0.0915 (MSE: 0.6745; MAE: 0.6065; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0044)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 381)]
  *FOLD R^2: 0.0272 (MSE: 0.6185; MAE: 0.5625; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0546
*Overall FOLDS R^2:    -0.0979 (+- 0.0461)
*R (sqrt R^2):         nan
*Pearson r:            0.0486 (p = 0.34654)
*Folds Pearson r:      0.0998 (p = 0.42721)
*Spearman rho:         0.0436 (p = 0.39879)
*Mean Squared Error:   0.5423
*Mean Absolute Error:  0.5369
*Train_Mean MAE:       0.1471

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0026)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 342)]
  *FOLD R^2: -0.0143 (MSE: 0.5956; MAE: 0.5735; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0052)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 838)]
  *FOLD R^2: -0.0034 (MSE: 0.6094; MAE: 0.6164; mean train mae: 0.6141)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0053)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 642)]
  *FOLD R^2: -0.0169 (MSE: 0.6571; MAE: 0.6378; mean train mae: 0.6373)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0055)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 613)]
  *FOLD R^2: -0.0220 (MSE: 0.8365; MAE: 0.6711; mean train mae: 0.6671)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0024)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 372)]
  *FOLD R^2: -0.0450 (MSE: 0.8442; MAE: 0.6795; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0149
*Overall FOLDS R^2:    -0.0203 (+- 0.0061)
*R (sqrt R^2):         nan
*Pearson r:            0.0541 (p = 0.29484)
*Folds Pearson r:      nan (p = nan)
*Spearman rho:         -0.0130 (p = 0.80172)
*Mean Squared Error:   0.7081
*Mean Absolute Error:  0.6355
*Train_Mean MAE:       0.0848

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0210)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 329)]
  *FOLD R^2: -0.0712 (MSE: 0.7300; MAE: 0.5913; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0015)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 597)]
  *FOLD R^2: 0.0400 (MSE: 0.8817; MAE: 0.6894; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0153)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 328)]
  *FOLD R^2: -0.0464 (MSE: 0.5976; MAE: 0.5234; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0527)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 711)]
  *FOLD R^2: -0.1572 (MSE: 1.1739; MAE: 0.7950; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0440)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 349)]
  *FOLD R^2: -0.0686 (MSE: 1.0400; MAE: 0.7276; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0507
*Overall FOLDS R^2:    -0.0607 (+- 0.0282)
*R (sqrt R^2):         nan
*Pearson r:            0.0922 (p = 0.07379)
*Folds Pearson r:      0.0908 (p = 0.55295)
*Spearman rho:         0.1279 (p = 0.01294)
*Mean Squared Error:   0.8835
*Mean Absolute Error:  0.6648
*Train_Mean MAE:       0.2330

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0538)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 351)]
  *FOLD R^2: -0.2044 (MSE: 3.4071; MAE: 1.3760; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0266)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 414)]
  *FOLD R^2: 0.0793 (MSE: 3.8027; MAE: 1.5429; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]

In [57]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:18:07
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0256)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 787)]
  *FOLD R^2: -0.0656 (MSE: 0.2937; MAE: 0.5089; mean train mae: 0.5083)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0315)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 462)]
  *FOLD R^2: -0.2578 (MSE: 0.3130; MAE: 0.4796; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 500)]
  *FOLD R^2: 0.0028 (MSE: 0.5237; MAE: 0.5040; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0055)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 432)]
  *FOLD R^2: -0.1371 (MSE: 0.2872; MAE: 0.4368; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0673)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 478)]
  *FOLD R^2: -0.0087 (MSE: 0.5695; MAE: 0.5914; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0145
*Overall FOLDS R^2:    -0.0933 (+- 0.0430)
*R (sqrt R^2):         nan
*Pearson r:            0.1536 (p = 0.00279)
*Folds Pearson r:      0.1621 (p = 0.27019)
*Spearman rho:         0.1680 (p = 0.00106)
*Mean Squared Error:   0.3969
*Mean Absolute Error:  0.5040
*Train_Mean MAE:       0.1536

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0678)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 824)]
  *FOLD R^2: -0.0010 (MSE: 0.7334; MAE: 0.6663; mean train mae: 0.6672)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0076)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 407)]
  *FOLD R^2: -0.1267 (MSE: 0.5709; MAE: 0.6185; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0355)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 451)]
  *FOLD R^2: -0.1526 (MSE: 0.4783; MAE: 0.4935; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0314)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 399)]
  *FOLD R^2: -0.2818 (MSE: 0.4154; MAE: 0.5201; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0192)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 394)]
  *FOLD R^2: -0.0678 (MSE: 0.4840; MAE: 0.5789; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0902
*Overall FOLDS R^2:    -0.1260 (+- 0.0419)
*R (sqrt R^2):         nan
*Pearson r:            0.0257 (p = 0.61827)
*Folds Pearson r:      nan (p = nan)
*Spearman rho:         0.0290 (p = 0.57443)
*Mean Squared Error:   0.5366
*Mean Absolute Error:  0.5755
*Train_Mean MAE:       0.1628

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0365)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 364)]
  *FOLD R^2: -0.2239 (MSE: 0.7832; MAE: 0.7042; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0761)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 618)]
  *FOLD R^2: -0.0002 (MSE: 0.4705; MAE: 0.5794; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0484)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 680)]
  *FOLD R^2: -0.0686 (MSE: 0.5129; MAE: 0.5773; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0637)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 810)]
  *FOLD R^2: -0.0540 (MSE: 0.4604; MAE: 0.5469; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: -0.0659)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 730)]
  *FOLD R^2: -0.0107 (MSE: 0.5685; MAE: 0.6132; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0641
*Overall FOLDS R^2:    -0.0715 (+- 0.0360)
*R (sqrt R^2):         nan
*Pearson r:            -0.0384 (p = 0.45682)
*Folds Pearson r:      -0.0141 (p = 0.72348)
*Spearman rho:         -0.1175 (p = 0.02254)
*Mean Squared Error:   0.5594
*Mean Absolute Error:  0.6043
*Train_Mean MAE:       0.1131

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0072)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 244)]
  *FOLD R^2: -0.0954 (MSE: 3.0813; MAE: 1.4167; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0084)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 240)]
  *FOLD R^2: -0.1137 (MSE: 2.5710; MAE: 1.2785; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.001, gamma=0.1) (score: -0.0189)

In [58]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:18:32
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL2', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0082)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 192)]
  *FOLD R^2: -0.0070 (MSE: 0.7275; MAE: 0.5523; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0010)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 200)]
  *FOLD R^2: -0.0002 (MSE: 0.7781; MAE: 0.6348; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0098)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 216)]
  *FOLD R^2: -0.0804 (MSE: 0.5983; MAE: 0.5508; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0085)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 684)]
  *FOLD R^2: -0.0319 (MSE: 1.0457; MAE: 0.7376; mean train mae: 0.7279)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.001) (score: 0.0089)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 169)]
  *FOLD R^2: -0.0300 (MSE: 0.4148; MAE: 0.4188; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0212
*Overall FOLDS R^2:    -0.0299 (+- 0.0126)
*R (sqrt R^2):         nan
*Pearson r:            -0.0979 (p = 0.06514)
*Folds Pearson r:      -0.0376 (p = 0.35668)
*Spearman rho:         -0.0768 (p = 0.14812)
*Mean Squared Error:   0.7126
*Mean Absolute Error:  0.5788
*Train_Mean MAE:       0.0560

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0034)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 185)]
  *FOLD R^2: -0.0245 (MSE: 0.9938; MAE: 0.6619; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0418)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 356)]
  *FOLD R^2: -0.0623 (MSE: 0.9968; MAE: 0.7706; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0125)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 175)]
  *FOLD R^2: -0.0025 (MSE: 0.7501; MAE: 0.6237; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0075)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 173)]
  *FOLD R^2: -0.0001 (MSE: 0.9840; MAE: 0.7180; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0006)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 314)]
  *FOLD R^2: -0.0483 (MSE: 0.4700; MAE: 0.5018; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0207
*Overall FOLDS R^2:    -0.0275 (+- 0.0110)
*R (sqrt R^2):         nan
*Pearson r:            0.0406 (p = 0.44551)
*Folds Pearson r:      0.0433 (p = 0.64595)
*Spearman rho:         0.0074 (p = 0.88922)
*Mean Squared Error:   0.8387
*Mean Absolute Error:  0.6551
*Train_Mean MAE:       0.1152

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0530)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 341)]
  *FOLD R^2: -0.1407 (MSE: 1.1029; MAE: 0.7111; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0264)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 624)]
  *FOLD R^2: -0.0586 (MSE: 0.9391; MAE: 0.7395; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0490)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 584)]
  *FOLD R^2: -0.0647 (MSE: 0.8673; MAE: 0.6903; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0596)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 288)]
  *FOLD R^2: -0.0044 (MSE: 1.2441; MAE: 0.8546; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0888)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 608)]
  *FOLD R^2: -0.3260 (MSE: 0.8701; MAE: 0.6313; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0942
*Overall FOLDS R^2:    -0.1189 (+- 0.0502)
*R (sqrt R^2):         nan
*Pearson r:            0.0181 (p = 0.73359)
*Folds Pearson r:      0.0221 (p = 0.62759)
*Spearman rho:         0.0256 (p = 0.62994)
*Mean Squared Error:   1.0043
*Mean Absolute Error:  0.7252
*Train_Mean MAE:       0.2454

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0909)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1114)]
  *FOLD R^2: -0.1274 (MSE: 6.1904; MAE: 1.7153; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0409)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1012)]
  *FOLD R^2: -0.1454 (MSE: 6.1381; MAE: 1.9450; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0375)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)

In [59]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:18:56
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0068)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 770)]
  *FOLD R^2: -0.0541 (MSE: 0.1995; MAE: 0.4284; mean train mae: 0.4178)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0117)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 811)]
  *FOLD R^2: -0.0712 (MSE: 0.3850; MAE: 0.5285; mean train mae: 0.5188)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0152)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 776)]
  *FOLD R^2: -0.0009 (MSE: 0.4730; MAE: 0.5561; mean train mae: 0.5508)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=1) (score: -0.0052)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=1)
settings:  [('degree', 3), ('gamma', 1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 1), ('fit_status_', 0), ('n_iter_', 653)]
  *FOLD R^2: -0.0005 (MSE: 0.3973; MAE: 0.5267; mean train mae: 0.5213)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0055)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 737)]
  *FOLD R^2: -0.0657 (MSE: 0.2938; MAE: 0.5011; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0114
*Overall FOLDS R^2:    -0.0385 (+- 0.0140)
*R (sqrt R^2):         nan
*Pearson r:            -0.1417 (p = 0.00741)
*Folds Pearson r:      nan (p = nan)
*Spearman rho:         -0.1494 (p = 0.00473)
*Mean Squared Error:   0.3498
*Mean Absolute Error:  0.5082
*Train_Mean MAE:       0.0276

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0255)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 576)]
  *FOLD R^2: -0.0106 (MSE: 0.6536; MAE: 0.6135; mean train mae: 0.6116)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0417)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 710)]
  *FOLD R^2: -0.0238 (MSE: 0.4479; MAE: 0.5520; mean train mae: 0.5499)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0168)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 618)]
  *FOLD R^2: -0.0140 (MSE: 0.7632; MAE: 0.6830; mean train mae: 0.6818)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0234)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 772)]
  *FOLD R^2: -0.0027 (MSE: 0.5152; MAE: 0.5865; mean train mae: 0.5856)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0332)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 553)]
  *FOLD R^2: -0.1019 (MSE: 0.3996; MAE: 0.5563; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: NearConstantInputWarning: An input array is nearly constant; the computed correlation coefficient may be inaccurate.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0081
*Overall FOLDS R^2:    -0.0306 (+- 0.0162)
*R (sqrt R^2):         nan
*Pearson r:            -0.1259 (p = 0.01751)
*Folds Pearson r:      0.0136 (p = 0.73396)
*Spearman rho:         -0.1112 (p = 0.03592)
*Mean Squared Error:   0.5556
*Mean Absolute Error:  0.5981
*Train_Mean MAE:       0.0219

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0091)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 212)]
  *FOLD R^2: 0.0074 (MSE: 0.6604; MAE: 0.5840; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.001) (score: 0.0033)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 160)]
  *FOLD R^2: -0.0172 (MSE: 0.7904; MAE: 0.5943; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.001) (score: -0.0250)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 174)]
  *FOLD R^2: -0.0049 (MSE: 0.8301; MAE: 0.6131; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0340)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 382)]
  *FOLD R^2: -0.1619 (MSE: 0.7629; MAE: 0.5837; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0014)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 155)]
  *FOLD R^2: -0.1025 (MSE: 0.4278; MAE: 0.4503; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0256
*Overall FOLDS R^2:    -0.0558 (+- 0.0293)
*R (sqrt R^2):         nan
*Pearson r:            -0.0018 (p = 0.97351)
*Folds Pearson r:      0.0846 (p = 0.36012)
*Spearman rho:         0.1142 (p = 0.03124)
*Mean Squared Error:   0.6946
*Mean Absolute Error:  0.5652
*Train_Mean MAE:       0.0835

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0114)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)

In [60]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:19:20
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0816)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 368)]
  *FOLD R^2: -0.1740 (MSE: 0.3358; MAE: 0.4307; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0096)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 400)]
  *FOLD R^2: 0.0685 (MSE: 0.6293; MAE: 0.5916; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0167)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 366)]
  *FOLD R^2: -0.0338 (MSE: 0.3370; MAE: 0.4955; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0366)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 408)]
  *FOLD R^2: -0.0669 (MSE: 0.6593; MAE: 0.5944; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0013)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 390)]
  *FOLD R^2: 0.0026 (MSE: 0.6341; MAE: 0.5715; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0076
*Overall FOLDS R^2:    -0.0407 (+- 0.0359)
*R (sqrt R^2):         nan
*Pearson r:            0.1398 (p = 0.00653)
*Folds Pearson r:      0.1396 (p = 0.32005)
*Spearman rho:         0.1253 (p = 0.01488)
*Mean Squared Error:   0.5181
*Mean Absolute Error:  0.5364
*Train_Mean MAE:       0.1669

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0223)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 186)]
  *FOLD R^2: 0.0127 (MSE: 0.5798; MAE: 0.5218; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0176)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 838)]
  *FOLD R^2: -0.0034 (MSE: 0.6094; MAE: 0.6164; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0432)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 429)]
  *FOLD R^2: -0.0526 (MSE: 0.6801; MAE: 0.6357; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0440)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 613)]
  *FOLD R^2: -0.0220 (MSE: 0.8365; MAE: 0.6711; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0017)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 365)]
  *FOLD R^2: -0.0184 (MSE: 0.8227; MAE: 0.6665; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0109
*Overall FOLDS R^2:    -0.0167 (+- 0.0097)
*R (sqrt R^2):         nan
*Pearson r:            0.0346 (p = 0.50292)
*Folds Pearson r:      0.1046 (p = 0.40703)
*Spearman rho:         0.0293 (p = 0.57013)
*Mean Squared Error:   0.7053
*Mean Absolute Error:  0.6221
*Train_Mean MAE:       0.0796

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0015)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 620)]
  *FOLD R^2: -0.0135 (MSE: 0.6906; MAE: 0.5861; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: -0.0018)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 623)]
  *FOLD R^2: 0.0800 (MSE: 0.8449; MAE: 0.6785; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0058)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 588)]
  *FOLD R^2: -0.0532 (MSE: 0.6015; MAE: 0.5264; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0410)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 730)]
  *FOLD R^2: -0.1275 (MSE: 1.1438; MAE: 0.7861; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0440)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 656)]
  *FOLD R^2: -0.0552 (MSE: 1.0268; MAE: 0.7223; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0233
*Overall FOLDS R^2:    -0.0339 (+- 0.0303)
*R (sqrt R^2):         nan
*Pearson r:            0.1386 (p = 0.00704)
*Folds Pearson r:      0.1470 (p = 0.30617)
*Spearman rho:         0.1747 (p = 0.00066)
*Mean Squared Error:   0.8604
*Mean Absolute Error:  0.6593
*Train_Mean MAE:       0.2408

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0394)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1032)]
  *FOLD R^2: -0.1391 (MSE: 3.2225; MAE: 1.3923; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0078)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 261)]
  *FOLD R^2: 0.0385 (MSE: 3.9714; MAE: 1.5567; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0096)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 233)]
  *FOLD R^2: -0.0928 (MSE: 3.3850; MAE: 1.4479; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)

In [61]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:19:45
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0195)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 787)]
  *FOLD R^2: -0.0656 (MSE: 0.2937; MAE: 0.5089; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0873)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 439)]
  *FOLD R^2: -0.2981 (MSE: 0.3231; MAE: 0.4864; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0081)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 831)]
  *FOLD R^2: -0.1326 (MSE: 0.5948; MAE: 0.5940; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0382)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 405)]
  *FOLD R^2: -0.1844 (MSE: 0.2992; MAE: 0.4509; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0916)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 468)]
  *FOLD R^2: -0.0400 (MSE: 0.5872; MAE: 0.6034; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0709
*Overall FOLDS R^2:    -0.1441 (+- 0.0412)
*R (sqrt R^2):         nan
*Pearson r:            0.0025 (p = 0.96067)
*Folds Pearson r:      0.0281 (p = 0.58487)
*Spearman rho:         -0.0131 (p = 0.79913)
*Mean Squared Error:   0.4189
*Mean Absolute Error:  0.5285
*Train_Mean MAE:       0.1153

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0066)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 364)]
  *FOLD R^2: -0.0288 (MSE: 0.7538; MAE: 0.6843; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0525)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 406)]
  *FOLD R^2: -0.1126 (MSE: 0.5637; MAE: 0.6152; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0275)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 402)]
  *FOLD R^2: -0.1816 (MSE: 0.4903; MAE: 0.5025; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0659)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 576)]
  *FOLD R^2: -0.5914 (MSE: 0.5158; MAE: 0.5774; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0024)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 381)]
  *FOLD R^2: -0.0423 (MSE: 0.4725; MAE: 0.5716; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1370
*Overall FOLDS R^2:    -0.1913 (+- 0.0927)
*R (sqrt R^2):         nan
*Pearson r:            0.0116 (p = 0.82262)
*Folds Pearson r:      0.0312 (p = 0.55006)
*Spearman rho:         -0.0025 (p = 0.96174)
*Mean Squared Error:   0.5596
*Mean Absolute Error:  0.5904
*Train_Mean MAE:       0.2123

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0035)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 375)]
  *FOLD R^2: -0.2097 (MSE: 0.7741; MAE: 0.6983; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0168)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 676)]
  *FOLD R^2: -0.0120 (MSE: 0.4761; MAE: 0.5732; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0130)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 766)]
  *FOLD R^2: -0.0289 (MSE: 0.4939; MAE: 0.5544; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0436)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 621)]
  *FOLD R^2: -0.0178 (MSE: 0.4446; MAE: 0.5228; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0101)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 465)]
  *FOLD R^2: -0.0341 (MSE: 0.5817; MAE: 0.6157; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0545
*Overall FOLDS R^2:    -0.0605 (+- 0.0335)
*R (sqrt R^2):         nan
*Pearson r:            -0.0476 (p = 0.35633)
*Folds Pearson r:      -0.0368 (p = 0.69972)
*Spearman rho:         -0.1156 (p = 0.02479)
*Mean Squared Error:   0.5544
*Mean Absolute Error:  0.5930
*Train_Mean MAE:       0.0613

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0384)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 249)]
  *FOLD R^2: -0.1129 (MSE: 3.1305; MAE: 1.4320; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0433)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 246)]
  *FOLD R^2: -0.1020 (MSE: 2.5441; MAE: 1.2766; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0041)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 238)]
  *FOLD R^2: -0.0511 (MSE: 2.5442; MAE: 1.2905; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]

#### SVR Predictions with Demographic Subgroups

Support Vector Regression predictions stratified by gender and demographic groups

In [62]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:20:10
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.001) (score: -0.0074)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 168)]
  *FOLD R^2: -0.0162 (MSE: 0.7342; MAE: 0.5575; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0004)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 214)]
  *FOLD R^2: -0.0021 (MSE: 0.7797; MAE: 0.6353; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0015)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 189)]
  *FOLD R^2: -0.0830 (MSE: 0.5998; MAE: 0.5508; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0489)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 435)]
  *FOLD R^2: -0.0129 (MSE: 1.0264; MAE: 0.7182; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0253)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 339)]
  *FOLD R^2: -0.4835 (MSE: 0.5974; MAE: 0.5737; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0707
*Overall FOLDS R^2:    -0.1195 (+- 0.0824)
*R (sqrt R^2):         nan
*Pearson r:            -0.0899 (p = 0.09042)
*Folds Pearson r:      -0.1064 (p = 0.27836)
*Spearman rho:         -0.1090 (p = 0.03988)
*Mean Squared Error:   0.7471
*Mean Absolute Error:  0.6069
*Train_Mean MAE:       0.0866

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0145)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 316)]
  *FOLD R^2: -0.1400 (MSE: 1.1058; MAE: 0.7175; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0860)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 606)]
  *FOLD R^2: -0.0975 (MSE: 1.0298; MAE: 0.7784; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0078)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 318)]
  *FOLD R^2: 0.0018 (MSE: 0.7469; MAE: 0.6510; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0375)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 505)]
  *FOLD R^2: -0.1355 (MSE: 1.1172; MAE: 0.7899; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0576)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1020)]
  *FOLD R^2: -0.7707 (MSE: 0.7939; MAE: 0.7023; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1661
*Overall FOLDS R^2:    -0.2284 (+- 0.1234)
*R (sqrt R^2):         nan
*Pearson r:            -0.0242 (p = 0.64934)
*Folds Pearson r:      -0.0003 (p = 0.65237)
*Spearman rho:         -0.0348 (p = 0.51276)
*Mean Squared Error:   0.9581
*Mean Absolute Error:  0.7276
*Train_Mean MAE:       0.2595

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0679)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 548)]
  *FOLD R^2: -0.1969 (MSE: 1.1572; MAE: 0.7341; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0483)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 542)]
  *FOLD R^2: -0.0449 (MSE: 0.9270; MAE: 0.7279; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0140)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 506)]
  *FOLD R^2: -0.0593 (MSE: 0.8629; MAE: 0.6895; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0168)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 269)]
  *FOLD R^2: -0.0120 (MSE: 1.2535; MAE: 0.8611; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0757)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 455)]
  *FOLD R^2: -0.3181 (MSE: 0.8650; MAE: 0.6263; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1033
*Overall FOLDS R^2:    -0.1262 (+- 0.0514)
*R (sqrt R^2):         nan
*Pearson r:            0.0097 (p = 0.85594)
*Folds Pearson r:      0.0178 (p = 0.56919)
*Spearman rho:         0.0324 (p = 0.54281)
*Mean Squared Error:   1.0127
*Mean Absolute Error:  0.7277
*Train_Mean MAE:       0.2486

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0452)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1076)]
  *FOLD R^2: -0.2054 (MSE: 6.6187; MAE: 1.8018; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0867)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1033)]
  *FOLD R^2: -0.1699 (MSE: 6.2695; MAE: 1.9515; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0235)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 329)]
  *FOLD R^2: -0.1449 (MSE: 4.9928; MAE: 1.7275; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]

In [63]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:20:33
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0182)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 770)]
  *FOLD R^2: -0.0541 (MSE: 0.1995; MAE: 0.4284; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0167)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 811)]
  *FOLD R^2: -0.0712 (MSE: 0.3850; MAE: 0.5285; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0246)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 776)]
  *FOLD R^2: -0.0009 (MSE: 0.4730; MAE: 0.5561; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 653)]
  *FOLD R^2: -0.0005 (MSE: 0.3973; MAE: 0.5267; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0305)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 737)]
  *FOLD R^2: -0.0657 (MSE: 0.2938; MAE: 0.5011; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0114
*Overall FOLDS R^2:    -0.0385 (+- 0.0140)
*R (sqrt R^2):         nan
*Pearson r:            -0.1417 (p = 0.00741)
*Folds Pearson r:      0.0219 (p = 0.44351)
*Spearman rho:         -0.1355 (p = 0.01048)
*Mean Squared Error:   0.3498
*Mean Absolute Error:  0.5082
*Train_Mean MAE:       0.0276

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0114)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 334)]
  *FOLD R^2: -0.1057 (MSE: 0.7150; MAE: 0.6218; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0242)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 364)]
  *FOLD R^2: -0.2479 (MSE: 0.5460; MAE: 0.5899; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0057)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 608)]
  *FOLD R^2: -0.0762 (MSE: 0.8100; MAE: 0.6474; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0095)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 772)]
  *FOLD R^2: -0.0027 (MSE: 0.5152; MAE: 0.5865; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0316)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 553)]
  *FOLD R^2: -0.1019 (MSE: 0.3996; MAE: 0.5563; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0833
*Overall FOLDS R^2:    -0.1069 (+- 0.0356)
*R (sqrt R^2):         nan
*Pearson r:            -0.0040 (p = 0.94052)
*Folds Pearson r:      0.0037 (p = 0.45564)
*Spearman rho:         0.0117 (p = 0.82541)
*Mean Squared Error:   0.5970
*Mean Absolute Error:  0.6004
*Train_Mean MAE:       0.1372

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.001) (score: 0.0020)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=0.1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 164)]
  *FOLD R^2: 0.0009 (MSE: 0.6647; MAE: 0.5856; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0409)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 320)]
  *FOLD R^2: -0.1230 (MSE: 0.8726; MAE: 0.7010; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0163)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 315)]
  *FOLD R^2: -0.0837 (MSE: 0.8952; MAE: 0.6418; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0623)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 333)]
  *FOLD R^2: -0.1205 (MSE: 0.7358; MAE: 0.5753; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0014)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 164)]
  *FOLD R^2: -0.1057 (MSE: 0.4290; MAE: 0.4514; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0629
*Overall FOLDS R^2:    -0.0864 (+- 0.0205)
*R (sqrt R^2):         nan
*Pearson r:            -0.0031 (p = 0.95396)
*Folds Pearson r:      0.0891 (p = 0.43870)
*Spearman rho:         0.0727 (p = 0.17086)
*Mean Squared Error:   0.7199
*Mean Absolute Error:  0.5913
*Train_Mean MAE:       0.1432

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0414)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 237)]
  *FOLD R^2: -0.0814 (MSE: 2.7775; MAE: 1.3097; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0409)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 235)]
  *FOLD R^2: -0.2446 (MSE: 3.6586; MAE: 1.5458; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0260)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 512), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 242)]
  *FOLD R^2: -0.0049 (MSE: 3.8808; MAE: 1.4380; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [64]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:20:56
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0809)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 421)]
  *FOLD R^2: -0.0658 (MSE: 0.3048; MAE: 0.4291; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0340)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 218)]
  *FOLD R^2: 0.0813 (MSE: 0.6206; MAE: 0.5778; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0374)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 444)]
  *FOLD R^2: 0.0507 (MSE: 0.3095; MAE: 0.4739; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0780)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 460)]
  *FOLD R^2: -0.0331 (MSE: 0.6384; MAE: 0.5739; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0758)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 448)]
  *FOLD R^2: 0.0129 (MSE: 0.6275; MAE: 0.5573; mean train mae: 0.5997)
*Overall R^2:          0.0293
*Overall FOLDS R^2:    0.0092 (+- 0.0240)
*R (sqrt R^2):         0.1712
*Pearson r:            0.2088 (p = 0.00004)
*Folds Pearson r:      0.2204 (p = 0.11346)
*Spearman rho:         0.2166 (p = 0.00002)
*Mean Squared Error:   0.4991
*Mean Absolute Error:  0.5220
*Train_Mean MAE:       0.1738

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0176)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 486)]
  *FOLD R^2: 0.0242 (MSE: 0.5730; MAE: 0.5654; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0281)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 485)]
  *FOLD R^2: -0.0014 (MSE: 0.6081; MAE: 0.6289; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0032)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 232)]
  *FOLD R^2: -0.0366 (MSE: 0.6698; MAE: 0.6166; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0033)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 518)]
  *FOLD R^2: 0.0108 (MSE: 0.8097; MAE: 0.6477; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0189)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 469)]
  *FOLD R^2: 0.0070 (MSE: 0.8021; MAE: 0.6536; mean train mae: 0.6564)
*Overall R^2:          0.0079
*Overall FOLDS R^2:    0.0008 (+- 0.0091)
*R (sqrt R^2):         0.0890
*Pearson r:            0.1513 (p = 0.00324)
*Folds Pearson r:      0.1771 (p = 0.20010)
*Spearman rho:         0.1310 (p = 0.01090)
*Mean Squared Error:   0.6922
*Mean Absolute Error:  0.6223
*Train_Mean MAE:       0.1610

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0831)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 615)]
  *FOLD R^2: -0.0965 (MSE: 0.7472; MAE: 0.6663; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0231)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()

In [65]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:21:37
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL1', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0695)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: -0.0059 (MSE: 0.2773; MAE: 0.4662; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1098)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: -0.0990 (MSE: 0.2735; MAE: 0.4659; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0335)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 567)]
  *FOLD R^2: -0.0710 (MSE: 0.5624; MAE: 0.5500; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0855)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 543)]
  *FOLD R^2: -0.1000 (MSE: 0.2779; MAE: 0.4493; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1363)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 523)]
  *FOLD R^2: 0.0064 (MSE: 0.5610; MAE: 0.5975; mean train mae: 0.6181)
*Overall R^2:          0.0035
*Overall FOLDS R^2:    -0.0539 (+- 0.0204)
*R (sqrt R^2):         0.0593
*Pearson r:            0.1659 (p = 0.00122)
*Folds Pearson r:      0.1966 (p = 0.14916)
*Spearman rho:         0.2013 (p = 0.00008)
*Mean Squared Error:   0.3898
*Mean Absolute Error:  0.5055
*Train_Mean MAE:       0.1492

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0545)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 229)]
  *FOLD R^2: 0.0016 (MSE: 0.7315; MAE: 0.6507; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0853)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 500)]
  *FOLD R^2: -0.0587 (MSE: 0.5364; MAE: 0.5976; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0488)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: -0.0891 (MSE: 0.4519; MAE: 0.5150; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0305)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 525)]
  *FOLD R^2: -0.1137 (MSE: 0.3609; MAE: 0.4832; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0841)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 514)]
  *FOLD R^2: -0.0820 (MSE: 0.4905; MAE: 0.5930; mean train mae: 0.5726)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0452
*Overall FOLDS R^2:    -0.0684 (+- 0.0175)
*R (sqrt R^2):         nan
*Pearson r:            0.0825 (p = 0.10963)
*Folds Pearson r:      0.1003 (p = 0.45210)
*Spearman rho:         0.1032 (p = 0.04520)
*Mean Squared Error:   0.5144
*Mean Absolute Error:  0.5679
*Train_Mean MAE:       0.1757

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0441)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 212)]
  *FOLD R^2: -0.0990 (MSE: 0.7032; MAE: 0.6490; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()

In [66]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:22:19
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL3', 'CELVAL1', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0385)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 199)]
  *FOLD R^2: -0.0542 (MSE: 0.7616; MAE: 0.5660; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0141)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 204)]
  *FOLD R^2: 0.0995 (MSE: 0.7006; MAE: 0.6099; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0353)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 556)]
  *FOLD R^2: -0.1692 (MSE: 0.6475; MAE: 0.6319; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0108)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 417)]
  *FOLD R^2: -0.0237 (MSE: 1.0373; MAE: 0.7383; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0419)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 574)]
  *FOLD R^2: -0.4052 (MSE: 0.5659; MAE: 0.5436; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0638
*Overall FOLDS R^2:    -0.1105 (+- 0.0762)
*R (sqrt R^2):         nan
*Pearson r:            0.0604 (p = 0.25566)
*Folds Pearson r:      0.1205 (p = 0.40413)
*Spearman rho:         0.1234 (p = 0.01986)
*Mean Squared Error:   0.7423
*Mean Absolute Error:  0.6180
*Train_Mean MAE:       0.1989

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0730)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 570)]
  *FOLD R^2: -0.0413 (MSE: 1.0101; MAE: 0.6798; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0920)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 570)]
  *FOLD R^2: -0.0992 (MSE: 1.0314; MAE: 0.8109; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0543)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 584)]
  *FOLD R^2: 0.0112 (MSE: 0.7399; MAE: 0.6662; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0243)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 416)]
  *FOLD R^2: 0.0011 (MSE: 0.9829; MAE: 0.7345; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0649)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 577)]
  *FOLD R^2: -0.3126 (MSE: 0.5885; MAE: 0.5971; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0591
*Overall FOLDS R^2:    -0.0882 (+- 0.0531)
*R (sqrt R^2):         nan
*Pearson r:            0.1102 (p = 0.03767)
*Folds Pearson r:      0.1393 (p = 0.30658)
*Spearman rho:         0.1201 (p = 0.02348)
*Mean Squared Error:   0.8702
*Mean Absolute Error:  0.6976
*Train_Mean MAE:       0.2634

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0986)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 602)]
  *FOLD R^2: -0.1457 (MSE: 1.1077; MAE: 0.7253; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0883)


In [67]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:23:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL2', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0090)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: -0.1074 (MSE: 0.2096; MAE: 0.4220; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0086)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 811)]
  *FOLD R^2: -0.0712 (MSE: 0.3850; MAE: 0.5285; mean train mae: 0.5188)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1149: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (pearsr, r_p) = pearsonr(ytest, ypred)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1150: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  (rho, rho_p) = spearmanr(ytest, ypred)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0019)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 531)]
  *FOLD R^2: 0.0250 (MSE: 0.4607; MAE: 0.5152; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0206)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 529)]
  *FOLD R^2: -0.0878 (MSE: 0.4320; MAE: 0.5206; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0047)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 512)]
  *FOLD R^2: -0.0832 (MSE: 0.2987; MAE: 0.4939; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0329
*Overall FOLDS R^2:    -0.0649 (+- 0.0208)
*R (sqrt R^2):         nan
*Pearson r:            0.0617 (p = 0.24561)
*Folds Pearson r:      nan (p = nan)
*Spearman rho:         0.1059 (p = 0.04595)
*Mean Squared Error:   0.3573
*Mean Absolute Error:  0.4961
*Train_Mean MAE:       0.1134

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0247)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 501)]
  *FOLD R^2: -0.0285 (MSE: 0.6651; MAE: 0.5937; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0328)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 528)]
  *FOLD R^2: -0.1839 (MSE: 0.5179; MAE: 0.5851; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0391)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 997)]
  *FOLD R^2: -0.0781 (MSE: 0.8114; MAE: 0.6504; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0434)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 492)]
  *FOLD R^2: -0.0883 (MSE: 0.5591; MAE: 0.6031; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0051)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 472)]
  *FOLD R^2: 0.0657 (MSE: 0.3388; MAE: 0.5046; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0493
*Overall FOLDS R^2:    -0.0626 (+- 0.0365)
*R (sqrt R^2):         nan
*Pearson r:            0.0909 (p = 0.08665)
*Folds Pearson r:      0.1015 (p = 0.41354)
*Spearman rho:         0.0966 (p = 0.06876)
*Mean Squared Error:   0.5783
*Mean Absolute Error:  0.5874
*Train_Mean MAE:       0.1891

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0267)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1150), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 195)]
  *FOLD R^2: 0.0679 (MSE: 0.6202; MAE: 0.5635; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler()]

In [34]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:24:08
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0360)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 220)]
  *FOLD R^2: 0.0196 (MSE: 0.2804; MAE: 0.3561; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0695)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 322)]
  *FOLD R^2: 0.0003 (MSE: 0.6753; MAE: 0.6177; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0330)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 290)]
  *FOLD R^2: -0.0915 (MSE: 0.3558; MAE: 0.4614; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0155)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 294)]
  *FOLD R^2: 0.0176 (MSE: 0.6071; MAE: 0.5340; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0664)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 301)]
  *FOLD R^2: -0.0031 (MSE: 0.6377; MAE: 0.5873; mean train mae: 0.5997)
*Overall R^2:          0.0077
*Overall FOLDS R^2:    -0.0114 (+- 0.0183)
*R (sqrt R^2):         0.0879
*Pearson r:            0.1293 (p = 0.01201)
*Folds Pearson r:      0.1657 (p = 0.18694)
*Spearman rho:         0.1535 (p = 0.00281)
*Mean Squared Error:   0.5102
*Mean Absolute Error:  0.5107
*Train_Mean MAE:       0.1199

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0003)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 689)]
  *FOLD R^2: -0.0024 (MSE: 0.5886; MAE: 0.5549; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0138)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 753)]
  *FOLD R^2: -0.0007 (MSE: 0.6077; MAE: 0.6154; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0200)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 276)]
  *FOLD R^2: -0.0588 (MSE: 0.6841; MAE: 0.6402; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0214)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 574)]
  *FOLD R^2: -0.0189 (MSE: 0.8340; MAE: 0.6694; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0597)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 224)]
  *FOLD R^2: -0.0749 (MSE: 0.8684; MAE: 0.6907; mean train mae: 0.6564)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0264
*Overall FOLDS R^2:    -0.0311 (+- 0.0135)
*R (sqrt R^2):         nan
*Pearson r:            -0.0007 (p = 0.98945)
*Folds Pearson r:      0.0919 (p = 0.47779)
*Spearman rho:         0.0047 (p = 0.92687)
*Mean Squared Error:   0.7161
*Mean Absolute Error:  0.6339
*Train_Mean MAE:       0.0799

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0517)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 362)]
  *FOLD R^2: 0.0024 (MSE: 0.6798; MAE: 0.5567; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0151)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 213)]
  *FOLD R^2: -0.0285 (MSE: 0.9445; MAE: 0.6852; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0363)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 209)]
  *FOLD R^2: -0.0056 (MSE: 0.5744; MAE: 0.5083; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0513)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 245)]
  *FOLD R^2: -0.0362 (MSE: 1.0511; MAE: 0.7025; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0228)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 234)]
  *FOLD R^2: 0.0201 (MSE: 0.9536; MAE: 0.6714; mean train mae: 0.6533)
*Overall R^2:          0.0016
*Overall FOLDS R^2:    -0.0095 (+- 0.0092)
*R (sqrt R^2):         0.0394
*Pearson r:            0.1025 (p = 0.04672)
*Folds Pearson r:      0.1048 (p = 0.38055)
*Spearman rho:         0.1098 (p = 0.03301)
*Mean Squared Error:   0.8395
*Mean Absolute Error:  0.6243
*Train_Mean MAE:       0.1287

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0609)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 791)]
  *FOLD R^2: -0.0644 (MSE: 3.0112; MAE: 1.2888; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0504)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 956)]
  *FOLD R^2: -0.0315 (MSE: 4.2604; MAE: 1.5733; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0722)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 825)]
  *FOLD R^2: -0.0634 (MSE: 3.2941; MAE: 1.4539; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0504)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()

In [35]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:24:20
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0126)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 264)]
  *FOLD R^2: -0.2733 (MSE: 0.3510; MAE: 0.4929; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0183)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 199)]
  *FOLD R^2: -0.2865 (MSE: 0.3202; MAE: 0.4646; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0044)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 743)]
  *FOLD R^2: -0.1318 (MSE: 0.5943; MAE: 0.5936; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1014)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 238)]
  *FOLD R^2: -0.3702 (MSE: 0.3461; MAE: 0.4736; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0392)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 209)]
  *FOLD R^2: -0.0391 (MSE: 0.5867; MAE: 0.6162; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1227
*Overall FOLDS R^2:    -0.2202 (+- 0.0530)
*R (sqrt R^2):         nan
*Pearson r:            -0.0026 (p = 0.96045)
*Folds Pearson r:      0.1020 (p = 0.42992)
*Spearman rho:         0.0143 (p = 0.78183)
*Mean Squared Error:   0.4392
*Mean Absolute Error:  0.5279
*Train_Mean MAE:       0.1647

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0618)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 239)]
  *FOLD R^2: 0.0390 (MSE: 0.7041; MAE: 0.6059; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0461)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 236)]
  *FOLD R^2: -0.0282 (MSE: 0.5210; MAE: 0.5459; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0542)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 231)]
  *FOLD R^2: 0.0847 (MSE: 0.3798; MAE: 0.4353; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1014)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 234)]
  *FOLD R^2: -0.2335 (MSE: 0.3998; MAE: 0.5082; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0608)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 225)]
  *FOLD R^2: 0.0289 (MSE: 0.4402; MAE: 0.5300; mean train mae: 0.5726)
*Overall R^2:          0.0058
*Overall FOLDS R^2:    -0.0218 (+- 0.0500)
*R (sqrt R^2):         0.0764
*Pearson r:            0.2081 (p = 0.00005)
*Folds Pearson r:      0.2201 (p = 0.11897)
*Spearman rho:         0.2485 (p = 0.00000)
*Mean Squared Error:   0.4893
*Mean Absolute Error:  0.5252
*Train_Mean MAE:       0.2292

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0057)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 233)]
  *FOLD R^2: 0.0649 (MSE: 0.5984; MAE: 0.5733; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0058)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 249)]
  *FOLD R^2: -0.0022 (MSE: 0.4714; MAE: 0.5363; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0507)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 212)]
  *FOLD R^2: -0.0034 (MSE: 0.4816; MAE: 0.5243; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0710)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 237)]
  *FOLD R^2: -0.1747 (MSE: 0.5131; MAE: 0.5481; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0045)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 237)]
  *FOLD R^2: 0.0067 (MSE: 0.5587; MAE: 0.6107; mean train mae: 0.6167)
*Overall R^2:          0.0017
*Overall FOLDS R^2:    -0.0217 (+- 0.0360)
*R (sqrt R^2):         0.0414
*Pearson r:            0.1495 (p = 0.00362)
*Folds Pearson r:      0.1813 (p = 0.24205)
*Spearman rho:         0.1535 (p = 0.00281)
*Mean Squared Error:   0.5248
*Mean Absolute Error:  0.5585
*Train_Mean MAE:       0.1586

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0777)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 188)]
  *FOLD R^2: 0.0687 (MSE: 2.6198; MAE: 1.3142; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0944)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 175)]
  *FOLD R^2: 0.0341 (MSE: 2.2299; MAE: 1.1996; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0835)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 205)]
  *FOLD R^2: 0.0862 (MSE: 2.2119; MAE: 1.2239; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1376)


In [36]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:24:31
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL1', 'CELVAL3', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0654)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 251)]
  *FOLD R^2: 0.0870 (MSE: 0.6596; MAE: 0.5449; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0345)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 188)]
  *FOLD R^2: 0.0272 (MSE: 0.7568; MAE: 0.6285; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0981)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 209)]
  *FOLD R^2: -0.0335 (MSE: 0.5724; MAE: 0.5843; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0444)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 244)]
  *FOLD R^2: 0.0200 (MSE: 0.9930; MAE: 0.6773; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0921)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1289)]
  *FOLD R^2: -0.2467 (MSE: 0.5020; MAE: 0.5752; mean train mae: 0.4148)
*Overall R^2:          0.0019
*Overall FOLDS R^2:    -0.0292 (+- 0.0515)
*R (sqrt R^2):         0.0437
*Pearson r:            0.1562 (p = 0.00313)
*Folds Pearson r:      0.1820 (p = 0.24207)
*Spearman rho:         0.2055 (p = 0.00009)
*Mean Squared Error:   0.6964
*Mean Absolute Error:  0.6020
*Train_Mean MAE:       0.1708

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0023)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 204)]
  *FOLD R^2: 0.0390 (MSE: 0.9322; MAE: 0.6778; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0056)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 223)]
  *FOLD R^2: -0.0199 (MSE: 0.9569; MAE: 0.7371; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0254)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 190)]
  *FOLD R^2: -0.0079 (MSE: 0.7542; MAE: 0.6573; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0169)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 229)]
  *FOLD R^2: -0.0642 (MSE: 1.0471; MAE: 0.7135; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0112)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 202)]
  *FOLD R^2: 0.0619 (MSE: 0.4206; MAE: 0.4807; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0004
*Overall FOLDS R^2:    0.0018 (+- 0.0199)
*R (sqrt R^2):         nan
*Pearson r:            0.1102 (p = 0.03776)
*Folds Pearson r:      0.1082 (p = 0.33420)
*Spearman rho:         0.1355 (p = 0.01051)
*Mean Squared Error:   0.8220
*Mean Absolute Error:  0.6533
*Train_Mean MAE:       0.1558

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0358)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 226)]
  *FOLD R^2: 0.0490 (MSE: 0.9195; MAE: 0.6165; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0308)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 333)]
  *FOLD R^2: -0.0282 (MSE: 0.9121; MAE: 0.6768; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0489)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1134)]
  *FOLD R^2: -0.1482 (MSE: 0.9353; MAE: 0.8063; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0131)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 243)]
  *FOLD R^2: 0.0729 (MSE: 1.1483; MAE: 0.7955; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0248)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 187)]
  *FOLD R^2: -0.0731 (MSE: 0.7042; MAE: 0.5419; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0066
*Overall FOLDS R^2:    -0.0255 (+- 0.0361)
*R (sqrt R^2):         nan
*Pearson r:            0.1218 (p = 0.02158)
*Folds Pearson r:      0.1804 (p = 0.37558)
*Spearman rho:         0.1546 (p = 0.00344)
*Mean Squared Error:   0.9239
*Mean Absolute Error:  0.6877
*Train_Mean MAE:       0.1842

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0466)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 169)]
  *FOLD R^2: 0.0687 (MSE: 5.1140; MAE: 1.5083; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0826)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 677)]
  *FOLD R^2: -0.0215 (MSE: 5.4743; MAE: 1.7969; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1477)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 623)]
  *FOLD R^2: -0.1426 (MSE: 4.9827; MAE: 1.7916; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)

#### SVR Predictions with Text Features

Support Vector Regression using text-based features (LIWC, categories, word embeddings)

In [37]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 04:24:41
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CELVAL3', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0117)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 768)]
  *FOLD R^2: -0.0513 (MSE: 0.1989; MAE: 0.4277; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0169)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 829)]
  *FOLD R^2: -0.0704 (MSE: 0.3847; MAE: 0.5282; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0174)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 637)]
  *FOLD R^2: -0.0006 (MSE: 0.4728; MAE: 0.5558; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0044)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 609)]
  *FOLD R^2: 0.0001 (MSE: 0.3971; MAE: 0.5263; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0192)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 613)]
  *FOLD R^2: -0.0657 (MSE: 0.2939; MAE: 0.5009; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0107
*Overall FOLDS R^2:    -0.0376 (+- 0.0139)
*R (sqrt R^2):         nan
*Pearson r:            -0.1289 (p = 0.01496)
*Folds Pearson r:      0.1397 (p = 0.31880)
*Spearman rho:         -0.1286 (p = 0.01517)
*Mean Squared Error:   0.3496
*Mean Absolute Error:  0.5078
*Train_Mean MAE:       0.0273

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0200)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 560)]
  *FOLD R^2: -0.0095 (MSE: 0.6529; MAE: 0.6128; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0218)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 212)]
  *FOLD R^2: -0.0565 (MSE: 0.4622; MAE: 0.5404; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0401)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 210)]
  *FOLD R^2: -0.1384 (MSE: 0.8568; MAE: 0.6865; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0183)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 223)]
  *FOLD R^2: -0.1284 (MSE: 0.5798; MAE: 0.5925; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0103)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 211)]
  *FOLD R^2: -0.0080 (MSE: 0.3655; MAE: 0.4969; mean train mae: 0.5574)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0580
*Overall FOLDS R^2:    -0.0682 (+- 0.0251)
*R (sqrt R^2):         nan
*Pearson r:            0.0529 (p = 0.31992)
*Folds Pearson r:      0.1091 (p = 0.35274)
*Spearman rho:         0.0924 (p = 0.08160)
*Mean Squared Error:   0.5831
*Mean Absolute Error:  0.5857
*Train_Mean MAE:       0.1628

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0074)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 408)]
  *FOLD R^2: -0.0051 (MSE: 0.6687; MAE: 0.5966; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0055)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 236)]
  *FOLD R^2: -0.0588 (MSE: 0.8227; MAE: 0.6055; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=0.1, gamma=0.1) (score: -0.0311)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=0.1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 0.1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 428)]
  *FOLD R^2: -0.0063 (MSE: 0.8313; MAE: 0.6278; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0391)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 228)]
  *FOLD R^2: -0.1134 (MSE: 0.7311; MAE: 0.5927; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0088)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 205)]
  *FOLD R^2: -0.1007 (MSE: 0.4271; MAE: 0.4683; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0284
*Overall FOLDS R^2:    -0.0569 (+- 0.0203)
*R (sqrt R^2):         nan
*Pearson r:            -0.0349 (p = 0.51132)
*Folds Pearson r:      0.0550 (p = 0.40990)
*Spearman rho:         -0.0096 (p = 0.85604)
*Mean Squared Error:   0.6965
*Mean Absolute Error:  0.5782
*Train_Mean MAE:       0.0653

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0114)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 172)]
  *FOLD R^2: 0.0604 (MSE: 2.4134; MAE: 1.2077; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0230)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 157)]
  *FOLD R^2: -0.0487 (MSE: 3.0827; MAE: 1.3845; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0279)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 103), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 180)]
  *FOLD R^2: -0.0594 (MSE: 4.0914; MAE: 1.5009; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [72]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_SMale50_cp_w$stratified_male$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:24:28
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL3', 'CELVAL1', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0855)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1036)]
  *FOLD R^2: 0.0041 (MSE: 0.2848; MAE: 0.3796; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1229)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 907)]
  *FOLD R^2: 0.0312 (MSE: 0.6545; MAE: 0.5762; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0737)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 530)]
  *FOLD R^2: -0.0341 (MSE: 0.3371; MAE: 0.4807; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0854)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 926)]
  *FOLD R^2: -0.3005 (MSE: 0.8036; MAE: 0.6418; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0799)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 154)]
  *FOLD R^2: -0.0082 (MSE: 0.6409; MAE: 0.5684; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0559
*Overall FOLDS R^2:    -0.0615 (+- 0.0543)
*R (sqrt R^2):         nan
*Pearson r:            0.1120 (p = 0.02970)
*Folds Pearson r:      0.1284 (p = 0.20742)
*Spearman rho:         0.1255 (p = 0.01474)
*Mean Squared Error:   0.5430
*Mean Absolute Error:  0.5288
*Train_Mean MAE:       0.1938

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0685)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 172)]
  *FOLD R^2: -0.0028 (MSE: 0.5889; MAE: 0.5272; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0776)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 189)]
  *FOLD R^2: -0.0179 (MSE: 0.6181; MAE: 0.6177; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0553)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 218)]
  *FOLD R^2: -0.0437 (MSE: 0.6744; MAE: 0.6253; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0985)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 191)]
  *FOLD R^2: -0.0185 (MSE: 0.8336; MAE: 0.6503; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0364)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 184)]
  *FOLD R^2: 0.0544 (MSE: 0.7639; MAE: 0.6183; mean train mae: 0.6564)
*Overall R^2:          0.0032
*Overall FOLDS R^2:    -0.0057 (+- 0.0147)
*R (sqrt R^2):         0.0569
*Pearson r:            0.1285 (p = 0.01255)
*Folds Pearson r:      0.1219 (p = 0.36685)
*Spearman rho:         0.1195 (p = 0.02033)
*Mean Squared Error:   0.6954
*Mean Absolute Error:  0.6076
*Train_Mean MAE:       0.1552

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1872)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 656)]
  *FOLD R^2: -0.1297 (MSE: 0.7699; MAE: 0.6788; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1365)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1045)]
  *FOLD R^2: 0.1657 (MSE: 0.7663; MAE: 0.6745; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1593)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1036)]
  *FOLD R^2: -1.6759 (MSE: 1.5283; MAE: 0.8275; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1884)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 1119)]
  *FOLD R^2: -0.1292 (MSE: 1.1455; MAE: 0.7891; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1084)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 896)]
  *FOLD R^2: -0.0666 (MSE: 1.0379; MAE: 0.7157; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.2489
*Overall FOLDS R^2:    -0.3671 (+- 0.2966)
*R (sqrt R^2):         nan
*Pearson r:            0.0497 (p = 0.33578)
*Folds Pearson r:      0.1097 (p = 0.26324)
*Spearman rho:         0.1110 (p = 0.03115)
*Mean Squared Error:   1.0501
*Mean Absolute Error:  0.7372
*Train_Mean MAE:       0.3380

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.2495)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 517)]
  *FOLD R^2: -0.0444 (MSE: 2.9546; MAE: 1.2980; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.2543)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 648)]
  *FOLD R^2: 0.1458 (MSE: 3.5282; MAE: 1.4578; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.2294)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 468)]
  *FOLD R^2: -0.6017 (MSE: 4.9614; MAE: 1.7129; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]

In [73]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_SFemale50_cp_w$stratified_female$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:24:39
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0046)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 563)]
  *FOLD R^2: -0.0451 (MSE: 0.2880; MAE: 0.4978; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0273)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 543)]
  *FOLD R^2: -0.1013 (MSE: 0.2741; MAE: 0.4908; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0188)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 575)]
  *FOLD R^2: -0.1295 (MSE: 0.5932; MAE: 0.5866; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0097)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 571)]
  *FOLD R^2: -0.1474 (MSE: 0.2898; MAE: 0.4838; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0265)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 572)]
  *FOLD R^2: 0.0012 (MSE: 0.5639; MAE: 0.6144; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0256
*Overall FOLDS R^2:    -0.0844 (+- 0.0246)
*R (sqrt R^2):         nan
*Pearson r:            -0.0928 (p = 0.07188)
*Folds Pearson r:      0.0851 (p = 0.47029)
*Spearman rho:         -0.1457 (p = 0.00459)
*Mean Squared Error:   0.4012
*Mean Absolute Error:  0.5344
*Train_Mean MAE:       0.0428

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0770)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 576)]
  *FOLD R^2: 0.0712 (MSE: 0.6805; MAE: 0.6447; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1160)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 182)]
  *FOLD R^2: -0.0319 (MSE: 0.5228; MAE: 0.5932; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0834)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 605)]
  *FOLD R^2: 0.0236 (MSE: 0.4051; MAE: 0.5198; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0795)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 592)]
  *FOLD R^2: -0.0680 (MSE: 0.3461; MAE: 0.5135; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.1190)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 188)]
  *FOLD R^2: -0.0110 (MSE: 0.4583; MAE: 0.5327; mean train mae: 0.5726)
*Overall R^2:          0.0192
*Overall FOLDS R^2:    -0.0032 (+- 0.0213)
*R (sqrt R^2):         0.1385
*Pearson r:            0.1569 (p = 0.00224)
*Folds Pearson r:      0.2080 (p = 0.13129)
*Spearman rho:         0.1259 (p = 0.01447)
*Mean Squared Error:   0.4827
*Mean Absolute Error:  0.5609
*Train_Mean MAE:       0.1043

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0508)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 566)]
  *FOLD R^2: -0.0118 (MSE: 0.6474; MAE: 0.6141; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0117)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 480)]
  *FOLD R^2: 0.0056 (MSE: 0.4678; MAE: 0.5625; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0023)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 583)]
  *FOLD R^2: 0.0080 (MSE: 0.4761; MAE: 0.5455; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0802)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 216)]
  *FOLD R^2: -0.2060 (MSE: 0.5268; MAE: 0.5164; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0392)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 192)]
  *FOLD R^2: -0.0350 (MSE: 0.5822; MAE: 0.6088; mean train mae: 0.6167)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0277
*Overall FOLDS R^2:    -0.0478 (+- 0.0360)
*R (sqrt R^2):         nan
*Pearson r:            0.0466 (p = 0.36645)
*Folds Pearson r:      0.1237 (p = 0.26720)
*Spearman rho:         0.0935 (p = 0.06982)
*Mean Squared Error:   0.5403
*Mean Absolute Error:  0.5694
*Train_Mean MAE:       0.1024

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0842)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 174)]
  *FOLD R^2: 0.1429 (MSE: 2.4112; MAE: 1.2298; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1078)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 157)]
  *FOLD R^2: -0.0293 (MSE: 2.3763; MAE: 1.2569; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0525)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 482)]
  *FOLD R^2: -0.0264 (MSE: 2.4845; MAE: 1.3530; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0909)


In [74]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_Swhite50_cp_w$stratified_white$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:24:50
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL1', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0047)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 134)]
  *FOLD R^2: -0.0416 (MSE: 0.7525; MAE: 0.5751; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.1) (score: 0.0006)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 426)]
  *FOLD R^2: 0.0400 (MSE: 0.7469; MAE: 0.6515; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0381)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 451)]
  *FOLD R^2: 0.0126 (MSE: 0.5468; MAE: 0.5631; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0173)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 472)]
  *FOLD R^2: -0.0181 (MSE: 1.0317; MAE: 0.7364; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0023)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 464)]
  *FOLD R^2: 0.0091 (MSE: 0.3990; MAE: 0.4320; mean train mae: 0.4148)
*Overall R^2:          0.0040
*Overall FOLDS R^2:    0.0004 (+- 0.0125)
*R (sqrt R^2):         0.0632
*Pearson r:            0.0969 (p = 0.06796)
*Folds Pearson r:      0.1646 (p = 0.28073)
*Spearman rho:         0.1013 (p = 0.05608)
*Mean Squared Error:   0.6950
*Mean Absolute Error:  0.5915
*Train_Mean MAE:       0.1002

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: -0.0028)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 808)]
  *FOLD R^2: -0.1701 (MSE: 1.1350; MAE: 0.7456; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0447)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 167)]
  *FOLD R^2: -0.0303 (MSE: 0.9668; MAE: 0.7125; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0360)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 179)]
  *FOLD R^2: -0.1533 (MSE: 0.8629; MAE: 0.6745; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0198)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 189)]
  *FOLD R^2: -0.0570 (MSE: 1.0400; MAE: 0.7379; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0206)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 153)]
  *FOLD R^2: -0.0110 (MSE: 0.4533; MAE: 0.4843; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0851
*Overall FOLDS R^2:    -0.0843 (+- 0.0291)
*R (sqrt R^2):         nan
*Pearson r:            0.0305 (p = 0.56622)
*Folds Pearson r:      0.0234 (p = 0.41781)
*Spearman rho:         0.0486 (p = 0.36096)
*Mean Squared Error:   0.8915
*Mean Absolute Error:  0.6709
*Train_Mean MAE:       0.1948

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0447)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 189)]
  *FOLD R^2: -0.0498 (MSE: 1.0150; MAE: 0.6582; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0540)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 900)]
  *FOLD R^2: -0.4117 (MSE: 1.2524; MAE: 0.8462; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1157)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 827)]
  *FOLD R^2: -1.0758 (MSE: 1.6910; MAE: 1.0002; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: -0.0001)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 125)]
  *FOLD R^2: 0.0239 (MSE: 1.2090; MAE: 0.8431; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1059)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 944)]
  *FOLD R^2: -0.4800 (MSE: 0.9712; MAE: 0.6532; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.3390
*Overall FOLDS R^2:    -0.3987 (+- 0.1750)
*R (sqrt R^2):         nan
*Pearson r:            -0.1142 (p = 0.03116)
*Folds Pearson r:      -0.0503 (p = 0.23872)
*Spearman rho:         -0.0914 (p = 0.08513)
*Mean Squared Error:   1.2290
*Mean Absolute Error:  0.8007
*Train_Mean MAE:       0.2954

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0722)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 621)]
  *FOLD R^2: -0.1645 (MSE: 6.3945; MAE: 1.8541; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0964)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 422)]
  *FOLD R^2: -0.4016 (MSE: 7.5109; MAE: 2.0958; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1247)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 397)]
  *FOLD R^2: -0.5055 (MSE: 6.5655; MAE: 2.0870; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]

In [75]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_Sblack50_cp_w$stratified_black$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:25:01
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CEL_Total', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0094)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 566)]
  *FOLD R^2: -0.0406 (MSE: 0.1969; MAE: 0.4233; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0016)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 606)]
  *FOLD R^2: -0.0649 (MSE: 0.3827; MAE: 0.5219; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0101)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 543)]
  *FOLD R^2: -0.0029 (MSE: 0.4739; MAE: 0.5541; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0180)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 535)]
  *FOLD R^2: 0.0084 (MSE: 0.3938; MAE: 0.5245; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: -0.0088)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 523)]
  *FOLD R^2: -0.0575 (MSE: 0.2916; MAE: 0.4922; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0058
*Overall FOLDS R^2:    -0.0315 (+- 0.0131)
*R (sqrt R^2):         nan
*Pearson r:            0.0090 (p = 0.86533)
*Folds Pearson r:      0.0767 (p = 0.54637)
*Spearman rho:         -0.0056 (p = 0.91573)
*Mean Squared Error:   0.3479
*Mean Absolute Error:  0.5032
*Train_Mean MAE:       0.0363

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0774)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 175)]
  *FOLD R^2: -0.0226 (MSE: 0.6613; MAE: 0.6015; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0835)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 187)]
  *FOLD R^2: 0.0658 (MSE: 0.4087; MAE: 0.5158; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0994)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 161)]
  *FOLD R^2: -0.0668 (MSE: 0.8029; MAE: 0.6988; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0642)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 167)]
  *FOLD R^2: 0.0409 (MSE: 0.4928; MAE: 0.5608; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0205)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 163)]
  *FOLD R^2: -0.0120 (MSE: 0.3670; MAE: 0.5025; mean train mae: 0.5574)
*Overall R^2:          0.0090
*Overall FOLDS R^2:    0.0011 (+- 0.0211)
*R (sqrt R^2):         0.0951
*Pearson r:            0.2010 (p = 0.00013)
*Folds Pearson r:      0.2259 (p = 0.15337)
*Spearman rho:         0.1819 (p = 0.00056)
*Mean Squared Error:   0.5461
*Mean Absolute Error:  0.5757
*Train_Mean MAE:       0.2029

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0035)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 218)]
  *FOLD R^2: 0.0241 (MSE: 0.6493; MAE: 0.5742; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0622)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 191)]
  *FOLD R^2: -0.0404 (MSE: 0.8084; MAE: 0.6048; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0134)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 190)]
  *FOLD R^2: -0.0829 (MSE: 0.8945; MAE: 0.6419; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0420)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 210)]
  *FOLD R^2: -0.0788 (MSE: 0.7084; MAE: 0.5978; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0193)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 225)]
  *FOLD R^2: -0.0937 (MSE: 0.4244; MAE: 0.4638; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0295
*Overall FOLDS R^2:    -0.0543 (+- 0.0193)
*R (sqrt R^2):         nan
*Pearson r:            -0.0240 (p = 0.65154)
*Folds Pearson r:      0.0081 (p = 0.27582)
*Spearman rho:         -0.0576 (p = 0.27858)
*Mean Squared Error:   0.6973
*Mean Absolute Error:  0.5766
*Train_Mean MAE:       0.0885

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0578)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.1)
settings:  [('degree', 3), ('gamma', 0.1), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.1), ('fit_status_', 0), ('n_iter_', 548)]
  *FOLD R^2: 0.0251 (MSE: 2.5041; MAE: 1.2583; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0885)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 430)]
  *FOLD R^2: -0.1026 (MSE: 3.2411; MAE: 1.5007; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0577)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 51)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 51), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 146)]
  *FOLD R^2: -0.0612 (MSE: 4.0984; MAE: 1.5582; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 51)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.1) (score: 0.0580)

In [76]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:25:12
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL1', 'CEL_Total', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0838)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 431)]
  *FOLD R^2: 0.0489 (MSE: 0.2720; MAE: 0.3721; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0927)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: -0.0101 (MSE: 0.6824; MAE: 0.6113; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0388)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 417)]
  *FOLD R^2: -0.0344 (MSE: 0.3372; MAE: 0.4456; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0561)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 263)]
  *FOLD R^2: -0.0291 (MSE: 0.6360; MAE: 0.5433; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1043)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 557)]
  *FOLD R^2: -0.0615 (MSE: 0.6748; MAE: 0.6292; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0099
*Overall FOLDS R^2:    -0.0172 (+- 0.0165)
*R (sqrt R^2):         nan
*Pearson r:            0.1094 (p = 0.03378)
*Folds Pearson r:      0.1415 (p = 0.31316)
*Spearman rho:         0.1237 (p = 0.01625)
*Mean Squared Error:   0.5193
*Mean Absolute Error:  0.5197
*Train_Mean MAE:       0.1353

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0653)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 482)]
  *FOLD R^2: -0.0027 (MSE: 0.5889; MAE: 0.5455; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0556)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 494)]
  *FOLD R^2: 0.0425 (MSE: 0.5815; MAE: 0.6032; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0555)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: 0.0175 (MSE: 0.6348; MAE: 0.6089; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0428)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 487)]
  *FOLD R^2: 0.0276 (MSE: 0.7959; MAE: 0.6321; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0578)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 521)]
  *FOLD R^2: 0.0127 (MSE: 0.7975; MAE: 0.6459; mean train mae: 0.6564)
*Overall R^2:          0.0263
*Overall FOLDS R^2:    0.0195 (+- 0.0067)
*R (sqrt R^2):         0.1621
*Pearson r:            0.1648 (p = 0.00132)
*Folds Pearson r:      0.1517 (p = 0.26552)
*Spearman rho:         0.1363 (p = 0.00803)
*Mean Squared Error:   0.6794
*Mean Absolute Error:  0.6069
*Train_Mean MAE:       0.0952

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1621)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 609)]
  *FOLD R^2: -0.0470 (MSE: 0.7135; MAE: 0.6409; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0605)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 402)]
  *FOLD R^2: 0.0592 (MSE: 0.8641; MAE: 0.6784; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1391)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 607)]
  *FOLD R^2: -0.3368 (MSE: 0.7635; MAE: 0.6907; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0403)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 418)]
  *FOLD R^2: 0.0639 (MSE: 0.9496; MAE: 0.6805; mean train mae: 0.6624)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0824)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 425)]
  *FOLD R^2: 0.0082 (MSE: 0.9651; MAE: 0.7374; mean train mae: 0.6533)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0116
*Overall FOLDS R^2:    -0.0505 (+- 0.0665)
*R (sqrt R^2):         nan
*Pearson r:            0.1817 (p = 0.00039)
*Folds Pearson r:      0.2317 (p = 0.06593)
*Spearman rho:         0.2299 (p = 0.00001)
*Mean Squared Error:   0.8506
*Mean Absolute Error:  0.6855
*Train_Mean MAE:       0.2585

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1948)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 538)]
  *FOLD R^2: -0.0398 (MSE: 2.9415; MAE: 1.2944; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1303)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 465)]
  *FOLD R^2: 0.0707 (MSE: 3.8385; MAE: 1.4990; mean train mae: 1.5804)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1486)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1522)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1486)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1486), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 527)]
  *FOLD R^2: -0.0491 (MSE: 3.2497; MAE: 1.4215; mean train mae: 1.4211)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1486)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [77]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:25:48
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0304)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 488)]
  *FOLD R^2: -0.0497 (MSE: 0.2893; MAE: 0.4935; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0492)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 265)]
  *FOLD R^2: -0.1606 (MSE: 0.2889; MAE: 0.4793; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0200)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 498)]
  *FOLD R^2: -0.0778 (MSE: 0.5660; MAE: 0.5705; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0497)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 548)]
  *FOLD R^2: -0.0382 (MSE: 0.2622; MAE: 0.4455; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0911)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 469)]
  *FOLD R^2: -0.0650 (MSE: 0.6013; MAE: 0.6230; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0248
*Overall FOLDS R^2:    -0.0783 (+- 0.0194)
*R (sqrt R^2):         nan
*Pearson r:            0.0176 (p = 0.73304)
*Folds Pearson r:      0.1430 (p = 0.24001)
*Spearman rho:         0.0323 (p = 0.53181)
*Mean Squared Error:   0.4009
*Mean Absolute Error:  0.5221
*Train_Mean MAE:       0.0867

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0346)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 510)]
  *FOLD R^2: 0.0664 (MSE: 0.6840; MAE: 0.6343; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0731)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 490)]
  *FOLD R^2: 0.0172 (MSE: 0.4980; MAE: 0.5817; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0337)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 509)]
  *FOLD R^2: 0.0704 (MSE: 0.3857; MAE: 0.4696; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: 0.0307)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 550)]
  *FOLD R^2: -0.0233 (MSE: 0.3317; MAE: 0.4894; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0745)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 228)]
  *FOLD R^2: -0.0003 (MSE: 0.4535; MAE: 0.5443; mean train mae: 0.5726)
*Overall R^2:          0.0435
*Overall FOLDS R^2:    0.0261 (+- 0.0165)
*R (sqrt R^2):         0.2086
*Pearson r:            0.2120 (p = 0.00003)
*Folds Pearson r:      0.2389 (p = 0.09602)
*Spearman rho:         0.2391 (p = 0.00000)
*Mean Squared Error:   0.4708
*Mean Absolute Error:  0.5439
*Train_Mean MAE:       0.1070

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0009)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 246)]
  *FOLD R^2: -0.0100 (MSE: 0.6463; MAE: 0.6050; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0030)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 258)]
  *FOLD R^2: -0.0046 (MSE: 0.4725; MAE: 0.5605; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0085)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 494)]
  *FOLD R^2: -0.0083 (MSE: 0.4840; MAE: 0.5167; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0127)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 239)]
  *FOLD R^2: -0.0203 (MSE: 0.4457; MAE: 0.4946; mean train mae: 0.5168)
Fold 4
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.001) (score: -0.0454)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=1, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 470)]
  *FOLD R^2: -0.0223 (MSE: 0.5750; MAE: 0.6117; mean train mae: 0.6167)
*Overall R^2:          0.0017
*Overall FOLDS R^2:    -0.0131 (+- 0.0031)
*R (sqrt R^2):         0.0412
*Pearson r:            0.0897 (p = 0.08180)
*Folds Pearson r:      0.0767 (p = 0.55147)
*Spearman rho:         0.1056 (p = 0.04045)
*Mean Squared Error:   0.5248
*Mean Absolute Error:  0.5577
*Train_Mean MAE:       0.0968

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0468)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (76, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 641)]
  *FOLD R^2: 0.0376 (MSE: 2.7071; MAE: 1.3247; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0721)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 610)]
  *FOLD R^2: -0.0465 (MSE: 2.4161; MAE: 1.3384; mean train mae: 1.2725)
Fold 2
   (feature group: 0): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0498)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (75, 1290)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1290), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 500)]
  *FOLD R^2: 0.1073 (MSE: 2.1610; MAE: 1.2226; mean train mae: 1.3755)
Fold 3
   (feature group: 0): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1290)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1290)
[COMBINED FEATS: Performing grid search for parameters over training]

In [78]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:26:20
-----
Loading Outcomes and Getting Groups for: {'CELVAL1', 'CEL_Total', 'CELVAL2', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1468)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 583)]
  *FOLD R^2: -0.2913 (MSE: 0.9329; MAE: 0.6862; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0451)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 394)]
  *FOLD R^2: 0.0521 (MSE: 0.7375; MAE: 0.6014; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1437)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 583)]
  *FOLD R^2: -0.5138 (MSE: 0.8384; MAE: 0.7104; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0991)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 571)]
  *FOLD R^2: -0.0926 (MSE: 1.1071; MAE: 0.7644; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1066)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 550)]
  *FOLD R^2: -0.1414 (MSE: 0.4597; MAE: 0.5799; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1683
*Overall FOLDS R^2:    -0.1974 (+- 0.0861)
*R (sqrt R^2):         nan
*Pearson r:            0.0642 (p = 0.22676)
*Folds Pearson r:      0.0943 (p = 0.36244)
*Spearman rho:         0.0942 (p = 0.07595)
*Mean Squared Error:   0.8152
*Mean Absolute Error:  0.6686
*Train_Mean MAE:       0.2927

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0201)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 400)]
  *FOLD R^2: -0.0171 (MSE: 0.9866; MAE: 0.6620; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0370)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 368)]
  *FOLD R^2: 0.0288 (MSE: 0.9112; MAE: 0.7101; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0474)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 374)]
  *FOLD R^2: -0.0310 (MSE: 0.7715; MAE: 0.6256; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0264)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 403)]
  *FOLD R^2: 0.0041 (MSE: 0.9799; MAE: 0.6978; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0518)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 395)]
  *FOLD R^2: 0.0504 (MSE: 0.4257; MAE: 0.4605; mean train mae: 0.4618)
*Overall R^2:          0.0082
*Overall FOLDS R^2:    0.0071 (+- 0.0133)
*R (sqrt R^2):         0.0908
*Pearson r:            0.1039 (p = 0.05014)
*Folds Pearson r:      0.1051 (p = 0.45124)
*Spearman rho:         0.1100 (p = 0.03809)
*Mean Squared Error:   0.8149
*Mean Absolute Error:  0.6312
*Train_Mean MAE:       0.0945

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0679)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 443)]
  *FOLD R^2: -0.0251 (MSE: 0.9911; MAE: 0.7324; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0889)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 582)]
  *FOLD R^2: -0.1733 (MSE: 1.0409; MAE: 0.8016; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1268)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 542)]
  *FOLD R^2: -0.3230 (MSE: 1.0777; MAE: 0.8193; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0454)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 420)]
  *FOLD R^2: 0.0594 (MSE: 1.1651; MAE: 0.8579; mean train mae: 0.8392)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1189)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 580)]
  *FOLD R^2: -0.2449 (MSE: 0.8169; MAE: 0.7127; mean train mae: 0.4251)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1096
*Overall FOLDS R^2:    -0.1414 (+- 0.0628)
*R (sqrt R^2):         nan
*Pearson r:            0.1028 (p = 0.05274)
*Folds Pearson r:      0.1238 (p = 0.29733)
*Spearman rho:         0.1253 (p = 0.01806)
*Mean Squared Error:   1.0185
*Mean Absolute Error:  0.7849
*Train_Mean MAE:       0.3082

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1559)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 513)]
  *FOLD R^2: -0.1280 (MSE: 6.1939; MAE: 1.7553; mean train mae: 1.6135)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1220)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 511)]
  *FOLD R^2: -0.0308 (MSE: 5.5237; MAE: 1.7707; mean train mae: 1.8061)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1484)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1484)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1651)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1484)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1484), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 479)]
  *FOLD R^2: -0.2142 (MSE: 5.2948; MAE: 1.8113; mean train mae: 1.6373)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1484)

In [79]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-06 20:26:52
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0318)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 261)]
  *FOLD R^2: -0.0232 (MSE: 0.1936; MAE: 0.3791; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: -0.0004)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 551)]
  *FOLD R^2: -0.0589 (MSE: 0.3805; MAE: 0.5146; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0779)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 462)]
  *FOLD R^2: -0.0521 (MSE: 0.4972; MAE: 0.5550; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0106)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 469)]
  *FOLD R^2: 0.0327 (MSE: 0.3841; MAE: 0.5112; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0238)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 461)]
  *FOLD R^2: -0.0050 (MSE: 0.2771; MAE: 0.4782; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0021
*Overall FOLDS R^2:    -0.0213 (+- 0.0149)
*R (sqrt R^2):         nan
*Pearson r:            0.0804 (p = 0.12981)
*Folds Pearson r:      0.0899 (p = 0.35771)
*Spearman rho:         0.0983 (p = 0.06404)
*Mean Squared Error:   0.3466
*Mean Absolute Error:  0.4877
*Train_Mean MAE:       0.0786

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0500)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 457)]
  *FOLD R^2: 0.0821 (MSE: 0.5936; MAE: 0.5742; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0802)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 468)]
  *FOLD R^2: 0.1374 (MSE: 0.3774; MAE: 0.4733; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0564)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 466)]
  *FOLD R^2: -0.0156 (MSE: 0.7644; MAE: 0.6652; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0723)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 423)]
  *FOLD R^2: -0.0224 (MSE: 0.5253; MAE: 0.5658; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0543)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 441)]
  *FOLD R^2: 0.0140 (MSE: 0.3575; MAE: 0.5008; mean train mae: 0.5574)
*Overall R^2:          0.0506
*Overall FOLDS R^2:    0.0391 (+- 0.0275)
*R (sqrt R^2):         0.2250
*Pearson r:            0.2265 (p = 0.00002)
*Folds Pearson r:      0.2566 (p = 0.25471)
*Spearman rho:         0.2387 (p = 0.00001)
*Mean Squared Error:   0.5232
*Mean Absolute Error:  0.5556
*Train_Mean MAE:       0.1301

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0344)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 393)]
  *FOLD R^2: 0.0229 (MSE: 0.6501; MAE: 0.5724; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0060)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 414)]
  *FOLD R^2: -0.0630 (MSE: 0.8260; MAE: 0.6200; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0425)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 240)]
  *FOLD R^2: -0.0166 (MSE: 0.8397; MAE: 0.6342; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0824)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 368)]
  *FOLD R^2: -0.2388 (MSE: 0.8134; MAE: 0.6287; mean train mae: 0.5626)
Fold 4
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0447)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 242)]
  *FOLD R^2: -0.0882 (MSE: 0.4222; MAE: 0.4864; mean train mae: 0.4618)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0492
*Overall FOLDS R^2:    -0.0767 (+- 0.0401)
*R (sqrt R^2):         nan
*Pearson r:            -0.0500 (p = 0.34707)
*Folds Pearson r:      -0.0173 (p = 0.48783)
*Spearman rho:         -0.0185 (p = 0.72844)
*Mean Squared Error:   0.7106
*Mean Absolute Error:  0.5884
*Train_Mean MAE:       0.1132

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1282)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 536)]
  *FOLD R^2: 0.0870 (MSE: 2.3450; MAE: 1.2067; mean train mae: 1.2809)
Fold 1
   (feature group: 0): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0818)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (72, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 521)]
  *FOLD R^2: 0.0631 (MSE: 2.7540; MAE: 1.3012; mean train mae: 1.4112)
Fold 2
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1204)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1279)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (71, 1204)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1204), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 562)]
  *FOLD R^2: -0.1245 (MSE: 4.3429; MAE: 1.5966; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1204)
  [Applying StandardScaler to X[0]: StandardScaler()]

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SMale50_cp_w$stratified_male$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:04:06
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CELVAL1', 'CELVAL2', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1001)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 587)]
  *FOLD R^2: -0.1177 (MSE: 0.3197; MAE: 0.4202; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1586)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 589)]
  *FOLD R^2: 0.0066 (MSE: 0.6711; MAE: 0.6159; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0845)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 418)]
  *FOLD R^2: -0.0673 (MSE: 0.3480; MAE: 0.4564; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0733)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 606)]
  *FOLD R^2: -0.1644 (MSE: 0.7195; MAE: 0.6119; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1883)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 575)]
  *FOLD R^2: 0.0083 (MSE: 0.6305; MAE: 0.6047; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0436
*Overall FOLDS R^2:    -0.0669 (+- 0.0304)
*R (sqrt R^2):         nan
*Pearson r:            0.1675 (p = 0.00110)
*Folds Pearson r:      0.1754 (p = 0.27030)
*Spearman rho:         0.2041 (p = 0.00007)
*Mean Squared Error:   0.5367
*Mean Absolute Error:  0.5413
*Train_Mean MAE:       0.2385

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0399)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 504)]
  *FOLD R^2: 0.0099 (MSE: 0.5814; MAE: 0.5376; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0264)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 476)]
  *FOLD R^2: 0.0610 (MSE: 0.5702; MAE: 0.5974; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0392)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 481)]
  *FOLD R^2: 0.0120 (MSE: 0.6384; MAE: 0.6157; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0135)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 508)]
  *FOLD R^2: 0.0176 (MSE: 0.8041; MAE: 0.6394; mean train mae: 0.6671)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0584)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 241)]
  *FOLD R^2: -0.0132 (MSE: 0.8185; MAE: 0.6612; mean train mae: 0.6564)
*Overall R^2:          0.0223
*Overall FOLDS R^2:    0.0175 (+- 0.0108)
*R (sqrt R^2):         0.1494
*Pearson r:            0.1504 (p = 0.00341)
*Folds Pearson r:      0.1616 (p = 0.25507)
*Spearman rho:         0.1307 (p = 0.01110)
*Mean Squared Error:   0.6821
*Mean Absolute Error:  0.6101
*Train_Mean MAE:       0.0886

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1560)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 572)]
  *FOLD R^2: -0.0351 (MSE: 0.7054; MAE: 0.6395; mean train mae: 0.5071)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0804)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 408)]
  *FOLD R^2: 0.0696 (MSE: 0.8544; MAE: 0.6721; mean train mae: 0.6321)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1640)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1507)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1640)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1640), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 593)]
  *FOLD R^2: -0.4501 (MSE: 0.8282; MAE: 0.7185; mean train mae: 0.4868)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SFemale50_cp_w$stratified_female$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:04:45
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0447)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 260)]
  *FOLD R^2: -0.0635 (MSE: 0.2931; MAE: 0.4612; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0624)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 255)]
  *FOLD R^2: -0.1485 (MSE: 0.2859; MAE: 0.4771; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0337)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 255)]
  *FOLD R^2: -0.0035 (MSE: 0.5270; MAE: 0.5217; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0854)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 241)]
  *FOLD R^2: -0.0556 (MSE: 0.2666; MAE: 0.4349; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1459)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 692)]
  *FOLD R^2: -0.1036 (MSE: 0.6231; MAE: 0.6014; mean train mae: 0.6181)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0187
*Overall FOLDS R^2:    -0.0750 (+- 0.0218)
*R (sqrt R^2):         nan
*Pearson r:            0.1145 (p = 0.02622)
*Folds Pearson r:      0.1898 (p = 0.28386)
*Spearman rho:         0.1390 (p = 0.00689)
*Mean Squared Error:   0.3985
*Mean Absolute Error:  0.4990
*Train_Mean MAE:       0.1405

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0699)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 239)]
  *FOLD R^2: 0.0871 (MSE: 0.6688; MAE: 0.6234; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.1037)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 241)]
  *FOLD R^2: 0.0461 (MSE: 0.4833; MAE: 0.5627; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1049)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 711)]
  *FOLD R^2: -0.0582 (MSE: 0.4391; MAE: 0.4756; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0745)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 264)]
  *FOLD R^2: -0.0117 (MSE: 0.3279; MAE: 0.4571; mean train mae: 0.5041)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.1129)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 244)]
  *FOLD R^2: 0.0259 (MSE: 0.4416; MAE: 0.5335; mean train mae: 0.5726)
*Overall R^2:          0.0404
*Overall FOLDS R^2:    0.0179 (+- 0.0222)
*R (sqrt R^2):         0.2011
*Pearson r:            0.2343 (p = 0.00000)
*Folds Pearson r:      0.2528 (p = 0.03963)
*Spearman rho:         0.2823 (p = 0.00000)
*Mean Squared Error:   0.4723
*Mean Absolute Error:  0.5305
*Train_Mean MAE:       0.1881

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0246)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (76, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 238)]
  *FOLD R^2: -0.0061 (MSE: 0.6438; MAE: 0.6036; mean train mae: 0.6234)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: -0.0037)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 247)]
  *FOLD R^2: 0.0158 (MSE: 0.4630; MAE: 0.5527; mean train mae: 0.5711)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 1444)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0130)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (75, 1444)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1444), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 514)]
  *FOLD R^2: -0.0059 (MSE: 0.4828; MAE: 0.5193; mean train mae: 0.5485)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)

#### ExtraTrees Predictions with OpenSmile Features

Extra Trees Regressor model predictions using OpenSmile acoustic features

In [3]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Swhite50_cp_w$stratified_white$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:05:21
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL3', 'CELVAL1', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1445)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 573)]
  *FOLD R^2: -0.2370 (MSE: 0.8937; MAE: 0.6709; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0617)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 370)]
  *FOLD R^2: 0.0321 (MSE: 0.7530; MAE: 0.6109; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1545)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 578)]
  *FOLD R^2: -0.6289 (MSE: 0.9021; MAE: 0.7369; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0584)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 385)]
  *FOLD R^2: -0.0428 (MSE: 1.0566; MAE: 0.7014; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1473)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 562)]
  *FOLD R^2: -0.1462 (MSE: 0.4616; MAE: 0.5679; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1661
*Overall FOLDS R^2:    -0.2045 (+- 0.1033)
*R (sqrt R^2):         nan
*Pearson r:            0.0404 (p = 0.44744)
*Folds Pearson r:      0.0463 (p = 0.18847)
*Spearman rho:         0.0435 (p = 0.41315)
*Mean Squared Error:   0.8137
*Mean Absolute Error:  0.6578
*Train_Mean MAE:       0.2608

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0688)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 414)]
  *FOLD R^2: -0.0081 (MSE: 0.9779; MAE: 0.6612; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0602)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 380)]
  *FOLD R^2: 0.0286 (MSE: 0.9115; MAE: 0.7135; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0642)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 408)]
  *FOLD R^2: -0.0222 (MSE: 0.7649; MAE: 0.6253; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0550)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 388)]
  *FOLD R^2: -0.0088 (MSE: 0.9926; MAE: 0.6995; mean train mae: 0.7197)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0640)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 402)]
  *FOLD R^2: 0.0525 (MSE: 0.4248; MAE: 0.4594; mean train mae: 0.4618)
*Overall R^2:          0.0091
*Overall FOLDS R^2:    0.0084 (+- 0.0124)
*R (sqrt R^2):         0.0953
*Pearson r:            0.1081 (p = 0.04150)
*Folds Pearson r:      0.1151 (p = 0.47919)
*Spearman rho:         0.1216 (p = 0.02176)
*Mean Squared Error:   0.8142
*Mean Absolute Error:  0.6318
*Train_Mean MAE:       0.0931

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0924)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 435)]
  *FOLD R^2: -0.0106 (MSE: 0.9771; MAE: 0.7243; mean train mae: 0.5868)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1117)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 573)]
  *FOLD R^2: -0.2270 (MSE: 1.0885; MAE: 0.8426; mean train mae: 0.6508)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1638)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1090)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1638)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1638), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 580)]
  *FOLD R^2: -0.5181 (MSE: 1.2366; MAE: 0.8794; mean train mae: 0.6565)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)

In [4]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Sblack50_cp_w$stratified_black$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:05:57
-----
Loading Outcomes and Getting Groups for: {'CELVAL3', 'CEL_Total', 'CELVAL1', 'CELVAL2'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0164)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 260)]
  *FOLD R^2: -0.0364 (MSE: 0.1961; MAE: 0.3789; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: -0.0050)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 525)]
  *FOLD R^2: -0.0628 (MSE: 0.3820; MAE: 0.5165; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0701)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 633)]
  *FOLD R^2: -0.2070 (MSE: 0.5703; MAE: 0.5789; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0060)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 455)]
  *FOLD R^2: 0.0214 (MSE: 0.3887; MAE: 0.5141; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: -0.0071)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 467)]
  *FOLD R^2: -0.0163 (MSE: 0.2802; MAE: 0.4800; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0510
*Overall FOLDS R^2:    -0.0602 (+- 0.0350)
*R (sqrt R^2):         nan
*Pearson r:            0.0582 (p = 0.27379)
*Folds Pearson r:      0.0976 (p = 0.51173)
*Spearman rho:         0.0812 (p = 0.12626)
*Mean Squared Error:   0.3635
*Mean Absolute Error:  0.4937
*Train_Mean MAE:       0.1155

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0771)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 447)]
  *FOLD R^2: 0.0635 (MSE: 0.6057; MAE: 0.5830; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0864)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 483)]
  *FOLD R^2: 0.1186 (MSE: 0.3856; MAE: 0.4841; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0972)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 440)]
  *FOLD R^2: -0.0041 (MSE: 0.7557; MAE: 0.6623; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.1007)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 429)]
  *FOLD R^2: -0.0202 (MSE: 0.5242; MAE: 0.5698; mean train mae: 0.5856)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0757)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 465)]
  *FOLD R^2: 0.0034 (MSE: 0.3614; MAE: 0.5061; mean train mae: 0.5574)
*Overall R^2:          0.0454
*Overall FOLDS R^2:    0.0322 (+- 0.0231)
*R (sqrt R^2):         0.2130
*Pearson r:            0.2163 (p = 0.00004)
*Folds Pearson r:      0.2439 (p = 0.23136)
*Spearman rho:         0.2226 (p = 0.00002)
*Mean Squared Error:   0.5261
*Mean Absolute Error:  0.5609
*Train_Mean MAE:       0.1190

= CELVAL3 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0261)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 248)]
  *FOLD R^2: 0.0215 (MSE: 0.6511; MAE: 0.5805; mean train mae: 0.5961)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0286)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (72, 1358)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 254)]
  *FOLD R^2: -0.0233 (MSE: 0.7951; MAE: 0.6209; mean train mae: 0.6246)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 1358)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0438)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] combined X shape: (71, 1358)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 1358), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 242)]
  *FOLD R^2: -0.0279 (MSE: 0.8491; MAE: 0.6402; mean train mae: 0.6368)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]

In [5]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SMale50_cp_w$stratified_male$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:06:28
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CEL_Total', 'CELVAL3', 'CELVAL1'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1366)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 622)]
  *FOLD R^2: -0.1185 (MSE: 0.3199; MAE: 0.4272; mean train mae: 0.4050)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0936)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 627)]
  *FOLD R^2: 0.0425 (MSE: 0.6469; MAE: 0.6285; mean train mae: 0.6084)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0752)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 633)]
  *FOLD R^2: 0.0597 (MSE: 0.3065; MAE: 0.4387; mean train mae: 0.4759)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1203)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 611)]
  *FOLD R^2: -0.1017 (MSE: 0.6808; MAE: 0.5898; mean train mae: 0.5701)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1242)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 605)]
  *FOLD R^2: -0.0194 (MSE: 0.6481; MAE: 0.5765; mean train mae: 0.5997)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0099
*Overall FOLDS R^2:    -0.0275 (+- 0.0325)
*R (sqrt R^2):         nan
*Pearson r:            0.1978 (p = 0.00011)
*Folds Pearson r:      0.2061 (p = 0.20639)
*Spearman rho:         0.2223 (p = 0.00001)
*Mean Squared Error:   0.5193
*Mean Absolute Error:  0.5316
*Train_Mean MAE:       0.2386

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0524)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 631)]
  *FOLD R^2: -0.0560 (MSE: 0.6202; MAE: 0.5732; mean train mae: 0.5524)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0663)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2790)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 645)]
  *FOLD R^2: 0.0321 (MSE: 0.5878; MAE: 0.5931; mean train mae: 0.6141)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0249)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2790)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2790), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 291)]
  *FOLD R^2: 0.0168 (MSE: 0.6352; MAE: 0.6199; mean train mae: 0.6373)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1486)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2790)
[COMBINED FEATS: Performing grid search for parameters over training]

In [6]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_SFemale50_cp_w$stratified_female$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:07:46
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CELVAL3', 'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 377 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0087)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 308)]
  *FOLD R^2: -0.0817 (MSE: 0.2981; MAE: 0.4751; mean train mae: 0.5083)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0997)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 360)]
  *FOLD R^2: -0.1328 (MSE: 0.2819; MAE: 0.4773; mean train mae: 0.4879)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0129)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 347)]
  *FOLD R^2: -0.0002 (MSE: 0.5252; MAE: 0.5122; mean train mae: 0.5882)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0331)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 314)]
  *FOLD R^2: -0.0466 (MSE: 0.2644; MAE: 0.4376; mean train mae: 0.4657)
Fold 4
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0954)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 345)]
  *FOLD R^2: -0.0057 (MSE: 0.5678; MAE: 0.6082; mean train mae: 0.6181)
*Overall R^2:          0.0109
*Overall FOLDS R^2:    -0.0534 (+- 0.0221)
*R (sqrt R^2):         0.1043
*Pearson r:            0.1557 (p = 0.00243)
*Folds Pearson r:      0.1707 (p = 0.25110)
*Spearman rho:         0.1764 (p = 0.00058)
*Mean Squared Error:   0.3869
*Mean Absolute Error:  0.5018
*Train_Mean MAE:       0.1361

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.1204)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (76, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 315)]
  *FOLD R^2: 0.0635 (MSE: 0.6861; MAE: 0.6372; mean train mae: 0.6672)
Fold 1
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.1440)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 330)]
  *FOLD R^2: 0.0150 (MSE: 0.4991; MAE: 0.5660; mean train mae: 0.6091)
Fold 2
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (302, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (302, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (302, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (302, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (302, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (302, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (302, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1295)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (75, 2594)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2594), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 653)]
  *FOLD R^2: 0.0559 (MSE: 0.3917; MAE: 0.4308; mean train mae: 0.5364)
Fold 3
   (feature group: 0): [Initial size: 377]
   (feature group: 1): [Initial size: 377]
   (feature group: 2): [Initial size: 377]
   (feature group: 3): [Initial size: 377]
   (feature group: 4): [Initial size: 377]
   (feature group: 5): [Initial size: 377]
   (feature group: 6): [Initial size: 377]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (301, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (301, 1290)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (301, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (301, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (301, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (301, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (301, 2594)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.1208)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Swhite50_cp_w$stratified_white$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:09:00
-----
Loading Outcomes and Getting Groups for: {'CELVAL2', 'CELVAL1', 'CEL_Total', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1215)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 572)]
  *FOLD R^2: -0.0619 (MSE: 0.7672; MAE: 0.6112; mean train mae: 0.5677)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0744)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 601)]
  *FOLD R^2: 0.0434 (MSE: 0.7443; MAE: 0.6849; mean train mae: 0.6441)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1741)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 583)]
  *FOLD R^2: -0.3411 (MSE: 0.7427; MAE: 0.6552; mean train mae: 0.5501)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0695)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 561)]
  *FOLD R^2: -0.0520 (MSE: 1.0660; MAE: 0.7535; mean train mae: 0.7279)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1416)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 604)]
  *FOLD R^2: -0.1200 (MSE: 0.4510; MAE: 0.5368; mean train mae: 0.4148)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0809
*Overall FOLDS R^2:    -0.1063 (+- 0.0575)
*R (sqrt R^2):         nan
*Pearson r:            0.1325 (p = 0.01236)
*Folds Pearson r:      0.1235 (p = 0.20222)
*Spearman rho:         0.1409 (p = 0.00774)
*Mean Squared Error:   0.7542
*Mean Absolute Error:  0.6484
*Train_Mean MAE:       0.2938

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0704)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 291)]
  *FOLD R^2: -0.0873 (MSE: 1.0547; MAE: 0.7103; mean train mae: 0.6699)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0912)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2788)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 282)]
  *FOLD R^2: 0.0210 (MSE: 0.9186; MAE: 0.7238; mean train mae: 0.7328)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0458)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2788)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2788), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 636)]
  *FOLD R^2: -0.1139 (MSE: 0.8335; MAE: 0.7004; mean train mae: 0.6246)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2788)
[COMBINED FEATS: Performing grid search for parameters over training]

In [8]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_Sblack50_cp_w$stratified_black$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total CELVAL1 CELVAL2 CELVAL3 \
    --nfold_test_regression --model svr --fold_column fold

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-13 12:10:09
-----
Loading Outcomes and Getting Groups for: {'CEL_Total', 'CELVAL2', 'CELVAL1', 'CELVAL3'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 356 (5 Folds)]


|COMBO: ()|
===========

= CELVAL1 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0110)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 330)]
  *FOLD R^2: -0.1982 (MSE: 0.2268; MAE: 0.4258; mean train mae: 0.4178)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0184)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 640)]
  *FOLD R^2: -0.2353 (MSE: 0.4439; MAE: 0.5550; mean train mae: 0.5188)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0989)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 625)]
  *FOLD R^2: -0.0329 (MSE: 0.4881; MAE: 0.5346; mean train mae: 0.5508)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: 0.0025)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 549)]
  *FOLD R^2: 0.0100 (MSE: 0.3932; MAE: 0.5189; mean train mae: 0.5213)
Fold 4
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.001) (score: -0.0085)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.001)
settings:  [('degree', 3), ('gamma', 0.001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.001), ('fit_status_', 0), ('n_iter_', 523)]
  *FOLD R^2: -0.0530 (MSE: 0.2903; MAE: 0.4953; mean train mae: 0.4989)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0659
*Overall FOLDS R^2:    -0.1019 (+- 0.0432)
*R (sqrt R^2):         nan
*Pearson r:            0.0028 (p = 0.95744)
*Folds Pearson r:      0.0355 (p = 0.44555)
*Spearman rho:         -0.0174 (p = 0.74385)
*Mean Squared Error:   0.3687
*Mean Absolute Error:  0.5060
*Train_Mean MAE:       0.1114

= CELVAL2 (w/ lang.)=
---------------------
Fold 0
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.1039)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 656)]
  *FOLD R^2: 0.0313 (MSE: 0.6265; MAE: 0.6065; mean train mae: 0.6116)
Fold 1
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (284, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (284, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=10, gamma=0.0001) (score: 0.0689)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (72, 2508)
[PREDICT] regressor: SVR(C=10, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 10), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 637)]
  *FOLD R^2: -0.0802 (MSE: 0.4726; MAE: 0.5385; mean train mae: 0.5499)
Fold 2
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0735)

[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler()
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler()
[PREDICT] combined X shape: (71, 2508)
[PREDICT] regressor: SVR(C=1, gamma=0.0001)
settings:  [('degree', 3), ('gamma', 0.0001), ('coef0', 0.0), ('tol', 0.001), ('C', 1), ('nu', 0.0), ('epsilon', 0.1), ('shrinking', True), ('probability', False), ('cache_size', 200), ('class_weight', None), ('verbose', False), ('max_iter', -1), ('random_state', None), ('_sparse', False), ('n_features_in_', 2508), ('_gamma', 0.0001), ('fit_status_', 0), ('n_iter_', 297)]
  *FOLD R^2: 0.0284 (MSE: 0.7313; MAE: 0.6440; mean train mae: 0.6818)
Fold 3
   (feature group: 0): [Initial size: 356]
   (feature group: 1): [Initial size: 356]
   (feature group: 2): [Initial size: 356]
   (feature group: 3): [Initial size: 356]
   (feature group: 4): [Initial size: 356]
   (feature group: 5): [Initial size: 356]
   (feature group: 6): [Initial size: 356]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler()]
 X[1]: (N, features): (285, 51)
  [Applying StandardScaler to X[1]: StandardScaler()]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler()]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler()]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler()]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler()]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (285, 2508)
[COMBINED FEATS: Performing grid search for parameters over training]
[COMBINED FEATS] best estimator: SVR(C=1, gamma=0.0001) (score: 0.0815)


### Extratrees model

In [16]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 17:39:03
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('oob_score', False), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('bootstrap', False), ('n_features_', 38), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42)]
  *FOLD R^2: 0.0615 (MSE: 4.3316; MAE: 1.6597; mean train mae: 1.7631)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('oob_score', False), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('bootstrap', False), ('n_features_', 38), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42)]
  *FOLD R^2: -0.0258 (MSE: 5.1012; MAE: 1.6655; mean train mae: 1.6116)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('oob_score', False), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('bootstrap', False), ('n_features_', 38), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42)]
  *FOLD R^2: 0.0814 (MSE: 3.3892; MAE: 1.4574; mean train mae: 1.4249)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('oob_score', False), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('bootstrap', False), ('n_features_', 38), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42)]
  *FOLD R^2: -0.1482 (MSE: 3.8603; MAE: 1.5557; mean train mae: 1.3929)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('oob_score', False), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('bootstrap', False), ('n_features_', 38), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42)]
  *FOLD R^2: -0.2084 (MSE: 4.0595; MAE: 1.5821; mean train mae: 1.4173)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0135
*Overall FOLDS R^2:    -0.0479 (+- 0.0510)
*R (sqrt R^2):         nan
*Pearson r:            0.1936 (p = 0.00015)
*Folds Pearson r:      0.2026 (p = 0.26601)
*Spearman rho:         0.2029 (p = 0.00007)
*Mean Squared Error:   4.1486
*Mean Absolute Error:  1.5841
*Train_Mean MAE:       0.6506

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': nan,
                        'R2': -0.013467972007035423,
                        'R2_folds': -0.047891271358596096,
                        'mae': 1.5841007036059804,
                        'mae_folds': 1.5840953801169591,
                        'mse': 4.1485998625769565,
                        'mse_folds': 4.1483653224171544,
                        'num_features': 38,
                        'r': 0.19359451464218286,
                        'r_folds': 0.20262710753933738,
                        'r_p': 0.00014921547095793239,
                        'r_p_folds': 0.2660142838407602,
                        'rho': 0.20294208728867605,
                        'rho_folds': 0.21877537066653169,
                        'rho_p': 6.9119862564793639e-05,
                        'rho_p_folds': 0.16984571216345823,
                        'se_R2_folds': 0.050994431992281278,
                        'se_mae_folds': 0.034172971222978153,
                        'se_mse_folds': 0.25365587488802094,
                        'se_r_folds': 0.056626042810910243,
                        'se_r_p_folds': 0.14824110596712259,
                        'se_rho_folds': 0.042153795557750777,
                        'se_rho_p_folds': 0.1281982332544867,
                        'se_train_mean_mae_folds': 0.064260640824542761,
                        'test_size': 75,
                        'train_mean_mae': 0.65063802001749727,
                        'train_mean_mae_folds': 1.5219657807886053,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$librosa_n$merged_data$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 9.84 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 05:34:05
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('n_features_', 38), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('oob_score', False), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('random_state', 42), ('max_depth', None), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_impurity_split', 1e-07), ('verbose', 0)]
  *FOLD R^2: -0.2945 (MSE: 3.6414; MAE: 1.5253; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('n_features_', 38), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('oob_score', False), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('random_state', 42), ('max_depth', None), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_impurity_split', 1e-07), ('verbose', 0)]
  *FOLD R^2: -0.1557 (MSE: 1.4766; MAE: 1.0075; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('n_features_', 38), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('oob_score', False), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('random_state', 42), ('max_depth', None), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_impurity_split', 1e-07), ('verbose', 0)]
  *FOLD R^2: -0.1261 (MSE: 3.8091; MAE: 1.4480; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('n_features_', 38), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('oob_score', False), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('random_state', 42), ('max_depth', None), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_impurity_split', 1e-07), ('verbose', 0)]
  *FOLD R^2: -0.0691 (MSE: 2.5878; MAE: 1.3296; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('n_features_', 38), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('oob_score', False), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('random_state', 42), ('max_depth', None), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_impurity_split', 1e-07), ('verbose', 0)]
  *FOLD R^2: -0.0170 (MSE: 2.3478; MAE: 1.2558; mean train mae: 1.2725)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1040
*Overall FOLDS R^2:    -0.1325 (+- 0.0420)
*R (sqrt R^2):         nan
*Pearson r:            0.0796 (p = 0.12307)
*Folds Pearson r:      0.1333 (p = 0.28261)
*Spearman rho:         0.0682 (p = 0.18623)
*Mean Squared Error:   2.7714
*Mean Absolute Error:  1.3130
*Train_Mean MAE:       0.4687

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.10398953989673765,
                        'R2_folds': -0.13246763507736786,
                        'mae': 1.3129818744473918,
                        'mae_folds': 1.3132304678362572,
                        'mse': 2.7714037522104329,
                        'mse_folds': 2.772536639863548,
                        'num_features': 38,
                        'r': 0.079556302236189452,
                        'r_folds': 0.13327463369680209,
                        'r_p': 0.12306886795582335,
                        'r_p_folds': 0.28260639756067307,
                        'rho': 0.068223950151980253,
                        'rho_folds': 0.10449219728137141,
                        'rho_p': 0.18623103725822376,
                        'rho_p_folds': 0.2351406703075789,
                        'se_R2_folds': 0.042037791541679644,
                        'se_mae_folds': 0.080041709806795008,
                        'se_mse_folds': 0.38591177834167217,
                        'se_r_folds': 0.078061737163112141,
                        'se_r_p_folds': 0.16242028587378959,
                        'se_rho_folds': 0.077642161493584314,
                        'se_rho_p_folds': 0.10468154772641085,
                        'se_train_mean_mae_folds': 0.072108818846987638,
                        'test_size': 75,
                        'train_mean_mae': 0.46871091871937931,
                        'train_mean_mae_folds': 1.2705838568390793,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$librosa_n$merged_data$message_id
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.08 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 10:56:58
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('warm_start', False), ('min_weight_fraction_leaf', 0.0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('class_weight', None), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('max_leaf_nodes', None), ('n_outputs_', 1), ('n_estimators', 1200), ('max_depth', None), ('random_state', 42), ('n_features_', 38)]
  *FOLD R^2: 0.0040 (MSE: 2.9278; MAE: 1.3166; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('warm_start', False), ('min_weight_fraction_leaf', 0.0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('class_weight', None), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('max_leaf_nodes', None), ('n_outputs_', 1), ('n_estimators', 1200), ('max_depth', None), ('random_state', 42), ('n_features_', 38)]
  *FOLD R^2: -0.0264 (MSE: 1.9359; MAE: 1.1468; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('warm_start', False), ('min_weight_fraction_leaf', 0.0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('class_weight', None), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('max_leaf_nodes', None), ('n_outputs_', 1), ('n_estimators', 1200), ('max_depth', None), ('random_state', 42), ('n_features_', 38)]
  *FOLD R^2: 0.0270 (MSE: 3.7576; MAE: 1.4289; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('warm_start', False), ('min_weight_fraction_leaf', 0.0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('class_weight', None), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('max_leaf_nodes', None), ('n_outputs_', 1), ('n_estimators', 1200), ('max_depth', None), ('random_state', 42), ('n_features_', 38)]
  *FOLD R^2: 0.1223 (MSE: 2.2543; MAE: 1.1790; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('warm_start', False), ('min_weight_fraction_leaf', 0.0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('class_weight', None), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('max_leaf_nodes', None), ('n_outputs_', 1), ('n_estimators', 1200), ('max_depth', None), ('random_state', 42), ('n_features_', 38)]
  *FOLD R^2: -0.0413 (MSE: 2.9085; MAE: 1.3153; mean train mae: 1.3612)
*Overall R^2:          0.0457
*Overall FOLDS R^2:    0.0171 (+- 0.0258)
*R (sqrt R^2):         0.2138
*Pearson r:            0.2359 (p = 0.00001)
*Folds Pearson r:      0.2405 (p = 0.08998)
*Spearman rho:         0.2548 (p = 0.00000)
*Mean Squared Error:   2.7573
*Mean Absolute Error:  1.2774
*Train_Mean MAE:       0.4567

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.21379136333168486,
                        'R2': 0.045706747035220485,
                        'R2_folds': 0.01713136504124051,
                        'mae': 1.2774438202247191,
                        'mae_folds': 1.2773335289514864,
                        'mse': 2.7573123478464421,
                        'mse_folds': 2.7568319749826116,
                        'num_features': 38,
                        'r': 0.23589282242336168,
                        'r_folds': 0.24045810376589899,
                        'r_p': 6.8334774175773347e-06,
                        'r_p_folds': 0.089983853544153752,
                        'rho': 0.25476003115284157,
                        'rho_folds': 0.25590640332610259,
                        'rho_p': 1.1131971141392957e-06,
                        'rho_p_folds': 0.075653841893733115,
                        'se_R2_folds': 0.025807109749260062,
                        'se_mae_folds': 0.04590007711984493,
                        'se_mse_folds': 0.28144754523331966,
                        'se_r_folds': 0.035693862181329153,
                        'se_r_p_folds': 0.038939031764451702,
                        'se_rho_folds': 0.037839268483486357,
                        'se_rho_p_folds': 0.038381954013665412,
                        'se_train_mean_mae_folds': 0.034262972911295757,
                        'test_size': 71,
                        'train_mean_mae': 0.45674877961536842,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$librosa_n$merged_data$message_id
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.30 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

#### ExtraTrees Predictions with Whisper Features

Extra Trees Regressor using Whisper speech embeddings

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 10:57:58
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('bootstrap', False), ('min_samples_split', 2), ('random_state', 42), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_features_', 38), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('max_depth', None), ('n_estimators', 1200), ('oob_score', False)]
  *FOLD R^2: 0.0908 (MSE: 3.9649; MAE: 1.5759; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('bootstrap', False), ('min_samples_split', 2), ('random_state', 42), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_features_', 38), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('max_depth', None), ('n_estimators', 1200), ('oob_score', False)]
  *FOLD R^2: 0.0848 (MSE: 7.2526; MAE: 2.0714; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('bootstrap', False), ('min_samples_split', 2), ('random_state', 42), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_features_', 38), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('max_depth', None), ('n_estimators', 1200), ('oob_score', False)]
  *FOLD R^2: -0.3413 (MSE: 3.6240; MAE: 1.4774; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('bootstrap', False), ('min_samples_split', 2), ('random_state', 42), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_features_', 38), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('max_depth', None), ('n_estimators', 1200), ('oob_score', False)]
  *FOLD R^2: 0.1351 (MSE: 4.6350; MAE: 1.7676; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 38)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('bootstrap', False), ('min_samples_split', 2), ('random_state', 42), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_features_', 38), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('max_depth', None), ('n_estimators', 1200), ('oob_score', False)]
  *FOLD R^2: -0.0670 (MSE: 5.8591; MAE: 1.7777; mean train mae: 1.6135)
*Overall R^2:          0.0229
*Overall FOLDS R^2:    -0.0195 (+- 0.0782)
*R (sqrt R^2):         0.1513
*Pearson r:            0.2363 (p = 0.00001)
*Folds Pearson r:      0.2230 (p = 0.24682)
*Spearman rho:         0.2740 (p = 0.00000)
*Mean Squared Error:   5.0640
*Mean Absolute Error:  1.7336
*Train_Mean MAE:       0.7429

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.15130128338801677,
                        'R2': 0.022892078354860956,
                        'R2_folds': -0.019536223332820457,
                        'mae': 1.7335557116104867,
                        'mae_folds': 1.7339999021909236,
                        'mse': 5.0640058227996256,
                        'mse_folds': 5.0671019351254127,
                        'num_features': 38,
                        'r': 0.23626866331379315,
                        'r_folds': 0.22304644164100673,
                        'r_p': 6.6002635943140637e-06,
                        'r_p_folds': 0.24681871116460624,
                        'rho': 0.2739573506856296,
                        'rho_folds': 0.26555139191140043,
                        'rho_p': 1.5074487047919372e-07,
                        'rho_p_folds': 0.19916351420545814,
                        'se_R2_folds': 0.078165304893503179,
                        'se_mae_folds': 0.091151803427730327,
                        'se_mse_folds': 0.59625171119859866,
                        'se_r_folds': 0.071775983907546012,
                        'se_r_p_folds': 0.14502270584610352,
                        'se_rho_folds': 0.06319804807669184,
                        'se_rho_p_folds': 0.16141264655878496,
                        'se_train_mean_mae_folds': 0.13773807905205238,
                        'test_size': 71,
                        'train_mean_mae': 0.74287124416109074,
                        'train_mean_mae_folds': 1.6588806523350628,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$librosa_n$merged_data$message_id
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.18 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [3]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 10:58:52
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('random_state', 42), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('bootstrap', False), ('oob_score', False), ('n_features_', 88), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('max_depth', None), ('max_leaf_nodes', None), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('class_weight', None)]
  *FOLD R^2: -0.0702 (MSE: 4.6673; MAE: 1.7467; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('random_state', 42), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('bootstrap', False), ('oob_score', False), ('n_features_', 88), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('max_depth', None), ('max_leaf_nodes', None), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('class_weight', None)]
  *FOLD R^2: 0.0168 (MSE: 7.7909; MAE: 2.2239; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('random_state', 42), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('bootstrap', False), ('oob_score', False), ('n_features_', 88), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('max_depth', None), ('max_leaf_nodes', None), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('class_weight', None)]
  *FOLD R^2: -0.5260 (MSE: 4.1231; MAE: 1.5848; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('random_state', 42), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('bootstrap', False), ('oob_score', False), ('n_features_', 88), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('max_depth', None), ('max_leaf_nodes', None), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('class_weight', None)]
  *FOLD R^2: 0.2867 (MSE: 3.8226; MAE: 1.5828; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('random_state', 42), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('bootstrap', False), ('oob_score', False), ('n_features_', 88), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('max_depth', None), ('max_leaf_nodes', None), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('class_weight', None)]
  *FOLD R^2: 0.0553 (MSE: 5.1874; MAE: 1.6952; mean train mae: 1.6135)
*Overall R^2:          0.0127
*Overall FOLDS R^2:    -0.0475 (+- 0.1193)
*R (sqrt R^2):         0.1126
*Pearson r:            0.2954 (p = 0.00000)
*Folds Pearson r:      0.3025 (p = 0.07768)
*Spearman rho:         0.3359 (p = 0.00000)
*Mean Squared Error:   5.1170
*Mean Absolute Error:  1.7666
*Train_Mean MAE:       0.9619

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.1125649207560557,
                        'R2': 0.0126708613848171,
                        'R2_folds': -0.047497473262167487,
                        'mae': 1.7666268726591761,
                        'mae_folds': 1.7666829681794471,
                        'mse': 5.1169787862827718,
                        'mse_folds': 5.1182455796817941,
                        'num_features': 88,
                        'r': 0.29542518663760825,
                        'r_folds': 0.30251645346688366,
                        'r_p': 1.3329949823843792e-08,
                        'r_p_folds': 0.077676489357964285,
                        'rho': 0.33591663013073264,
                        'rho_folds': 0.33329972299180183,
                        'rho_p': 7.7291697029795824e-11,
                        'rho_p_folds': 0.11228278645835958,
                        'se_R2_folds': 0.1193129754399669,
                        'se_mae_folds': 0.10610467722734275,
                        'se_mse_folds': 0.63309388307676939,
                        'se_r_folds': 0.063799188486786299,
                        'se_r_p_folds': 0.047251073576911579,
                        'se_rho_folds': 0.072294959332119227,
                        'se_rho_p_folds': 0.094234172145341716,
                        'se_train_mean_mae_folds': 0.13773807905205249,
                        'test_size': 71,
                        'train_mean_mae': 0.96194727622774889,
                        'train_mean_mae_folds': 1.658880652335063,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$opensmile_n$merged_data$message_id
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.23 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [4]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:00:24
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('oob_score', False), ('max_leaf_nodes', None), ('n_features_', 88), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_estimators', 1200), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('n_jobs', 12), ('bootstrap', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('warm_start', False)]
  *FOLD R^2: -0.0036 (MSE: 2.9501; MAE: 1.3232; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('oob_score', False), ('max_leaf_nodes', None), ('n_features_', 88), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_estimators', 1200), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('n_jobs', 12), ('bootstrap', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('warm_start', False)]
  *FOLD R^2: -0.0633 (MSE: 2.0054; MAE: 1.1447; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('oob_score', False), ('max_leaf_nodes', None), ('n_features_', 88), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_estimators', 1200), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('n_jobs', 12), ('bootstrap', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('warm_start', False)]
  *FOLD R^2: 0.0483 (MSE: 3.6753; MAE: 1.4282; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('oob_score', False), ('max_leaf_nodes', None), ('n_features_', 88), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_estimators', 1200), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('n_jobs', 12), ('bootstrap', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('warm_start', False)]
  *FOLD R^2: 0.2018 (MSE: 2.0502; MAE: 1.1273; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('oob_score', False), ('max_leaf_nodes', None), ('n_features_', 88), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_estimators', 1200), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('n_jobs', 12), ('bootstrap', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('warm_start', False)]
  *FOLD R^2: -0.0970 (MSE: 3.0639; MAE: 1.3651; mean train mae: 1.3612)
*Overall R^2:          0.0484
*Overall FOLDS R^2:    0.0173 (+- 0.0469)
*R (sqrt R^2):         0.2200
*Pearson r:            0.2454 (p = 0.00000)
*Folds Pearson r:      0.2650 (p = 0.12619)
*Spearman rho:         0.2786 (p = 0.00000)
*Mean Squared Error:   2.7496
*Mean Absolute Error:  1.2778
*Train_Mean MAE:       0.4617

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.21997193005931059,
                        'R2': 0.048387650014018235,
                        'R2_folds': 0.017265728851422902,
                        'mae': 1.2778183520599251,
                        'mae_folds': 1.2776906298904538,
                        'mse': 2.7495662102059923,
                        'mse_folds': 2.7490012174241434,
                        'num_features': 88,
                        'r': 0.24536952785662358,
                        'r_folds': 0.26495345706936879,
                        'r_p': 2.7974591901618175e-06,
                        'r_p_folds': 0.12618776852715435,
                        'rho': 0.27864628459892749,
                        'rho_folds': 0.28930689581707109,
                        'rho_p': 9.0301826183352485e-08,
                        'rho_p_folds': 0.089847759949157571,
                        'se_R2_folds': 0.046894643019027606,
                        'se_mae_folds': 0.053906972721381126,
                        'se_mse_folds': 0.28556913486928098,
                        'se_r_folds': 0.062222101858343065,
                        'se_r_p_folds': 0.061370277009515542,
                        'se_rho_folds': 0.06045730148192556,
                        'se_rho_p_folds': 0.050950690206888839,
                        'se_train_mean_mae_folds': 0.034262972911295729,
                        'test_size': 71,
                        'train_mean_mae': 0.46174031056684767,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$opensmile_n$merged_data$message_id
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.38 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [5]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:01:40
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('min_samples_split', 2), ('n_estimators', 1200), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_features_', 88)]
  *FOLD R^2: -0.1197 (MSE: 3.1674; MAE: 1.4281; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('min_samples_split', 2), ('n_estimators', 1200), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_features_', 88)]
  *FOLD R^2: 0.0716 (MSE: 2.8758; MAE: 1.3000; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('min_samples_split', 2), ('n_estimators', 1200), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_features_', 88)]
  *FOLD R^2: 0.0520 (MSE: 3.9156; MAE: 1.5717; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('min_samples_split', 2), ('n_estimators', 1200), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_features_', 88)]
  *FOLD R^2: 0.0545 (MSE: 4.5325; MAE: 1.4749; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('min_samples_split', 2), ('n_estimators', 1200), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_features_', 88)]
  *FOLD R^2: 0.0867 (MSE: 4.3920; MAE: 1.6193; mean train mae: 1.6607)
*Overall R^2:          0.0527
*Overall FOLDS R^2:    0.0290 (+- 0.0337)
*R (sqrt R^2):         0.2295
*Pearson r:            0.2818 (p = 0.00000)
*Folds Pearson r:      0.2815 (p = 0.06418)
*Spearman rho:         0.3238 (p = 0.00000)
*Mean Squared Error:   3.7727
*Mean Absolute Error:  1.4782
*Train_Mean MAE:       0.6860

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.2294640741680542,
                        'R2': 0.052653761333802285,
                        'R2_folds': 0.029031229871933961,
                        'mae': 1.4782051282051281,
                        'mae_folds': 1.4788139473684212,
                        'mse': 3.7726548076923079,
                        'mse_folds': 3.7766602904239761,
                        'num_features': 88,
                        'r': 0.28183161946282886,
                        'r_folds': 0.28150458456731409,
                        'r_p': 2.5877551795355193e-08,
                        'r_p_folds': 0.064182753194117079,
                        'rho': 0.32378914059449498,
                        'rho_folds': 0.31017311091714356,
                        'rho_p': 1.1925211238360773e-10,
                        'rho_p_folds': 0.088935252467585088,
                        'se_R2_folds': 0.033717475705222405,
                        'se_mae_folds': 0.050179048380789661,
                        'se_mse_folds': 0.29338487864303026,
                        'se_r_folds': 0.041750450331923518,
                        'se_r_p_folds': 0.047719131301966956,
                        'se_rho_folds': 0.063369000054349825,
                        'se_rho_p_folds': 0.05508732911297648,
                        'se_train_mean_mae_folds': 0.062265467210680825,
                        'test_size': 75,
                        'train_mean_mae': 0.6860436176525081,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$opensmile_n$merged_data$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.74 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [6]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:03:12
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_outputs_', 1), ('max_leaf_nodes', None), ('n_jobs', 12), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('n_features_', 88)]
  *FOLD R^2: -0.1382 (MSE: 3.2019; MAE: 1.4877; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_outputs_', 1), ('max_leaf_nodes', None), ('n_jobs', 12), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('n_features_', 88)]
  *FOLD R^2: -0.2193 (MSE: 1.5579; MAE: 1.0204; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_outputs_', 1), ('max_leaf_nodes', None), ('n_jobs', 12), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('n_features_', 88)]
  *FOLD R^2: -0.0418 (MSE: 3.5237; MAE: 1.4484; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_outputs_', 1), ('max_leaf_nodes', None), ('n_jobs', 12), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('n_features_', 88)]
  *FOLD R^2: 0.0640 (MSE: 2.2657; MAE: 1.2839; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 88)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 88)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_outputs_', 1), ('max_leaf_nodes', None), ('n_jobs', 12), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('min_impurity_split', 1e-07), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('n_features_', 88)]
  *FOLD R^2: -0.0702 (MSE: 2.4706; MAE: 1.3060; mean train mae: 1.2725)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0368
*Overall FOLDS R^2:    -0.0811 (+- 0.0425)
*R (sqrt R^2):         nan
*Pearson r:            0.1649 (p = 0.00131)
*Folds Pearson r:      0.1798 (p = 0.26038)
*Spearman rho:         0.1035 (p = 0.04465)
*Mean Squared Error:   2.6028
*Mean Absolute Error:  1.3090
*Train_Mean MAE:       0.4706

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.036807373656476683,
                        'R2_folds': -0.081090827530130721,
                        'mae': 1.308974358974359,
                        'mae_folds': 1.3092675438596493,
                        'mse': 2.6027527814618336,
                        'mse_folds': 2.6039413133040932,
                        'num_features': 88,
                        'r': 0.16488218553604503,
                        'r_folds': 0.17979448205174273,
                        'r_p': 0.0013143931413400365,
                        'r_p_folds': 0.2603768769172819,
                        'rho': 0.1034807181540312,
                        'rho_folds': 0.10555222521809489,
                        'rho_p': 0.044648231773027014,
                        'rho_p_folds': 0.22376627013454606,
                        'se_R2_folds': 0.042471573518055535,
                        'se_mae_folds': 0.073565729427351623,
                        'se_mse_folds': 0.31175622727331603,
                        'se_r_folds': 0.047200493311934023,
                        'se_r_p_folds': 0.11735433734059081,
                        'se_rho_folds': 0.056745339496577681,
                        'se_rho_p_folds': 0.057416350052155368,
                        'se_train_mean_mae_folds': 0.072108818846987666,
                        'test_size': 75,
                        'train_mean_mae': 0.47063982954452172,
                        'train_mean_mae_folds': 1.2705838568390788,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$opensmile_n$merged_data$message_id
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.48 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:06:11
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('random_state', 42), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('bootstrap', False), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('n_jobs', 12), ('n_outputs_', 1)]
  *FOLD R^2: -0.0371 (MSE: 2.9338; MAE: 1.2622; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('random_state', 42), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('bootstrap', False), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('n_jobs', 12), ('n_outputs_', 1)]
  *FOLD R^2: -0.0911 (MSE: 3.3799; MAE: 1.4963; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('random_state', 42), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('bootstrap', False), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('n_jobs', 12), ('n_outputs_', 1)]
  *FOLD R^2: 0.0721 (MSE: 3.8327; MAE: 1.5120; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('random_state', 42), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('bootstrap', False), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('n_jobs', 12), ('n_outputs_', 1)]
  *FOLD R^2: 0.0357 (MSE: 4.6225; MAE: 1.4827; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('random_state', 42), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('bootstrap', False), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('n_jobs', 12), ('n_outputs_', 1)]
  *FOLD R^2: -0.0644 (MSE: 5.1184; MAE: 1.7052; mean train mae: 1.6607)
*Overall R^2:          0.0023
*Overall FOLDS R^2:    -0.0169 (+- 0.0275)
*R (sqrt R^2):         0.0482
*Pearson r:            0.1544 (p = 0.00265)
*Folds Pearson r:      0.1730 (p = 0.25833)
*Spearman rho:         0.1546 (p = 0.00261)
*Mean Squared Error:   3.9731
*Mean Absolute Error:  1.4911
*Train_Mean MAE:       0.4415

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.04820148020620043,
                        'R2': 0.0023233826940687319,
                        'R2_folds': -0.016946411583242348,
                        'mae': 1.4911118479221925,
                        'mae_folds': 1.4917083040935672,
                        'mse': 3.9730874871058055,
                        'mse_folds': 3.9774408520467839,
                        'num_features': 512,
                        'r': 0.15438693510721621,
                        'r_folds': 0.17300107567565304,
                        'r_p': 0.0026493672452762083,
                        'r_p_folds': 0.25832629246313177,
                        'rho': 0.15463927160507032,
                        'rho_folds': 0.17249513486461979,
                        'rho_p': 0.0026063669207162916,
                        'rho_p_folds': 0.28790156442919435,
                        'se_R2_folds': 0.027461025229704714,
                        'se_mae_folds': 0.062854121852335063,
                        'se_mse_folds': 0.35693312578089531,
                        'se_r_folds': 0.043096524297566455,
                        'se_r_p_folds': 0.10841880954262723,
                        'se_rho_folds': 0.05061644345243084,
                        'se_rho_p_folds': 0.10633700513102214,
                        'se_train_mean_mae_folds': 0.062265467210680825,
                        'test_size': 75,
                        'train_mean_mae': 0.44149791738491084,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_mean_n$merged_data$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 28.91 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [8]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:07:30
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('class_weight', None), ('bootstrap', False), ('n_estimators', 1200), ('min_samples_split', 2), ('max_leaf_nodes', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 512), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_depth', None), ('n_outputs_', 1)]
  *FOLD R^2: -0.1227 (MSE: 3.1582; MAE: 1.3972; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('class_weight', None), ('bootstrap', False), ('n_estimators', 1200), ('min_samples_split', 2), ('max_leaf_nodes', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 512), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_depth', None), ('n_outputs_', 1)]
  *FOLD R^2: -0.5203 (MSE: 1.9425; MAE: 1.1491; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('class_weight', None), ('bootstrap', False), ('n_estimators', 1200), ('min_samples_split', 2), ('max_leaf_nodes', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 512), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_depth', None), ('n_outputs_', 1)]
  *FOLD R^2: -0.0320 (MSE: 3.4908; MAE: 1.4512; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('class_weight', None), ('bootstrap', False), ('n_estimators', 1200), ('min_samples_split', 2), ('max_leaf_nodes', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 512), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_depth', None), ('n_outputs_', 1)]
  *FOLD R^2: 0.0882 (MSE: 2.2070; MAE: 1.2484; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('class_weight', None), ('bootstrap', False), ('n_estimators', 1200), ('min_samples_split', 2), ('max_leaf_nodes', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 512), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_depth', None), ('n_outputs_', 1)]
  *FOLD R^2: -0.0609 (MSE: 2.4491; MAE: 1.2787; mean train mae: 1.2725)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0552
*Overall FOLDS R^2:    -0.1295 (+- 0.0926)
*R (sqrt R^2):         nan
*Pearson r:            0.0535 (p = 0.30006)
*Folds Pearson r:      0.0732 (p = 0.35239)
*Spearman rho:         0.0374 (p = 0.46882)
*Mean Squared Error:   2.6490
*Mean Absolute Error:  1.3048
*Train_Mean MAE:       0.3629

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.055226067432389891,
                        'R2_folds': -0.12953004349306838,
                        'mae': 1.3047590627763042,
                        'mae_folds': 1.3049275438596488,
                        'mse': 2.6489902096227524,
                        'mse_folds': 2.6495163952729044,
                        'num_features': 512,
                        'r': 0.053511743977144831,
                        'r_folds': 0.073204178732462072,
                        'r_p': 0.30006103358248321,
                        'r_p_folds': 0.35238861850189335,
                        'rho': 0.037419765551713231,
                        'rho_folds': 0.053875379595838713,
                        'rho_p': 0.46881930235574554,
                        'rho_p_folds': 0.33346159740056136,
                        'se_R2_folds': 0.092602854503315984,
                        'se_mae_folds': 0.048190199599502562,
                        'se_mse_folds': 0.26094680146270749,
                        'se_r_folds': 0.088042801267358334,
                        'se_r_p_folds': 0.14901126554888011,
                        'se_rho_folds': 0.088578299586721698,
                        'se_rho_p_folds': 0.13905550459656191,
                        'se_train_mean_mae_folds': 0.07210881884698768,
                        'test_size': 75,
                        'train_mean_mae': 0.36285277811002686,
                        'train_mean_mae_folds': 1.2705838568390793,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_mean_n$merged_data$message_id
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 27.37 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [9]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:09:45
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('random_state', 42), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('n_features_', 512), ('oob_score', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('max_depth', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('n_jobs', 12)]
  *FOLD R^2: -0.0688 (MSE: 4.6607; MAE: 1.7364; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('random_state', 42), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('n_features_', 512), ('oob_score', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('max_depth', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('n_jobs', 12)]
  *FOLD R^2: 0.0234 (MSE: 7.7392; MAE: 2.1246; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('random_state', 42), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('n_features_', 512), ('oob_score', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('max_depth', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('n_jobs', 12)]
  *FOLD R^2: -0.2258 (MSE: 3.3119; MAE: 1.3117; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('random_state', 42), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('n_features_', 512), ('oob_score', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('max_depth', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('n_jobs', 12)]
  *FOLD R^2: 0.0161 (MSE: 5.2724; MAE: 1.8262; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('random_state', 42), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('n_features_', 512), ('oob_score', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('max_depth', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('n_jobs', 12)]
  *FOLD R^2: -0.0991 (MSE: 6.0352; MAE: 1.7394; mean train mae: 1.6135)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0423
*Overall FOLDS R^2:    -0.0708 (+- 0.0406)
*R (sqrt R^2):         nan
*Pearson r:            0.0583 (p = 0.27232)
*Folds Pearson r:      0.0495 (p = 0.44181)
*Spearman rho:         -0.0134 (p = 0.80041)
*Mean Squared Error:   5.4018
*Mean Absolute Error:  1.7476
*Train_Mean MAE:       0.4655

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.042282250908913799,
                        'R2_folds': -0.070831768225093003,
                        'mae': 1.7476076779026217,
                        'mae_folds': 1.7476393453312469,
                        'mse': 5.4017813904494387,
                        'mse_folds': 5.403868844059728,
                        'num_features': 512,
                        'r': 0.058335844840404084,
                        'r_folds': 0.049472197261904029,
                        'r_p': 0.27231690673884362,
                        'r_p_folds': 0.44181154593664712,
                        'rho': -0.013446258203233294,
                        'rho_folds': -0.02481084036888264,
                        'rho_p': 0.80040525045035948,
                        'rho_p_folds': 0.3634625593718469,
                        'se_R2_folds': 0.040620750678826492,
                        'se_mae_folds': 0.11636441607809578,
                        'se_mse_folds': 0.65720698183991233,
                        'se_r_folds': 0.047831706013255114,
                        'se_r_p_folds': 0.12263099978196788,
                        'se_rho_folds': 0.053230809857296113,
                        'se_rho_p_folds': 0.077326843813583068,
                        'se_train_mean_mae_folds': 0.13773807905205243,
                        'test_size': 71,
                        'train_mean_mae': 0.46545559272819087,
                        'train_mean_mae_folds': 1.6588806523350628,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_mean_n$merged_data$message_id
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 28.09 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [10]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:11:40
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('warm_start', False), ('n_jobs', 12), ('n_features_', 512), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_outputs_', 1), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.1812 (MSE: 3.4723; MAE: 1.4787; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('warm_start', False), ('n_jobs', 12), ('n_features_', 512), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_outputs_', 1), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.2545 (MSE: 2.3661; MAE: 1.2932; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('warm_start', False), ('n_jobs', 12), ('n_features_', 512), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_outputs_', 1), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: 0.0241 (MSE: 3.7687; MAE: 1.4134; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('warm_start', False), ('n_jobs', 12), ('n_features_', 512), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_outputs_', 1), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.0205 (MSE: 2.6212; MAE: 1.3104; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('warm_start', False), ('n_jobs', 12), ('n_features_', 512), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('max_depth', None), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_outputs_', 1), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.0090 (MSE: 2.8182; MAE: 1.3311; mean train mae: 1.3612)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0420
*Overall FOLDS R^2:    -0.0882 (+- 0.0489)
*R (sqrt R^2):         nan
*Pearson r:            0.0515 (p = 0.33271)
*Folds Pearson r:      0.0912 (p = 0.41325)
*Spearman rho:         0.0593 (p = 0.26447)
*Mean Squared Error:   3.0106
*Mean Absolute Error:  1.3657
*Train_Mean MAE:       0.3453

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.041954415021185465,
                        'R2_folds': -0.088203787465346434,
                        'mae': 1.3656694756554308,
                        'mae_folds': 1.365351167188315,
                        'mse': 3.0105984355493138,
                        'mse_folds': 3.009297817580638,
                        'num_features': 512,
                        'r': 0.051486307133437513,
                        'r_folds': 0.09121891116327803,
                        'r_p': 0.33271095930680239,
                        'r_p_folds': 0.41324997592059243,
                        'rho': 0.059298446025583068,
                        'rho_folds': 0.096716860976901436,
                        'rho_p': 0.26447001289253874,
                        'rho_p_folds': 0.41987327995004753,
                        'se_R2_folds': 0.048895805929795241,
                        'se_mae_folds': 0.031336464282943205,
                        'se_mse_folds': 0.23595998767542939,
                        'se_r_folds': 0.031296384736828387,
                        'se_r_p_folds': 0.094918311629635155,
                        'se_rho_folds': 0.043530731071414128,
                        'se_rho_p_folds': 0.12716347129099967,
                        'se_train_mean_mae_folds': 0.034262972911295757,
                        'test_size': 71,
                        'train_mean_mae': 0.34529404957286536,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_mean_n$merged_data$message_id
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 26.00 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [11]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:12:58
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('n_jobs', 12), ('warm_start', False), ('random_state', 42), ('n_features_', 512), ('verbose', 0), ('n_estimators', 1200), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('bootstrap', False), ('oob_score', False), ('min_samples_leaf', 1)]
  *FOLD R^2: -0.0616 (MSE: 3.0032; MAE: 1.2738; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('n_jobs', 12), ('warm_start', False), ('random_state', 42), ('n_features_', 512), ('verbose', 0), ('n_estimators', 1200), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('bootstrap', False), ('oob_score', False), ('min_samples_leaf', 1)]
  *FOLD R^2: -0.1985 (MSE: 3.7124; MAE: 1.5571; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('n_jobs', 12), ('warm_start', False), ('random_state', 42), ('n_features_', 512), ('verbose', 0), ('n_estimators', 1200), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('bootstrap', False), ('oob_score', False), ('min_samples_leaf', 1)]
  *FOLD R^2: 0.0363 (MSE: 3.9807; MAE: 1.5476; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('n_jobs', 12), ('warm_start', False), ('random_state', 42), ('n_features_', 512), ('verbose', 0), ('n_estimators', 1200), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('bootstrap', False), ('oob_score', False), ('min_samples_leaf', 1)]
  *FOLD R^2: 0.0313 (MSE: 4.6436; MAE: 1.4966; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('n_jobs', 12), ('warm_start', False), ('random_state', 42), ('n_features_', 512), ('verbose', 0), ('n_estimators', 1200), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('bootstrap', False), ('oob_score', False), ('min_samples_leaf', 1)]
  *FOLD R^2: -0.0235 (MSE: 4.9221; MAE: 1.6764; mean train mae: 1.6607)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0167
*Overall FOLDS R^2:    -0.0432 (+- 0.0383)
*R (sqrt R^2):         nan
*Pearson r:            0.1278 (p = 0.01299)
*Folds Pearson r:      0.1327 (p = 0.26167)
*Spearman rho:         0.1300 (p = 0.01151)
*Mean Squared Error:   4.0487
*Mean Absolute Error:  1.5098
*Train_Mean MAE:       0.4445

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.016671029292190553,
                        'R2_folds': -0.043212768183738051,
                        'mae': 1.5097922192749778,
                        'mae_folds': 1.510295380116959,
                        'mse': 4.0487296934865897,
                        'mse_folds': 4.0524144928849903,
                        'num_features': 512,
                        'r': 0.1278319260025606,
                        'r_folds': 0.13266721570082513,
                        'r_p': 0.01299144620778498,
                        'r_p_folds': 0.26166931263725179,
                        'rho': 0.13001790465566918,
                        'rho_folds': 0.14898083788952671,
                        'rho_p': 0.011509316822622075,
                        'rho_p_folds': 0.21242812631809288,
                        'se_R2_folds': 0.038312606456089679,
                        'se_mae_folds': 0.059080599472083196,
                        'se_mse_folds': 0.30511556726555333,
                        'se_r_folds': 0.052203018323045469,
                        'se_r_p_folds': 0.093576289591090961,
                        'se_rho_folds': 0.049853811548510464,
                        'se_rho_p_folds': 0.098097651826618781,
                        'se_train_mean_mae_folds': 0.062265467210680825,
                        'test_size': 75,
                        'train_mean_mae': 0.44454583512161489,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_median_n$merged_data$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 28.51 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [12]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:15:08
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('n_jobs', 12), ('random_state', 42), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.1485 (MSE: 3.2309; MAE: 1.4086; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('n_jobs', 12), ('random_state', 42), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.5906 (MSE: 2.0323; MAE: 1.1738; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('n_jobs', 12), ('random_state', 42), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0230 (MSE: 3.4600; MAE: 1.4410; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('n_jobs', 12), ('random_state', 42), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0761 (MSE: 2.2364; MAE: 1.2368; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_features_', 512), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('n_jobs', 12), ('random_state', 42), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0090 (MSE: 2.3293; MAE: 1.2637; mean train mae: 1.2725)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0587
*Overall FOLDS R^2:    -0.1390 (+- 0.1060)
*R (sqrt R^2):         nan
*Pearson r:            0.0528 (p = 0.30681)
*Folds Pearson r:      0.0750 (p = 0.27889)
*Spearman rho:         0.0344 (p = 0.50583)
*Mean Squared Error:   2.6576
*Mean Absolute Error:  1.3047
*Train_Mean MAE:       0.3635

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.058675307234551166,
                        'R2_folds': -0.13899135156237469,
                        'mae': 1.3047082228116711,
                        'mae_folds': 1.3047802046783628,
                        'mse': 2.6576490200412612,
                        'mse_folds': 2.6577880312134505,
                        'num_features': 512,
                        'r': 0.052771040833394262,
                        'r_folds': 0.075027407962393683,
                        'r_p': 0.30681025794858313,
                        'r_p_folds': 0.27888528227866061,
                        'rho': 0.034371382791322729,
                        'rho_folds': 0.038032269598205652,
                        'rho_p': 0.50582537620678214,
                        'rho_p_folds': 0.30739706786682719,
                        'se_R2_folds': 0.10595824850029599,
                        'se_mae_folds': 0.045957482264529205,
                        'se_mse_folds': 0.25680235918581845,
                        'se_r_folds': 0.092268898865965066,
                        'se_r_p_folds': 0.13532405682664625,
                        'se_rho_folds': 0.090255226266025085,
                        'se_rho_p_folds': 0.15814921393520148,
                        'se_train_mean_mae_folds': 0.07210881884698768,
                        'test_size': 75,
                        'train_mean_mae': 0.36346289872815074,
                        'train_mean_mae_folds': 1.2705838568390788,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_median_n$merged_data$message_id
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 28.45 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [13]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:16:27
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('verbose', 0), ('bootstrap', False), ('n_features_', 512), ('n_outputs_', 1), ('n_jobs', 12), ('max_depth', None), ('random_state', 42), ('warm_start', False), ('oob_score', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.0594 (MSE: 4.6198; MAE: 1.7050; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('verbose', 0), ('bootstrap', False), ('n_features_', 512), ('n_outputs_', 1), ('n_jobs', 12), ('max_depth', None), ('random_state', 42), ('warm_start', False), ('oob_score', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: 0.0307 (MSE: 7.6809; MAE: 2.1327; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('verbose', 0), ('bootstrap', False), ('n_features_', 512), ('n_outputs_', 1), ('n_jobs', 12), ('max_depth', None), ('random_state', 42), ('warm_start', False), ('oob_score', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.1836 (MSE: 3.1980; MAE: 1.2931; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('verbose', 0), ('bootstrap', False), ('n_features_', 512), ('n_outputs_', 1), ('n_jobs', 12), ('max_depth', None), ('random_state', 42), ('warm_start', False), ('oob_score', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: 0.0075 (MSE: 5.3187; MAE: 1.8235; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('verbose', 0), ('bootstrap', False), ('n_features_', 512), ('n_outputs_', 1), ('n_jobs', 12), ('max_depth', None), ('random_state', 42), ('warm_start', False), ('oob_score', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('min_samples_split', 2)]
  *FOLD R^2: -0.1662 (MSE: 6.4037; MAE: 1.8046; mean train mae: 1.6135)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0500
*Overall FOLDS R^2:    -0.0742 (+- 0.0392)
*R (sqrt R^2):         nan
*Pearson r:            0.0519 (p = 0.32908)
*Folds Pearson r:      0.0498 (p = 0.33736)
*Spearman rho:         0.0551 (p = 0.29954)
*Mean Squared Error:   5.4419
*Mean Absolute Error:  1.7517
*Train_Mean MAE:       0.4886

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.0500212781479068,
                        'R2_folds': -0.074200476091456261,
                        'mae': 1.7516573033707863,
                        'mae_folds': 1.7517886345852898,
                        'mse': 5.441890039794008,
                        'mse_folds': 5.4442059098689359,
                        'num_features': 512,
                        'r': 0.051873893474125209,
                        'r_folds': 0.04982695781845882,
                        'r_p': 0.32907948507718998,
                        'r_p_folds': 0.33736498772362572,
                        'rho': 0.055134882235338988,
                        'rho_folds': 0.057328704516208438,
                        'rho_p': 0.2995431591835922,
                        'rho_p_folds': 0.36388278417599074,
                        'se_R2_folds': 0.03916060752851442,
                        'se_mae_folds': 0.12093137845871753,
                        'se_mse_folds': 0.68306416788512059,
                        'se_r_folds': 0.061667259416833389,
                        'se_r_p_folds': 0.12546669860607679,
                        'se_rho_folds': 0.062511970364668476,
                        'se_rho_p_folds': 0.13543143131856514,
                        'se_train_mean_mae_folds': 0.13773807905205246,
                        'test_size': 71,
                        'train_mean_mae': 0.48858935109203389,
                        'train_mean_mae_folds': 1.6588806523350628,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_median_n$merged_data$message_id
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 27.01 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [14]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:20:32
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_jobs', 12), ('verbose', 0), ('warm_start', False), ('min_samples_split', 2), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('max_depth', None), ('n_features_', 512)]
  *FOLD R^2: -0.1782 (MSE: 3.4636; MAE: 1.4809; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_jobs', 12), ('verbose', 0), ('warm_start', False), ('min_samples_split', 2), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('max_depth', None), ('n_features_', 512)]
  *FOLD R^2: -0.2725 (MSE: 2.4002; MAE: 1.2699; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_jobs', 12), ('verbose', 0), ('warm_start', False), ('min_samples_split', 2), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('max_depth', None), ('n_features_', 512)]
  *FOLD R^2: 0.0093 (MSE: 3.8262; MAE: 1.4366; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_jobs', 12), ('verbose', 0), ('warm_start', False), ('min_samples_split', 2), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('max_depth', None), ('n_features_', 512)]
  *FOLD R^2: -0.0666 (MSE: 2.7395; MAE: 1.3218; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 512)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 512)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('n_jobs', 12), ('verbose', 0), ('warm_start', False), ('min_samples_split', 2), ('oob_score', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('n_outputs_', 1), ('max_depth', None), ('n_features_', 512)]
  *FOLD R^2: -0.0292 (MSE: 2.8747; MAE: 1.3361; mean train mae: 1.3612)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0597
*Overall FOLDS R^2:    -0.1075 (+- 0.0463)
*R (sqrt R^2):         nan
*Pearson r:            0.0456 (p = 0.39052)
*Folds Pearson r:      0.0788 (p = 0.40454)
*Spearman rho:         0.0691 (p = 0.19302)
*Mean Squared Error:   3.0620
*Mean Absolute Error:  1.3694
*Train_Mean MAE:       0.3713

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.059731758542667546,
                        'R2_folds': -0.1074605844175133,
                        'mae': 1.3693749999999998,
                        'mae_folds': 1.3690609350547729,
                        'mse': 3.0619638713327095,
                        'mse_folds': 3.0608325319781335,
                        'num_features': 512,
                        'r': 0.045646663708046681,
                        'r_folds': 0.078777254027656091,
                        'r_p': 0.39051807477618394,
                        'r_p_folds': 0.40454427319340158,
                        'rho': 0.06914985567413108,
                        'rho_folds': 0.097441021299909614,
                        'rho_p': 0.19302344276329558,
                        'rho_p_folds': 0.33107487942531727,
                        'se_R2_folds': 0.04633518311495094,
                        'se_mae_folds': 0.034766232053265587,
                        'se_mse_folds': 0.22998593483414334,
                        'se_r_folds': 0.037684704701456469,
                        'se_r_p_folds': 0.090831300245643412,
                        'se_rho_folds': 0.057108233962081673,
                        'se_rho_p_folds': 0.14616367380603834,
                        'se_train_mean_mae_folds': 0.034262972911295729,
                        'test_size': 71,
                        'train_mean_mae': 0.37133429596431422,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_median_n$merged_data$message_id
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 26.40 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [15]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:22:31
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
   (feature group: 1): [Initial size: 391]
   (feature group: 2): [Initial size: 391]
   (feature group: 3): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_features_', 1150), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_jobs', 12), ('oob_score', False), ('random_state', 42), ('warm_start', False), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('bootstrap', False), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0262 (MSE: 2.7548; MAE: 1.3167; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
   (feature group: 1): [Initial size: 391]
   (feature group: 2): [Initial size: 391]
   (feature group: 3): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_features_', 1150), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_jobs', 12), ('oob_score', False), ('random_state', 42), ('warm_start', False), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('bootstrap', False), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0971 (MSE: 2.7969; MAE: 1.2805; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
   (feature group: 1): [Initial size: 391]
   (feature group: 2): [Initial size: 391]
   (feature group: 3): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_features_', 1150), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_jobs', 12), ('oob_score', False), ('random_state', 42), ('warm_start', False), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('bootstrap', False), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.1114 (MSE: 3.6702; MAE: 1.4757; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
   (feature group: 1): [Initial size: 391]
   (feature group: 2): [Initial size: 391]
   (feature group: 3): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_features_', 1150), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_jobs', 12), ('oob_score', False), ('random_state', 42), ('warm_start', False), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('bootstrap', False), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0359 (MSE: 4.6215; MAE: 1.5076; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
   (feature group: 1): [Initial size: 391]
   (feature group: 2): [Initial size: 391]
   (feature group: 3): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_features_', 1150), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_jobs', 12), ('oob_score', False), ('random_state', 42), ('warm_start', False), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('bootstrap', False), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0515 (MSE: 4.5611; MAE: 1.6263; mean train mae: 1.6607)
*Overall R^2:          0.0769
*Overall FOLDS R^2:    0.0644 (+- 0.0151)
*R (sqrt R^2):         0.2773
*Pearson r:            0.2876 (p = 0.00000)
*Folds Pearson r:      0.2988 (p = 0.01688)
*Spearman rho:         0.3431 (p = 0.00000)
*Mean Squared Error:   3.6761
*Mean Absolute Error:  1.4406
*Train_Mean MAE:       0.5516

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.27730528073273225,
                        'R2': 0.076898218722259437,
                        'R2_folds': 0.064431458252887319,
                        'mae': 1.4406100795755969,
                        'mae_folds': 1.4413673099415205,
                        'mse': 3.6761051355732386,
                        'mse_folds': 3.6809065164230019,
                        'num_features': 1150,
                        'r': 0.2875616617072746,
                        'r_folds': 0.29881716426457022,
                        'r_p': 1.3048763761639313e-08,
                        'r_p_folds': 0.016880227948951929,
                        'rho': 0.34305961484785108,
                        'rho_folds': 0.35107694571143233,
                        'rho_p': 7.4990079460133942e-12,
                        'rho_p_folds': 0.009176958928874315,
                        'se_R2_folds': 0.015122669527180943,
                        'se_mae_folds': 0.056978484945522948,
                        'se_mse_folds': 0.36324828605993142,
                        'se_r_folds': 0.023848359016609196,
                        'se_r_p_folds': 0.0067589188880627198,
                        'se_rho_folds': 0.039017474530914156,
                        'se_rho_p_folds': 0.0047634208706054393,
                        'se_train_mean_mae_folds': 0.062265467210680839,
                        'test_size': 75,
                        'train_mean_mae': 0.55164877212485364,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$librosa_n$merged_data$message_id', 'feat$opensmile_n$merged_data$message_id', 'feat$whisper_mean_n$merged_data$message_id', 'feat$whisper_median_n$merged_data$message_id']
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 49.00 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

#### ExtraTrees Predictions with Demographic Subgroups

Extra Trees Regressor predictions stratified by demographic groups

In [16]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:23:24
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
   (feature group: 1): [Initial size: 400]
   (feature group: 2): [Initial size: 400]
   (feature group: 3): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('oob_score', False), ('max_depth', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1150), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('verbose', 0)]
  *FOLD R^2: -0.1272 (MSE: 3.1709; MAE: 1.4540; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
   (feature group: 1): [Initial size: 400]
   (feature group: 2): [Initial size: 400]
   (feature group: 3): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (301, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (301, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (301, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('oob_score', False), ('max_depth', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1150), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('verbose', 0)]
  *FOLD R^2: -0.3724 (MSE: 1.7536; MAE: 1.0963; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
   (feature group: 1): [Initial size: 400]
   (feature group: 2): [Initial size: 400]
   (feature group: 3): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('oob_score', False), ('max_depth', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1150), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('verbose', 0)]
  *FOLD R^2: -0.0261 (MSE: 3.4708; MAE: 1.4164; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
   (feature group: 1): [Initial size: 400]
   (feature group: 2): [Initial size: 400]
   (feature group: 3): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('oob_score', False), ('max_depth', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1150), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('verbose', 0)]
  *FOLD R^2: 0.1149 (MSE: 2.1424; MAE: 1.2416; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
   (feature group: 1): [Initial size: 400]
   (feature group: 2): [Initial size: 400]
   (feature group: 3): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (302, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (302, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (302, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('oob_score', False), ('max_depth', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1150), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('verbose', 0)]
  *FOLD R^2: -0.0266 (MSE: 2.3699; MAE: 1.2528; mean train mae: 1.2725)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0281
*Overall FOLDS R^2:    -0.0875 (+- 0.0725)
*R (sqrt R^2):         nan
*Pearson r:            0.1219 (p = 0.01786)
*Folds Pearson r:      0.1539 (p = 0.39307)
*Spearman rho:         0.1175 (p = 0.02252)
*Mean Squared Error:   2.5809
*Mean Absolute Error:  1.2921
*Train_Mean MAE:       0.4062

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': nan,
                        'R2': -0.02810041241506922,
                        'R2_folds': -0.087487338152504562,
                        'mae': 1.2921175950486294,
                        'mae_folds': 1.2922080701754386,
                        'mse': 2.5808952328323018,
                        'mse_folds': 2.5815279676900582,
                        'num_features': 1150,
                        'r': 0.12193788666871065,
                        'r_folds': 0.15394178791114074,
                        'r_p': 0.017856115624125927,
                        'r_p_folds': 0.39307437373734289,
                        'rho': 0.11748155048920172,
                        'rho_folds': 0.11546173375339248,
                        'rho_p': 0.022524202228773178,
                        'rho_p_folds': 0.35276684799029623,
                        'se_R2_folds': 0.072453582951079745,
                        'se_mae_folds': 0.057990452347429777,
                        'se_mse_folds': 0.28714514506095623,
                        'se_r_folds': 0.090285553226888124,
                        'se_r_p_folds': 0.14569270930690092,
                        'se_rho_folds': 0.092957361265877045,
                        'se_rho_p_folds': 0.12895006843183465,
                        'se_train_mean_mae_folds': 0.07210881884698768,
                        'test_size': 75,
                        'train_mean_mae': 0.40620400012195496,
                        'train_mean_mae_folds': 1.2705838568390788,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$librosa_n$merged_data$message_id', 'feat$opensmile_n$merged_data$message_id', 'feat$whisper_mean_n$merged_data$message_id', 'feat$whisper_median_n$merged_data$message_id']
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 47.17 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [17]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:24:15
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
   (feature group: 1): [Initial size: 374]
   (feature group: 2): [Initial size: 374]
   (feature group: 3): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_features_', 1150), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('warm_start', False), ('n_outputs_', 1), ('n_jobs', 12), ('verbose', 0), ('min_samples_split', 2)]
  *FOLD R^2: 0.1686 (MSE: 3.6257; MAE: 1.5303; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
   (feature group: 1): [Initial size: 374]
   (feature group: 2): [Initial size: 374]
   (feature group: 3): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_features_', 1150), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('warm_start', False), ('n_outputs_', 1), ('n_jobs', 12), ('verbose', 0), ('min_samples_split', 2)]
  *FOLD R^2: 0.0368 (MSE: 7.6326; MAE: 2.1310; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
   (feature group: 1): [Initial size: 374]
   (feature group: 2): [Initial size: 374]
   (feature group: 3): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_features_', 1150), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('warm_start', False), ('n_outputs_', 1), ('n_jobs', 12), ('verbose', 0), ('min_samples_split', 2)]
  *FOLD R^2: -0.1737 (MSE: 3.1711; MAE: 1.3830; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
   (feature group: 1): [Initial size: 374]
   (feature group: 2): [Initial size: 374]
   (feature group: 3): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_features_', 1150), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('warm_start', False), ('n_outputs_', 1), ('n_jobs', 12), ('verbose', 0), ('min_samples_split', 2)]
  *FOLD R^2: 0.2249 (MSE: 4.1536; MAE: 1.5443; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
   (feature group: 1): [Initial size: 374]
   (feature group: 2): [Initial size: 374]
   (feature group: 3): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_features_', 1150), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('warm_start', False), ('n_outputs_', 1), ('n_jobs', 12), ('verbose', 0), ('min_samples_split', 2)]
  *FOLD R^2: -0.0975 (MSE: 6.0262; MAE: 1.7562; mean train mae: 1.6135)
*Overall R^2:          0.0510
*Overall FOLDS R^2:    0.0318 (+- 0.0678)
*R (sqrt R^2):         0.2259
*Pearson r:            0.2662 (p = 0.00000)
*Folds Pearson r:      0.2745 (p = 0.21633)
*Spearman rho:         0.3186 (p = 0.00000)
*Mean Squared Error:   4.9182
*Mean Absolute Error:  1.6686
*Train_Mean MAE:       0.7183

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.22588556233908633,
                        'R2': 0.051024287273245261,
                        'R2_folds': 0.03183039192552075,
                        'mae': 1.6685767790262171,
                        'mae_folds': 1.6689663536776211,
                        'mse': 4.9182065035892633,
                        'mse_folds': 4.9218473036754489,
                        'num_features': 1150,
                        'r': 0.26619153393245765,
                        'r_folds': 0.27451226075842272,
                        'r_p': 3.4492836635011515e-07,
                        'r_p_folds': 0.21633273320150845,
                        'rho': 0.31855337913666459,
                        'rho_folds': 0.31326102620556828,
                        'rho_p': 7.7353040464672766e-10,
                        'rho_p_folds': 0.12174964083165045,
                        'se_R2_folds': 0.067809245071350388,
                        'se_mae_folds': 0.11620885817531411,
                        'se_mse_folds': 0.74574395565931595,
                        'se_r_folds': 0.079441401598321276,
                        'se_r_p_folds': 0.15611157542609222,
                        'se_rho_folds': 0.072495386359780506,
                        'se_rho_p_folds': 0.075735665925675918,
                        'se_train_mean_mae_folds': 0.13773807905205243,
                        'test_size': 71,
                        'train_mean_mae': 0.71834790430501205,
                        'train_mean_mae_folds': 1.658880652335063,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$librosa_n$merged_data$message_id', 'feat$opensmile_n$merged_data$message_id', 'feat$whisper_mean_n$merged_data$message_id', 'feat$whisper_median_n$merged_data$message_id']
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 46.76 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [18]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 11:25:05
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (284, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_features_', 1150), ('bootstrap', False), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('verbose', 0), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_estimators', 1200), ('max_depth', None), ('n_outputs_', 1), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: -0.1292 (MSE: 3.3195; MAE: 1.4515; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_features_', 1150), ('bootstrap', False), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('verbose', 0), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_estimators', 1200), ('max_depth', None), ('n_outputs_', 1), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: -0.1432 (MSE: 2.1563; MAE: 1.2109; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_features_', 1150), ('bootstrap', False), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('verbose', 0), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_estimators', 1200), ('max_depth', None), ('n_outputs_', 1), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.0334 (MSE: 3.7330; MAE: 1.3966; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_features_', 1150), ('bootstrap', False), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('verbose', 0), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_estimators', 1200), ('max_depth', None), ('n_outputs_', 1), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.1118 (MSE: 2.2814; MAE: 1.1868; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 38)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 88)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 512)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 512)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1150)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1150)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('n_features_', 1150), ('bootstrap', False), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('verbose', 0), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('n_estimators', 1200), ('max_depth', None), ('n_outputs_', 1), ('max_leaf_nodes', None), ('class_weight', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: -0.0035 (MSE: 2.8029; MAE: 1.3113; mean train mae: 1.3612)
*Overall R^2:          0.0102
*Overall FOLDS R^2:    -0.0262 (+- 0.0435)
*R (sqrt R^2):         0.1010
*Pearson r:            0.1751 (p = 0.00091)
*Folds Pearson r:      0.2033 (p = 0.22806)
*Spearman rho:         0.1774 (p = 0.00077)
*Mean Squared Error:   2.8599
*Mean Absolute Error:  1.3118
*Train_Mean MAE:       0.4172

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.10099052969728677,
                        'R2': 0.010199087088538561,
                        'R2_folds': -0.026156027847866435,
                        'mae': 1.3118281835205994,
                        'mae_folds': 1.3114347613458528,
                        'mse': 2.8599073404338329,
                        'mse_folds': 2.8586128493685878,
                        'num_features': 1150,
                        'r': 0.1751015144232107,
                        'r_folds': 0.20330787332406491,
                        'r_p': 0.00090710379583919352,
                        'r_p_folds': 0.22806459237983953,
                        'rho': 0.17741310005304159,
                        'rho_folds': 0.21888831074221496,
                        'rho_p': 0.00077278647713496318,
                        'rho_p_folds': 0.20649905157593187,
                        'se_R2_folds': 0.043547559586829904,
                        'se_mae_folds': 0.045830509001167127,
                        'se_mse_folds': 0.26881393193238728,
                        'se_r_folds': 0.049457879772913826,
                        'se_r_p_folds': 0.15451831267039143,
                        'se_rho_folds': 0.049482115364651975,
                        'se_rho_p_folds': 0.14040719522426881,
                        'se_train_mean_mae_folds': 0.034262972911295757,
                        'test_size': 71,
                        'train_mean_mae': 0.41721349892690318,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$librosa_n$merged_data$message_id', 'feat$opensmile_n$merged_data$message_id', 'feat$whisper_mean_n$merged_data$message_id', 'feat$whisper_median_n$merged_data$message_id']
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 45.39 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 13:48:59
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_features_', 103), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_impurity_split', 1e-07), ('oob_score', False), ('n_outputs_', 1), ('n_jobs', 12), ('warm_start', False)]
  *FOLD R^2: 0.0753 (MSE: 2.6160; MAE: 1.1918; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_features_', 103), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_impurity_split', 1e-07), ('oob_score', False), ('n_outputs_', 1), ('n_jobs', 12), ('warm_start', False)]
  *FOLD R^2: 0.0262 (MSE: 3.0165; MAE: 1.3600; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_features_', 103), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_impurity_split', 1e-07), ('oob_score', False), ('n_outputs_', 1), ('n_jobs', 12), ('warm_start', False)]
  *FOLD R^2: -0.0085 (MSE: 4.1657; MAE: 1.5943; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_features_', 103), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_impurity_split', 1e-07), ('oob_score', False), ('n_outputs_', 1), ('n_jobs', 12), ('warm_start', False)]
  *FOLD R^2: 0.0336 (MSE: 4.6324; MAE: 1.5029; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('class_weight', None), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_features_', 103), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_impurity_split', 1e-07), ('oob_score', False), ('n_outputs_', 1), ('n_jobs', 12), ('warm_start', False)]
  *FOLD R^2: 0.0122 (MSE: 4.7503; MAE: 1.6054; mean train mae: 1.6607)
*Overall R^2:          0.0381
*Overall FOLDS R^2:    0.0278 (+- 0.0124)
*R (sqrt R^2):         0.1951
*Pearson r:            0.2153 (p = 0.00002)
*Folds Pearson r:      0.2469 (p = 0.05818)
*Spearman rho:         0.1941 (p = 0.00015)
*Mean Squared Error:   3.8308
*Mean Absolute Error:  1.4500
*Train_Mean MAE:       0.4866

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.19510354075818934,
                        'R2': 0.038065391616382449,
                        'R2_folds': 0.027757693175182639,
                        'mae': 1.4499778956675509,
                        'mae_folds': 1.4509061695906431,
                        'mse': 3.8307506557618627,
                        'mse_folds': 3.8361615435428846,
                        'num_features': 103,
                        'r': 0.21530176100190565,
                        'r_folds': 0.2469466902645534,
                        'r_p': 2.4859730154633885e-05,
                        'r_p_folds': 0.058180442843369942,
                        'rho': 0.19409769708749716,
                        'rho_folds': 0.20646443791966612,
                        'rho_p': 0.00014925413323876454,
                        'rho_p_folds': 0.12067937693334689,
                        'se_R2_folds': 0.012416383110473784,
                        'se_mae_folds': 0.070011511208688315,
                        'se_mse_folds': 0.38673398087445643,
                        'se_r_folds': 0.0277998258689892,
                        'se_r_p_folds': 0.023130330956658746,
                        'se_rho_folds': 0.031352761472155266,
                        'se_rho_p_folds': 0.041274728662523442,
                        'se_train_mean_mae_folds': 0.062265467210680825,
                        'test_size': 75,
                        'train_mean_mae': 0.48659889959121644,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_LIWC2022_lw$merged_data$message_id$1gra
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.60 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 13:49:23
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('bootstrap', False), ('min_samples_leaf', 1), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('class_weight', None)]
  *FOLD R^2: 0.0661 (MSE: 2.6272; MAE: 1.2580; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('bootstrap', False), ('min_samples_leaf', 1), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('class_weight', None)]
  *FOLD R^2: -0.1711 (MSE: 1.4963; MAE: 1.0015; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('bootstrap', False), ('min_samples_leaf', 1), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('class_weight', None)]
  *FOLD R^2: -0.0614 (MSE: 3.5900; MAE: 1.4577; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('bootstrap', False), ('min_samples_leaf', 1), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('class_weight', None)]
  *FOLD R^2: 0.1479 (MSE: 2.0627; MAE: 1.1620; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('bootstrap', False), ('min_samples_leaf', 1), ('verbose', 0), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('class_weight', None)]
  *FOLD R^2: 0.0727 (MSE: 2.1409; MAE: 1.2069; mean train mae: 1.2725)
*Overall R^2:          0.0512
*Overall FOLDS R^2:    0.0108 (+- 0.0506)
*R (sqrt R^2):         0.2264
*Pearson r:            0.2504 (p = 0.00000)
*Folds Pearson r:      0.2669 (p = 0.22292)
*Spearman rho:         0.2777 (p = 0.00000)
*Mean Squared Error:   2.3817
*Mean Absolute Error:  1.2168
*Train_Mean MAE:       0.4097

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.22637834460458453,
                        'R2': 0.051247154905912029,
                        'R2_folds': 0.010825132409690453,
                        'mae': 1.2167595048629531,
                        'mae_folds': 1.2172234502923975,
                        'mse': 2.3817048076923077,
                        'mse_folds': 2.3834112670077978,
                        'num_features': 103,
                        'r': 0.25041434010980596,
                        'r_folds': 0.26687202349848338,
                        'r_p': 8.4488221631333551e-07,
                        'r_p_folds': 0.22292094960850681,
                        'rho': 0.27767149043712397,
                        'rho_folds': 0.27096679909993665,
                        'rho_p': 4.2133824835898569e-08,
                        'rho_p_folds': 0.24838773388761942,
                        'se_R2_folds': 0.050576413035098577,
                        'se_mae_folds': 0.066087202413546597,
                        'se_mse_folds': 0.31393224843195411,
                        'se_r_folds': 0.073771651716749764,
                        'se_r_p_folds': 0.17283599153282231,
                        'se_rho_folds': 0.079521516448919222,
                        'se_rho_p_folds': 0.15544170503552759,
                        'se_train_mean_mae_folds': 0.072108818846987693,
                        'test_size': 75,
                        'train_mean_mae': 0.40966281805026883,
                        'train_mean_mae_folds': 1.2705838568390793,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_LIWC2022_lw$merged_data$message_id$1gra
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.96 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [3]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 13:52:01
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 374 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 374]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('random_state', 42), ('n_estimators', 1200), ('max_depth', None), ('warm_start', False), ('max_leaf_nodes', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('n_jobs', 12), ('min_impurity_split', 1e-07)]
  *FOLD R^2: -0.2265 (MSE: 5.3487; MAE: 1.8802; mean train mae: 1.6373)
Fold 1
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('random_state', 42), ('n_estimators', 1200), ('max_depth', None), ('warm_start', False), ('max_leaf_nodes', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('n_jobs', 12), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0405 (MSE: 7.6034; MAE: 2.0736; mean train mae: 2.0914)
Fold 2
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('random_state', 42), ('n_estimators', 1200), ('max_depth', None), ('warm_start', False), ('max_leaf_nodes', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('n_jobs', 12), ('min_impurity_split', 1e-07)]
  *FOLD R^2: -0.1106 (MSE: 3.0007; MAE: 1.2821; mean train mae: 1.1460)
Fold 3
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('random_state', 42), ('n_estimators', 1200), ('max_depth', None), ('warm_start', False), ('max_leaf_nodes', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('n_jobs', 12), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0714 (MSE: 4.9761; MAE: 1.7201; mean train mae: 1.8061)
Fold 4
   (feature group: 0): [Initial size: 374]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('oob_score', False), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('random_state', 42), ('n_estimators', 1200), ('max_depth', None), ('warm_start', False), ('max_leaf_nodes', None), ('class_weight', None), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('n_jobs', 12), ('min_impurity_split', 1e-07)]
  *FOLD R^2: 0.0590 (MSE: 5.1670; MAE: 1.5941; mean train mae: 1.6135)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0071
*Overall FOLDS R^2:    -0.0332 (+- 0.0522)
*R (sqrt R^2):         nan
*Pearson r:            0.1608 (p = 0.00234)
*Folds Pearson r:      0.1679 (p = 0.26192)
*Spearman rho:         0.1567 (p = 0.00303)
*Mean Squared Error:   5.2195
*Mean Absolute Error:  1.7105
*Train_Mean MAE:       0.6119

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.0071189163973588432,
                        'R2_folds': -0.033240838102477688,
                        'mae': 1.7104939138576782,
                        'mae_folds': 1.7100159102764736,
                        'mse': 5.2195422265137328,
                        'mse_folds': 5.2191783869653099,
                        'num_features': 103,
                        'r': 0.16078257618229197,
                        'r_folds': 0.16786919708443068,
                        'r_p': 0.0023439557333627191,
                        'r_p_folds': 0.26192424821313198,
                        'rho': 0.15671729555720415,
                        'rho_folds': 0.16325389698660855,
                        'rho_p': 0.0030280323353387398,
                        'rho_p_folds': 0.143273950140965,
                        'se_R2_folds': 0.052244907786054486,
                        'se_mae_folds': 0.11963409662186322,
                        'se_mse_folds': 0.65375280163686555,
                        'se_r_folds': 0.047775844180215632,
                        'se_r_p_folds': 0.14398293801928572,
                        'se_rho_folds': 0.067054959240702247,
                        'se_rho_p_folds': 0.064488047460661613,
                        'se_train_mean_mae_folds': 0.13773807905205235,
                        'test_size': 71,
                        'train_mean_mae': 0.61188441589866605,
                        'train_mean_mae_folds': 1.6588806523350628,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_LIWC2022_lw$merged_data$message_id$1gra
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.75 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [4]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 13:52:16
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('class_weight', None), ('bootstrap', False), ('min_samples_leaf', 1), ('max_depth', None), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('warm_start', False), ('random_state', 42), ('verbose', 0), ('min_samples_split', 2), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0689 (MSE: 2.7370; MAE: 1.3000; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('class_weight', None), ('bootstrap', False), ('min_samples_leaf', 1), ('max_depth', None), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('warm_start', False), ('random_state', 42), ('verbose', 0), ('min_samples_split', 2), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.3049 (MSE: 2.4612; MAE: 1.2873; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('class_weight', None), ('bootstrap', False), ('min_samples_leaf', 1), ('max_depth', None), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('warm_start', False), ('random_state', 42), ('verbose', 0), ('min_samples_split', 2), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0172 (MSE: 3.9284; MAE: 1.4811; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('class_weight', None), ('bootstrap', False), ('min_samples_leaf', 1), ('max_depth', None), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('warm_start', False), ('random_state', 42), ('verbose', 0), ('min_samples_split', 2), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1538 (MSE: 2.1736; MAE: 1.1301; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 103)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 103)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('class_weight', None), ('bootstrap', False), ('min_samples_leaf', 1), ('max_depth', None), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('warm_start', False), ('random_state', 42), ('verbose', 0), ('min_samples_split', 2), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 103), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.1308 (MSE: 3.1583; MAE: 1.4231; mean train mae: 1.3612)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0007
*Overall FOLDS R^2:    -0.0460 (+- 0.0716)
*R (sqrt R^2):         nan
*Pearson r:            0.1593 (p = 0.00258)
*Folds Pearson r:      0.1856 (p = 0.35322)
*Spearman rho:         0.1854 (p = 0.00044)
*Mean Squared Error:   2.8913
*Mean Absolute Error:  1.3243
*Train_Mean MAE:       0.4138

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': nan,
                        'R2': -0.00065941793104462576,
                        'R2_folds': -0.046039519875115634,
                        'mae': 1.3242649812734082,
                        'mae_folds': 1.3243332029212311,
                        'mse': 2.8912816479400751,
                        'mse_folds': 2.8917162522278734,
                        'num_features': 103,
                        'r': 0.15928016793002098,
                        'r_folds': 0.18555889081745697,
                        'r_p': 0.0025783876752349106,
                        'r_p_folds': 0.35321573629574232,
                        'rho': 0.18537137125439046,
                        'rho_folds': 0.19914412824338493,
                        'rho_p': 0.00043843467748945237,
                        'rho_p_folds': 0.34453661114688483,
                        'se_R2_folds': 0.071597667198602888,
                        'se_mae_folds': 0.054412174599202126,
                        'se_mse_folds': 0.27355426894849966,
                        'se_r_folds': 0.077657523592093436,
                        'se_r_p_folds': 0.14143332860431099,
                        'se_rho_folds': 0.07024743635674123,
                        'se_rho_p_folds': 0.15751927897070112,
                        'se_train_mean_mae_folds': 0.034262972911295757,
                        'test_size': 71,
                        'train_mean_mae': 0.41377782687371129,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_LIWC2022_lw$merged_data$message_id$1gra
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.12 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:04:07
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_samples_split', 2), ('verbose', 0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 101), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('class_weight', None), ('warm_start', False), ('oob_score', False), ('min_impurity_split', 1e-07), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('random_state', 42), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0248 (MSE: 4.7302; MAE: 1.6928; mean train mae: 1.7631)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_samples_split', 2), ('verbose', 0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 101), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('class_weight', None), ('warm_start', False), ('oob_score', False), ('min_impurity_split', 1e-07), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('random_state', 42), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0518 (MSE: 5.2305; MAE: 1.6581; mean train mae: 1.6116)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_samples_split', 2), ('verbose', 0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 101), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('class_weight', None), ('warm_start', False), ('oob_score', False), ('min_impurity_split', 1e-07), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('random_state', 42), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0650 (MSE: 3.9295; MAE: 1.5116; mean train mae: 1.4249)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_samples_split', 2), ('verbose', 0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 101), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('class_weight', None), ('warm_start', False), ('oob_score', False), ('min_impurity_split', 1e-07), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('random_state', 42), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0465 (MSE: 3.2057; MAE: 1.3302; mean train mae: 1.3929)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_outputs_', 1), ('min_samples_split', 2), ('verbose', 0), ('n_estimators', 1200), ('bootstrap', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 101), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('class_weight', None), ('warm_start', False), ('oob_score', False), ('min_impurity_split', 1e-07), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('random_state', 42), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0287 (MSE: 3.2627; MAE: 1.3716; mean train mae: 1.4173)
*Overall R^2:          0.0048
*Overall FOLDS R^2:    -0.0133 (+- 0.0196)
*R (sqrt R^2):         0.0693
*Pearson r:            0.1561 (p = 0.00230)
*Folds Pearson r:      0.1657 (p = 0.28847)
*Spearman rho:         0.1668 (p = 0.00112)
*Mean Squared Error:   4.0738
*Mean Absolute Error:  1.5132
*Train_Mean MAE:       0.4645

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': 0.069255059059235846,
                        'R2': 0.0047962632052982457,
                        'R2_folds': -0.013266966146630033,
                        'mae': 1.5132211961301669,
                        'mae_folds': 1.5128483918128655,
                        'mse': 4.0738357794635007,
                        'mse_folds': 4.071701261720273,
                        'num_features': 101,
                        'r': 0.1561272403792722,
                        'r_folds': 0.16574232816236054,
                        'r_p': 0.0023025785086004846,
                        'r_p_folds': 0.28846964341762471,
                        'rho': 0.1667884436464134,
                        'rho_folds': 0.15354484734831275,
                        'rho_p': 0.0011174386521344457,
                        'rho_p_folds': 0.28185944438534072,
                        'se_R2_folds': 0.019633225195934002,
                        'se_mae_folds': 0.065364512479684667,
                        'se_mse_folds': 0.35782340745841568,
                        'se_r_folds': 0.044035625079037743,
                        'se_r_p_folds': 0.13572019191946888,
                        'se_rho_folds': 0.05461135106949299,
                        'se_rho_p_folds': 0.13186798913818515,
                        'se_train_mean_mae_folds': 0.064260640824542747,
                        'test_size': 75,
                        'train_mean_mae': 0.46446914529974037,
                        'train_mean_mae_folds': 1.5219657807886053,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.93 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [2]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:04:22
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('n_features_', 101), ('max_leaf_nodes', None), ('min_samples_split', 2), ('warm_start', False), ('verbose', 0), ('n_estimators', 1200), ('min_samples_leaf', 1), ('class_weight', None), ('random_state', 42), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('oob_score', False)]
  *FOLD R^2: 0.0968 (MSE: 1.4767; MAE: 0.9963; mean train mae: 0.9881)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('n_features_', 101), ('max_leaf_nodes', None), ('min_samples_split', 2), ('warm_start', False), ('verbose', 0), ('n_estimators', 1200), ('min_samples_leaf', 1), ('class_weight', None), ('random_state', 42), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('oob_score', False)]
  *FOLD R^2: 0.0764 (MSE: 2.2258; MAE: 1.1743; mean train mae: 1.2166)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('n_features_', 101), ('max_leaf_nodes', None), ('min_samples_split', 2), ('warm_start', False), ('verbose', 0), ('n_estimators', 1200), ('min_samples_leaf', 1), ('class_weight', None), ('random_state', 42), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('oob_score', False)]
  *FOLD R^2: -0.0606 (MSE: 2.8741; MAE: 1.3544; mean train mae: 1.3061)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('n_features_', 101), ('max_leaf_nodes', None), ('min_samples_split', 2), ('warm_start', False), ('verbose', 0), ('n_estimators', 1200), ('min_samples_leaf', 1), ('class_weight', None), ('random_state', 42), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('oob_score', False)]
  *FOLD R^2: 0.0448 (MSE: 2.9171; MAE: 1.4126; mean train mae: 1.4482)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_impurity_split', 1e-07), ('n_features_', 101), ('max_leaf_nodes', None), ('min_samples_split', 2), ('warm_start', False), ('verbose', 0), ('n_estimators', 1200), ('min_samples_leaf', 1), ('class_weight', None), ('random_state', 42), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('oob_score', False)]
  *FOLD R^2: -0.0728 (MSE: 2.0025; MAE: 1.1855; mean train mae: 1.1876)
*Overall R^2:          0.0257
*Overall FOLDS R^2:    0.0169 (+- 0.0315)
*R (sqrt R^2):         0.1604
*Pearson r:            0.1910 (p = 0.00018)
*Folds Pearson r:      0.2344 (p = 0.15403)
*Spearman rho:         0.1916 (p = 0.00018)
*Mean Squared Error:   2.3000
*Mean Absolute Error:  1.2247
*Train_Mean MAE:       0.3529

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': 0.16038026563171379,
                        'R2': 0.025721829604099078,
                        'R2_folds': 0.016924039547521509,
                        'mae': 1.2247163588390502,
                        'mae_folds': 1.2246131286549709,
                        'mse': 2.3000238621372029,
                        'mse_folds': 2.2992408473927877,
                        'num_features': 101,
                        'r': 0.19102982638635052,
                        'r_folds': 0.23435751103653621,
                        'r_p': 0.00018315914746999074,
                        'r_p_folds': 0.15402777666194362,
                        'rho': 0.1915681555942037,
                        'rho_folds': 0.23056703632011785,
                        'rho_p': 0.00017548482817958329,
                        'rho_p_folds': 0.16938960166883693,
                        'se_R2_folds': 0.031460582321323365,
                        'se_mae_folds': 0.065842015799507464,
                        'se_mse_folds': 0.24349954432610788,
                        'se_r_folds': 0.045619520005196916,
                        'se_r_p_folds': 0.11694585133776197,
                        'se_rho_folds': 0.047922829496439966,
                        'se_rho_p_folds': 0.12414545051345376,
                        'se_train_mean_mae_folds': 0.067496961857478818,
                        'test_size': 75,
                        'train_mean_mae': 0.35294981353977389,
                        'train_mean_mae_folds': 1.2293448844884489,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.63 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [3]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:04:38
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('n_features_', 101), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_samples_split', 2), ('n_outputs_', 1), ('class_weight', None)]
  *FOLD R^2: -0.2678 (MSE: 6.1476; MAE: 1.9961; mean train mae: 1.7185)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('n_features_', 101), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_samples_split', 2), ('n_outputs_', 1), ('class_weight', None)]
  *FOLD R^2: -0.1348 (MSE: 5.9714; MAE: 1.7403; mean train mae: 1.7737)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('n_features_', 101), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_samples_split', 2), ('n_outputs_', 1), ('class_weight', None)]
  *FOLD R^2: 0.0682 (MSE: 4.8872; MAE: 1.7309; mean train mae: 1.7502)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 299    Test size: 74]
 X[0]: (N, features): (299, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (299, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('n_features_', 101), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_samples_split', 2), ('n_outputs_', 1), ('class_weight', None)]
  *FOLD R^2: -0.0147 (MSE: 5.9436; MAE: 1.7883; mean train mae: 1.7214)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 299    Test size: 74]
 X[0]: (N, features): (299, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (299, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('n_features_', 101), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('min_samples_leaf', 1), ('random_state', 42), ('max_leaf_nodes', None), ('n_estimators', 1200), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('verbose', 0), ('min_samples_split', 2), ('n_outputs_', 1), ('class_weight', None)]
  *FOLD R^2: -0.0864 (MSE: 5.1759; MAE: 1.6619; mean train mae: 1.6157)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0390
*Overall FOLDS R^2:    -0.0871 (+- 0.0507)
*R (sqrt R^2):         nan
*Pearson r:            0.0862 (p = 0.09646)
*Folds Pearson r:      0.1556 (p = 0.24482)
*Spearman rho:         0.0918 (p = 0.07656)
*Mean Squared Error:   5.6255
*Mean Absolute Error:  1.7838
*Train_Mean MAE:       0.5481

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 373,
                        'R': nan,
                        'R2': -0.0389723974991254,
                        'R2_folds': -0.087083317483233807,
                        'mae': 1.7838047363717604,
                        'mae_folds': 1.7834916516516519,
                        'mse': 5.625501331173667,
                        'mse_folds': 5.6251506487987983,
                        'num_features': 101,
                        'r': 0.086198972311548508,
                        'r_folds': 0.15563467748831278,
                        'r_p': 0.096455392735287235,
                        'r_p_folds': 0.24482186642385867,
                        'rho': 0.091813267501638665,
                        'rho_folds': 0.16454768712311293,
                        'rho_p': 0.076560793622713133,
                        'rho_p_folds': 0.20313910946332209,
                        'se_R2_folds': 0.05071331552648687,
                        'se_mae_folds': 0.050850697189125396,
                        'se_mse_folds': 0.22276959050925851,
                        'se_r_folds': 0.028973025777875951,
                        'se_r_p_folds': 0.087446454042924934,
                        'se_rho_folds': 0.025600428833417867,
                        'se_rho_p_folds': 0.055816410713988254,
                        'se_train_mean_mae_folds': 0.024163286428984253,
                        'test_size': 74,
                        'train_mean_mae': 0.54812325851068666,
                        'train_mean_mae_folds': 1.7159151113583562,
                        'train_size': 299,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.82 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:04:53
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('bootstrap', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_jobs', 12), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('warm_start', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('verbose', 0), ('n_features_', 101), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.1001 (MSE: 1.8141; MAE: 1.0769; mean train mae: 1.0692)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('bootstrap', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_jobs', 12), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('warm_start', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('verbose', 0), ('n_features_', 101), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0318 (MSE: 5.5757; MAE: 1.8772; mean train mae: 1.8770)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 298    Test size: 75]
 X[0]: (N, features): (298, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (298, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('bootstrap', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_jobs', 12), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('warm_start', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('verbose', 0), ('n_features_', 101), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0166 (MSE: 2.6528; MAE: 1.3391; mean train mae: 1.3486)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 299    Test size: 74]
 X[0]: (N, features): (299, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (299, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('bootstrap', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_jobs', 12), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('warm_start', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('verbose', 0), ('n_features_', 101), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0620 (MSE: 2.2050; MAE: 1.2215; mean train mae: 1.2901)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 299    Test size: 74]
 X[0]: (N, features): (299, 101)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (299, 101)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 101)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('bootstrap', False), ('class_weight', None), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_jobs', 12), ('random_state', 42), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('warm_start', False), ('n_outputs_', 1), ('min_samples_leaf', 1), ('verbose', 0), ('n_features_', 101), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.1766 (MSE: 2.2225; MAE: 1.1470; mean train mae: 1.0784)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0275
*Overall FOLDS R^2:    -0.0460 (+- 0.0378)
*R (sqrt R^2):         nan
*Pearson r:            0.0931 (p = 0.07254)
*Folds Pearson r:      0.1224 (p = 0.42724)
*Spearman rho:         0.1248 (p = 0.01588)
*Mean Squared Error:   2.8977
*Mean Absolute Error:  1.3331
*Train_Mean MAE:       0.3509

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 373,
                        'R': nan,
                        'R2': -0.027479635563478766,
                        'R2_folds': -0.045980644166490794,
                        'mae': 1.3331277926720286,
                        'mae_folds': 1.3323338138138139,
                        'mse': 2.8976566689008036,
                        'mse_folds': 2.8940091708708708,
                        'num_features': 101,
                        'r': 0.093088855229598116,
                        'r_folds': 0.12241856844002068,
                        'r_p': 0.072540474221824566,
                        'r_p_folds': 0.42723520546018712,
                        'rho': 0.12480586141169257,
                        'rho_folds': 0.12798827007617533,
                        'rho_p': 0.015876245745403996,
                        'rho_p_folds': 0.35104894524197106,
                        'se_R2_folds': 0.037815353091851446,
                        'se_mae_folds': 0.12786822457661642,
                        'se_mse_folds': 0.61126910954571723,
                        'se_r_folds': 0.042353231622015083,
                        'se_r_p_folds': 0.14928916015841884,
                        'se_rho_folds': 0.045284167737339766,
                        'se_rho_p_folds': 0.1230369688600388,
                        'se_train_mean_mae_folds': 0.13151330698492839,
                        'test_size': 74,
                        'train_mean_mae': 0.35091381619456291,
                        'train_mean_mae_folds': 1.3326400851256412,
                        'train_size': 299,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 11.39 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [6]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 14:07:18
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 391 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('warm_start', False), ('oob_score', False), ('n_features_', 1313), ('class_weight', None), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('verbose', 0), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('n_jobs', 12)]
  *FOLD R^2: 0.0498 (MSE: 2.6881; MAE: 1.2596; mean train mae: 1.2682)
Fold 1
   (feature group: 0): [Initial size: 391]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('warm_start', False), ('oob_score', False), ('n_features_', 1313), ('class_weight', None), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('verbose', 0), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('n_jobs', 12)]
  *FOLD R^2: 0.0325 (MSE: 2.9970; MAE: 1.3730; mean train mae: 1.4211)
Fold 2
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('warm_start', False), ('oob_score', False), ('n_features_', 1313), ('class_weight', None), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('verbose', 0), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('n_jobs', 12)]
  *FOLD R^2: 0.0852 (MSE: 3.7785; MAE: 1.4813; mean train mae: 1.5804)
Fold 3
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('warm_start', False), ('oob_score', False), ('n_features_', 1313), ('class_weight', None), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('verbose', 0), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('n_jobs', 12)]
  *FOLD R^2: 0.0953 (MSE: 4.3367; MAE: 1.5054; mean train mae: 1.5684)
Fold 4
   (feature group: 0): [Initial size: 391]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('warm_start', False), ('oob_score', False), ('n_features_', 1313), ('class_weight', None), ('max_depth', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('verbose', 0), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('n_jobs', 12)]
  *FOLD R^2: 0.0820 (MSE: 4.4143; MAE: 1.5252; mean train mae: 1.6607)
*Overall R^2:          0.0863
*Overall FOLDS R^2:    0.0690 (+- 0.0106)
*R (sqrt R^2):         0.2938
*Pearson r:            0.2997 (p = 0.00000)
*Folds Pearson r:      0.3014 (p = 0.01472)
*Spearman rho:         0.2333 (p = 0.00000)
*Mean Squared Error:   3.6387
*Mean Absolute Error:  1.4283
*Train_Mean MAE:       0.4863

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.2937662918691748,
                        'R2': 0.086298634238565208,
                        'R2_folds': 0.06897383315254986,
                        'mae': 1.4282935455349248,
                        'mae_folds': 1.4288909064327484,
                        'mse': 3.6386694849690544,
                        'mse_folds': 3.6429154063109168,
                        'num_features': 1313,
                        'r': 0.29966188455672804,
                        'r_folds': 0.30142266415650931,
                        'r_p': 2.9202657963302167e-09,
                        'r_p_folds': 0.014719411919362105,
                        'rho': 0.23330682115317694,
                        'rho_folds': 0.23588314546972583,
                        'rho_p': 4.6879084346323096e-06,
                        'rho_p_folds': 0.052628471647547526,
                        'se_R2_folds': 0.010637778680413443,
                        'se_mae_folds': 0.044570418924643536,
                        'se_mse_folds': 0.31135850063821108,
                        'se_r_folds': 0.018749045107929341,
                        'se_r_p_folds': 0.0081143597820510557,
                        'se_rho_folds': 0.01731661968959114,
                        'se_rho_p_folds': 0.016738261435054556,
                        'se_train_mean_mae_folds': 0.062265467210680825,
                        'test_size': 75,
                        'train_mean_mae': 0.48630890482120698,
                        'train_mean_mae_folds': 1.4997635533466347,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$1to3gram$merged_data$message_id$0_05$pmi6_0
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 37.50 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 14:07:59
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 400 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('n_outputs_', 1), ('oob_score', False), ('n_features_', 1313), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_depth', None), ('random_state', 42), ('min_samples_split', 2), ('class_weight', None), ('max_leaf_nodes', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0249 (MSE: 2.8831; MAE: 1.3692; mean train mae: 1.3094)
Fold 1
   (feature group: 0): [Initial size: 400]
 [Train size: 301    Test size: 76]
 X[0]: (N, features): (301, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (301, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('n_outputs_', 1), ('oob_score', False), ('n_features_', 1313), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_depth', None), ('random_state', 42), ('min_samples_split', 2), ('class_weight', None), ('max_leaf_nodes', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0555 (MSE: 1.2068; MAE: 0.8953; mean train mae: 0.9666)
Fold 2
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('n_outputs_', 1), ('oob_score', False), ('n_features_', 1313), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_depth', None), ('random_state', 42), ('min_samples_split', 2), ('class_weight', None), ('max_leaf_nodes', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0364 (MSE: 3.2592; MAE: 1.3884; mean train mae: 1.4289)
Fold 3
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('n_outputs_', 1), ('oob_score', False), ('n_features_', 1313), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_depth', None), ('random_state', 42), ('min_samples_split', 2), ('class_weight', None), ('max_leaf_nodes', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1863 (MSE: 1.9696; MAE: 1.1228; mean train mae: 1.3755)
Fold 4
   (feature group: 0): [Initial size: 400]
 [Train size: 302    Test size: 75]
 X[0]: (N, features): (302, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (302, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('n_outputs_', 1), ('oob_score', False), ('n_features_', 1313), ('n_estimators', 1200), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('verbose', 0), ('max_depth', None), ('random_state', 42), ('min_samples_split', 2), ('class_weight', None), ('max_leaf_nodes', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0787 (MSE: 2.1268; MAE: 1.1846; mean train mae: 1.2725)
*Overall R^2:          0.0887
*Overall FOLDS R^2:    0.0664 (+- 0.0309)
*R (sqrt R^2):         0.2977
*Pearson r:            0.3033 (p = 0.00000)
*Folds Pearson r:      0.3131 (p = 0.04823)
*Spearman rho:         0.3490 (p = 0.00000)
*Mean Squared Error:   2.2878
*Mean Absolute Error:  1.1917
*Train_Mean MAE:       0.4329

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 377,
                        'R': 0.29774419943717806,
                        'R2': 0.088651608298486062,
                        'R2_folds': 0.066412478087089971,
                        'mae': 1.1917484526967286,
                        'mae_folds': 1.1920657309941518,
                        'mse': 2.2878064157824936,
                        'mse_folds': 2.289101657017544,
                        'num_features': 1313,
                        'r': 0.30329373050632252,
                        'r_folds': 0.31310223903893253,
                        'r_p': 1.8378676170522922e-09,
                        'r_p_folds': 0.048234575119149484,
                        'rho': 0.34901501627791576,
                        'rho_folds': 0.33326549935307215,
                        'rho_p': 3.0658558455768589e-12,
                        'rho_p_folds': 0.046506053461448947,
                        'se_R2_folds': 0.030910193304090523,
                        'se_mae_folds': 0.080707479813235228,
                        'se_mse_folds': 0.3220878071379798,
                        'se_r_folds': 0.057772898120496893,
                        'se_r_p_folds': 0.027066662944164578,
                        'se_rho_folds': 0.057256091035674354,
                        'se_rho_p_folds': 0.036036333667085793,
                        'se_train_mean_mae_folds': 0.072108818846987666,
                        'test_size': 75,
                        'train_mean_mae': 0.43293309247233142,
                        'train_mean_mae_folds': 1.2705838568390793,
                        'train_size': 302,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$1to3gram$merged_data$message_id$0_05$pmi6_0
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 36.41 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [5]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:06:54
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 289    Test size: 71]
 X[0]: (N, features): (289, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (289, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_jobs', 12), ('n_features_', 1313), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('min_impurity_split', 1e-07), ('class_weight', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('verbose', 0), ('n_outputs_', 1), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('warm_start', False), ('random_state', 42)]
  *FOLD R^2: -0.1073 (MSE: 5.6518; MAE: 1.8479; mean train mae: 1.7855)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 288    Test size: 72]
 X[0]: (N, features): (288, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (288, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_jobs', 12), ('n_features_', 1313), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('min_impurity_split', 1e-07), ('class_weight', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('verbose', 0), ('n_outputs_', 1), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('warm_start', False), ('random_state', 42)]
  *FOLD R^2: -0.1928 (MSE: 6.3385; MAE: 1.8342; mean train mae: 1.7928)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 287    Test size: 73]
 X[0]: (N, features): (287, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (287, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_jobs', 12), ('n_features_', 1313), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('min_impurity_split', 1e-07), ('class_weight', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('verbose', 0), ('n_outputs_', 1), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('warm_start', False), ('random_state', 42)]
  *FOLD R^2: 0.0753 (MSE: 4.7384; MAE: 1.6488; mean train mae: 1.7262)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 288    Test size: 72]
 X[0]: (N, features): (288, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (288, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_jobs', 12), ('n_features_', 1313), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('min_impurity_split', 1e-07), ('class_weight', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('verbose', 0), ('n_outputs_', 1), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('warm_start', False), ('random_state', 42)]
  *FOLD R^2: -0.0450 (MSE: 6.1756; MAE: 1.7751; mean train mae: 1.7165)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 288    Test size: 72]
 X[0]: (N, features): (288, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (288, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_jobs', 12), ('n_features_', 1313), ('max_leaf_nodes', None), ('min_weight_fraction_leaf', 0.0), ('oob_score', False), ('min_impurity_split', 1e-07), ('class_weight', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('verbose', 0), ('n_outputs_', 1), ('bootstrap', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_depth', None), ('warm_start', False), ('random_state', 42)]
  *FOLD R^2: -0.0116 (MSE: 4.6036; MAE: 1.6557; mean train mae: 1.5706)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0149
*Overall FOLDS R^2:    -0.0563 (+- 0.0403)
*R (sqrt R^2):         nan
*Pearson r:            0.1290 (p = 0.01433)
*Folds Pearson r:      0.1711 (p = 0.34977)
*Spearman rho:         0.1250 (p = 0.01766)
*Mean Squared Error:   5.4990
*Mean Absolute Error:  1.7518
*Train_Mean MAE:       0.5453

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 360,
                        'R': nan,
                        'R2': -0.014932667536325939,
                        'R2_folds': -0.056286111865105681,
                        'mae': 1.7517893518518519,
                        'mae_folds': 1.7523422089487712,
                        'mse': 5.49904772183642,
                        'mse_folds': 5.5015847268770859,
                        'num_features': 1313,
                        'r': 0.1289768891513742,
                        'r_folds': 0.17110243578466067,
                        'r_p': 0.014329708782622999,
                        'r_p_folds': 0.3497717529529058,
                        'rho': 0.12499141885011048,
                        'rho_folds': 0.17433904447684073,
                        'rho_p': 0.017662941627175612,
                        'rho_p_folds': 0.33455961019289771,
                        'se_R2_folds': 0.04032835961132742,
                        'se_mae_folds': 0.03816186765095482,
                        'se_mse_folds': 0.32037729500146911,
                        'se_r_folds': 0.053903377885042618,
                        'se_r_p_folds': 0.1783657780700231,
                        'se_rho_folds': 0.054616259808626021,
                        'se_rho_p_folds': 0.15946878231629832,
                        'se_train_mean_mae_folds': 0.03575003328440543,
                        'test_size': 72,
                        'train_mean_mae': 0.54533873456790127,
                        'train_mean_mae_folds': 1.7183288027181245,
                        'train_size': 288,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$1to3gram$merged_data$message_id$0_05$pmi6_0
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 37.54 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

#### ExtraTrees Predictions with Text Features

Extra Trees Regressor using text-based features and linguistic patterns

In [9]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 14:10:12
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_features_', 1313), ('bootstrap', False), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('class_weight', None), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_jobs', 12), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0300 (MSE: 2.8514; MAE: 1.3607; mean train mae: 1.4112)
Fold 1
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_features_', 1313), ('bootstrap', False), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('class_weight', None), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_jobs', 12), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.1024 (MSE: 2.0793; MAE: 1.2280; mean train mae: 1.2655)
Fold 2
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_features_', 1313), ('bootstrap', False), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('class_weight', None), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_jobs', 12), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0398 (MSE: 4.0158; MAE: 1.4974; mean train mae: 1.4677)
Fold 3
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_features_', 1313), ('bootstrap', False), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('class_weight', None), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_jobs', 12), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.1383 (MSE: 2.2133; MAE: 1.1792; mean train mae: 1.2809)
Fold 4
   (feature group: 0): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 1313)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1313)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('n_features_', 1313), ('bootstrap', False), ('min_samples_split', 2), ('min_impurity_split', 1e-07), ('class_weight', None), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_jobs', 12), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0511 (MSE: 2.9359; MAE: 1.3760; mean train mae: 1.3612)
*Overall R^2:          0.0243
*Overall FOLDS R^2:    -0.0050 (+- 0.0372)
*R (sqrt R^2):         0.1558
*Pearson r:            0.1939 (p = 0.00023)
*Folds Pearson r:      0.2036 (p = 0.28150)
*Spearman rho:         0.1921 (p = 0.00027)
*Mean Squared Error:   2.8192
*Mean Absolute Error:  1.3283
*Train_Mean MAE:       0.3868

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.15582781292743733,
                        'R2': 0.024282307281748405,
                        'R2_folds': -0.0050065084948835992,
                        'mae': 1.3283426966292133,
                        'mae_folds': 1.3282515975482527,
                        'mse': 2.8192156171972531,
                        'mse_folds': 2.8191250612121799,
                        'num_features': 1313,
                        'r': 0.19389264549118135,
                        'r_folds': 0.20356446685076177,
                        'r_p': 0.0002327956610570787,
                        'r_p_folds': 0.28150166205686966,
                        'rho': 0.19205526789560162,
                        'rho_folds': 0.19825728358787664,
                        'rho_p': 0.00026745909954631916,
                        'rho_p_folds': 0.24917801705862286,
                        'se_R2_folds': 0.037199383497685125,
                        'se_mae_folds': 0.050674881950902972,
                        'se_mse_folds': 0.30732462972117486,
                        'se_r_folds': 0.06003940762979984,
                        'se_r_p_folds': 0.14814284202853278,
                        'se_rho_folds': 0.051817066762247482,
                        'se_rho_p_folds': 0.13961828196517351,
                        'se_train_mean_mae_folds': 0.034262972911295708,
                        'test_size': 71,
                        'train_mean_mae': 0.38677087278542277,
                        'train_mean_mae_folds': 1.3573058232435549,
                        'train_size': 285,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$1to3gram$merged_data$message_id$0_05$pmi6_0
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 33.51 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [6]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:08:33
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 291    Test size: 74]
 X[0]: (N, features): (291, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (291, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (291, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (291, 1690)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 1690)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_estimators', 1200), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_depth', None), ('warm_start', False), ('n_features_', 1690), ('max_leaf_nodes', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('oob_score', False), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.0710 (MSE: 4.3947; MAE: 1.6513; mean train mae: 1.7919)
Fold 1
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 291    Test size: 74]
 X[0]: (N, features): (291, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (291, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (291, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (291, 1690)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 1690)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_estimators', 1200), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_depth', None), ('warm_start', False), ('n_features_', 1690), ('max_leaf_nodes', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('oob_score', False), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.0339 (MSE: 4.9237; MAE: 1.6365; mean train mae: 1.6570)
Fold 2
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 292    Test size: 73]
 X[0]: (N, features): (292, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (292, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (292, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (292, 1690)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1690)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_estimators', 1200), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_depth', None), ('warm_start', False), ('n_features_', 1690), ('max_leaf_nodes', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('oob_score', False), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: -0.0241 (MSE: 3.6653; MAE: 1.4601; mean train mae: 1.4135)
Fold 3
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 292    Test size: 73]
 X[0]: (N, features): (292, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (292, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (292, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (292, 1690)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1690)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_estimators', 1200), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_depth', None), ('warm_start', False), ('n_features_', 1690), ('max_leaf_nodes', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('oob_score', False), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.0732 (MSE: 2.7487; MAE: 1.2199; mean train mae: 1.2941)
Fold 4
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 294    Test size: 71]
 X[0]: (N, features): (294, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (294, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (294, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (294, 1690)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1690)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_estimators', 1200), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('max_depth', None), ('warm_start', False), ('n_features_', 1690), ('max_leaf_nodes', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('oob_score', False), ('min_impurity_split', 1e-07), ('bootstrap', False), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12)]
  *FOLD R^2: 0.0257 (MSE: 3.3743; MAE: 1.4183; mean train mae: 1.4251)
*Overall R^2:          0.0546
*Overall FOLDS R^2:    0.0359 (+- 0.0159)
*R (sqrt R^2):         0.2336
*Pearson r:            0.2442 (p = 0.00000)
*Folds Pearson r:      0.2554 (p = 0.11261)
*Spearman rho:         0.1734 (p = 0.00088)
*Mean Squared Error:   3.8284
*Mean Absolute Error:  1.4785
*Train_Mean MAE:       0.4297

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 365,
                        'R': 0.23356048958487852,
                        'R2': 0.054550502295128145,
                        'R2_folds': 0.035911118485868185,
                        'mae': 1.4784543378995436,
                        'mae_folds': 1.4772181829717039,
                        'mse': 3.8283803177321154,
                        'mse_folds': 3.8213401323837339,
                        'num_features': 1690,
                        'r': 0.24416753712015546,
                        'r_folds': 0.25540653817106901,
                        'r_p': 2.3532370289671751e-06,
                        'r_p_folds': 0.11261127818870346,
                        'rho': 0.17342313227114003,
                        'rho_folds': 0.17750330492049532,
                        'rho_p': 0.00087747069848547615,
                        'rho_p_folds': 0.2941211929207857,
                        'se_R2_folds': 0.015917087617044509,
                        'se_mae_folds': 0.070899015546981192,
                        'se_mse_folds': 0.341679896125197,
                        'se_r_folds': 0.043652595568051622,
                        'se_r_p_folds': 0.086479085260377855,
                        'se_rho_folds': 0.050347429914083072,
                        'se_rho_p_folds': 0.13582879430217557,
                        'se_train_mean_mae_folds': 0.080989114180771579,
                        'test_size': 71,
                        'train_mean_mae': 0.42965318696440857,
                        'train_mean_mae_folds': 1.5163262337875092,
                        'train_size': 294,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$cat_LIWC2022_lw$merged_data$message_id$1gra', 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra', 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0']
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 44.50 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:09:21
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1494)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1494)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_features_', 1494), ('warm_start', False), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('oob_score', False), ('bootstrap', False), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0)]
  *FOLD R^2: 0.1662 (MSE: 1.3848; MAE: 0.9345; mean train mae: 1.0100)
Fold 1
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 287    Test size: 69]
 X[0]: (N, features): (287, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (287, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (287, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (287, 1494)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 1494)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_features_', 1494), ('warm_start', False), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('oob_score', False), ('bootstrap', False), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0)]
  *FOLD R^2: 0.1504 (MSE: 1.9187; MAE: 1.0770; mean train mae: 1.1750)
Fold 2
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 282    Test size: 74]
 X[0]: (N, features): (282, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (282, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (282, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (282, 1494)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 1494)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_features_', 1494), ('warm_start', False), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('oob_score', False), ('bootstrap', False), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0)]
  *FOLD R^2: -0.0511 (MSE: 2.8501; MAE: 1.3043; mean train mae: 1.2984)
Fold 3
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 283    Test size: 73]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 1494)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1494)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_features_', 1494), ('warm_start', False), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('oob_score', False), ('bootstrap', False), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0)]
  *FOLD R^2: 0.1145 (MSE: 2.6625; MAE: 1.3482; mean train mae: 1.4261)
Fold 4
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
 [Train size: 287    Test size: 69]
 X[0]: (N, features): (287, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (287, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (287, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (287, 1494)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 1494)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_depth', None), ('n_features_', 1494), ('warm_start', False), ('verbose', 0), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('min_samples_leaf', 1), ('n_estimators', 1200), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('oob_score', False), ('bootstrap', False), ('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0)]
  *FOLD R^2: -0.0593 (MSE: 2.0696; MAE: 1.2219; mean train mae: 1.2278)
*Overall R^2:          0.0724
*Overall FOLDS R^2:    0.0642 (+- 0.0442)
*R (sqrt R^2):         0.2691
*Pearson r:            0.2720 (p = 0.00000)
*Folds Pearson r:      0.3132 (p = 0.11757)
*Spearman rho:         0.2844 (p = 0.00000)
*Mean Squared Error:   2.1876
*Mean Absolute Error:  1.1795
*Train_Mean MAE:       0.3803

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.26912217314001752,
                        'R2': 0.072426744075605565,
                        'R2_folds': 0.064154019722090672,
                        'mae': 1.1795248127340825,
                        'mae_folds': 1.1771817816587653,
                        'mse': 2.187602069678527,
                        'mse_folds': 2.1771483553235731,
                        'num_features': 1494,
                        'r': 0.27201584804211459,
                        'r_folds': 0.31321306965783469,
                        'r_p': 1.8585541259472603e-07,
                        'r_p_folds': 0.11756551394792611,
                        'rho': 0.28440406857221973,
                        'rho_folds': 0.31813158360471894,
                        'rho_p': 4.7500631259213954e-08,
                        'rho_p_folds': 0.089771587642567888,
                        'se_R2_folds': 0.044220237852129488,
                        'se_mae_folds': 0.068207619158760724,
                        'se_mse_folds': 0.23618263818606675,
                        'se_r_folds': 0.063926875165402866,
                        'se_r_p_folds': 0.093072885114720408,
                        'se_rho_folds': 0.059381737459191203,
                        'se_rho_p_folds': 0.07333850893917343,
                        'se_train_mean_mae_folds': 0.061491701168845177,
                        'test_size': 69,
                        'train_mean_mae': 0.38026104132474853,
                        'train_mean_mae_folds': 1.2274712898902258,
                        'train_size': 287,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$cat_LIWC2022_lw$merged_data$message_id$1gra', 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra', 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0']
Outcome table - stratified_female
Outcome(s) - CEL_Total
-------
Interface Runtime: 37.90 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [8]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:10:02
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 285    Test size: 70]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1688)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (70, 1688)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('class_weight', None), ('n_features_', 1688), ('random_state', 42), ('oob_score', False), ('warm_start', False), ('min_impurity_split', 1e-07), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('bootstrap', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0864 (MSE: 5.5029; MAE: 1.8148; mean train mae: 1.7777)
Fold 1
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 286    Test size: 69]
 X[0]: (N, features): (286, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (286, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (286, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (286, 1688)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 1688)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('class_weight', None), ('n_features_', 1688), ('random_state', 42), ('oob_score', False), ('warm_start', False), ('min_impurity_split', 1e-07), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('bootstrap', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.2033 (MSE: 6.1255; MAE: 1.7194; mean train mae: 1.7113)
Fold 2
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 282    Test size: 73]
 X[0]: (N, features): (282, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (282, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (282, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (282, 1688)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1688)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('class_weight', None), ('n_features_', 1688), ('random_state', 42), ('oob_score', False), ('warm_start', False), ('min_impurity_split', 1e-07), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('bootstrap', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0979 (MSE: 4.6223; MAE: 1.6084; mean train mae: 1.7313)
Fold 3
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 283    Test size: 72]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 1688)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1688)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('class_weight', None), ('n_features_', 1688), ('random_state', 42), ('oob_score', False), ('warm_start', False), ('min_impurity_split', 1e-07), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('bootstrap', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0633 (MSE: 6.2840; MAE: 1.8222; mean train mae: 1.7145)
Fold 4
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 284    Test size: 71]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1688)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1688)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('class_weight', None), ('n_features_', 1688), ('random_state', 42), ('oob_score', False), ('warm_start', False), ('min_impurity_split', 1e-07), ('max_depth', None), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('bootstrap', False), ('n_estimators', 1200), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0087 (MSE: 3.8594; MAE: 1.5395; mean train mae: 1.4831)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0148
*Overall FOLDS R^2:    -0.0528 (+- 0.0441)
*R (sqrt R^2):         nan
*Pearson r:            0.1451 (p = 0.00618)
*Folds Pearson r:      0.2116 (p = 0.36167)
*Spearman rho:         0.1291 (p = 0.01495)
*Mean Squared Error:   5.2726
*Mean Absolute Error:  1.7003
*Train_Mean MAE:       0.5639

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 355,
                        'R': nan,
                        'R2': -0.014779754538478906,
                        'R2_folds': -0.052750063470725861,
                        'mae': 1.7002676056338029,
                        'mae_folds': 1.7008722469836557,
                        'mse': 5.2725548435054774,
                        'mse_folds': 5.2788237201160673,
                        'num_features': 1688,
                        'r': 0.14507033098032318,
                        'r_folds': 0.21164250837102996,
                        'r_p': 0.0061777643499590033,
                        'r_p_folds': 0.36167114286313262,
                        'rho': 0.12907164161211382,
                        'rho_folds': 0.20326606408378961,
                        'rho_p': 0.01495336763999237,
                        'rho_p_folds': 0.20823387076739083,
                        'se_R2_folds': 0.04407097997204755,
                        'se_mae_folds': 0.05005525436382452,
                        'se_mse_folds': 0.41100770013429011,
                        'se_r_folds': 0.072201422342914032,
                        'se_r_p_folds': 0.19759802351571648,
                        'se_rho_folds': 0.064990337434533293,
                        'se_rho_p_folds': 0.12291937187831257,
                        'se_train_mean_mae_folds': 0.046064816768988978,
                        'test_size': 71,
                        'train_mean_mae': 0.56386563512530585,
                        'train_mean_mae_folds': 1.6835568691844707,
                        'train_size': 284,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$cat_LIWC2022_lw$merged_data$message_id$1gra', 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra', 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0']
Outcome table - stratified_white
Outcome(s) - CEL_Total
-------
Interface Runtime: 46.14 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [9]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:10:52
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1408)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1408)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('n_estimators', 1200), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1408), ('class_weight', None), ('warm_start', False)]
  *FOLD R^2: -0.0837 (MSE: 1.8430; MAE: 1.0958; mean train mae: 1.0890)
Fold 1
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 283    Test size: 73]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 1408)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 1408)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('n_estimators', 1200), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1408), ('class_weight', None), ('warm_start', False)]
  *FOLD R^2: 0.0481 (MSE: 5.2353; MAE: 1.8283; mean train mae: 1.8963)
Fold 2
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 1408)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 1408)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('n_estimators', 1200), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1408), ('class_weight', None), ('warm_start', False)]
  *FOLD R^2: 0.0248 (MSE: 2.6877; MAE: 1.3349; mean train mae: 1.3558)
Fold 3
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 1408)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 1408)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('n_estimators', 1200), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1408), ('class_weight', None), ('warm_start', False)]
  *FOLD R^2: 0.0038 (MSE: 2.3695; MAE: 1.2575; mean train mae: 1.2992)
Fold 4
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
 [Train size: 288    Test size: 68]
 X[0]: (N, features): (288, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (288, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (288, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (288, 1408)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (68, 1408)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_samples_split', 2), ('min_weight_fraction_leaf', 0.0), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('n_jobs', 12), ('oob_score', False), ('n_estimators', 1200), ('random_state', 42), ('verbose', 0), ('min_samples_leaf', 1), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_features_', 1408), ('class_weight', None), ('warm_start', False)]
  *FOLD R^2: 0.0656 (MSE: 1.8066; MAE: 1.0661; mean train mae: 1.0780)
*Overall R^2:          0.0283
*Overall FOLDS R^2:    0.0117 (+- 0.0233)
*R (sqrt R^2):         0.1683
*Pearson r:            0.1931 (p = 0.00025)
*Folds Pearson r:      0.2146 (p = 0.09594)
*Spearman rho:         0.1832 (p = 0.00051)
*Mean Squared Error:   2.8075
*Mean Absolute Error:  1.3209
*Train_Mean MAE:       0.3704

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 356,
                        'R': 0.16833012416286169,
                        'R2': 0.028335030700684438,
                        'R2_folds': 0.011706162244938634,
                        'mae': 1.320941011235955,
                        'mae_folds': 1.3165237076538978,
                        'mse': 2.8075057740324594,
                        'mse_folds': 2.7884246306465803,
                        'num_features': 1408,
                        'r': 0.19309965381657707,
                        'r_folds': 0.21462486924286056,
                        'r_p': 0.00024720653637285464,
                        'r_p_folds': 0.095939452474319564,
                        'rho': 0.18321444982280005,
                        'rho_folds': 0.18864898415096829,
                        'rho_p': 0.00051242049876376182,
                        'rho_p_folds': 0.12413760092206147,
                        'se_R2_folds': 0.023296857507427406,
                        'se_mae_folds': 0.12281942039744828,
                        'se_mse_folds': 0.56675598794259696,
                        'se_r_folds': 0.022099386580733734,
                        'se_r_p_folds': 0.031193221691806491,
                        'se_rho_folds': 0.012956566412494827,
                        'se_rho_p_folds': 0.022445607577555021,
                        'se_train_mean_mae_folds': 0.13311084708923651,
                        'test_size': 68,
                        'train_mean_mae': 0.3703622753861045,
                        'train_mean_mae_folds': 1.3436817864983912,
                        'train_size': 288,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$cat_LIWC2022_lw$merged_data$message_id$1gra', 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra', 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0']
Outcome table - stratified_black
Outcome(s) - CEL_Total
-------
Interface Runtime: 39.96 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [10]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_male$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:11:36
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 291    Test size: 74]
 X[0]: (N, features): (291, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (291, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (291, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (291, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (291, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (291, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (291, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (291, 2840)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 2840)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_features_', 2840), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('bootstrap', False), ('class_weight', None), ('n_estimators', 1200), ('warm_start', False), ('n_jobs', 12), ('min_samples_leaf', 1), ('n_outputs_', 1), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.1618 (MSE: 3.9653; MAE: 1.5808; mean train mae: 1.7919)
Fold 1
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 291    Test size: 74]
 X[0]: (N, features): (291, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (291, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (291, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (291, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (291, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (291, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (291, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (291, 2840)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 2840)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_features_', 2840), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('bootstrap', False), ('class_weight', None), ('n_estimators', 1200), ('warm_start', False), ('n_jobs', 12), ('min_samples_leaf', 1), ('n_outputs_', 1), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0548 (MSE: 5.3758; MAE: 1.7232; mean train mae: 1.6570)
Fold 2
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 292    Test size: 73]
 X[0]: (N, features): (292, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (292, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (292, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (292, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (292, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (292, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (292, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (292, 2840)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 2840)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_features_', 2840), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('bootstrap', False), ('class_weight', None), ('n_estimators', 1200), ('warm_start', False), ('n_jobs', 12), ('min_samples_leaf', 1), ('n_outputs_', 1), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0406 (MSE: 3.4337; MAE: 1.4179; mean train mae: 1.4135)
Fold 3
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 292    Test size: 73]
 X[0]: (N, features): (292, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (292, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (292, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (292, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (292, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (292, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (292, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (292, 2840)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 2840)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_features_', 2840), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('bootstrap', False), ('class_weight', None), ('n_estimators', 1200), ('warm_start', False), ('n_jobs', 12), ('min_samples_leaf', 1), ('n_outputs_', 1), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0598 (MSE: 2.7882; MAE: 1.2176; mean train mae: 1.2941)
Fold 4
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 294    Test size: 71]
 X[0]: (N, features): (294, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (294, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (294, 1486)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (294, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (294, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (294, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (294, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (294, 2840)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 2840)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_split', 2), ('n_features_', 2840), ('min_impurity_split', 1e-07), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,

In [11]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_female$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:13:03
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 2644)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 2644)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_split', 2), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('n_outputs_', 1), ('class_weight', None), ('n_features_', 2644), ('min_impurity_split', 1e-07), ('random_state', 42), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1812 (MSE: 1.3599; MAE: 0.9273; mean train mae: 1.0100)
Fold 1
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 287    Test size: 69]
 X[0]: (N, features): (287, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (287, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (287, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (287, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (287, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (287, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (287, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (287, 2644)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 2644)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_split', 2), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('n_outputs_', 1), ('class_weight', None), ('n_features_', 2644), ('min_impurity_split', 1e-07), ('random_state', 42), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0834 (MSE: 2.0699; MAE: 1.1059; mean train mae: 1.1750)
Fold 2
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 282    Test size: 74]
 X[0]: (N, features): (282, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (282, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (282, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (282, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (282, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (282, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (282, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (282, 2644)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (74, 2644)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_split', 2), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('n_outputs_', 1), ('class_weight', None), ('n_features_', 2644), ('min_impurity_split', 1e-07), ('random_state', 42), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: -0.0371 (MSE: 2.8122; MAE: 1.3271; mean train mae: 1.2984)
Fold 3
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 283    Test size: 73]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (283, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (283, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (283, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (283, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 2644)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 2644)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_split', 2), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('n_outputs_', 1), ('class_weight', None), ('n_features_', 2644), ('min_impurity_split', 1e-07), ('random_state', 42), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0921 (MSE: 2.7300; MAE: 1.3743; mean train mae: 1.4261)
Fold 4
   (feature group: 0): [Initial size: 379]
   (feature group: 1): [Initial size: 379]
   (feature group: 2): [Initial size: 379]
   (feature group: 3): [Initial size: 379]
   (feature group: 4): [Initial size: 379]
   (feature group: 5): [Initial size: 379]
   (feature group: 6): [Initial size: 379]
 [Train size: 287    Test size: 69]
 X[0]: (N, features): (287, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (287, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (287, 1290)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (287, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (287, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (287, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (287, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (287, 2644)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 2644)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('verbose', 0), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('n_estimators', 1200), ('bootstrap', False), ('min_samples_split', 2), ('max_depth', None), ('oob_score', False), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('warm_start', False), ('n_outputs_', 1), ('class_weight', None), ('n_features_', 2644), ('min_impurity_split', 1e-07), ('random_state', 42), ('n_jobs', 12), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',

In [12]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_white$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:14:20
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 285    Test size: 70]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 2838)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (70, 2838)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_depth', None), ('warm_start', False), ('oob_score', False), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('n_features_', 2838), ('verbose', 0), ('bootstrap', False), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('n_jobs', 12)]
  *FOLD R^2: 0.1194 (MSE: 4.4607; MAE: 1.6512; mean train mae: 1.7777)
Fold 1
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 286    Test size: 69]
 X[0]: (N, features): (286, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (286, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (286, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (286, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (286, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (286, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (286, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (286, 2838)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (69, 2838)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_depth', None), ('warm_start', False), ('oob_score', False), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('n_features_', 2838), ('verbose', 0), ('bootstrap', False), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('n_jobs', 12)]
  *FOLD R^2: -0.0439 (MSE: 5.3142; MAE: 1.6210; mean train mae: 1.7113)
Fold 2
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 282    Test size: 73]
 X[0]: (N, features): (282, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (282, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (282, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (282, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (282, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (282, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (282, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (282, 2838)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 2838)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_depth', None), ('warm_start', False), ('oob_score', False), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('n_features_', 2838), ('verbose', 0), ('bootstrap', False), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('n_jobs', 12)]
  *FOLD R^2: 0.2345 (MSE: 3.9224; MAE: 1.4945; mean train mae: 1.7313)
Fold 3
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 283    Test size: 72]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (283, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (283, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (283, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (283, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 2838)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 2838)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_depth', None), ('warm_start', False), ('oob_score', False), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('n_features_', 2838), ('verbose', 0), ('bootstrap', False), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_samples_leaf', 1), ('n_jobs', 12)]
  *FOLD R^2: 0.0914 (MSE: 5.3696; MAE: 1.6209; mean train mae: 1.7145)
Fold 4
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 284    Test size: 71]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1484)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 2838)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 2838)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_depth', None), ('warm_start', False), ('oob_score', False), ('class_weight', None), ('n_outputs_', 1), ('min_weight_fraction_leaf', 0.0), ('n_features_', 2838), ('verbose', 0), ('bootstrap', False), ('max_leaf_nodes', None), ('min_samples_split', 2), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('random_state', 42), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,

In [13]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$stratified_black$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:15:43
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 373 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 2558)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 2558)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 2558), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2)]
  *FOLD R^2: -0.1340 (MSE: 1.9285; MAE: 1.1235; mean train mae: 1.0890)
Fold 1
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 283    Test size: 73]
 X[0]: (N, features): (283, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (283, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (283, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (283, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (283, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (283, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (283, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (283, 2558)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (73, 2558)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 2558), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2)]
  *FOLD R^2: 0.0444 (MSE: 5.2553; MAE: 1.7824; mean train mae: 1.8963)
Fold 2
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 284    Test size: 72]
 X[0]: (N, features): (284, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (284, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (284, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (284, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (284, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (284, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (284, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (284, 2558)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (72, 2558)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 2558), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2)]
  *FOLD R^2: 0.0372 (MSE: 2.6537; MAE: 1.3056; mean train mae: 1.3558)
Fold 3
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 285    Test size: 71]
 X[0]: (N, features): (285, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (285, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (285, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (285, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (285, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (285, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (285, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (285, 2558)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (71, 2558)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('oob_score', False), ('n_features_', 2558), ('n_estimators', 1200), ('min_weight_fraction_leaf', 0.0), ('verbose', 0), ('random_state', 42), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('max_leaf_nodes', None), ('warm_start', False), ('max_depth', None), ('min_samples_split', 2)]
  *FOLD R^2: 0.1838 (MSE: 1.9414; MAE: 1.1369; mean train mae: 1.2992)
Fold 4
   (feature group: 0): [Initial size: 373]
   (feature group: 1): [Initial size: 373]
   (feature group: 2): [Initial size: 373]
   (feature group: 3): [Initial size: 373]
   (feature group: 4): [Initial size: 373]
   (feature group: 5): [Initial size: 373]
   (feature group: 6): [Initial size: 373]
 [Train size: 288    Test size: 68]
 X[0]: (N, features): (288, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (288, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (288, 1204)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (288, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (288, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (288, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (288, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (288, 2558)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (68, 2558)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('n_outputs_', 1), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,

In [14]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:17:02
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1468 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
   (feature group: 3): [Initial size: 1468]
   (feature group: 4): [Initial size: 1468]
   (feature group: 5): [Initial size: 1468]
   (feature group: 6): [Initial size: 1468]
 [Train size: 1082    Test size: 272]
 X[0]: (N, features): (1082, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1082, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1082, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (1082, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (1082, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (1082, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (1082, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1082, 2667)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (272, 2667)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('random_state', 42), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('class_weight', None), ('verbose', 0), ('n_outputs_', 1), ('oob_score', False), ('n_estimators', 1200), ('n_features_', 2667)]
  *FOLD R^2: 0.0698 (MSE: 2.6857; MAE: 1.2326; mean train mae: 1.2906)
Fold 1
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
   (feature group: 3): [Initial size: 1468]
   (feature group: 4): [Initial size: 1468]
   (feature group: 5): [Initial size: 1468]
   (feature group: 6): [Initial size: 1468]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1084, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1084, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (1084, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (1084, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (1084, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (1084, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1084, 2667)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (270, 2667)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('random_state', 42), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('class_weight', None), ('verbose', 0), ('n_outputs_', 1), ('oob_score', False), ('n_estimators', 1200), ('n_features_', 2667)]
  *FOLD R^2: 0.0085 (MSE: 3.9604; MAE: 1.4183; mean train mae: 1.4728)
Fold 2
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
   (feature group: 3): [Initial size: 1468]
   (feature group: 4): [Initial size: 1468]
   (feature group: 5): [Initial size: 1468]
   (feature group: 6): [Initial size: 1468]
 [Train size: 1080    Test size: 274]
 X[0]: (N, features): (1080, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1080, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1080, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (1080, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (1080, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (1080, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (1080, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1080, 2667)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (274, 2667)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('random_state', 42), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('class_weight', None), ('verbose', 0), ('n_outputs_', 1), ('oob_score', False), ('n_estimators', 1200), ('n_features_', 2667)]
  *FOLD R^2: 0.0793 (MSE: 4.3630; MAE: 1.5913; mean train mae: 1.6967)
Fold 3
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
   (feature group: 3): [Initial size: 1468]
   (feature group: 4): [Initial size: 1468]
   (feature group: 5): [Initial size: 1468]
   (feature group: 6): [Initial size: 1468]
 [Train size: 1086    Test size: 268]
 X[0]: (N, features): (1086, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1086, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1086, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (1086, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (1086, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (1086, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (1086, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1086, 2667)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (268, 2667)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('random_state', 42), ('max_leaf_nodes', None), ('max_depth', None), ('bootstrap', False), ('n_jobs', 12), ('min_impurity_split', 1e-07), ('warm_start', False), ('class_weight', None), ('verbose', 0), ('n_outputs_', 1), ('oob_score', False), ('n_estimators', 1200), ('n_features_', 2667)]
  *FOLD R^2: 0.0770 (MSE: 2.6674; MAE: 1.2807; mean train mae: 1.3567)
Fold 4
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
   (feature group: 3): [Initial size: 1468]
   (feature group: 4): [Initial size: 1468]
   (feature group: 5): [Initial size: 1468]
   (feature group: 6): [Initial size: 1468]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1084, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1084, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[3]: (N, features): (1084, 38)
  [Applying StandardScaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[4]: (N, features): (1084, 88)
  [Applying StandardScaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[5]: (N, features): (1084, 512)
  [Applying StandardScaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[6]: (N, features): (1084, 512)
  [Applying StandardScaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1084, 2667)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[3]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[4]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[5]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[6]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (270, 2667)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,

In [15]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra' 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-11 15:22:54
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1468 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
 [Train size: 1082    Test size: 272]
 X[0]: (N, features): (1082, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1082, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1082, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1082, 1517)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (272, 1517)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('bootstrap', False), ('n_features_', 1517), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('n_jobs', 12), ('oob_score', False), ('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_depth', None)]
  *FOLD R^2: 0.0753 (MSE: 2.6698; MAE: 1.2034; mean train mae: 1.2906)
Fold 1
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1084, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1084, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1084, 1517)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (270, 1517)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('bootstrap', False), ('n_features_', 1517), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('n_jobs', 12), ('oob_score', False), ('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_depth', None)]
  *FOLD R^2: 0.0149 (MSE: 3.9349; MAE: 1.4369; mean train mae: 1.4728)
Fold 2
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
 [Train size: 1080    Test size: 274]
 X[0]: (N, features): (1080, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1080, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1080, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1080, 1517)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (274, 1517)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('bootstrap', False), ('n_features_', 1517), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('n_jobs', 12), ('oob_score', False), ('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_depth', None)]
  *FOLD R^2: 0.0586 (MSE: 4.4610; MAE: 1.6045; mean train mae: 1.6967)
Fold 3
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
 [Train size: 1086    Test size: 268]
 X[0]: (N, features): (1086, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1086, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1086, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1086, 1517)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (268, 1517)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('bootstrap', False), ('n_features_', 1517), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('n_jobs', 12), ('oob_score', False), ('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_depth', None)]
  *FOLD R^2: 0.0625 (MSE: 2.7091; MAE: 1.2695; mean train mae: 1.3567)
Fold 4
   (feature group: 0): [Initial size: 1468]
   (feature group: 1): [Initial size: 1468]
   (feature group: 2): [Initial size: 1468]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 103)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[1]: (N, features): (1084, 101)
  [Applying StandardScaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[2]: (N, features): (1084, 1313)
  [Applying StandardScaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (1084, 1517)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[1]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] applying *existing* standard scaler to X[2]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (270, 1517)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('max_leaf_nodes', None), ('min_samples_leaf', 1), ('min_samples_split', 2), ('verbose', 0), ('bootstrap', False), ('n_features_', 1517), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('random_state', 42), ('n_outputs_', 1), ('n_jobs', 12), ('oob_score', False), ('warm_start', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('class_weight', None), ('max_depth', None)]
  *FOLD R^2: 0.0673 (MSE: 4.2885; MAE: 1.5554; mean train mae: 1.6299)
*Overall R^2:          0.0627
*Overall FOLDS R^2:    0.0557 (+- 0.0095)
*R (sqrt R^2):         0.2504
*Pearson r:            0.2529 (p = 0.00000)
*Folds Pearson r:      0.2603 (p = 0.00022)
*Spearman rho:         0.2771 (p = 0.00000)
*Mean Squared Error:   3.6151
*Mean Absolute Error:  1.4144
*Train_Mean MAE:       0.3816

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 1354,
                        'R': 0.25036559659621194,
                        'R2': 0.062682931958977117,
                        'R2_folds': 0.055725676116318935,
                        'mae': 1.414411619891679,
                        'mae_folds': 1.4139461978938339,
                        'mse': 3.6151118794107995,
                        'mse_folds': 3.6126636607184737,
                        'num_features': 1517,
                        'r': 0.25292461410066469,
                        'r_folds': 0.26025754124985634,
                        'r_p': 3.314521431522356e-21,
                        'r_p_folds': 0.0002161466561013382,
                        'rho': 0.27710307760024916,
                        'rho_folds': 0.2788210099474871,
                        'rho_p': 2.7184968233475066e-25,
                        'rho_p_folds': 0.00065011178087625318,
                        'se_R2_folds': 0.0094653929151342821,
                        'se_mae_folds': 0.069864319300922406,
                        'se_mse_folds': 0.3455852378988169,
                        'se_r_folds': 0.016774679006665742,
                        'se_r_p_folds': 0.00018443771837598508,
                        'se_rho_folds': 0.023237605690564898,
                        'se_rho_p_folds': 0.00058080099175176667,
                        'se_train_mean_mae_folds': 0.069320616457029652,
                        'test_size': 270,
                        'train_mean_mae': 0.38155399105591536,
                        'train_mean_mae_folds': 1.4893486834564702,
                        'train_size': 1084,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - ['feat$cat_LIWC2022_lw$merged_data$message_id$1gra', 'feat$cat_klaatch_senten2_lda_cp_w$merged_data$message_id$1gra', 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0']
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 178.68 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [10]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-25 16:21:07
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]
^C

In [59]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$librosa_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:26:26
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 38)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 38), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0515 (MSE: 4.3863; MAE: 1.5316; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 38)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 38), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0328 (MSE: 3.8645; MAE: 1.5298; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 38)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 38), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0480 (MSE: 3.8618; MAE: 1.4523; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 38)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 38), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0041 (MSE: 3.5683; MAE: 1.4534; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 38)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 38)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 38)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 38), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0761 (MSE: 3.9458; MAE: 1.5412; mean train mae: 1.4633)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0177
*Overall FOLDS R^2:    -0.0233 (+- 0.0191)
*R (sqrt R^2):         nan
*Pearson r:            0.1398 (p = 0.00000)
*Folds Pearson r:      0.1380 (p = 0.10099)
*Spearman rho:         0.1509 (p = 0.00000)
*Mean Squared Error:   3.9250
*Mean Absolute Error:  1.5017
*Train_Mean MAE:       0.5058

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$librosa_n$merged_data$message_id
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 12.21 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

## XGBoost Model Predictions

Running XGBoost gradient boosting predictions across different feature types and subgroups

In [60]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$opensmile_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:26:41
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 88)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 88), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.1096 (MSE: 4.6290; MAE: 1.5937; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 88)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 88), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0536 (MSE: 3.9422; MAE: 1.5661; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 88)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 88), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0778 (MSE: 3.7411; MAE: 1.4383; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 88)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 88), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0219 (MSE: 3.6316; MAE: 1.4676; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 88)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 88)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 88)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 88), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0254 (MSE: 3.7599; MAE: 1.4968; mean train mae: 1.4633)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0216
*Overall FOLDS R^2:    -0.0265 (+- 0.0272)
*R (sqrt R^2):         nan
*Pearson r:            0.1440 (p = 0.00000)
*Folds Pearson r:      0.1440 (p = 0.15228)
*Spearman rho:         0.1596 (p = 0.00000)
*Mean Squared Error:   3.9403
*Mean Absolute Error:  1.5124
*Train_Mean MAE:       0.5334

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$opensmile_n$merged_data$message_id
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 18.59 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [61]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_mean_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:27:03
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0515 (MSE: 4.3862; MAE: 1.5138; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0337 (MSE: 3.8677; MAE: 1.5592; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0137 (MSE: 4.1123; MAE: 1.5155; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0332 (MSE: 3.4359; MAE: 1.3951; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0012 (MSE: 3.6626; MAE: 1.4693; mean train mae: 1.4633)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0093
*Overall FOLDS R^2:    -0.0129 (+- 0.0130)
*R (sqrt R^2):         nan
*Pearson r:            0.1070 (p = 0.00008)
*Folds Pearson r:      0.1196 (p = 0.13865)
*Spearman rho:         0.0997 (p = 0.00024)
*Mean Squared Error:   3.8926
*Mean Absolute Error:  1.4906
*Train_Mean MAE:       0.3561

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_mean_n$merged_data$message_id
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 81.20 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [62]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$whisper_median_n$merged_data$message_id' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:28:28
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0760 (MSE: 4.4884; MAE: 1.5464; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0252 (MSE: 3.8361; MAE: 1.5478; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0185 (MSE: 4.1316; MAE: 1.5126; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0027 (MSE: 3.5442; MAE: 1.4223; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 512)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 512)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 512)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 512), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0120 (MSE: 3.7108; MAE: 1.4795; mean train mae: 1.4633)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1398: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.0220
*Overall FOLDS R^2:    -0.0258 (+- 0.0120)
*R (sqrt R^2):         nan
*Pearson r:            0.0903 (p = 0.00087)
*Folds Pearson r:      0.1020 (p = 0.17131)
*Spearman rho:         0.0931 (p = 0.00060)
*Mean Squared Error:   3.9418
*Mean Absolute Error:  1.5017
*Train_Mean MAE:       0.3644

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$whisper_median_n$merged_data$message_id
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 79.07 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [ ]:
 'feat$opensmile_n$merged_data$message_id' 'feat$whisper_mean_n$merged_data$message_id' 'feat$whisper_median_n$merged_data$message_id'

In [55]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_LIWC2015_lw$merged_data$message_id$1gra' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:21:07
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 74)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 74)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 74)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 74), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0039 (MSE: 4.1553; MAE: 1.4797; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 74)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 74)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 74)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 74), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.1010 (MSE: 3.3636; MAE: 1.4782; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 74)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 74)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 74)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 74), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0836 (MSE: 3.7177; MAE: 1.4096; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 74)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 74)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 74)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 74), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0293 (MSE: 3.6580; MAE: 1.4258; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 74)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 74)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 74)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 74), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0590 (MSE: 3.4506; MAE: 1.4261; mean train mae: 1.4633)
*Overall R^2:          0.0488
*Overall FOLDS R^2:    0.0436 (+- 0.0219)
*R (sqrt R^2):         0.2209
*Pearson r:            0.2307 (p = 0.00000)
*Folds Pearson r:      0.2390 (p = 0.00563)
*Spearman rho:         0.2305 (p = 0.00000)
*Mean Squared Error:   3.6687
*Mean Absolute Error:  1.4439
*Train_Mean MAE:       0.4249

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_LIWC2015_lw$merged_data$message_id$1gra
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 17.81 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [56]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_Klaatch_50_cp_w$merged_data$message_id$1gra' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:21:28
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 270]
 X[0]: (N, features): (1083, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 51)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 51)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 51), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0191 (MSE: 4.2514; MAE: 1.4937; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1082    Test size: 271]
 X[0]: (N, features): (1082, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1082, 51)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 51)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 51), ('_n_samples', 1082), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0671 (MSE: 3.4907; MAE: 1.5088; mean train mae: 1.5527)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 270]
 X[0]: (N, features): (1083, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 51)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 51)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 51), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0022 (MSE: 4.0613; MAE: 1.5013; mean train mae: 1.5225)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1082    Test size: 271]
 X[0]: (N, features): (1082, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1082, 51)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 51)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 51), ('_n_samples', 1082), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0479 (MSE: 3.7239; MAE: 1.4688; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1082    Test size: 271]
 X[0]: (N, features): (1082, 51)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1082, 51)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 51)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 51), ('_n_samples', 1082), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0562 (MSE: 3.4608; MAE: 1.4266; mean train mae: 1.4633)
*Overall R^2:          0.0162
*Overall FOLDS R^2:    0.0117 (+- 0.0196)
*R (sqrt R^2):         0.1272
*Pearson r:            0.1769 (p = 0.00000)
*Folds Pearson r:      0.1916 (p = 0.02047)
*Spearman rho:         0.1863 (p = 0.00000)
*Mean Squared Error:   3.7971
*Mean Absolute Error:  1.4798
*Train_Mean MAE:       0.4366

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$cat_Klaatch_50_cp_w$merged_data$message_id$1gra
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 13.85 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [57]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$1to3gram$merged_data$message_id$0_05$pmi6_0' \
    --outcome_table merged_data  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --csv --output overall_csv

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 03:21:46
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 1354 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 1354]
 [Train size: 1084    Test size: 270]
 X[0]: (N, features): (1084, 1313)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1084, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (270, 1313)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 1313), ('_n_samples', 1084), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: -0.0201 (MSE: 4.2554; MAE: 1.4834; mean train mae: 1.4868)
Fold 1
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 1313)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 1313)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 1313), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.1236 (MSE: 3.2792; MAE: 1.4401; mean train mae: 1.5526)
Fold 2
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 1313)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 1313)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 1313), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0654 (MSE: 3.7912; MAE: 1.4025; mean train mae: 1.5187)
Fold 3
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 1313)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 1313)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 1313), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0447 (MSE: 3.3948; MAE: 1.3327; mean train mae: 1.4227)
Fold 4
   (feature group: 0): [Initial size: 1354]
 [Train size: 1083    Test size: 271]
 X[0]: (N, features): (1083, 1313)
  [Applying StandardScaler to X[0]: StandardScaler()]
[COMBINED FEATS (from multiX)] Combined size: (1083, 1313)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler()
[PREDICT] combined X shape: (271, 1313)
[PREDICT] regressor: ExtraTreesRegressor(n_estimators=1200, n_jobs=12, random_state=42)
settings:  [('estimator', ExtraTreeRegressor()), ('n_estimators', 1200), ('bootstrap', False), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('warm_start', False), ('class_weight', None), ('max_samples', None), ('max_depth', None), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_weight_fraction_leaf', 0.0), ('max_features', 1.0), ('max_leaf_nodes', None), ('min_impurity_decrease', 0.0), ('ccp_alpha', 0.0), ('monotonic_cst', None), ('n_features_in_', 1313), ('_n_samples', 1083), ('n_outputs_', 1), ('_n_samples_bootstrap', None), ('estimator_', ExtraTreeRegressor())]
  *FOLD R^2: 0.0755 (MSE: 3.3901; MAE: 1.4144; mean train mae: 1.4633)
*Overall R^2:          0.0610
*Overall FOLDS R^2:    0.0578 (+- 0.0209)
*R (sqrt R^2):         0.2469
*Pearson r:            0.2480 (p = 0.00000)
*Folds Pearson r:      0.2608 (p = 0.01497)
*Spearman rho:         0.2768 (p = 0.00000)
*Mean Squared Error:   3.6217
*Mean Absolute Error:  1.4146
*Train_Mean MAE:       0.3853

[TEST COMPLETE]

Wrote to: <_io.TextIOWrapper name='overall_csv.accuracy_data.csv' mode='w' encoding='UTF-8'>
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$1to3gram$merged_data$message_id$0_05$pmi6_0
Outcome table - merged_data
Outcome(s) - CEL_Total
-------
Interface Runtime: 151.71 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [1]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -g message_id \
-f 'feat$1to3gram$stratified_male$message_id' \
    --estimate_lda_topics \
    --mallet_path /home/karthik9/mallet-2.0.8RC3/bin/mallet \
    --lda_lexicon_name SMale_LDA_50 \
    --num_lda_threads 10 \
    --save_lda_files SMale_LDA_50 \
    --num_topics 50

/home/vinmayk/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
Warning: Cannot import langid (cannot use addLanguageFilterTable)
TopicExtractor: gensim Mallet wrapper unavailable, using Mallet directly.

-----
DLATK Interface Initiated: 2025-02-11 16:00:45
-----
Writing joined feature lines file: SMale_LDA_50/lda_msgs.txt.
Yielding values with zeros for 1354 groups * 432724 feats.
Wrote joined features file to: SMale_LDA_50/lda_msgs.txt
Estimating LDA topics. This may take a long time!
Estimating LDA topics using Mallet.
Traceback (most recent call last):
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 2266, in <module>
    main()
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 1162, in main
    state_file = lda_estimator.estimate_topics(args.printjoinedfeaturelines, args.mallet_path)
  File "/home/vinmayk/dlatk/dlatk/topicExtractor.py", line 308, in estimate_topics
    mallet = OurLdaMallet(mallet_path, id2word=corpora.Dictionary([["dummy"]]),
NameError: name 'corpora' is not defined

## Binary Classification: Loneliness Detection

Predicting loneliness as a binary outcome (lonely = 0, not lonely = 1)

## XGB

In [8]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_data$moe_male$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_data$moe_female$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_data$moe_white$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_data$moe_black$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:49:45
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('max_depth', None), ('max_leaf_nodes', None), ('n_features_', 6), ('verbose', 0), ('min_impurity_split', 1e-07), ('warm_start', False), ('bootstrap', False), ('n_jobs', 12), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('random_state', 42), ('min_samples_leaf', 1), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.2043 (MSE: 3.6725; MAE: 1.4679; mean train mae: 1.7631)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('max_depth', None), ('max_leaf_nodes', None), ('n_features_', 6), ('verbose', 0), ('min_impurity_split', 1e-07), ('warm_start', False), ('bootstrap', False), ('n_jobs', 12), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('random_state', 42), ('min_samples_leaf', 1), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1820 (MSE: 4.0679; MAE: 1.4276; mean train mae: 1.6116)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('max_depth', None), ('max_leaf_nodes', None), ('n_features_', 6), ('verbose', 0), ('min_impurity_split', 1e-07), ('warm_start', False), ('bootstrap', False), ('n_jobs', 12), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('random_state', 42), ('min_samples_leaf', 1), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1370 (MSE: 3.1844; MAE: 1.4332; mean train mae: 1.4249)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('max_depth', None), ('max_leaf_nodes', None), ('n_features_', 6), ('verbose', 0), ('min_impurity_split', 1e-07), ('warm_start', False), ('bootstrap', False), ('n_jobs', 12), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('random_state', 42), ('min_samples_leaf', 1), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0299 (MSE: 3.2617; MAE: 1.4661; mean train mae: 1.3929)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('n_estimators', 1200), ('max_depth', None), ('max_leaf_nodes', None), ('n_features_', 6), ('verbose', 0), ('min_impurity_split', 1e-07), ('warm_start', False), ('bootstrap', False), ('n_jobs', 12), ('n_outputs_', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('random_state', 42), ('min_samples_leaf', 1), ('oob_score', False), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.1416 (MSE: 2.8835; MAE: 1.2711; mean train mae: 1.4173)
*Overall R^2:          0.1656
*Overall FOLDS R^2:    0.1389 (+- 0.0269)
*R (sqrt R^2):         0.4070
*Pearson r:            0.4163 (p = 0.00000)
*Folds Pearson r:      0.4052 (p = 0.00288)
*Spearman rho:         0.4450 (p = 0.00000)
*Mean Squared Error:   3.4154
*Mean Absolute Error:  1.4135
*Train_Mean MAE:       0.8040

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': 0.40698842694814058,
                        'R2': 0.16563957966972198,
                        'R2_folds': 0.1389446202990039,
                        'mae': 1.4135356200527704,
                        'mae_folds': 1.4131607602339185,
                        'mse': 3.4154286279683381,
                        'mse_folds': 3.4140289054093573,
                        'num_features': 6,
                        'r': 0.4162611699759442,
                        'r_folds': 0.40522911602337003,
                        'r_p': 2.5794883565452969e-17,
                        'r_p_folds': 0.002882667685701861,
                        'rho': 0.44498987562000775,
                        'rho_folds': 0.42739043542939542,
                        'rho_p': 7.8676273284785074e-20,
                        'rho_p_folds': 0.006643496506187424,
                        'se_R2_folds': 0.026855378605952218,
                        'se_mae_folds': 0.032610227212086576,
                        'se_mse_folds': 0.18457380754185934,
                        'se_r_folds': 0.030518121297797719,
                        'se_r_p_folds': 0.0024373871034978609,
                        'se_rho_folds': 0.046620001973077828,
                        'se_rho_p_folds': 0.0058037948965713546,
                        'se_train_mean_mae_folds': 0.064260640824542678,
                        'test_size': 75,
                        'train_mean_mae': 0.80398587450658243,
                        'train_mean_mae_folds': 1.5219657807886051,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$combined_data$moe_male$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 9.90 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.


/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:49:59
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_jobs', 12), ('warm_start', False), ('oob_score', False), ('min_samples_leaf', 1), ('class_weight', None), ('max_depth', None), ('n_outputs_', 1), ('bootstrap', False), ('random_state', 42), ('n_estimators', 1200), ('n_features_', 6), ('max_leaf_nodes', None), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random'))]
  *FOLD R^2: 0.0103 (MSE: 1.6180; MAE: 0.9946; mean train mae: 0.9881)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 6)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 6)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 6)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('min_weight_fraction_leaf', 0.0), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_samples_split', 2), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,

In [7]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_text$moe_male$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_text$moe_female$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_text$moe_white$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_text$moe_black$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:48:29
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('n_features_', 3)]
  *FOLD R^2: -0.0739 (MSE: 4.9566; MAE: 1.7298; mean train mae: 1.7631)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('n_features_', 3)]
  *FOLD R^2: -0.1620 (MSE: 5.7786; MAE: 1.7616; mean train mae: 1.6116)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('n_features_', 3)]
  *FOLD R^2: -0.1376 (MSE: 4.1974; MAE: 1.6340; mean train mae: 1.4249)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('n_features_', 3)]
  *FOLD R^2: -0.1008 (MSE: 3.7012; MAE: 1.5841; mean train mae: 1.3929)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_estimators', 1200), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('max_leaf_nodes', None), ('warm_start', False), ('n_jobs', 12), ('min_weight_fraction_leaf', 0.0), ('n_outputs_', 1), ('min_samples_split', 2), ('min_samples_leaf', 1), ('min_impurity_split', 1e-07), ('bootstrap', False), ('verbose', 0), ('random_state', 42), ('max_depth', None), ('oob_score', False), ('n_features_', 3)]
  *FOLD R^2: -0.1624 (MSE: 3.9050; MAE: 1.4419; mean train mae: 1.4173)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1404: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1016
*Overall FOLDS R^2:    -0.1274 (+- 0.0156)
*R (sqrt R^2):         nan
*Pearson r:            0.1777 (p = 0.00051)
*Folds Pearson r:      0.1665 (p = 0.18188)
*Spearman rho:         0.1758 (p = 0.00059)
*Mean Squared Error:   4.5093
*Mean Absolute Error:  1.6308
*Train_Mean MAE:       0.8709

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': nan,
                        'R2': -0.10159213478923501,
                        'R2_folds': -0.12735668129987734,
                        'mae': 1.6307519788918208,
                        'mae_folds': 1.6302548830409358,
                        'mse': 4.5093334029610093,
                        'mse_folds': 4.5077429998781673,
                        'num_features': 3,
                        'r': 0.17767568919458912,
                        'r_folds': 0.16654136203167438,
                        'r_p': 0.00051039437375294272,
                        'r_p_folds': 0.18187958159039394,
                        'rho': 0.17582265071236083,
                        'rho_folds': 0.15622192274855451,
                        'rho_p': 0.00058512299941976406,
                        'rho_p_folds': 0.2416638768381712,
                        'se_R2_folds': 0.01561901281684565,
                        'se_mae_folds': 0.050907486046229002,
                        'se_mse_folds': 0.34215644535882156,
                        'se_r_folds': 0.020513205708664561,
                        'se_r_p_folds': 0.048399977757469181,
                        'se_rho_folds': 0.043221644290776656,
                        'se_rho_p_folds': 0.13260502792217574,
                        'se_train_mean_mae_folds': 0.064260640824542678,
                        'test_size': 75,
                        'train_mean_mae': 0.87086275274236924,
                        'train_mean_mae_folds': 1.5219657807886051,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$combined_text$moe_male$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.11 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.


/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:48:43
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_outputs_', 1), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('min_impurity_split', 1e-07), ('min_weight_fraction_leaf', 0.0), ('min_samples_split', 2), ('n_estimators', 1200), ('n_features_', 3), ('random_state', 42), ('verbose', 0), ('n_jobs', 12), ('oob_score', False), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('warm_start', False), ('max_depth', None), ('bootstrap', False), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0931 (MSE: 1.7871; MAE: 1.0481; mean train mae: 0.9881)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('class_weight', None), ('n_outputs_', 1), ('min_samples_leaf', 1), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,

In [9]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_audio$moe_male$message_id' \
    --outcome_table stratified_male  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_audio$moe_female$message_id' \
    --outcome_table stratified_female  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_audio$moe_white$message_id' \
    --outcome_table stratified_white  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model 


!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$combined_audio$moe_black$message_id' \
    --outcome_table stratified_black  --group_freq_thresh 1 \
    --outcomes CEL_Total \
    --nfold_test_regression --model extratrees --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:53:34
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 3), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('min_impurity_split', 1e-07), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_samples_split', 2), ('warm_start', False), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0987 (MSE: 5.0711; MAE: 1.7421; mean train mae: 1.7631)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 3), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('min_impurity_split', 1e-07), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_samples_split', 2), ('warm_start', False), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.2094 (MSE: 6.0140; MAE: 1.7643; mean train mae: 1.6116)
Fold 2
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 3), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('min_impurity_split', 1e-07), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_samples_split', 2), ('warm_start', False), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.0443 (MSE: 3.8532; MAE: 1.4921; mean train mae: 1.4249)
Fold 3
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 3), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('min_impurity_split', 1e-07), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_samples_split', 2), ('warm_start', False), ('max_leaf_nodes', None)]
  *FOLD R^2: -0.3937 (MSE: 4.6860; MAE: 1.7648; mean train mae: 1.3929)
Fold 4
   (feature group: 0): [Initial size: 379]
 [Train size: 304    Test size: 75]
 X[0]: (N, features): (304, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (304, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (75, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('n_features_', 3), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('class_weight', None), ('min_samples_leaf', 1), ('oob_score', False), ('n_jobs', 12), ('random_state', 42), ('verbose', 0), ('min_impurity_split', 1e-07), ('max_depth', None), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('bootstrap', False), ('min_samples_split', 2), ('warm_start', False), ('max_leaf_nodes', None)]
  *FOLD R^2: 0.0741 (MSE: 3.1105; MAE: 1.3929; mean train mae: 1.4173)
/home/vinmayk/dlatk/dlatk/regressionPredictor.py:1404: RuntimeWarning: invalid value encountered in sqrt
  reportStats['R'] = sqrt(reportStats['R2'])
*Overall R^2:          -0.1117
*Overall FOLDS R^2:    -0.1344 (+- 0.0709)
*R (sqrt R^2):         nan
*Pearson r:            0.1395 (p = 0.00651)
*Folds Pearson r:      0.1420 (p = 0.39021)
*Spearman rho:         0.1892 (p = 0.00021)
*Mean Squared Error:   4.5507
*Mean Absolute Error:  1.6319
*Train_Mean MAE:       0.7616

[TEST COMPLETE]

{'CEL_Total': {(): {1: {'N': 379,
                        'R': nan,
                        'R2': -0.11170823006485397,
                        'R2_folds': -0.13441137252884833,
                        'mae': 1.6318733509234828,
                        'mae_folds': 1.6312445614035085,
                        'mse': 4.5507433267370274,
                        'mse_folds': 4.5469531189083821,
                        'num_features': 3,
                        'r': 0.13952982658133595,
                        'r_folds': 0.14202963237062988,
                        'r_p': 0.0065143018120153388,
                        'r_p_folds': 0.39021240527525558,
                        'rho': 0.18924603736221615,
                        'rho_folds': 0.18894368017623114,
                        'rho_p': 0.00021089386951603944,
                        'rho_p_folds': 0.29655640326428573,
                        'se_R2_folds': 0.070916736555330512,
                        'se_mae_folds': 0.070414596437586283,
                        'se_mse_folds': 0.44680911850785904,
                        'se_r_folds': 0.065797113675999802,
                        'se_r_p_folds': 0.17717049936492257,
                        'se_rho_folds': 0.072561120015236791,
                        'se_rho_p_folds': 0.1498628246557509,
                        'se_train_mean_mae_folds': 0.064260640824542747,
                        'test_size': 75,
                        'train_mean_mae': 0.76157350617163611,
                        'train_mean_mae_folds': 1.5219657807886053,
                        'train_size': 304,
                        '{modelFS_desc}': 'None',
                        '{model_desc}': 'ExtraTreesRegressor(bootstrap=False, '
                                        "criterion='mse', max_depth=None,      "
                                        "max_features='auto', "
                                        'max_leaf_nodes=None,      '
                                        'min_impurity_split=1e-07, '
                                        'min_samples_leaf=1,      '
                                        'min_samples_split=2, '
                                        'min_weight_fraction_leaf=0.0,      '
                                        'n_estimators=1200, n_jobs=12, '
                                        'oob_score=False, '
                                        'random_state=42,      verbose=0, '
                                        'warm_start=False)'}}}}
-------
Settings:

Database - Audio_features
Corpus - merged_data
Group ID - message_id
Feature table(s) - feat$combined_audio$moe_male$message_id
Outcome table - stratified_male
Outcome(s) - CEL_Total
-------
Interface Runtime: 10.16 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.


/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-03-26 16:53:47
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
    ***explicit fold labels specified, not splitting again***
[number of groups: 379 (5 Folds)]


|COMBO: ()|
===========

= CEL_Total (w/ lang.)=
-----------------------
Fold 0
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('max_depth', None), ('random_state', 42), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('warm_start', False), ('n_features_', 3), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('class_weight', None), ('n_jobs', 12), ('base_estimator_', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, random_state=None,
          splitter='random')), ('n_outputs_', 1), ('min_samples_split', 2), ('oob_score', False)]
  *FOLD R^2: -0.1804 (MSE: 1.9298; MAE: 1.1175; mean train mae: 0.9881)
Fold 1
   (feature group: 0): [Initial size: 379]
 [Train size: 303    Test size: 76]
 X[0]: (N, features): (303, 3)
  [Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
[COMBINED FEATS (from multiX)] Combined size: (303, 3)
[COMBINED FEATS: Training regression model: extratrees]
model: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
[PREDICT] applying *existing* standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
[PREDICT] combined X shape: (76, 3)
[PREDICT] regressor: ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_split=1e-07, min_samples_leaf=1,
          min_samples_split=2, min_weight_fraction_leaf=0.0,
          n_estimators=1200, n_jobs=12, oob_score=False, random_state=42,
          verbose=0, warm_start=False)
settings:  [('bootstrap', False), ('max_depth', None), ('random_state', 42), ('min_samples_leaf', 1), ('max_leaf_nodes', None), ('min_impurity_split', 1e-07), ('verbose', 0), ('min_weight_fraction_leaf', 0.0), ('n_estimators', 1200), ('warm_start', False), ('n_features_', 3), ('base_estimator', ExtraTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
          max_leaf_nodes=None, min_impurity_split=1e-07,
          min_samples_leaf=1, min_samples_split=2,

## Topic Analysis and Interpretation

Retrieving and analyzing top topics/words associated with predictions using MySQL database queries

In [1]:
import sys
print(sys.executable)

/data/anaconda2/envs/dlatk/bin/python

In [1]:
!python /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t la_table -g message_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-08 14:05:39
-----
query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$1gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$1gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_id`),
query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$meta_1gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$meta_1gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_i
finding messages for 1468 'message_id's
SQL QUERY: ALTER TABLE feat$1gram$la_table$message_id DISABLE KEYS
 [0%] Inserted 123 total ngram rows covering 1 message_ids
 [5%] Inserted 30146 total ngram rows covering 74 message_ids
 [10%] Inserted 51111 total ngram rows covering 147 message_ids
 [15%] Inserted 78532 total ngram rows covering 221 message_ids
 [20%] Inserted 104833 total ngram rows covering 294 message_ids
 [25%] Inserted 129971 total ngram rows covering 367 message_ids
 [30%] Inserted 157166 total ngram rows covering 441 message_ids
 [35%] Inserted 177048 total ngram rows covering 514 message_ids
 [40%] Inserted 204426 total ngram rows covering 588 message_ids
 [45%] Inserted 225419 total ngram rows covering 661 message_ids
 [50%] Inserted 250646 total ngram rows covering 734 message_ids
 [55%] Inserted 271748 total ngram rows covering 808 message_ids
 [60%] Inserted 294119 total ngram rows covering 881 message_ids
 [65%] Inserted 320474 total ngram rows covering 955 message_ids
 [70%] Inserted 343618 total ngram rows covering 1028 message_ids
 [75%] Inserted 372125 total ngram rows covering 1101 message_ids
 [80%] Inserted 397018 total ngram rows covering 1175 message_ids
 [85%] Inserted 424130 total ngram rows covering 1248 message_ids
 [90%] Inserted 453840 total ngram rows covering 1322 message_ids
 [95%] Inserted 480017 total ngram rows covering 1395 message_ids
 [100%] Inserted 505225 total ngram rows covering 1468 message_ids
Done Reading / Inserting.
Adding Keys (if goes to keycache, then decrease MAX_TO_DISABLE_KEYS or run myisamchk -n).
SQL QUERY: ALTER TABLE feat$1gram$la_table$message_id ENABLE KEYS
Done

query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$2gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$2gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_id`),
query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$meta_2gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$meta_2gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_i
finding messages for 1468 'message_id's
SQL QUERY: ALTER TABLE feat$2gram$la_table$message_id DISABLE KEYS
 [0%] Inserted 213 total ngram rows covering 1 message_ids
 [5%] Inserted 93544 total ngram rows covering 74 message_ids
 [10%] Inserted 149779 total ngram rows covering 147 message_ids
 [15%] Inserted 234540 total ngram rows covering 221 message_ids
 [20%] Inserted 310208 total ngram rows covering 294 message_ids
 [25%] Inserted 382138 total ngram rows covering 367 message_ids
 [30%] Inserted 465774 total ngram rows covering 441 message_ids
 [35%] Inserted 520931 total ngram rows covering 514 message_ids
 [40%] Inserted 602984 total ngram rows covering 588 message_ids
 [45%] Inserted 659324 total ngram rows covering 661 message_ids
 [50%] Inserted 731753 total ngram rows covering 734 message_ids
 [55%] Inserted 789501 total ngram rows covering 808 message_ids
 [60%] Inserted 851941 total ngram rows covering 881 message_ids
 [65%] Inserted 930414 total ngram rows covering 955 message_ids
 [70%] Inserted 996542 total ngram rows covering 1028 message_ids
 [75%] Inserted 1085024 total ngram rows covering 1101 message_ids
 [80%] Inserted 1158419 total ngram rows covering 1175 message_ids
 [85%] Inserted 1238328 total ngram rows covering 1248 message_ids
 [90%] Inserted 1326880 total ngram rows covering 1322 message_ids
 [95%] Inserted 1402784 total ngram rows covering 1395 message_ids
 [100%] Inserted 1477821 total ngram rows covering 1468 message_ids
Done Reading / Inserting.
Adding Keys (if goes to keycache, then decrease MAX_TO_DISABLE_KEYS or run myisamchk -n).
SQL QUERY: ALTER TABLE feat$2gram$la_table$message_id ENABLE KEYS
Done

query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$3gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$3gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(102) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_id`),
query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$meta_3gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$meta_3gram$la_table$message_id ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field` (`group_i
finding messages for 1468 'message_id's
SQL QUERY: ALTER TABLE feat$3gram$la_table$message_id DISABLE KEYS
 [0%] Inserted 222 total ngram rows covering 1 message_ids
 [5%] Inserted 131550 total ngram rows covering 74 message_ids
 [10%] Inserted 205960 total ngram rows covering 147 message_ids
 [15%] Inserted 325498 total ngram rows covering 221 message_ids
 [20%] Inserted 428294 total ngram rows covering 294 message_ids
 [25%] Inserted 525579 total ngram rows covering 367 message_ids
 [30%] Inserted 643285 total ngram rows covering 441 message_ids
 [35%] Inserted 718371 total ngram rows covering 514 message_ids
 [40%] Inserted 831795 total ngram rows covering 588 message_ids
 [45%] Inserted 905925 total ngram rows covering 661 message_ids
 [50%] Inserted 1004467 total ngram rows covering 734 message_ids
 [55%] Inserted 1082124 total ngram rows covering 808 message_ids
 [60%] Inserted 1166078 total ngram rows covering 881 message_ids
 [65%] Inserted 1276198 total ngram rows covering 955 message_ids
 [70%] Inserted 1365176 total ngram rows covering 1028 message_ids
 [75%] Inserted 1491097 total ngram rows covering 1101 message_ids
 [80%] Inserted 1593373 total ngram rows covering 1175 message_ids
 [85%] Inserted 1703338 total ngram rows covering 1248 message_ids
 [90%] Inserted 1825907 total ngram rows covering 1322 message_ids
 [95%] Inserted 1931019 total ngram rows covering 1395 message_ids
 [100%] Inserted 2034853 total ngram rows covering 1468 message_ids
Done Reading / Inserting.
Adding Keys (if goes to keycache, then decrease MAX_TO_DISABLE_KEYS or run myisamchk -n).
SQL QUERY: ALTER TABLE feat$3gram$la_table$message_id ENABLE KEYS
Done

SQL QUERY: DROP TABLE IF EXISTS feat$1to3gram$la_table$message_id
SQL QUERY: CREATE TABLE feat$1to3gram$la_table$message_id ( id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(102), value int(11), group_norm DOUBLE, KEY `correl_field` (`group_id`), KEY `feature` (`feat`)) CHARACTER SET utf8mb4
SQL QUERY: ALTER TABLE feat$1to3gram$la_table$message_id DISABLE KEYS
SQL QUERY: INSERT INTO feat$1to3gram$la_table$message_id (group_id, feat, value, group_norm) SELECT group_id, feat, value, group_norm from feat$1gram$la_table$message_id;
SQL QUERY: INSERT INTO feat$1to3gram$la_table$message_id (group_id, feat, value, group_norm) SELECT group_id, feat, value, group_norm from feat$2gram$la_table$message_id;
SQL QUERY: INSERT INTO feat$1to3gram$la_table$message_id (group_id, feat, value, group_norm) SELECT group_id, feat, value, group_norm from feat$3gram$la_table$message_id;
SQL QUERY: ALTER TABLE feat$1to3gram$la_table$message_id ENABLE KEYS
-------
Settings:

Database - Audio_features
Corpus - la_table
Group ID - message_id
Feature table(s) - feat$1to3gram$la_table$message_id
-------
Interface Runtime: 209.43 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

In [2]:
!python /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t la_table -c message_id --add_lex_table -l LIWC2022 --liwc_normalization

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-08 14:09:12
-----
###################################################################
  WARNING: The lexicon you specified has weights, but you didn't
  specify --weighted_lexicon so the weights won't be used
###################################################################
query: SELECT column_type FROM information_schema.columns WHERE table_schema='Audio_features' AND table_name='la_table' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$cat_LIWC2022_lw$la_table$message_id$1gra
SQL QUERY: CREATE TABLE feat$cat_LIWC2022_lw$la_table$message_id$1gra ( id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, group_id varchar(191), feat VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE, KEY `correl_field`
WORD TABLE feat$1gram$la_table$message_id
SQL QUERY: ALTER TABLE feat$cat_LIWC2022_lw$la_table$message_id$1gra DISABLE KEYS
14 out of 1468 group Id's processed; 0.01 complete
28 out of 1468 group Id's processed; 0.02 complete
42 out of 1468 group Id's processed; 0.03 complete
56 out of 1468 group Id's processed; 0.04 complete
70 out of 1468 group Id's processed; 0.05 complete
84 out of 1468 group Id's processed; 0.06 complete
98 out of 1468 group Id's processed; 0.07 complete
112 out of 1468 group Id's processed; 0.08 complete
126 out of 1468 group Id's processed; 0.09 complete
140 out of 1468 group Id's processed; 0.10 complete
154 out of 1468 group Id's processed; 0.10 complete
168 out of 1468 group Id's processed; 0.11 complete
182 out of 1468 group Id's processed; 0.12 complete
196 out of 1468 group Id's processed; 0.13 complete
210 out of 1468 group Id's processed; 0.14 complete
224 out of 1468 group Id's processed; 0.15 complete
238 out of 1468 group Id's processed; 0.16 complete
252 out of 1468 group Id's processed; 0.17 complete
266 out of 1468 group Id's processed; 0.18 complete
280 out of 1468 group Id's processed; 0.19 complete
294 out of 1468 group Id's processed; 0.20 complete
308 out of 1468 group Id's processed; 0.21 complete
322 out of 1468 group Id's processed; 0.22 complete
336 out of 1468 group Id's processed; 0.23 complete
350 out of 1468 group Id's processed; 0.24 complete
364 out of 1468 group Id's processed; 0.25 complete
378 out of 1468 group Id's processed; 0.26 complete
392 out of 1468 group Id's processed; 0.27 complete
406 out of 1468 group Id's processed; 0.28 complete
420 out of 1468 group Id's processed; 0.29 complete
434 out of 1468 group Id's processed; 0.30 complete
448 out of 1468 group Id's processed; 0.31 complete
462 out of 1468 group Id's processed; 0.31 complete
476 out of 1468 group Id's processed; 0.32 complete
490 out of 1468 group Id's processed; 0.33 complete
504 out of 1468 group Id's processed; 0.34 complete
518 out of 1468 group Id's processed; 0.35 complete
532 out of 1468 group Id's processed; 0.36 complete
546 out of 1468 group Id's processed; 0.37 complete
560 out of 1468 group Id's processed; 0.38 complete
574 out of 1468 group Id's processed; 0.39 complete
588 out of 1468 group Id's processed; 0.40 complete
602 out of 1468 group Id's processed; 0.41 complete
616 out of 1468 group Id's processed; 0.42 complete
630 out of 1468 group Id's processed; 0.43 complete
644 out of 1468 group Id's processed; 0.44 complete
658 out of 1468 group Id's processed; 0.45 complete
672 out of 1468 group Id's processed; 0.46 complete
686 out of 1468 group Id's processed; 0.47 complete
700 out of 1468 group Id's processed; 0.48 complete
714 out of 1468 group Id's processed; 0.49 complete
728 out of 1468 group Id's processed; 0.50 complete
742 out of 1468 group Id's processed; 0.51 complete
756 out of 1468 group Id's processed; 0.51 complete
770 out of 1468 group Id's processed; 0.52 complete
784 out of 1468 group Id's processed; 0.53 complete
798 out of 1468 group Id's processed; 0.54 complete
812 out of 1468 group Id's processed; 0.55 complete
826 out of 1468 group Id's processed; 0.56 complete
840 out of 1468 group Id's processed; 0.57 complete
854 out of 1468 group Id's processed; 0.58 complete
868 out of 1468 group Id's processed; 0.59 complete
882 out of 1468 group Id's processed; 0.60 complete
896 out of 1468 group Id's processed; 0.61 complete
910 out of 1468 group Id's processed; 0.62 complete
924 out of 1468 group Id's processed; 0.63 complete
938 out of 1468 group Id's processed; 0.64 complete
952 out of 1468 group Id's processed; 0.65 complete
966 out of 1468 group Id's processed; 0.66 complete
980 out of 1468 group Id's processed; 0.67 complete
994 out of 1468 group Id's processed; 0.68 complete
1008 out of 1468 group Id's processed; 0.69 complete
1022 out of 1468 group Id's processed; 0.70 complete
1036 out of 1468 group Id's processed; 0.71 complete
1050 out of 1468 group Id's processed; 0.72 complete
1064 out of 1468 group Id's processed; 0.72 complete
1078 out of 1468 group Id's processed; 0.73 complete
1092 out of 1468 group Id's processed; 0.74 complete
1106 out of 1468 group Id's processed; 0.75 complete
1120 out of 1468 group Id's processed; 0.76 complete
1134 out of 1468 group Id's processed; 0.77 complete
1148 out of 1468 group Id's processed; 0.78 complete
1162 out of 1468 group Id's processed; 0.79 complete
1176 out of 1468 group Id's processed; 0.80 complete
1190 out of 1468 group Id's processed; 0.81 complete
1204 out of 1468 group Id's processed; 0.82 complete
1218 out of 1468 group Id's processed; 0.83 complete
1232 out of 1468 group Id's processed; 0.84 complete
1246 out of 1468 group Id's processed; 0.85 complete
1260 out of 1468 group Id's processed; 0.86 complete
1274 out of 1468 group Id's processed; 0.87 complete
1288 out of 1468 group Id's processed; 0.88 complete
1302 out of 1468 group Id's processed; 0.89 complete
1316 out of 1468 group Id's processed; 0.90 complete
1330 out of 1468 group Id's processed; 0.91 complete
1344 out of 1468 group Id's processed; 0.92 complete
1358 out of 1468 group Id's processed; 0.93 complete
1372 out of 1468 group Id's processed; 0.93 complete
1386 out of 1468 group Id's processed; 0.94 complete
1400 out of 1468 group Id's processed; 0.95 complete
1414 out of 1468 group Id's processed; 0.96 complete
1428 out of 1468 group Id's processed; 0.97 complete
1442 out of 1468 group Id's processed; 0.98 complete
1456 out of 1468 group Id's processed; 0.99 complete
1468 out of 1468 group Id's processed; 1.00 complete
SQL QUERY: ALTER TABLE feat$cat_LIWC2022_lw$la_table$message_id$1gra ENABLE KEYS
-------
Settings:

Database - Audio_features
Corpus - la_table
Group ID - message_id
Feature table(s) - feat$cat_LIWC2022_lw$la_table$message_id$1gra
-------
Interface Runtime: 15.24 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

## lonely = 0 & not lonely = 1

In [14]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t la_table -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table la_table  --group_freq_thresh 1 \
    --outcomes status \
    --nfold_test_classifiers --model etc --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-08 15:49:01
-----
Loading Outcomes and Getting Groups for: {'status'}
WARNING: Could not determine variance of status. Skipping variance check.
    ***explicit fold labels specified, not splitting or stratifying again***


|COMBO: ()|
===========

= status (w/ lang.)=
--------------------

Fold 0
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 103)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 103)
 *confusion matrix:
[[ 76  58]
 [ 45 115]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.63      0.57      0.60       134
          1       0.66      0.72      0.69       160

avg / total       0.65      0.65      0.65       294

 *FOLD ACC: 0.6497 (mfclass_acc: 0.5442); mfclass: 1; auc: 0.6727


Fold 1
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 103)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 103)
 *confusion matrix:
[[ 65  59]
 [ 56 114]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.54      0.52      0.53       124
          1       0.66      0.67      0.66       170

avg / total       0.61      0.61      0.61       294

 *FOLD ACC: 0.6088 (mfclass_acc: 0.5782); mfclass: 1; auc: 0.6275


Fold 2
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 103)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 103)
 *confusion matrix:
[[79 76]
 [46 93]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.63      0.51      0.56       155
          1       0.55      0.67      0.60       139

avg / total       0.59      0.59      0.58       294

 *FOLD ACC: 0.5850 (mfclass_acc: 0.4728); mfclass: 1; auc: 0.6589


Fold 3
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 103)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 103)
 *confusion matrix:
[[80 70]
 [48 95]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.62      0.53      0.58       150
          1       0.58      0.66      0.62       143

avg / total       0.60      0.60      0.60       293

 *FOLD ACC: 0.5973 (mfclass_acc: 0.4881); mfclass: 1; auc: 0.6276


Fold 4
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 103)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 103)
 *confusion matrix:
[[ 72  75]
 [ 44 102]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.62      0.49      0.55       147
          1       0.58      0.70      0.63       146

avg / total       0.60      0.59      0.59       293

 *FOLD ACC: 0.5939 (mfclass_acc: 0.4983); mfclass: 1; auc: 0.6455

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py:177: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  score = y_true == y_pred
Traceback (most recent call last):
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 2266, in <module>
    main()
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 1996, in main
    groupsWhere = args.groupswhere, testFolds = args.test_folds)
  File "/home/vinmayk/dlatk/dlatk/classifyPredictor.py", line 1082, in testControlCombos
    reportStats['f1'] = f1_score(ytrue, ypred, average='macro')
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 692, in f1_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 806, in fbeta_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 1004, in precision_recall_fscore_support
    present_labels = unique_labels(y_true, y_pred)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/utils/multiclass.py", line 104, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)

In [ ]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t la_table -c message_id \
-f 'feat$cat_LIWC2022_lw$merged_data$message_id$1gra' \
    --outcome_table la_table  --group_freq_thresh 1 \
    --outcomes status \
    --nfold_test_classifiers --model etc --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-08 14:33:32
-----
Loading Outcomes and Getting Groups for: {'status'}
WARNING: Could not determine variance of status. Skipping variance check.
    ***explicit fold labels specified, not splitting or stratifying again***


|COMBO: ()|
===========

= status (w/ lang.)=
--------------------

Fold 0
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 3)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 3)
 *confusion matrix:
[[75 59]
 [69 91]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.52      0.56      0.54       134
          1       0.61      0.57      0.59       160

avg / total       0.57      0.56      0.57       294

 *FOLD ACC: 0.5646 (mfclass_acc: 0.5442); mfclass: 1; auc: 0.5774


Fold 1
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 3)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 3)
 *confusion matrix:
[[55 69]
 [82 88]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.40      0.44      0.42       124
          1       0.56      0.52      0.54       170

avg / total       0.49      0.49      0.49       294

 *FOLD ACC: 0.4864 (mfclass_acc: 0.5782); mfclass: 1; auc: 0.5043


Fold 2
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 3)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 3)
 *confusion matrix:
[[70 85]
 [56 83]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.56      0.45      0.50       155
          1       0.49      0.60      0.54       139

avg / total       0.53      0.52      0.52       294

 *FOLD ACC: 0.5204 (mfclass_acc: 0.4728); mfclass: 1; auc: 0.5342


Fold 3
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 3)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 3)
 *confusion matrix:
[[65 85]
 [62 81]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.51      0.43      0.47       150
          1       0.49      0.57      0.52       143

avg / total       0.50      0.50      0.50       293

 *FOLD ACC: 0.4983 (mfclass_acc: 0.4881); mfclass: 1; auc: 0.4888


Fold 4
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 3)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 3)
 *confusion matrix:
[[66 81]
 [66 80]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.50      0.45      0.47       147
          1       0.50      0.55      0.52       146

avg / total       0.50      0.50      0.50       293

 *FOLD ACC: 0.4983 (mfclass_acc: 0.4983); mfclass: 1; auc: 0.5110

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py:177: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  score = y_true == y_pred
Traceback (most recent call last):
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 2266, in <module>
    main()
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 1996, in main
    groupsWhere = args.groupswhere, testFolds = args.test_folds)
  File "/home/vinmayk/dlatk/dlatk/classifyPredictor.py", line 1082, in testControlCombos
    reportStats['f1'] = f1_score(ytrue, ypred, average='macro')
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 692, in f1_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 806, in fbeta_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 1004, in precision_recall_fscore_support
    present_labels = unique_labels(y_true, y_pred)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/utils/multiclass.py", line 104, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)

In [12]:
!python3 /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t la_table -c message_id \
-f 'feat$combined$merged_data$message_id' \
    --outcome_table la_table  --group_freq_thresh 1 \
    --outcomes status \
    --nfold_test_classifiers --model etc --fold_column fold --turn_off_backoff_model

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-08 14:33:47
-----
Loading Outcomes and Getting Groups for: {'status'}
WARNING: Could not determine variance of status. Skipping variance check.
    ***explicit fold labels specified, not splitting or stratifying again***


|COMBO: ()|
===========

= status (w/ lang.)=
--------------------

Fold 0
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 6)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 6)
 *confusion matrix:
[[ 69  65]
 [ 45 115]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.61      0.51      0.56       134
          1       0.64      0.72      0.68       160

avg / total       0.62      0.63      0.62       294

 *FOLD ACC: 0.6259 (mfclass_acc: 0.5442); mfclass: 1; auc: 0.6726


Fold 1
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 6)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 6)
 *confusion matrix:
[[ 69  55]
 [ 60 110]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.53      0.56      0.55       124
          1       0.67      0.65      0.66       170

avg / total       0.61      0.61      0.61       294

 *FOLD ACC: 0.6088 (mfclass_acc: 0.5782); mfclass: 1; auc: 0.6237


Fold 2
   (feature group: 0): [Initial size: 1468]
[Train size: 1174    Test size: 294]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1174, 6)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (294, 6)
 *confusion matrix:
[[ 95  60]
 [ 33 106]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.74      0.61      0.67       155
          1       0.64      0.76      0.70       139

avg / total       0.69      0.68      0.68       294

 *FOLD ACC: 0.6837 (mfclass_acc: 0.4728); mfclass: 1; auc: 0.7337


Fold 3
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 6)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 6)
 *confusion matrix:
[[84 66]
 [49 94]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.63      0.56      0.59       150
          1       0.59      0.66      0.62       143

avg / total       0.61      0.61      0.61       293

 *FOLD ACC: 0.6075 (mfclass_acc: 0.4881); mfclass: 1; auc: 0.6436


Fold 4
   (feature group: 0): [Initial size: 1468]
[Train size: 1175    Test size: 293]
[Applying StandardScaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)]
 X[0]: (N, features): (1175, 6)
[Training classification model: etc]
model: ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=10, oob_score=False,
           random_state=None, verbose=0, warm_start=False)
  predict: applying standard scaler to X[0]: StandardScaler(copy=True, with_mean=True, with_std=True)
  predict: combined X shape: (293, 6)
 *confusion matrix:
[[73 74]
 [48 98]]
 *precision and recall:
             precision    recall  f1-score   support

          0       0.60      0.50      0.54       147
          1       0.57      0.67      0.62       146

avg / total       0.59      0.58      0.58       293

 *FOLD ACC: 0.5836 (mfclass_acc: 0.4983); mfclass: 1; auc: 0.6299

/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py:177: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  score = y_true == y_pred
Traceback (most recent call last):
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 2266, in <module>
    main()
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 1996, in main
    groupsWhere = args.groupswhere, testFolds = args.test_folds)
  File "/home/vinmayk/dlatk/dlatk/classifyPredictor.py", line 1082, in testControlCombos
    reportStats['f1'] = f1_score(ytrue, ypred, average='macro')
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 692, in f1_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 806, in fbeta_score
    sample_weight=sample_weight)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 1004, in precision_recall_fscore_support
    present_labels = unique_labels(y_true, y_pred)
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/sklearn/utils/multiclass.py", line 104, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)

In [1]:
!python /home/vinmayk/dlatk/dlatkInterface.py -d Audio_features -t merged_data -c message_id \
-f 'feat$cat_Final_Klaatch_100_cp_w$merged_data$message_id$1gra' \
  --outcome_table merged_data --group_freq_thresh 5 \
  --outcomes CEL_Total --output_name Final_Klaatch_100 \
  --topic_tagcloud --make_topic_wordcloud --topic_lexicon Final_Klaatch_100_freq_t50ll \
  --tagcloud_colorscheme bluered --csv

/home/vinmayk/.local/lib/python3.5/site-packages/xgboost/__init__.py:29: FutureWarning: Python 3.5 support is deprecated; XGBoost will require Python 3.6+ in the near future. Consider upgrading to Python 3.6+.
  FutureWarning)
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

-----
DLATK Interface Initiated: 2025-04-22 18:11:07
-----
Loading Outcomes and Getting Groups for: {'CEL_Total'}
Yielding data over ['CEL_Total'], adjusting for: [].
Yielding norms with zeros (1465 groups * 101 feats).
/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/scipy/stats/stats.py:3021: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den
Generating Correlation Matrix.
 print to file: Final_Klaatch_100.csv
Namespace(IDP=False, adaptationfactors=None, adaptcolumns=None, adapttable=None, addcharngrams=False, addcorplextable=False, addfeatnorms=False, addfkscore=False, addldafeattable=None, addldamsgs=None, addlextable=False, addmessageid=None, addner=False, addngrams=False, addngramsfromtok=False, addoutcomefeats=False, addparses=False, addphrasetable=False, addpnames=None, addpostable=False, addpostimexdiff=False, addsegmented=False, addsentperrow=False, addsenttokenized=False, addstdfeats=False, addtimexdiff=False, addtokenized=False, addtopiclexfromtopicfile=False, addtweetpos=False, addtweettok=False, addwnnopos=False, addwnpos=False, aggregategroup=False, allcontrolsonly=True, archetypesimilarity=None, auc=False, barplot=False, batchsize=32, blacklist=False, bonferroni=True, bootstrapp=0, bracketlabels='', categories='', cattobinfields=[], cattointfields=[], cca=0, ccaOutcomesVsControls=False, ccaPermute=0, classToLex=None, cleancloud=False, cleanmessages=False, cohensd=False, colabify=False, colloc_column='feat', colloc_pmi_thresh=3.0, colloc_table='test_collocs', combinefeattables=None, combmodels=['ridgecv'], combormatrix=False, combotestclassifiers=False, combotestregression=False, compTCsample1=[], compTCsample2=[], compTagcloud=False, confint=True, controladjustreg=False, controlcombosizes=[], corpdb='Audio_features', corptable='merged_data', corptopictc=False, correl_field='message_id', correlate=False, createcollocscores=False, createcopiedtable=None, createdists=False, createrandsample=None, csv=True, date_field='updated_time', dbengine='mysql', ddlaFiles=None, ddlaSignificance=0.001, ddlaTagcloud=False, deduplicate=False, densifytable=None, descplot=False, describetables=False, embaddfeat=False, embaggs=['mean'], embclass=None, embkeepmsg=False, emblayeraggs=['concatenate'], emblayers=[-2], embmodel='bert-base-uncased', embnocontext=False, embtablename=None, encoding='utf8mb4', estimate_lda_topics=False, extension=None, extra_lda_stopwords=None, factoradaptation=False, factoraddition=False, factorselectiontype='rfe', feat_as_control=False, feat_as_outcome=False, feat_as_path_start=False, feat_blacklist='', feat_whitelist='', featcollocfilter=False, featcorrelfilter=False, featflexibin=False, featgroupoutcomes=False, featlabelmaplex='', featlabelmaptable='', featnames=['honor'], featoccfilter=False, feattable='feat$cat_Final_Klaatch_100_cp_w$merged_data$message_id$1gra', feature_type_name=None, featureselection='', featureselectionparams=None, featureselectionstring='', fitreducer=False, flexiplotfile='', fold_column=None, folds=5, freq=True, frominitfile='', fsparams=False, groupfreqthresh=5, groupidrange=None, groupswhere='', gzipcsv='', include_sub_collocs=False, integrationmethod='', interactionDdla=None, interactions=False, interpolategroup=None, kbest=None, keepduplicates=False, langfilter=[], language='en', lda_alpha=5.0, lda_beta=0.01, lda_iterations=1000, lda_lexicon_name=None, ldamsgtbl='messages_en_lda$msgs_en_tok_a30', lexicon_normalization=False, lexicondb='dlatk_lexica', lexinterface=False, lextable='', lexvaluefunc=<function main.<locals>.<lambda> at 0x7f389fb16d90>, lightenglishfilter=False, listfeattables=False, loadmodels=False, loessplot='', logisticReg=False, low_variance_thresh=0.0, lowercaseonly=True, makealltopicwordclouds=False, maketopiclabelmap=False, maketopicwordclouds=True, makewordclouds=False, mallet_path=None, masktable=None, maxP=0.05, maxtcwords=100, mediation=False, mediation_style='baron', mediationboot=False, mediationbootnum=1000, mediationcsv=False, mediationsummary=True, message_field='message', messageid_field='message_id', metafeats=True, minabseffectsize=0.0, minfeatsum=0, model='ridgecv', multicategory_normalization=False, multir=False, mysqlconfigfile='/home/vinmayk/.my.cnf', n=[1], n_components=None, newSQLtable=None, no_features=False, no_lda_lexicon=False, no_lda_stopping=False, nolang=False, num_lda_threads=4, num_stopwords=50, num_topics=100, numbins=None, numoffactors=None, numtopicwords=15, nvalue=True, outcomeWithOutcome=False, outcomeWithOutcomeOnly=False, outcomecontrols=[], outcomefields=['CEL_Total'], outcomeinteraction=[], outcomemediators=[], outcomepathstarts=[], outcometable='merged_data', outlier_to_mean=False, outputInteractionTerms=False, outputdir='.', outputname='Final_Klaatch_100', p_correction_method='BH', pairedfactors=False, pcacomp=None, penaltyFeats=None, penaltyOutcomes=None, pickle=False, picklefile='', pmi=3.0, pocc=0.01, pos_ngram=False, pred_csv=False, predictCcaCompsFromModel=False, predictCtoOutcomeTable=None, predictRtoOutcomeTable=None, predictalltofeats=None, predictclassifiers=False, predictclasstoreg=False, predictctofeats=None, predictprobstofeats=None, predictregression=False, predictrtofeats=None, prefixsupergroups=False, preservebintable=False, printcsv=None, printfreqcsv=None, printjoinedfeaturelines=None, printnumgroups=False, printtokenizedlines=None, prob_csv=False, reducedlexicon=None, reducertolexicon=None, regrToLex=None, report=False, res_controls=False, residualizedfactoradaptation=False, rmatrix=False, roc=False, save_lda_files=None, savemodels=False, scatterplot=False, segmentationModel='ctb', showfeatfreqs=True, showtables=False, skipbinstep=False, sort=False, spamfilter=None, sparse=False, spearman=False, standardize=True, stratifyfolds=False, supertopics=None, tagcloud=False, tagcloudcolorscheme='bluered', tcfilter=True, test_folds=None, testclassifiers=False, testclasstoreg=False, testcombregression=[], testregression=False, tfidf=False, toinitfile=None, tokenizermodel=None, top_messages=False, topicdupefilter=False, topicfile='', topiclexicon='Final_Klaatch_100_freq_t50ll', topiclexmethod='csv_lik', topiclist='', topictc=True, train_bootstraps=None, train_bootstraps_ns=None, trainclassifiers=False, trainclasstoreg=False, trainregression=False, transformdrtofeats=None, transwordaggs=['mean'], ttestfeats=False, turn_off_backoff_model=False, useFeatTableFeats=False, use_collocs=False, useunicode=True, usexcontrols=False, usexfeats=False, valuefunc=<function main.<locals>.<lambda> at 0x7f389fb16c80>, viewtables=False, weightedeval=None, weightedlexicon=False, weightedsample='', whitelist=False, wordTable=None, zScoreGroup=False)

outputting topic tagcloud data to: Final_Klaatch_100_topic_tagcloud.txt
Final_Klaatch_100_topic_tagcloud
Generating wordclouds using amueller's python package...
Traceback (most recent call last):
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 2266, in <module>
    main()
  File "/home/vinmayk/dlatk/dlatkInterface.py", line 1685, in main
    wordcloud.tagcloudToWordcloud(outputFile, withTitle=True, fontFamily="Meloche Rg", fontStyle="bold", toFolders=True, metric=metric, keepDuplicates=args.keepduplicates)
  File "/home/vinmayk/dlatk/dlatk/lib/wordcloud.py", line 568, in tagcloudToWordcloud
    wordcloud(ngrams, freqs,output_file, colors, rgb=False, title=title, fontFamily=fontFamily, fontStyle=fontStyle)
  File "/home/vinmayk/dlatk/dlatk/lib/wordcloud.py", line 256, in wordcloud
    mask=img_array).generate_from_frequencies(dict(word_freq_tup))
  File "/data/anaconda2/envs/dlatk/lib/python3.5/site-packages/wordcloud/wordcloud.py", line 255, in generate_from_frequencies
    for word, count in frequencies:
ValueError: too many values to unpack (expected 2)

import mysql.connector
import pandas as pd
# Connect to MySQL database
conn = mysql.connector.connect(
    host='127.0.0.1',
    database='dlatk_lexica',
    username='vinmayk', password='yA2Siru4l4yfEf1a'
)
# Create a cursor
cursor = conn.cursor()
# Initialize variables separately
cursor.execute("SET @num := 0;")
cursor.execute("SET @type := '';")
# Define the query
query = """
SELECT category,
       GROUP_CONCAT(term ORDER BY weight DESC SEPARATOR ', ') AS termy
FROM (
    SELECT category, term, weight,
           (@num := IF(@type = category, @num + 1, 1)) AS row_number,
           (@type := category) AS dummy
    FROM `Final_Klaatch_100_freq_t50ll`
    ORDER BY category, weight DESC
) AS x
WHERE x.row_number <= 10
GROUP BY category;
"""
# Fetch data into a pandas DataFrame
new_df = pd.read_sql_query(query, con=conn)
# Close cursor and connection
cursor.close()
conn.close()
# Print the DataFrame
new_df.to_csv('Final_100topics_Klaatch.csv', index=False)

In [2]:
import pandas as pd
import json

import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, text

db = sqlalchemy.engine.url.URL(drivername='mysql+pymysql',
                            host='127.0.0.1',
                            database='Audio_features',
                            username = "vinmayk", password = "yA2Siru4l4yfEf1a", port=None,
                            query={'read_default_file': '~/.my.cnf', 'charset':'utf8mb4'})
engine = sqlalchemy.create_engine(db)

In [3]:
table = 'feat$cat_Final_Klaatch_50_cp_w$merged_data$message_id$1gra'
msg_table = 'merged_data'

In [4]:
# read tables
tbl = pd.read_sql_table(table, engine)
msg_tbl = pd.read_sql_table(msg_table, engine)
#msg_tbl = msg_tbl[['message_id', 'message', 'KlaatchID_x', 'Date_x' , 'CEL_Total', 'CELVAL1', 'CELVAL2', 'CELVAL3']]

In [5]:
tbl

            id           group_id        feat  value  group_norm
0            1     103_2021-04-21          12     93    0.195711
1            2     103_2021-04-21          31     28    0.009537
2            3     103_2021-04-21          83      8    0.000445
3            4     103_2021-04-21          10     30    0.006536
4            5     103_2021-04-21          18     51    0.023640
...        ...                ...         ...    ...         ...
147685  147686  997606_2024-10-25          15    168    0.007278
147686  147687  997606_2024-10-25          28     46    0.001827
147687  147688  997606_2024-10-25          74     40    0.000766
147688  147689  997606_2024-10-25          76   1287    0.241210
147689  147690  997606_2024-10-25  _intercept      1    1.000000

[147690 rows x 5 columns]

In [6]:
# drop row where feat == '_intercept'
tbl = tbl[tbl['feat'] != '_intercept']
# convert feat to int
tbl['feat'] = tbl['feat'].astype(int)

tbl = tbl.rename(columns={'feat': 'category'})

/tmp/ipykernel_1384335/3160203219.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tbl['feat'] = tbl['feat'].astype(int)

In [7]:
tbl = tbl.merge(msg_tbl, left_on='group_id', right_on='message_id', how='left')

In [8]:
tbl

,id,group_id,category,value,group_norm,message_id,message,Date,CEL_Total,CELVAL1,CELVAL2,CELVAL3,klaatch_id,fold
0,1,103_2021-04-21,12,93,0.195711,103_2021-04-21,Hello. What's going on today? It's out in I lo...,2021-04-21,1,0,0,1,103,3
1,2,103_2021-04-21,31,28,0.009537,103_2021-04-21,Hello. What's going on today? It's out in I lo...,2021-04-21,1,0,0,1,103,3
2,3,103_2021-04-21,83,8,0.000445,103_2021-04-21,Hello. What's going on today? It's out in I lo...,2021-04-21,1,0,0,1,103,3
3,4,103_2021-04-21,10,30,0.006536,103_2021-04-21,Hello. What's going on today? It's out in I lo...,2021-04-21,1,0,0,1,103,3
4,5,103_2021-04-21,18,51,0.023640,103_2021-04-21,Hello. What's going on today? It's out in I lo...,2021-04-21,1,0,0,1,103,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146220,147685,997606_2024-10-25,99,28,0.001594,997606_2024-10-25,"Hello. Okay. Nope. Sure. Yes. Yep. Okay. Well,...",2024-10-25,9,2,3,4,997606,4
146221,147686,997606_2024-10-25,15,168,0.007278,997606_2024-10-25,"Hello. Okay. Nope. Sure. Yes. Yep. Okay. Well,...",2024-10-25,9,2,3,4,997606,4
146222,147687,997606_2024-10-25,28,46,0.001827,997606_2024-10-25,"Hello. Okay. Nope. Sure. Yes. Yep. Okay. Well,...",2024-10-25,9,2,3,4,997606,4
146223,147688,997606_2024-10-25,74,40,0.000766,997606_2024-10-25,"Hello. Okay. Nope. Sure. Yes. Yep. Okay. Well,...",2024-10-25,9,2,3,4,997606,4
146224,147689,997606_2024-10-25,76,1287,0.241210,997606_2024-10-25,"Hello. Okay. Nope. Sure. Yes. Yep. Okay. Well,...",2024-10-25,9,2,3,4,997606,4

In [9]:
# subset tbl to where message > 5 words
tbl_5_words = tbl[tbl['message'].str.split().str.len() > 5]

In [10]:
top_10_msgs = tbl.groupby('category').apply(lambda x: x.nlargest(10, 'group_norm')).reset_index(drop=True)

/tmp/ipykernel_1384335/676043890.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_10_msgs = tbl.groupby('category').apply(lambda x: x.nlargest(10, 'group_norm')).reset_index(drop=True)

In [11]:
top_10_msgs

,id,group_id,category,value,group_norm,message_id,message,Date,CEL_Total,CELVAL1,CELVAL2,CELVAL3,klaatch_id,fold
0,3475,128_2021-04-28,0,15,0.013553,128_2021-04-28,"Hello. Okay, surprise. Okay. I took care of th...",2021-04-28,1,1,0,0,128,3
1,132522,777_2023-07-31,0,131,0.013215,777_2023-07-31,"Oh, hello. Yeah, Hi. Good. I didn't. You cut o...",2023-07-31,4,1,2,1,777,4
2,49053,507_2021-02-09,0,8,0.013131,507_2021-02-09,So. Oh. Sure. People could. Yes. So I'd watch ...,2021-02-09,5,1,1,3,507,0
3,99723,679_2022-09-08,0,280,0.011227,679_2022-09-08,Hello. Hello. Yes. I'm out of breath right now...,2022-09-08,3,1,1,1,679,1
4,99622,679_2022-05-10,0,128,0.010738,679_2022-05-10,Hello. Yes. Mm hmm. All right. Okay. Would you...,2022-05-10,5,1,3,1,679,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,98763,678_2022-08-18,99,18,0.011893,678_2022-08-18,"Hello. I'm busy, man, playing video games. Som...",2022-08-18,3,1,1,1,678,1
996,92305,661_2021-06-23,99,16,0.011484,661_2021-06-23,Go a new. Yeah. Good. That package to get ba...,2021-06-23,12,4,4,4,661,0
997,2110,117_2021-02-08,99,20,0.011465,117_2021-02-08,Hello. OK. Ok. Yesterday I went to KIPP's with...,2021-02-08,0,0,0,0,117,3
998,117986,734_2024-03-28,99,20,0.011382,734_2024-03-28,"h. Yes. I'm fine, thank you. Yes. I'm feeling ...",2024-03-28,3,1,1,1,734,0
999,12793,223_2022-03-28,99,53,0.011106,223_2022-03-28,But most associates may help you. This sounds ...,2022-03-28,9,1,4,4,223,2

In [12]:
top_10_msgs.columns

Index(['id', 'group_id', 'category', 'value', 'group_norm', 'message_id',
       'message', 'Date', 'CEL_Total', 'CELVAL1', 'CELVAL2', 'CELVAL3',
       'klaatch_id', 'fold'],
      dtype='object')

In [13]:
top_10_topics = pd.read_csv('/home/vinmayk/Final_100topics_Klaatch.csv')

In [14]:
top_10_msgs

,id,group_id,category,value,group_norm,message_id,message,Date,CEL_Total,CELVAL1,CELVAL2,CELVAL3,klaatch_id,fold
0,3475,128_2021-04-28,0,15,0.013553,128_2021-04-28,"Hello. Okay, surprise. Okay. I took care of th...",2021-04-28,1,1,0,0,128,3
1,132522,777_2023-07-31,0,131,0.013215,777_2023-07-31,"Oh, hello. Yeah, Hi. Good. I didn't. You cut o...",2023-07-31,4,1,2,1,777,4
2,49053,507_2021-02-09,0,8,0.013131,507_2021-02-09,So. Oh. Sure. People could. Yes. So I'd watch ...,2021-02-09,5,1,1,3,507,0
3,99723,679_2022-09-08,0,280,0.011227,679_2022-09-08,Hello. Hello. Yes. I'm out of breath right now...,2022-09-08,3,1,1,1,679,1
4,99622,679_2022-05-10,0,128,0.010738,679_2022-05-10,Hello. Yes. Mm hmm. All right. Okay. Would you...,2022-05-10,5,1,3,1,679,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,98763,678_2022-08-18,99,18,0.011893,678_2022-08-18,"Hello. I'm busy, man, playing video games. Som...",2022-08-18,3,1,1,1,678,1
996,92305,661_2021-06-23,99,16,0.011484,661_2021-06-23,Go a new. Yeah. Good. That package to get ba...,2021-06-23,12,4,4,4,661,0
997,2110,117_2021-02-08,99,20,0.011465,117_2021-02-08,Hello. OK. Ok. Yesterday I went to KIPP's with...,2021-02-08,0,0,0,0,117,3
998,117986,734_2024-03-28,99,20,0.011382,734_2024-03-28,"h. Yes. I'm fine, thank you. Yes. I'm feeling ...",2024-03-28,3,1,1,1,734,0
999,12793,223_2022-03-28,99,53,0.011106,223_2022-03-28,But most associates may help you. This sounds ...,2022-03-28,9,1,4,4,223,2

In [15]:
# merge top 3 msgs with top 10 words
top_10_msgs = top_10_msgs.merge(top_10_topics, on='category', how='left')
#print(top_10_msgs.columns)
#K=top_10_msgs[['id_x', 'id_y', 'group_id', 'category', 'message_id', 'message', 'termy']]
K=top_10_msgs[['id', 'group_id', 'category', 'message_id', 'message', 'termy']]
K
#top_10_msgs.columns

,id,group_id,category,message_id,message,termy
0,3475,128_2021-04-28,0,128_2021-04-28,"Hello. Okay, surprise. Okay. I took care of th...","dog, course, of course, course ,, of course ,,..."
1,132522,777_2023-07-31,0,777_2023-07-31,"Oh, hello. Yeah, Hi. Good. I didn't. You cut o...","dog, course, of course, course ,, of course ,,..."
2,49053,507_2021-02-09,0,507_2021-02-09,So. Oh. Sure. People could. Yes. So I'd watch ...,"dog, course, of course, course ,, of course ,,..."
3,99723,679_2022-09-08,0,679_2022-09-08,Hello. Hello. Yes. I'm out of breath right now...,"dog, course, of course, course ,, of course ,,..."
4,99622,679_2022-05-10,0,679_2022-05-10,Hello. Yes. Mm hmm. All right. Okay. Would you...,"dog, course, of course, course ,, of course ,,..."
...,...,...,...,...,...,...
995,98763,678_2022-08-18,99,678_2022-08-18,"Hello. I'm busy, man, playing video games. Som...","ow, jason, ow , tub, ow, ow ,, ow , ow, ambul..."
996,92305,661_2021-06-23,99,661_2021-06-23,Go a new. Yeah. Good. That package to get ba...,"ow, jason, ow , tub, ow, ow ,, ow , ow, ambul..."
997,2110,117_2021-02-08,99,117_2021-02-08,Hello. OK. Ok. Yesterday I went to KIPP's with...,"ow, jason, ow , tub, ow, ow ,, ow , ow, ambul..."
998,117986,734_2024-03-28,99,734_2024-03-28,"h. Yes. I'm fine, thank you. Yes. I'm feeling ...","ow, jason, ow , tub, ow, ow ,, ow , ow, ambul..."
999,12793,223_2022-03-28,99,223_2022-03-28,But most associates may help you. This sounds ...,"ow, jason, ow , tub, ow, ow ,, ow , ow, ambul..."

In [ ]:
K[K['category']==18]['message'].to_list()

['TIL caregiver PTSD is real. HAHAHAHAHAHAHAHAHAJCDFHCCJNNVKHHJJJJN FUCK. \n\nThe human brain is an absolute travesty. Kill me.',
 "This is so hard It really really sucks and is very hard. That's about where I'm at right now. \n\nStay strong everyone.",
 'Conflicted CONFLICTED. Easier. Harder. Grieving. Distancing. Loving. Apathetic. This part of the dementia journey is a study in contradictions.\n\n[Curtain Up!](https://www.stumpedtowndementia.com/post/curtain-up)',
 "exelon I'm going to start.yhis soon, the patch. Does.smyone.hsvr any.expetirnces.yhey can share? thanks",
 "End-stage Alzheimer's and COVID My Dad, not even 70, is at the very end of a horrible decade with early-onset.  Today he tested positive for COVID, as did my Mom (no dementia).  Yup.",
 'Conflicted Easier. Harder. Grieving. Distancing. Loving. Apathetic. This part of the dementia journey is a study in contradictions.\n\n[Curtain Up!](https://www.stumpedtowndementia.com/post/curtain-up)',
 'Merry Christmas/Holidays To all the carers putting in the grind. No one understands what we do.  Love.',
 'Reunion. A funeral. Trepedation. Humor. Dementia. Keeping up with the kin sometimes requires a little bit of dementia caregiving work on our part. \n\n[All in the family.](https://www.stumpedtowndementia.com/post/all-in-the-family)',
 'Reunions. A funeral. Trepidation. Humor. Dementia. Keeping up with the kin sometimes requires a little bit of dementia caregiving work on our part.\n\n[All in the family.](https://www.stumpedtowndementia.com/post/all-in-the-family)',
 'Breaking the rules: General consensus says not to bring forth reality. Not to bring forth "now". This isn\'t always applicable or the best thing to do. Choose wisely.']

In [16]:
# Resolve column conflict
if 'termy' in top_10_msgs.columns:
    top_10_msgs = top_10_msgs.drop(columns=['termy'])

# Merge without conflicts
top_10_msgs = top_10_msgs.merge(top_10_topics, on='category', how='left')

# Select desired columns
#result = top_10_msgs[['id_x', 'id_y', 'group_id', 'category', 'message_id', 'message', 'termy']]
result = top_10_msgs[['id', 'group_id', 'category', 'message_id', 'message', 'termy']]

# Save to CSV
result.to_csv('Final_Klaatch_messages.csv', index=False)

print("CSV file 'top_10_messages.csv' has been created.")

CSV file 'top_10_messages.csv' has been created.